### ISSUE TITLE
🐛 Bug: alter table `nc_base_users_v2` add primary key `nc_base_users_v2_pkey`(`base_id`, `fk_user_id`) - Multiple primary key defined

### ISSUE THREAD

**Issue by raf-microsoft** [nocodb/nocodb#10117]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

I'm experiencing the following issue. The DB MySQL 8, hosted on Azure Flexi Server:

```js
[Nest] 30940  - 25/12/2024, 4:36:51 pm   ERROR [ExceptionHandler] alter table `nc_base_users_v2` add primary key `nc_base_users_v2_pkey`(`base_id`, `fk_user_id`) - Multiple primary key defined
Error: alter table `nc_base_users_v2` add primary key `nc_base_users_v2_pkey`(`base_id`, `fk_user_id`) - Multiple primary key defined
    at Packet.asError (C:\Development\greedo\node_modules\mysql2\lib\packets\packet.js:740:17)
    at Query.execute (C:\Development\greedo\node_modules\mysql2\lib\commands\command.js:29:26)
    at Connection.handlePacket (C:\Development\greedo\node_modules\mysql2\lib\base\connection.js:475:34)
    at PacketParser.onPacket (C:\Development\greedo\node_modules\mysql2\lib\base\connection.js:93:12)
    at PacketParser.executeStart (C:\Development\greedo\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Development\greedo\node_modules\mysql2\lib\base\connection.js:100:25)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
PS C:\Development\greedo>
```

From what I see the DB is created and tables are populated however when I run `npm start` Nest crashes with the error above.

**Replication steps:**

```js
npx create-nocodb-app
...pointed to the remote clean DB
npm uninstall
npm install --save nocodb
...as the version in npx create-nocodb-app is outdated
npm start
```

### Desired Behavior

Run

### Project Details

Node.js
MySQL 8

### Attachments

![image](https://github.com/user-attachments/assets/1ffb12e9-13f8-4ca2-b372-9a36da1a1a63)

**Comment by raf-microsoft** [comment]
Ok, did a few more tests, the version from npx `0.207.3` will install and run on the DB but after update to the latest `0.258.10` throw the error above.

**Comment by o1lab** [comment]
Please use docker setup.

Just wondering how you 've `my_row_id` as the primary key ? did you happen to do any changes to this database structure ?

**Comment by raf-microsoft** [comment]
I performed a clean install on the empty DB whatever is there is done by the script. Btw, in `0.250.1` which works, this table looks exactly the same and `my_row_id` ia also set as primary key.

![image](https://github.com/user-attachments/assets/5d5cc1ab-d93e-4b84-a7af-59afd187fd75)
![image](https://github.com/user-attachments/assets/124c702e-673e-47db-9beb-dd982e1133f6)
![image](https://github.com/user-attachments/assets/cf58d26d-141c-4659-acfc-452c4b93359c)

**Comment by raf-microsoft** [comment]
Ok, this issue starts from [0.251.2](https://github.com/nocodb/nocodb/releases/tag/0.251.2)

**Comment by antonioseric** [comment]
Any updates on this issue??

This issue is blocker for updating to latest version with MySQL configuration.
