### ISSUE TITLE
Error: Cannot use column reference in DEFAULT expression 

### ISSUE THREAD

**Issue by captain-otter** [nocodb/nocodb#1032]
NocoDB used as docker : true
NocoDB version : 0.84.8
Database used in NC_DB URL : pg
Project was created by clicking : New Project
Database on which spreadsheet is created : pg
OS on which NocoDB is running : Debian Buster VM inside Proxmox
Node.js version if running as node :
Database version : PostgreSQL 13.3

**Steps To Reproduce**
1. Create a table
2. Add a new column that is of text type (SingleLineText,LongText,SingleSelect,MultiSelect, etc.)
3. Specify the default value that is not a number. For example "ABC"

**Expected behavior**
Default value for that column is set.

**What happens**
In the log (of docker container) I get this error:
```
error: 
ALTER TABLE "nc_44wz__test_table" ALTER COLUMN "title6"  SET DEFAULT asd;
; - cannot use column reference in DEFAULT expression
    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 116,
  severity: 'ERROR',
  code: '0A000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_expr.c',
  line: '596',
  routine: 'transformColumnRef'
}
```

**Comment by wingkwong** [comment]
You should use single quote instead. Revised examples for strings in 113fcfa49135ed24a411ceee0ca2e600114d9161.

![image](https://user-images.githubusercontent.com/35857179/152515257-83b8d0d2-bf38-4778-b5f8-d5b205dba04a.png)
