### ISSUE TITLE
Knex: Timeout acquiring a connection. The pool is probably full when creating project with a lot of tables (260 in my case)

### ISSUE THREAD

**Issue by darkgoldxp** [nocodb/nocodb#1150]
**Please enter the following details**

please provide the following details :
NocoDB used as docker : **true** 
NocoDB version : **0.84.9 and 0.84.10**
Database used in NC_DB URL  : **pg**
Project was created  by clicking : **New Project by connecting to external database**
Database on which spreadsheet is created : **mysql**
OS on which NocoDB is running : **linux**
Node.js version if running as node : **v12.22.6**
Database version : **pg 13.4**

**Steps To Reproduce**
Local deployement on docker via docker compose
Open dashboard and create account
Create projet by connecting to external database connection 

**Expected behavior**
When i create a new project by connecting to external database connection during creation after a couple of time the error occure in log
```
nocodb_0.84.10  | select * from "nc_relations" where "project_id" = 'reporting_gtb6' and "db_alias" = 'db'
nocodb_0.84.10  | ╔══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
nocodb_0.84.10  | ║                                                                                                                                  ║
nocodb_0.84.10  | ║                                                 EXCEPTION OCCURED!! in MysqlClient @ columnList                                  ║
nocodb_0.84.10  | ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -            ║
nocodb_0.84.10  | ║   MESSAGE:                                                                                                                       ║
nocodb_0.84.10  | ║   Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?                     ║
nocodb_0.84.10  | ║                                                                                                                                  ║
nocodb_0.84.10  | ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -            ║
nocodb_0.84.10  | ║   CODE:                                                                                                                          ║
nocodb_0.84.10  | ║   undefined                                                                                                                      ║
nocodb_0.84.10  | ║                                                                                                                                  ║
nocodb_0.84.10  | ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -            ║
nocodb_0.84.10  | ║   STACK:                                                                                                                         ║
nocodb_0.84.10  | ║   KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?   ║
nocodb_0.84.10  | ║       at Client_MySQL2.acquireConnection (/usr/src/app/node_modules/knex/lib/client.js:348:26)                                   ║
nocodb_0.84.10  | ║       at runNextTicks (internal/process/task_queues.js:62:5)                                                                     ║
nocodb_0.84.10  | ║       at listOnTimeout (internal/timers.js:523:9)                                                                                ║
nocodb_0.84.10  | ║       at processTimers (internal/timers.js:497:7)                                                                                ║
nocodb_0.84.10  | ║                                                                                                                                  ║
nocodb_0.84.10  | ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -            ║
nocodb_0.84.10  | ║                                                                                                                                  ║
nocodb_0.84.10  | ║                                                                                                                                  ║
nocodb_0.84.10  | ╚══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
^[[55;200Rnocodb_0.84.10  | KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
nocodb_0.84.10  |     at Client_MySQL2.acquireConnection (/usr/src/app/node_modules/knex/lib/client.js:348:26)
nocodb_0.84.10  |     at runNextTicks (internal/process/task_queues.js:62:5)
nocodb_0.84.10  |     at listOnTimeout (internal/timers.js:523:9)
nocodb_0.84.10  |     at processTimers (internal/timers.js:497:7) {
nocodb_0.84.10  |   sql: 'SELECT\n' +
nocodb_0.84.10  |     'c.table_name as tn,\n' +
nocodb_0.84.10  |     'c.column_name as cn,\n' +
nocodb_0.84.10  |     'c.data_type as dt,\n' +
nocodb_0.84.10  |     'c.column_type as ct,\n' +
nocodb_0.84.10  |     'c.character_maximum_length as clen,\n' +
nocodb_0.84.10  |     'c.numeric_precision as np,\n' +
nocodb_0.84.10  |     'c.numeric_scale as ns,\n' +
nocodb_0.84.10  |     '-- c.datetime_precision as dp,\n' +
nocodb_0.84.10  |     'c.ordinal_position as cop,\n' +
nocodb_0.84.10  |     'c.column_key as ck,\n' +
nocodb_0.84.10  |     'c.extra as ext, -- gives ai\n' +
nocodb_0.84.10  |     'c.column_default as cdf,\n' +
nocodb_0.84.10  |     'c.is_nullable as nrqd,\n' +
nocodb_0.84.10  |     'c.privileges as priv,\n' +
nocodb_0.84.10  |     'c.column_comment as cc,\n' +
nocodb_0.84.10  |     '-- c.generation_expression,\n' +
nocodb_0.84.10  |     'c.character_set_name as csn,\n' +
nocodb_0.84.10  |     'c.collation_name as clnn,\n' +
nocodb_0.84.10  |     'ct.CONSTRAINT_TYPE as cst\n' +
nocodb_0.84.10  |     'FROM\n' +
nocodb_0.84.10  |     'information_schema.COLUMNS as c\n' +
nocodb_0.84.10  |     'Left join(\n' +
nocodb_0.84.10  |     '        select\n' +
nocodb_0.84.10  |     '                tc.CONSTRAINT_NAME,\n' +
nocodb_0.84.10  |     '                tc.TABLE_NAME,\n' +
nocodb_0.84.10  |     '                tc.CONSTRAINT_SCHEMA,\n' +
nocodb_0.84.10  |     '                tc.CONSTRAINT_TYPE,\n' +
nocodb_0.84.10  |     '                s.COLUMN_NAME\n' +
nocodb_0.84.10  |     '        from\n' +
nocodb_0.84.10  |     '                information_schema.TABLE_CONSTRAINTS as tc\n' +
nocodb_0.84.10  |     '        LEFT JOIN information_schema.STATISTICS as s ON\n' +
nocodb_0.84.10  |     '                s.table_schema = tc.CONSTRAINT_SCHEMA\n' +
nocodb_0.84.10  |     '                and s.TABLE_NAME = tc.TABLE_NAME\n' +
nocodb_0.84.10  |     '                and s.INDEX_NAME = tc.CONSTRAINT_NAME\n' +
nocodb_0.84.10  |     '        where\n' +
nocodb_0.84.10  |     '                tc.CONSTRAINT_SCHEMA = ?\n' +
nocodb_0.84.10  |     '                and s.TABLE_NAME = ?\n' +
nocodb_0.84.10  |     ') ct on\n' +
nocodb_0.84.10  |     'c.TABLE_SCHEMA = ct.CONSTRAINT_SCHEMA\n' +
nocodb_0.84.10  |     'AND c.TABLE_NAME = ct.TABLE_NAME\n' +
nocodb_0.84.10  |     'AND c.COLUMN_NAME = ct.COLUMN_NAME\n' +
nocodb_0.84.10  |     'WHERE\n' +
nocodb_0.84.10  |     'c.table_schema = ?\n' +
nocodb_0.84.10  |     'and c.TABLE_NAME = ?\n' +
nocodb_0.84.10  |     'ORDER BY\n' +
nocodb_0.84.10  |     'c.table_name,\n' +
nocodb_0.84.10  |     'c.ordinal_position',
nocodb_0.84.10  |   bindings: [
nocodb_0.84.10  |     'reporting',
nocodb_0.84.10  |     'ttr_anomalie_critique_calcul_OLD',
nocodb_0.84.10  |     'reporting',
nocodb_0.84.10  |     'ttr_anomalie_critique_calcul_OLD'
nocodb_0.84.10  |   ]
nocodb_0.84.10  | }
nocodb_0.84.10  | KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
nocodb_0.84.10  |     at Client_MySQL2.acquireConnection (/usr/src/app/node_modules/knex/lib/client.js:348:26)
nocodb_0.84.10  |     at runNextTicks (internal/process/task_queues.js:62:5)
nocodb_0.84.10  |     at listOnTimeout (internal/timers.js:523:9)
nocodb_0.84.10  |     at processTimers (internal/timers.js:497:7) {
nocodb_0.84.10  |   sql: 'SELECT\n' +
nocodb_0.84.10  |     'c.table_name as tn,\n' +
nocodb_0.84.10  |     'c.column_name as cn,\n' +
nocodb_0.84.10  |     'c.data_type as dt,\n' +
nocodb_0.84.10  |     'c.column_type as ct,\n' +
nocodb_0.84.10  |     'c.character_maximum_length as clen,\n' +
nocodb_0.84.10  |     'c.numeric_precision as np,\n' +
nocodb_0.84.10  |     'c.numeric_scale as ns,\n' +
nocodb_0.84.10  |     '-- c.datetime_precision as dp,\n' +
nocodb_0.84.10  |     'c.ordinal_position as cop,\n' +
nocodb_0.84.10  |     'c.column_key as ck,\n' +
nocodb_0.84.10  |     'c.extra as ext, -- gives ai\n' +
nocodb_0.84.10  |     'c.column_default as cdf,\n' +
nocodb_0.84.10  |     'c.is_nullable as nrqd,\n' +
nocodb_0.84.10  |     'c.privileges as priv,\n' +
nocodb_0.84.10  |     'c.column_comment as cc,\n' +
nocodb_0.84.10  |     '-- c.generation_expression,\n' +
nocodb_0.84.10  |     'c.character_set_name as csn,\n' +
nocodb_0.84.10  |     'c.collation_name as clnn,\n' +
nocodb_0.84.10  |     'ct.CONSTRAINT_TYPE as cst\n' +
nocodb_0.84.10  |     'FROM\n' +
nocodb_0.84.10  |     'information_schema.COLUMNS as c\n' +
nocodb_0.84.10  |     'Left join(\n' +
nocodb_0.84.10  |     '        select\n' +
nocodb_0.84.10  |     '                tc.CONSTRAINT_NAME,\n' +
nocodb_0.84.10  |     '                tc.TABLE_NAME,\n' +
nocodb_0.84.10  |     '                tc.CONSTRAINT_SCHEMA,\n' +
nocodb_0.84.10  |     '                tc.CONSTRAINT_TYPE,\n' +
nocodb_0.84.10  |     '                s.COLUMN_NAME\n' +
nocodb_0.84.10  |     '        from\n' +
nocodb_0.84.10  |     '                information_schema.TABLE_CONSTRAINTS as tc\n' +
nocodb_0.84.10  |     '        LEFT JOIN information_schema.STATISTICS as s ON\n' +
nocodb_0.84.10  |     '                s.table_schema = tc.CONSTRAINT_SCHEMA\n' +
nocodb_0.84.10  |     '                and s.TABLE_NAME = tc.TABLE_NAME\n' +
nocodb_0.84.10  |     '                and s.INDEX_NAME = tc.CONSTRAINT_NAME\n' +
nocodb_0.84.10  |     '        where\n' +
nocodb_0.84.10  |     '                tc.CONSTRAINT_SCHEMA = ?\n' +
nocodb_0.84.10  |     '                and s.TABLE_NAME = ?\n' +
nocodb_0.84.10  |     ') ct on\n' +
nocodb_0.84.10  |     'c.TABLE_SCHEMA = ct.CONSTRAINT_SCHEMA\n' +
nocodb_0.84.10  |     'AND c.TABLE_NAME = ct.TABLE_NAME\n' +
nocodb_0.84.10  |     'AND c.COLUMN_NAME = ct.COLUMN_NAME\n' +
nocodb_0.84.10  |     'WHERE\n' +
nocodb_0.84.10  |     'c.table_schema = ?\n' +
nocodb_0.84.10  |     'and c.TABLE_NAME = ?\n' +
nocodb_0.84.10  |     'ORDER BY\n' +
nocodb_0.84.10  |     'c.table_name,\n' +
nocodb_0.84.10  |     'c.ordinal_position',
nocodb_0.84.10  |   bindings: [
nocodb_0.84.10  |     'reporting',
nocodb_0.84.10  |     'ttr_anomalie_critique_calcul_OLD',
nocodb_0.84.10  |     'reporting',
nocodb_0.84.10  |     'ttr_anomalie_critique_calcul_OLD'
nocodb_0.84.10  |   ]
nocodb_0.84.10  | }
```

After that project can run but no tables swagger are avalaible

Try with another database with only 64 tables and everything it's OK.

So I think it's because of the number of tables

Can you help me ?

**Comment by o1lab** [comment]
How many tables are there in your database ? 

Hard to say connection gets full if there are more tables - are the 64 tables schema and this schema in the same database ?

**Comment by darkgoldxp** [comment]
Hello, 
I have 260 tables the schema
Yes it's the same database, one schema with 64 tables and one with 260 tables.
All fonctionnality seems to work except the generation of api endpoint in the swagger.

**Comment by darkgoldxp** [comment]
After clean tables problem is not reproduce
