### ISSUE TITLE
🐛  [Import CSV] Bug: Script error : "cannot read properties of undefined" when using pagination

### ISSUE THREAD

**Issue by cacmar** [nocodb/nocodb#1297]
Hi everyone,

First of all, you do a very good job and thank you for this amazing project !

**Project infos**

Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.84.10**

**Steps To Reproduce**
- Case 1 -
1. Go to my projet
2. Click on the second page
3. Only the first row is loaded and a script error appears

- Case 2 -
1. Go to my projet
2. Click on the third page or others
3. All the page is loaded and a script error appears

Also when the script error appears every buttons/actions are disabled and the "loading" animation on the top left is still running...

**Expected behavior**
I expected to be able to check all the data using the pagination index. 

**Screenshots**

![image](https://user-images.githubusercontent.com/95369211/154647058-641244ff-fb85-4647-978b-732407b5e291.png)

Regards

**Comment by dstala** [comment]
@cacmar, will it be possible to share a sample database file for us to reproduce this issue? 

pagination is working fine when we try with sample Postgres sakila database
https://github.com/jOOQ/sakila/tree/main/postgres-sakila-db

**Comment by cacmar** [comment]
Thanks for your interest @dstala 

I found the real problem. 

You can reproduce the error with this process :

- Import this Excel file to create a new project
- Change the column "dates_selectionnees" to multiselect with those options :
19/06/2022
18/09/2022
27/11/2022
24/04/2022
- Now click to go to the second page --> the script error appends and you can't use any buttons

[nocodb_data_to_import.xlsx](https://github.com/nocodb/nocodb/files/8096195/nocodb_data_to_import.xlsx)

**Comment by dstala** [comment]
@cacmar 
Thanks for sharing excel file. We are able to reproduce issue & will look into.

Other observations
- Excel import & pagination works fine if 'multiselect' option toggling is not done
- Warning on project creation, before triggering pagination
vue.runtime.esm.js:619 [Vue warn]: Duplicate keys detected: ''. This may cause an update error. 

Pagination error (observed as indicated by @cacmar)
client.js:103 TypeError: Cannot read properties of undefined (reading 'key')
    at sameVnode (vue.runtime.esm.js:5861:1)
    at updateChildren (vue.runtime.esm.js:6263:1)
    at patchVnode (vue.runtime.esm.js:6363:28)
    at VueComponent.patch [as __patch__] (vue.runtime.esm.js:6526:1)
    at VueComponent.Vue._update (vue.runtime.esm.js:3963:1)
    at VueComponent.updateComponent (vue.runtime.esm.js:4075:1)
    at Watcher.get (vue.runtime.esm.js:4495:1)
    at Watcher.run (vue.runtime.esm.js:4570:1)
    at flushSchedulerQueue (vue.runtime.esm.js:4326:1)
    at Array.<anonymous> (vue.runtime.esm.js:1989:1)

**Comment by dstala** [comment]
@cacmar
Issue observed during handling of multiple empty separators for options (comma in this case).
While we work on a solution to fix this- you can use attached excel for your continued experiments
[nocodb_data_to_import_v2.xlsx](https://github.com/nocodb/nocodb/files/8099849/nocodb_data_to_import_v2.xlsx)
Changes: replaced occurrence of multiple empty option separators with a single one.

**Comment by cacmar** [comment]
Thank you for your answer @dstala

**Comment by JeffersonDing** [comment]
Same issue here after importing a large base from Airtable. The docker logs show 
```
[Nest] 9  - 08/13/2023, 7:19:21 AM   ERROR [i] Please check server log for more details
Error: Please check server log for more details
    at Function.internalServerError (/usr/src/app/docker/main.js:1:654573)
    at b.getDataList (/usr/src/app/docker/main.js:1:1143546)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async b.dataList (/usr/src/app/docker/main.js:1:1141491)
    at async p.dataList (/usr/src/app/docker/main.js:1:51532)
TypeError: Cannot read properties of undefined (reading 'as')
    at t.BaseModelSqlv2.selectObject (/usr/src/app/docker/main.js:1:217967)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async t.BaseModelSqlv2.list (/usr/src/app/docker/main.js:1:196781)
    at async b.getDataList (/usr/src/app/docker/main.js:1:1143471)
    at async b.dataList (/usr/src/app/docker/main.js:1:1141491)
    at async p.dataList (/usr/src/app/docker/main.js:1:51532)
```
Some views do work while other's don't.

**Comment by dstala** [comment]
We can skip empty options & continue with type conversion.

**Comment by dstala** [comment]
type conversions are skipped during import csv now. all fields are mapped by default as single line text

if you face any issue still, please reopen this thread
