### ISSUE TITLE
Tables connected by a natural id (a foreign key that is not the primary key on the other side) are not viewed properly

### ISSUE THREAD

**Issue by ardnaskela** [nocodb/nocodb#1299]
NocoDB used as docker : false
NocoDB version : 0.84.12
Database used in NC_DB URL  : pg
Project was created  by clicking :New Project by connecting to external database
Database on which spreadsheet is created : pg 
OS on which NocoDB is running : ubuntu
Node.js version if running as node : v14.17.2
Database version : 12.9

**Steps To Reproduce**

Execute the following queries on a Postgres DB (customer_phone is related to customer using a natural foreign key (user_email), while customer_address is using the customer pk (uid) as a foreign key).

```
create table "customer" (
	"uid" bigserial not null,
	"customer_email" varchar(255) unique,
	constraint "user_pk" primary key ("uid")
);

create table "customer_phone" (
	"uid" bigserial not null,
	"customer_email" varchar(255),
	"phone_number" varchar(255),
	constraint "userphone_pk" primary key ("uid")
);

create table "customer_address" (
	"uid" bigserial not null,
	"customer_uid" bigint,
	"address" varchar(255),
	constraint "customer_address_pk" primary key ("uid")
);

alter table "customer_phone" add constraint "customer_phone_fk1" foreign key ("customer_email") references "customer"("customer_email") ON UPDATE CASCADE ON DELETE CASCADE;
alter table "customer_address" add constraint "customer_address_fk1" foreign key ("customer_uid") references "customer"("uid") ON UPDATE CASCADE ON DELETE CASCADE;

insert into customer (customer_email) values ('user1@test.com');
insert into customer_phone (customer_email, phone_number) values ('user1@test.com', '1234567');
insert into customer_address (customer_uid, address) values (1, 'Somewhere Str. 1');
```

Open nocodb -> New Project -> Create by Connecting to External Database -> connect to the DB with the tables created

Customer view sees the address record to which it's connected by customer uid and **not** the phone record to which it's connected by customer email.
Both customer phone and customer address views see the customer they are related to. 

**Expected behavior**
Customer view should see both customer_phone and customer_address entries that customer table is related to.

**Screenshots**
![image](https://user-images.githubusercontent.com/15897676/154747250-ab9e4d49-6b7a-43ac-a068-4e1c7c8529b9.png)
![image](https://user-images.githubusercontent.com/15897676/154747304-21239497-7de3-4c03-8782-88b6e491e300.png)
![image](https://user-images.githubusercontent.com/15897676/154747410-8240d98a-06e9-416b-a4ca-e1c7cf6f6ad6.png)

**Comment by wingkwong** [comment]
Attached error log.

```
error: update "customer_phone" set "customer_email" = $1 where "uid" = $2 - insert or update on table "customer_phone" violates foreign key constraint "customer_phone_fk1"
    at Parser.parseErrorMessage (/<REDACTED>/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/<REDACTED>/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/<REDACTED>/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/<REDACTED>/nocodb/packages/nocodb/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 270,
  severity: 'ERROR',
  code: '23503',
  detail: 'Key (customer_email)=(1) is not present in table "customer".',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'customer_phone',
  column: undefined,
  dataType: undefined,
  constraint: 'customer_phone_fk1',
  file: 'ri_triggers.c',
  line: '2539',
  routine: 'ri_ReportViolation'
}
PUT /nc/postgres_sd7s/api/v1/CustomerPhone/1 400 184 - 9.183 ms
```

**Comment by ardnaskela** [comment]
Hello @wingkwong , first of all, thank you for the immense work done on the issue.

Unfortunately, the anomaly seems to persist on the select level after data import from SQL: there are no errors log-wise, but upon opening the Customer view all the underlying select statements keep using the value of the customer PK as opposed to the natural key when retrieving data from the related tables and as a result nothing is found: 

_select * from "customer_phone" where "customer_email" = '1';_
and not
_select * from "customer_phone" where "customer_email" = 'user1@test.com';_

**Comment by wingkwong** [comment]
@ardnaskela  please DM me in Discord.

![image](https://user-images.githubusercontent.com/35857179/158981502-e0b38bb1-90d7-4336-8400-e46c99c2c848.png)

**Comment by ardnaskela** [comment]
Hello @wingkwong , ok will do.
I tried downloading and updating the develop branch, thinking that maybe the master of the seed repo was not updated, but to no avail, unfortunately.

Just to make it clear: I am not talking about lookup columns (unfortunately, it's not an option), but the newly imported db with existing relationships one-to-many and many-to-many using natural ids. Those exhibit the problem described.

All of those relationships are shown as empty upon importing the db from scratch and on the log there is the logical error shown in my previous comment (the foreign key is derived from the customer table and not the imported Postgres constraint).

The lookup column is not an option because the db is meant for consumption by a different frontend, so all the changes made to the relationships must be saved to the original table / the original intermediate table in case of many-to-many.

Kind regards.

**Comment by wingkwong** [comment]
Steps to reproduce. (Provided by Alexandra)

![image](https://user-images.githubusercontent.com/35857179/159672912-78d39382-f761-4a23-a43d-9db75ee95ded.png)

```sql
create table "customer" (
	"uid" bigserial not null,
	"email" varchar(255) unique,
	constraint "user_pk" primary key ("uid")
);

create table "customer_phone" (
	"uid" bigserial not null,
	"customer_email" varchar(255),
	"phone_number" varchar(255),
	constraint "userphone_pk" primary key ("uid")
);

create table "customer_address" (
	"uid" bigserial not null,
	"customer_uid" bigint,
	"address" varchar(255),
	constraint "customer_address_pk" primary key ("uid")
);

create table "profile" (
	"code" varchar(255) not null,
	"description" varchar(255) not null,
	constraint "profile_pk" primary key ("code")
);

create table "customer_to_profile" (
	"customer_email" varchar(255) not null,
	"profile_code" varchar(255) not null,
	constraint "customer_to_profile_pk" primary key ("customer_email", profile_code)
);

alter table "customer_phone" add constraint "customer_phone_fk1" foreign key ("customer_email") references "customer"("email") ON UPDATE CASCADE ON DELETE CASCADE;
alter table "customer_address" add constraint "customer_address_fk1" foreign key ("customer_uid") references "customer"("uid") ON UPDATE CASCADE ON DELETE CASCADE;
alter table "customer_to_profile" add constraint "customer_to_profile_fk1" foreign key ("customer_email") references "customer"("email") ON UPDATE CASCADE ON DELETE CASCADE;
alter table "customer_to_profile" add constraint "customer_to_profile_fk2" foreign key ("profile_code") references "profile"("code") ON UPDATE CASCADE ON DELETE CASCADE;

insert into customer (email) values ('user1@test.com');
insert into customer_phone (customer_email, phone_number) values ('user1@test.com', '1234567');
insert into customer_address (customer_uid, address) values (1, 'Somewhere Str. 1');
insert into profile (code, description) values ('PRIVATE', 'Person');
insert into profile (code, description) values ('BUSINESS', 'Organization');
insert into customer_to_profile (customer_email, profile_code) values ('user1@test.com', 'PRIVATE');
```

Log Excerpt

```
select "customer"."uid" as "Uid", "customer"."email" as "Email" from "customer"
select "customer"."uid" as "Uid", "customer"."email" as "Email" from "customer"
select * from "customer_address" where "customer_uid" = '1'
select * from "customer_phone" where "customer_email" = '1'
select count("customer"."uid") as "count" from "customer"
select count("customer"."uid") as "count" from "customer"
select * from "profile" inner join "customer_to_profile" on "customer_to_profile"."profile_code" = "profile"."code" where "customer_to_profile"."customer_email" = '1'
GET /nc/arvel_crynyd_q6xl/api/v1/Customer/count?where= 200 13 - 55.595 ms
GET /nc/arvel_crynyd_q6xl/api/v1/Customer?limit=25&offset=0&where=&sort=&hm=customer_address,customer_phone&bt=&mm=profile 200 134 - 81.619 ms
DB OPS xcAuditModelCommentsCount
POST /dashboard/?q=sqlOp_xcAuditModelCommentsCount 200 2 - 4.801 ms
DB OPS tableXcModelGet
POST /dashboard/?q=sqlOp_tableXcModelGet 200 1997 - 3.917 ms
DB OPS tableXcModelGet
POST /dashboard/?q=sqlOp_tableXcModelGet 200 2722 - 14.676 ms
DB OPS tableXcModelGet
POST /dashboard/?q=sqlOp_tableXcModelGet 200 2534 - 3.361 ms
DB OPS tableXcModelGet
POST /dashboard/?q=sqlOp_tableXcModelGet 200 2561 - 2.927 ms
select "customer"."uid" as "Uid", "customer"."email" as "Email" from "customer"
select "customer"."uid" as "Uid", "customer"."email" as "Email" from "customer"
select * from "customer_address" where "customer_uid" = '1'
select * from "customer_phone" where "customer_email" = '1'
select * from "profile" inner join "customer_to_profile" on "customer_to_profile"."profile_code" = "profile"."code" where "customer_to_profile"."customer_email" = '1'
select count("customer"."uid") as "count" from "customer"
select count("customer"."uid") as "count" from "customer"
GET /nc/arvel_crynyd_q6xl/api/v1/Customer?limit=25&offset=0&where=&sort=&hm=customer_address,customer_phone&bt=&mm=profile 304 - - 40.313 ms
GET /nc/arvel_crynyd_q6xl/api/v1/Customer/count?where= 304 - - 37.790 ms
DB OPS xcAuditModelCommentsCount
POST /dashboard/?q=sqlOp_xcAuditModelCommentsCount 200 2 - 2.332 ms
POST /dashboard/?q=sqlOp_xcVirtualTableUpdate 200 1 - 21.410 ms
```

**Comment by o1lab** [comment]
@ardnaskela : please check it in 0.90 (latest version) and let us know

**Comment by o1lab** [comment]
<img width="795" alt="Screenshot 2022-04-20 at 16 30 55" src="https://user-images.githubusercontent.com/5435402/164267706-b7f6a703-55e7-40bb-ac52-0362f8df64fd.png">

Verified with example provided.
