### ISSUE TITLE
Unable to run nocodb with postgres RDS

### ISSUE THREAD

**Issue by neutralboy** [nocodb/nocodb#156]
Firstly, this is an amazing project. Thanks for all the hard work!

I'm trying to deploy nocodb on my AWS EC2 instance using docker and connect it to me RDS Postgres version 12.5. 
The error seems to happen only on connect to RDS. Ive attached a picture below to show the docker logs
![Screenshot from 2021-05-27 20-08-00](https://user-images.githubusercontent.com/21339738/119846410-ba96b200-bf27-11eb-8318-d575a264c027.png)

I can connect to the database using `psql` CLI. 

```
noco_1   | error: CREATE DATABASE  null - syntax error at or near "null"
noco_1   |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
noco_1   |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
noco_1   |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
noco_1   |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
noco_1   |     at Socket.emit (events.js:314:20)
noco_1   |     at Socket.EventEmitter.emit (domain.js:483:12)
noco_1   |     at addChunk (_stream_readable.js:297:12)
noco_1   |     at readableAddChunk (_stream_readable.js:272:9)
noco_1   |     at Socket.Readable.push (_stream_readable.js:213:10)
noco_1   |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
noco_1   |   length: 93,
noco_1   |   severity: 'ERROR',
noco_1   |   code: '42601',
noco_1   |   detail: undefined,
noco_1   |   hint: undefined,
noco_1   |   position: '18',
noco_1   |   internalPosition: undefined,
noco_1   |   internalQuery: undefined,
noco_1   |   where: undefined,
noco_1   |   schema: undefined,
noco_1   |   table: undefined,
noco_1   |   column: undefined,
noco_1   |   dataType: undefined,
noco_1   |   constraint: undefined,
noco_1   |   file: 'scan.l',
noco_1   |   line: '1150',
noco_1   |   routine: 'scanner_yyerror'
noco_1   | }
noco_1   | error: CREATE DATABASE  null - syntax error at or near "null"
noco_1   |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
noco_1   |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
noco_1   |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
noco_1   |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
noco_1   |     at Socket.emit (events.js:314:20)
noco_1   |     at Socket.EventEmitter.emit (domain.js:483:12)
noco_1   |     at addChunk (_stream_readable.js:297:12)
noco_1   |     at readableAddChunk (_stream_readable.js:272:9)
noco_1   |     at Socket.Readable.push (_stream_readable.js:213:10)
noco_1   |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
noco_1   |   length: 93,
noco_1   |   severity: 'ERROR',
noco_1   |   code: '42601',
noco_1   |   detail: undefined,
noco_1   |   hint: undefined,
noco_1   |   position: '18',
noco_1   |   internalPosition: undefined,
noco_1   |   internalQuery: undefined,
noco_1   |   where: undefined,
noco_1   |   schema: undefined,
noco_1   |   table: undefined,
noco_1   |   column: undefined,
noco_1   |   dataType: undefined,
noco_1   |   constraint: undefined,
noco_1   |   file: 'scan.l',
noco_1   |   line: '1150',
noco_1   |   routine: 'scanner_yyerror'
noco_1   | }
```

Here's the complete log. Thank you for your help in advance! :)

**Comment by pranavxc** [comment]
@neutralboy : join our Discord community so we can help you quickly  👍 
 https://discord.gg/5RgZmkW

**Comment by o1lab** [comment]
After clear local storage in browser & resetting docker-compose.env file.

This problem was resolved.
