### ISSUE TITLE
Error when editing a SingleSelect column

### ISSUE THREAD

**Issue by Lukasdotcom** [nocodb/nocodb#1597]
NocoDB used as docker : true
NocoDB version : v0.84.15
Database used in NC_DB URL  : mysql
Project was created  by clicking : New Project
Database on which spreadsheet is created : mysql
OS on which NocoDB is running : ubuntu
Node.js version if running as node : 
Database version : 10.7.3

**Steps To Reproduce**
1. Go to Table with a SingleSelect column type
2. Click on Edit and add an option.
3. Displays an error.

**Expected behavior**
An error should not happen.

**Log**
```
Error: ALTER TABLE `nc_ve0y__players` 

    CHANGE

    COLUMN `Buy or Sell` `Buy or Sell` enum('Sell','Buy','Maybe Buy','Maybe Sell') NULL

    DEFAULT "NULL"; - Invalid default value for 'Buy or Sell'

    at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:728:17)

    at Query.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:29:26)

    at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:456:32)

    at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:85:12)

    at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)

    at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:92:25)

    at Socket.emit (events.js:314:20)

    at Socket.EventEmitter.emit (domain.js:483:12)

    at addChunk (_stream_readable.js:297:12)

    at readableAddChunk (_stream_readable.js:272:9) {

  code: 'ER_INVALID_DEFAULT',

  errno: 1067,

  sqlState: '42000',

  sqlMessage: "Invalid default value for 'Buy or Sell'",

  sql: 'ALTER TABLE `nc_ve0y__players` \n' +

    '    CHANGE\n' +

    "    COLUMN `Buy or Sell` `Buy or Sell` enum('Sell','Buy','Maybe Buy','Maybe Sell') NULL\n" +

    '    DEFAULT "NULL";'

}
```
Join our discord : https://discord.gg/5RgZmkW for realtime help.

Node version : **v12.22.1**
Arch type: **arm64**
Platform: **linux**
Docker: **true**
Database: **mysql**
packageVersion: **0.9.27**

**Comment by Lukasdotcom** [comment]
I did some troubleshooting and I think the problem has to do with the NULL having quotation marks around it. I don't know where in the code this can be fixed though.

**Comment by wingkwong** [comment]
Before saving, did you see the same thing? 

<img width="408" alt="image" src="https://user-images.githubusercontent.com/35857179/161680756-059056a2-cd90-481c-b861-1fd867cf9d9f.png">

**Comment by Lukasdotcom** [comment]
It looked like this and then I pressed save and it gave the error:
![Screenshot 2022-04-05 9 13 31 AM](https://user-images.githubusercontent.com/72501726/161761863-315ad5a8-c8b2-46a4-a91a-c7e70bd7cb29.png)
