### ISSUE TITLE
Cannot import project

### ISSUE THREAD

**Issue by loranger** [nocodb/nocodb#1616]
Hello,

I try to migrate my datas from a local nocodb to a self-hosted one.
They both use the same docker-compose file (except domain and db credentials).
Both works fine, but as soons as I try to import the meta.zip I just exported from the local nocodb, PG crashes and my new nocodb is corrupted and bricked until I flush the database volume (which is quite annoying)

NocoDB used as docker : true
NocoDB version : latest (should be 0.84.16, how can I figure out ?)
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project
Database on which spreadsheet is created : pg
OS on which NocoDB is running : Docker 20.10.13 on Debian 11
Node.js version if running as node : /
Database version : latest (14.2)

**Steps To Reproduce**
1. Download [this export](https://github.com/nocodb/nocodb/files/8445337/meta.zip)
2. Import
3. Boom

<details>
<summary>logs I had regarding the exception</summary>

```
nocodb-nocodb    | GET /nc/import_zg1o/projectApiInfo 200 500 - 12.827 ms
nocodb-nocodb    | GET /user/me?project_id=import_zg1o 200 148 - 2.339 ms
nocodb-nocodb    | Within PROJECT_READ_BY_WEB handler { api: 'PROJECT_READ_BY_WEB', project_id: 'import_zg1o' }
nocodb-nocodb    | DB OPS PROJECT_READ_BY_WEB
nocodb-nocodb    | POST /dashboard/?q=sqlOp_PROJECT_READ_BY_WEB 200 668 - 15.510 ms
nocodb-nocodb    | select * from "nc_roles" where "project_id" = '' and "db_alias" = ''
nocodb-nocodb    | select * from "nc_models" where "project_id" = 'import_zg1o' and "db_alias" = 'db' and "mm" is null and (("type" = 'table') or ("type" = 'view') or ("type" = 'vtable')) order by "order" asc
nocodb-nocodb    | select * from "nc_disabled_models_for_role" where "project_id" = 'import_zg1o' and "db_alias" = 'db' and (("type" = 'table') or ("type" = 'view') or ("type" = 'vtable'))
nocodb-nocodb    | DB OPS xcTableAndViewList
nocodb-nocodb    | POST /dashboard/?q=sqlOp_xcTableAndViewList 200 20 - 21.202 ms
nocodb-nocodb    | select * from "nc_roles" where "project_id" = '' and "db_alias" = ''
nocodb-nocodb    | GET /admin/roles?project_id=import_zg1o 200 904 - 10.622 ms
nocodb-nocodb    | GET /admin?limit=20&offset=0&query=&project_id=import_zg1o 200 406 - 15.603 ms
nocodb-nocodb    | select * from "nc_roles" where "project_id" = '' and "db_alias" = ''
nocodb-nocodb    | GET /admin/roles?project_id=import_zg1o 304 - - 12.067 ms
nocodb-nocodb    | GET /admin?limit=10&offset=0&query=&project_id=import_zg1o 200 406 - 16.741 ms
nocodb-nocodb    | Error: aborted
nocodb-nocodb    |     at PendingOperation.abort (/usr/src/app/node_modules/tarn/dist/PendingOperation.js:25:21)
nocodb-nocodb    |     at /usr/src/app/node_modules/tarn/dist/Pool.js:208:25
nocodb-nocodb    |     at Array.map (<anonymous>)
nocodb-nocodb    |     at /usr/src/app/node_modules/tarn/dist/Pool.js:207:53
nocodb-nocodb    |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
nocodb-nocodb    | Error: Unable to acquire a connection
nocodb-nocodb    |     at Client_PG.acquireConnection (/usr/src/app/node_modules/knex/lib/client.js:339:13)
nocodb-nocodb    |     at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/runner.js:264:8)
nocodb-nocodb    |     at Runner.run (/usr/src/app/node_modules/knex/lib/runner.js:26:12)
nocodb-nocodb    |     at Builder.Target.then (/usr/src/app/node_modules/knex/lib/interface.js:22:43)
nocodb-nocodb    |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
nocodb-nocodb    | POST /dashboard/?q=sqlOp_projectList&skipProjectHasDb=1 400 40 - 3.851 ms
nocodb-nocodb    | GET /user/me 304 - - 2.298 ms
nocodb-nocodb    | Error: Unable to acquire a connection
nocodb-nocodb    |     at Client_PG.acquireConnection (/usr/src/app/node_modules/knex/lib/client.js:339:13)
nocodb-nocodb    |     at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/runner.js:264:8)
nocodb-nocodb    |     at Runner.run (/usr/src/app/node_modules/knex/lib/runner.js:26:12)
nocodb-nocodb    |     at Builder.Target.then (/usr/src/app/node_modules/knex/lib/interface.js:22:43)
nocodb-nocodb    |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
nocodb-nocodb    | POST /dashboard/?q=sqlOp_projectList&skipProjectHasDb=1 400 40 - 3.213 ms
nocodb-nocodb    | POST /dashboard/?q=sqlOp_xcMetaTablesImportZipToLocalFsAndDb&project_id=import_zg1o - - - - ms
nocodb-nocodb    | GET /dashboard/ 304 - - 2.284 ms
nocodb-nocodb    | GET /dashboard/_nuxt/94ff77b.js 304 - - 5.960 ms
nocodb-nocodb    | GET /dashboard/_nuxt/c6c8d58.js 304 - - 5.573 ms
nocodb-nocodb    | GET /dashboard/_nuxt/bbf27ec.js 304 - - 4.196 ms
nocodb-nocodb    | GET /dashboard/_nuxt/a33459a.js 304 - - 4.760 ms
nocodb-nocodb    | GET /dashboard/_nuxt/c90d2d4.js 304 - - 6.245 ms
nocodb-nocodb    | GET /dashboard/_nuxt/5adb8c9.js 304 - - 6.649 ms
nocodb-nocodb    | GET /dashboard/_nuxt/7a9942f.js 304 - - 7.266 ms
nocodb-nocodb    | GET /dashboard/_nuxt/3424a00.js 304 - - 1.929 ms
nocodb-nocodb    | GET /dashboard/_nuxt/a18d94d.js 304 - - 1.814 ms
nocodb-nocodb    | Error: Unable to acquire a connection
nocodb-nocodb    |     at Client_PG.acquireConnection (/usr/src/app/node_modules/knex/lib/client.js:339:13)
nocodb-nocodb    |     at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/runner.js:264:8)
nocodb-nocodb    |     at Runner.run (/usr/src/app/node_modules/knex/lib/runner.js:26:12)
nocodb-nocodb    |     at Builder.Target.then (/usr/src/app/node_modules/knex/lib/interface.js:22:43)
```

</details>

**Expected behavior**
I think the exported project should be imported and ready very quickly (because the exported project is very small)

**Screenshots**
Better than screenshots, a screencast:

https://user-images.githubusercontent.com/6014/162267602-75b3b110-6d7b-49e7-a9b5-c4fe3db708c3.mp4

Node version : ?
Arch type: **amd64**
Platform: **linux**
Docker: **true**
Database: **postgresql**
packageVersion: **:latest**

**Comment by wingkwong** [comment]
Export & Import have been deprecated in new version.
