### ISSUE TITLE
Bug: Type set does not exist

### ISSUE THREAD

**Issue by brasilikum** [nocodb/nocodb#165]
This happened when I tried to add a column of type single select. Let me know if I can help with any more info to squash this bug.

I am very excited this project exists! Keep it up

```
2021-05-28T00:12:19.614196+00:00 app[web.1]: ║                                                                                                                         ║
2021-05-28T00:12:19.614197+00:00 app[web.1]: ║                                                 EXCEPTION OCCURED!! in PGClient @ tableUpdate                           ║
2021-05-28T00:12:19.614197+00:00 app[web.1]: ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
2021-05-28T00:12:19.614197+00:00 app[web.1]: ║   MESSAGE:                                                                                                              ║
2021-05-28T00:12:19.614198+00:00 app[web.1]: ║   ALTER TABLE "xa1__hi"  ADD  "title7" set NULL ; - type "set" does not exist                                           ║
2021-05-28T00:12:19.614198+00:00 app[web.1]: ║                                                                                                                         ║
2021-05-28T00:12:19.614198+00:00 app[web.1]: ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
2021-05-28T00:12:19.614199+00:00 app[web.1]: ║   CODE:                                                                                                                 ║
2021-05-28T00:12:19.614199+00:00 app[web.1]: ║   42704                                                                                                                 ║
2021-05-28T00:12:19.614199+00:00 app[web.1]: ║                                                                                                                         ║
2021-05-28T00:12:19.614200+00:00 app[web.1]: ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
2021-05-28T00:12:19.614200+00:00 app[web.1]: ║   STACK:                                                                                                                ║
2021-05-28T00:12:19.614200+00:00 app[web.1]: ║   error: ALTER TABLE "xa1__hi"  ADD  "title7" set NULL ; - type "set" does not exist                                    ║
2021-05-28T00:12:19.614201+00:00 app[web.1]: ║       at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)                         ║
2021-05-28T00:12:19.614201+00:00 app[web.1]: ║       at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)                              ║
2021-05-28T00:12:19.614201+00:00 app[web.1]: ║       at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)                                      ║
2021-05-28T00:12:19.614202+00:00 app[web.1]: ║       at TLSSocket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)                              ║
2021-05-28T00:12:19.614202+00:00 app[web.1]: ║       at TLSSocket.emit (events.js:314:20)                                                                              ║
2021-05-28T00:12:19.614202+00:00 app[web.1]: ║       at TLSSocket.EventEmitter.emit (domain.js:483:12)                                                                 ║
2021-05-28T00:12:19.614203+00:00 app[web.1]: ║       at addChunk (_stream_readable.js:297:12)                                                                          ║
2021-05-28T00:12:19.614203+00:00 app[web.1]: ║       at readableAddChunk (_stream_readable.js:272:9)                                                                   ║
2021-05-28T00:12:19.614203+00:00 app[web.1]: ║       at TLSSocket.Readable.push (_stream_readable.js:213:10)                                                           ║
2021-05-28T00:12:19.614204+00:00 app[web.1]: ║       at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)                                                  ║
2021-05-28T00:12:19.614204+00:00 app[web.1]: ║                                                                                                                         ║
2021-05-28T00:12:19.614204+00:00 app[web.1]: ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
2021-05-28T00:12:19.614204+00:00 app[web.1]: ║                                                                                                                         ║
2021-05-28T00:12:19.614205+00:00 app[web.1]: ║                                                                                                                         ║
2021-05-28T00:12:19.614212+00:00 app[web.1]: 
```

**Comment by pranavxc** [comment]
Fixed in nocodb@0.9.15
