### ISSUE TITLE
[MSSQL] 🐛 Bug: 'update table failed' after changing type or Column type

### ISSUE THREAD

**Issue by stepanof** [nocodb/nocodb#1676]
Hello Team!

NocoDB used as docker : true
NocoDB version :  0.84.15
Database used in NC_DB URL  : sqlite3
Project was created  by clicking :  New Project by connecting to external database
Database on which spreadsheet is created : mysql
OS on which NocoDB is running : linux

**Steps To Reproduce**
1. Go to Project (which was created by connecting to external database)
2. Create New column with 'Number' type
![image](https://user-images.githubusercontent.com/68236577/163215534-e6828acd-17f0-44b9-95ee-52f2917bf28d.png)
4. Try to Edit column and change Column type from 'Number' to 'SingleLineText'
![image](https://user-images.githubusercontent.com/68236577/163215613-b5e2eb76-f531-4713-a33d-990451e0874d.png)
6. Click Save
![image](https://user-images.githubusercontent.com/68236577/163215661-d085e95e-95cd-46bb-adb5-28e124b06beb.png)
8. See error 'update table failed'
![image](https://user-images.githubusercontent.com/68236577/163214161-37e5e28c-8fdd-479a-bc54-5d154de6f625.png)

**Expected behavior**
I expected to see column with modified type.

**Comment by wingkwong** [comment]
I couldn't reproduce this issue with the setup you provided.  Even with or without values in the cells, I'm still able to change the type from 'Number' to 'SingleLineText'.

Could you please share some logs?

**Comment by stepanof** [comment]
Here is log while I attemp to change Column type:

2022-04-14T08:49:04.888748825Z Within DB_TABLE_UPDATE handler {
2022-04-14T08:49:04.888795623Z   api: 'tableUpdate',
2022-04-14T08:49:04.888800152Z   env: '_noco',
2022-04-14T08:49:04.888803906Z   dbAlias: 'db',
2022-04-14T08:49:04.888807500Z   project_id: 'nocodb_mssql_test_lbxk',
2022-04-14T08:49:04.888811315Z   args: {
2022-04-14T08:49:04.888814724Z     tn: '123',
2022-04-14T08:49:04.888818278Z     _tn: '123',
2022-04-14T08:49:04.888821746Z     originalColumns: [
2022-04-14T08:49:04.888824976Z       [Object], [Object],
2022-04-14T08:49:04.888828393Z       [Object], [Object],
2022-04-14T08:49:04.888831640Z       [Object], [Object],
2022-04-14T08:49:04.888834842Z       [Object]
2022-04-14T08:49:04.888838015Z     ],
2022-04-14T08:49:04.888841291Z     columns: [
2022-04-14T08:49:04.888844975Z       [Object], [Object],
2022-04-14T08:49:04.888848191Z       [Object], [Object],
2022-04-14T08:49:04.888851651Z       [Object], [Object],
2022-04-14T08:49:04.888854823Z       [Object]
2022-04-14T08:49:04.888858091Z     ]
2022-04-14T08:49:04.888881162Z   },
2022-04-14T08:49:04.888886837Z   sqlOpPlus: true
2022-04-14T08:49:04.888890374Z }
2022-04-14T08:49:04.888899296Z {
2022-04-14T08:49:04.888903042Z   api: 'tableUpdate',
2022-04-14T08:49:04.888906268Z   env: '_noco',
2022-04-14T08:49:04.888909640Z   dbAlias: 'db',
2022-04-14T08:49:04.888912934Z   project_id: 'nocodb_mssql_test_lbxk',
2022-04-14T08:49:04.888916157Z   args: {
2022-04-14T08:49:04.888919461Z     tn: '123',
2022-04-14T08:49:04.888922653Z     _tn: '123',
2022-04-14T08:49:04.888925811Z     originalColumns: [
2022-04-14T08:49:04.888928980Z       [Object], [Object],
2022-04-14T08:49:04.888932174Z       [Object], [Object],
2022-04-14T08:49:04.888935434Z       [Object], [Object],
2022-04-14T08:49:04.888938585Z       [Object]
2022-04-14T08:49:04.888941731Z     ],
2022-04-14T08:49:04.888944927Z     columns: [
2022-04-14T08:49:04.888948190Z       [Object], [Object],
2022-04-14T08:49:04.888951355Z       [Object], [Object],
2022-04-14T08:49:04.888954494Z       [Object], [Object],
2022-04-14T08:49:04.888957640Z       [Object]
2022-04-14T08:49:04.888960809Z     ]
2022-04-14T08:49:04.888963995Z   },
2022-04-14T08:49:04.888967147Z   sqlOpPlus: true
2022-04-14T08:49:04.888970555Z }
2022-04-14T08:49:04.916409221Z ╔═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
2022-04-14T08:49:04.916449406Z ║                                                                                                                         ║
2022-04-14T08:49:04.916454082Z ║                                                 EXCEPTION OCCURED!! in MssqlClient @ tableUpdate                        ║
2022-04-14T08:49:04.916457722Z ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
2022-04-14T08:49:04.916461171Z ║   MESSAGE:                                                                                                              ║
2022-04-14T08:49:04.916464852Z ║                                                                                                                         ║
2022-04-14T08:49:04.916468268Z ║   ALTER TABLE [dbo].[123] ALTER COLUMN [TestColumn] varchar();                                                          ║
2022-04-14T08:49:04.916471828Z ║                                                                                                                         ║
2022-04-14T08:49:04.916493126Z ║   ALTER TABLE [dbo].[123] ALTER COLUMN [TestColumn] TYPE varchar;                                                       ║
2022-04-14T08:49:04.916498433Z ║    - Incorrect syntax near 'varchar'.                                                                                   ║
2022-04-14T08:49:04.916503272Z ║                                                                                                                         ║
2022-04-14T08:49:04.916508475Z ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
2022-04-14T08:49:04.916513635Z ║   CODE:                                                                                                                 ║
2022-04-14T08:49:04.916518516Z ║   EREQUEST                                                                                                              ║
2022-04-14T08:49:04.916522743Z ║                                                                                                                         ║
2022-04-14T08:49:04.916526629Z ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
2022-04-14T08:49:04.916529968Z ║   STACK:                                                                                                                ║
2022-04-14T08:49:04.916533321Z ║   RequestError:                                                                                                         ║
2022-04-14T08:49:04.916536660Z ║   ALTER TABLE [dbo].[123] ALTER COLUMN [TestColumn] varchar();                                                          ║
2022-04-14T08:49:04.916540325Z ║                                                                                                                         ║
2022-04-14T08:49:04.916543804Z ║   ALTER TABLE [dbo].[123] ALTER COLUMN [TestColumn] TYPE varchar;                                                       ║
2022-04-14T08:49:04.916547249Z ║    - Incorrect syntax near 'varchar'.                                                                                   ║
2022-04-14T08:49:04.916550669Z ║       at handleError (/usr/src/app/node_modules/mssql/lib/tedious/request.js:374:15)                                    ║
2022-04-14T08:49:04.916554323Z ║       at Connection.emit (events.js:314:20)                                                                             ║
2022-04-14T08:49:04.916557686Z ║       at Connection.EventEmitter.emit (domain.js:483:12)                                                                ║
2022-04-14T08:49:04.916561052Z ║       at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:832:12)                                ║
2022-04-14T08:49:04.916565336Z ║       at Parser.emit (events.js:314:20)                                                                                 ║
2022-04-14T08:49:04.916568686Z ║       at Parser.EventEmitter.emit (domain.js:483:12)                                                                    ║
2022-04-14T08:49:04.916572025Z ║       at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:37:14)                  ║
2022-04-14T08:49:04.916580726Z ║       at Parser.emit (events.js:314:20)                                                                                 ║
2022-04-14T08:49:04.916584650Z ║       at Parser.EventEmitter.emit (domain.js:483:12)                                                                    ║
2022-04-14T08:49:04.916588038Z ║       at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12)                            ║
2022-04-14T08:49:04.916591606Z ║                                                                                                                         ║
2022-04-14T08:49:04.916594966Z ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
2022-04-14T08:49:04.916598421Z ║                                                                                                                         ║
2022-04-14T08:49:04.916601799Z ║                                                                                                                         ║
2022-04-14T08:49:04.916605225Z ╚═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
2022-04-14T08:49:04.917477858Z RequestError: 
2022-04-14T08:49:04.917510542Z ALTER TABLE [dbo].[123] ALTER COLUMN [TestColumn] varchar();
2022-04-14T08:49:04.917514988Z 
2022-04-14T08:49:04.917519276Z ALTER TABLE [dbo].[123] ALTER COLUMN [TestColumn] TYPE varchar;
2022-04-14T08:49:04.917522963Z  - Incorrect syntax near 'varchar'.
2022-04-14T08:49:04.917526402Z     at handleError (/usr/src/app/node_modules/mssql/lib/tedious/request.js:374:15)
2022-04-14T08:49:04.917530260Z     at Connection.emit (events.js:314:20)
2022-04-14T08:49:04.917533622Z     at Connection.EventEmitter.emit (domain.js:483:12)
2022-04-14T08:49:04.917536925Z     at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:832:12)
2022-04-14T08:49:04.917540525Z     at Parser.emit (events.js:314:20)
2022-04-14T08:49:04.917543980Z     at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-14T08:49:04.917547260Z     at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
2022-04-14T08:49:04.917550691Z     at Parser.emit (events.js:314:20)
2022-04-14T08:49:04.917553901Z     at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-14T08:49:04.917557236Z     at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12) {
2022-04-14T08:49:04.917560772Z   code: 'EREQUEST',
2022-04-14T08:49:04.917564409Z   originalError: Error: Incorrect syntax near 'varchar'.
2022-04-14T08:49:04.917567765Z       at handleError (/usr/src/app/node_modules/mssql/lib/tedious/request.js:372:19)
2022-04-14T08:49:04.917589800Z       at Connection.emit (events.js:314:20)
2022-04-14T08:49:04.917593293Z       at Connection.EventEmitter.emit (domain.js:483:12)
2022-04-14T08:49:04.917596534Z       at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:832:12)
2022-04-14T08:49:04.917600028Z       at Parser.emit (events.js:314:20)
2022-04-14T08:49:04.917603152Z       at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-14T08:49:04.917606458Z       at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
2022-04-14T08:49:04.917609848Z       at Parser.emit (events.js:314:20)
2022-04-14T08:49:04.917612975Z       at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-14T08:49:04.917616183Z       at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12) {
2022-04-14T08:49:04.917619596Z     info: ErrorMessageToken {
2022-04-14T08:49:04.917622854Z       name: 'ERROR',
2022-04-14T08:49:04.917625986Z       event: 'errorMessage',
2022-04-14T08:49:04.917629117Z       number: 102,
2022-04-14T08:49:04.917632381Z       state: 1,
2022-04-14T08:49:04.917635535Z       class: 15,
2022-04-14T08:49:04.917638649Z       message: "Incorrect syntax near 'varchar'.",
2022-04-14T08:49:04.917642022Z       serverName: 'SERVER_NAME',
2022-04-14T08:49:04.917645196Z       procName: '',
2022-04-14T08:49:04.917648287Z       lineNumber: 4
2022-04-14T08:49:04.917651375Z     }
2022-04-14T08:49:04.917654547Z   },
2022-04-14T08:49:04.917657715Z   number: 102,
2022-04-14T08:49:04.917660858Z   lineNumber: 4,
2022-04-14T08:49:04.917664028Z   state: 1,
2022-04-14T08:49:04.917667205Z   class: 15,
2022-04-14T08:49:04.917670278Z   serverName: 'SERVER_NAME',
2022-04-14T08:49:04.917673899Z   procName: '',
2022-04-14T08:49:04.917676972Z   precedingErrors: [
2022-04-14T08:49:04.917680093Z     RequestError: Incorrect syntax near ')'.
2022-04-14T08:49:04.917703030Z         at handleError (/usr/src/app/node_modules/mssql/lib/tedious/request.js:374:15)
2022-04-14T08:49:04.917718595Z         at Connection.emit (events.js:314:20)
2022-04-14T08:49:04.917722788Z         at Connection.EventEmitter.emit (domain.js:483:12)
2022-04-14T08:49:04.917726894Z         at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:832:12)
2022-04-14T08:49:04.917731752Z         at Parser.emit (events.js:314:20)
2022-04-14T08:49:04.917736840Z         at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-14T08:49:04.917741573Z         at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
2022-04-14T08:49:04.917759311Z         at Parser.emit (events.js:314:20)
2022-04-14T08:49:04.917764690Z         at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-14T08:49:04.917769445Z         at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12) {
2022-04-14T08:49:04.917773995Z       code: 'EREQUEST',
2022-04-14T08:49:04.917779035Z       originalError: [Error],
2022-04-14T08:49:04.917783956Z       number: 102,
2022-04-14T08:49:04.917788762Z       lineNumber: 2,
2022-04-14T08:49:04.917792945Z       state: 1,
2022-04-14T08:49:04.917797274Z       class: 15,
2022-04-14T08:49:04.917801730Z       serverName: 'SERVER_NAME',
2022-04-14T08:49:04.917806650Z       procName: ''
2022-04-14T08:49:04.917811940Z     }
2022-04-14T08:49:04.917816511Z   ]
2022-04-14T08:49:04.917820950Z }
2022-04-14T08:49:04.917825883Z RequestError: 
2022-04-14T08:49:04.917830297Z ALTER TABLE [dbo].[123] ALTER COLUMN [TestColumn] varchar();
2022-04-14T08:49:04.917833973Z 
2022-04-14T08:49:04.917837214Z ALTER TABLE [dbo].[123] ALTER COLUMN [TestColumn] TYPE varchar;
2022-04-14T08:49:04.917840647Z  - Incorrect syntax near 'varchar'.
2022-04-14T08:49:04.917844074Z     at handleError (/usr/src/app/node_modules/mssql/lib/tedious/request.js:374:15)
2022-04-14T08:49:04.917847940Z     at Connection.emit (events.js:314:20)
2022-04-14T08:49:04.917851171Z     at Connection.EventEmitter.emit (domain.js:483:12)
2022-04-14T08:49:04.917854408Z     at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:832:12)
2022-04-14T08:49:04.917857932Z     at Parser.emit (events.js:314:20)
2022-04-14T08:49:04.917861297Z     at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-14T08:49:04.917865133Z     at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
2022-04-14T08:49:04.917868613Z     at Parser.emit (events.js:314:20)
2022-04-14T08:49:04.917871795Z     at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-14T08:49:04.917875224Z     at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12) {
2022-04-14T08:49:04.917878586Z   code: 'EREQUEST',
2022-04-14T08:49:04.917881870Z   originalError: Error: Incorrect syntax near 'varchar'.
2022-04-14T08:49:04.917885324Z       at handleError (/usr/src/app/node_modules/mssql/lib/tedious/request.js:372:19)
2022-04-14T08:49:04.917888862Z       at Connection.emit (events.js:314:20)
2022-04-14T08:49:04.917892243Z       at Connection.EventEmitter.emit (domain.js:483:12)
2022-04-14T08:49:04.917895606Z       at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:832:12)
2022-04-14T08:49:04.917899278Z       at Parser.emit (events.js:314:20)
2022-04-14T08:49:04.917927872Z       at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-14T08:49:04.917931469Z       at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
2022-04-14T08:49:04.917934920Z       at Parser.emit (events.js:314:20)
2022-04-14T08:49:04.917938060Z       at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-14T08:49:04.917941338Z       at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12) {
2022-04-14T08:49:04.917944803Z     info: ErrorMessageToken {
2022-04-14T08:49:04.917948255Z       name: 'ERROR',
2022-04-14T08:49:04.917951541Z       event: 'errorMessage',
2022-04-14T08:49:04.917954746Z       number: 102,
2022-04-14T08:49:04.917957897Z       state: 1,
2022-04-14T08:49:04.917961090Z       class: 15,
2022-04-14T08:49:04.917964200Z       message: "Incorrect syntax near 'varchar'.",
2022-04-14T08:49:04.917967844Z       serverName: 'SERVER_NAME',
2022-04-14T08:49:04.917971015Z       procName: '',
2022-04-14T08:49:04.917974149Z       lineNumber: 4
2022-04-14T08:49:04.917977302Z     }
2022-04-14T08:49:04.917980459Z   },
2022-04-14T08:49:04.917983632Z   number: 102,
2022-04-14T08:49:04.917986796Z   lineNumber: 4,
2022-04-14T08:49:04.917989872Z   state: 1,
2022-04-14T08:49:04.917992954Z   class: 15,
2022-04-14T08:49:04.917996189Z   serverName: 'SERVER_NAME',
2022-04-14T08:49:04.917999591Z   procName: '',
2022-04-14T08:49:04.918002727Z   precedingErrors: [
2022-04-14T08:49:04.918005856Z     RequestError: Incorrect syntax near ')'.
2022-04-14T08:49:04.918009402Z         at handleError (/usr/src/app/node_modules/mssql/lib/tedious/request.js:374:15)
2022-04-14T08:49:04.918012692Z         at Connection.emit (events.js:314:20)
2022-04-14T08:49:04.918015955Z         at Connection.EventEmitter.emit (domain.js:483:12)
2022-04-14T08:49:04.918019237Z         at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:832:12)
2022-04-14T08:49:04.918022648Z         at Parser.emit (events.js:314:20)
2022-04-14T08:49:04.918025773Z         at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-14T08:49:04.918028977Z         at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
2022-04-14T08:49:04.918032390Z         at Parser.emit (events.js:314:20)
2022-04-14T08:49:04.918035527Z         at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-14T08:49:04.918038792Z         at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12) {
2022-04-14T08:49:04.918042095Z       code: 'EREQUEST',
2022-04-14T08:49:04.918050666Z       originalError: [Error],
2022-04-14T08:49:04.918054069Z       number: 102,
2022-04-14T08:49:04.918057198Z       lineNumber: 2,
2022-04-14T08:49:04.918060325Z       state: 1,
2022-04-14T08:49:04.918063438Z       class: 15,
2022-04-14T08:49:04.918066577Z       serverName: 'SERVER_NAME',
2022-04-14T08:49:04.918069868Z       procName: ''
2022-04-14T08:49:04.918073075Z     }
2022-04-14T08:49:04.918076253Z   ]
2022-04-14T08:49:04.918079879Z }
2022-04-14T08:49:04.919052543Z POST /dashboard/?q=sqlOpPlus_tableUpdate 500 176 - 32.028 ms
2022-04-14T08:49:24.988588551Z POST /dashboard/?q=sqlOp_xcRelease - - - - ms

**Comment by o1lab** [comment]
Could you please try this with latest version (0.90.5)

**Comment by stepanof** [comment]
I have change root db for pg.
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mssql**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.90.5**

I still can't change type of the column. By the way now I dont
Log is here:
```
2022-04-20T17:55:10.587711425Z ╔═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
2022-04-20T17:55:10.587746644Z ║                                                                                                                         ║
2022-04-20T17:55:10.587751421Z ║                                                 EXCEPTION OCCURED!! in MssqlClient @ tableUpdate                        ║
2022-04-20T17:55:10.587755204Z ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
2022-04-20T17:55:10.587758751Z ║   MESSAGE:                                                                                                              ║
2022-04-20T17:55:10.587762465Z ║                                                                                                                         ║
2022-04-20T17:55:10.587766144Z ║   ALTER TABLE [dbo].[complan__t_e_s_t] ALTER COLUMN [12] TYPE varchar;                                                  ║
2022-04-20T17:55:10.587769576Z ║    - Incorrect syntax near 'varchar'.                                                                                   ║
2022-04-20T17:55:10.587772933Z ║                                                                                                                         ║
2022-04-20T17:55:10.587791741Z ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
2022-04-20T17:55:10.587795324Z ║   CODE:                                                                                                                 ║
2022-04-20T17:55:10.587798708Z ║   EREQUEST                                                                                                              ║
2022-04-20T17:55:10.587802188Z ║                                                                                                                         ║
2022-04-20T17:55:10.587805527Z ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
2022-04-20T17:55:10.587809432Z ║   STACK:                                                                                                                ║
2022-04-20T17:55:10.587813119Z ║   RequestError:                                                                                                         ║
2022-04-20T17:55:10.587816435Z ║   ALTER TABLE [dbo].[complan__t_e_s_t] ALTER COLUMN [12] TYPE varchar;                                                  ║
2022-04-20T17:55:10.587820049Z ║    - Incorrect syntax near 'varchar'.                                                                                   ║
2022-04-20T17:55:10.587823665Z ║       at handleError (/usr/src/app/node_modules/mssql/lib/tedious/request.js:374:15)                                    ║
2022-04-20T17:55:10.587827033Z ║       at Connection.emit (events.js:314:20)                                                                             ║
2022-04-20T17:55:10.587830353Z ║       at Connection.EventEmitter.emit (domain.js:483:12)                                                                ║
2022-04-20T17:55:10.587833673Z ║       at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:832:12)                                ║
2022-04-20T17:55:10.587837579Z ║       at Parser.emit (events.js:314:20)                                                                                 ║
2022-04-20T17:55:10.587840938Z ║       at Parser.EventEmitter.emit (domain.js:483:12)                                                                    ║
2022-04-20T17:55:10.587844270Z ║       at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:37:14)                  ║
2022-04-20T17:55:10.587847909Z ║       at Parser.emit (events.js:314:20)                                                                                 ║
2022-04-20T17:55:10.587851264Z ║       at Parser.EventEmitter.emit (domain.js:483:12)                                                                    ║
2022-04-20T17:55:10.587854645Z ║       at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12)                            ║
2022-04-20T17:55:10.587858005Z ║                                                                                                                         ║
2022-04-20T17:55:10.587865500Z ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
2022-04-20T17:55:10.587869333Z ║                                                                                                                         ║
2022-04-20T17:55:10.587872825Z ║                                                                                                                         ║
2022-04-20T17:55:10.587876301Z ╚═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
2022-04-20T17:55:10.588247785Z RequestError: 
2022-04-20T17:55:10.588266275Z ALTER TABLE [dbo].[complan__t_e_s_t] ALTER COLUMN [12] TYPE varchar;
2022-04-20T17:55:10.588270522Z  - Incorrect syntax near 'varchar'.
2022-04-20T17:55:10.588273912Z     at handleError (/usr/src/app/node_modules/mssql/lib/tedious/request.js:374:15)
2022-04-20T17:55:10.588277374Z     at Connection.emit (events.js:314:20)
2022-04-20T17:55:10.588280671Z     at Connection.EventEmitter.emit (domain.js:483:12)
2022-04-20T17:55:10.588284119Z     at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:832:12)
2022-04-20T17:55:10.588287789Z     at Parser.emit (events.js:314:20)
2022-04-20T17:55:10.588290938Z     at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-20T17:55:10.588294165Z     at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
2022-04-20T17:55:10.588297723Z     at Parser.emit (events.js:314:20)
2022-04-20T17:55:10.588300885Z     at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-20T17:55:10.588304067Z     at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12) {
2022-04-20T17:55:10.588307509Z   code: 'EREQUEST',
2022-04-20T17:55:10.588310797Z   originalError: Error: Incorrect syntax near 'varchar'.
2022-04-20T17:55:10.588314184Z       at handleError (/usr/src/app/node_modules/mssql/lib/tedious/request.js:372:19)
2022-04-20T17:55:10.588317496Z       at Connection.emit (events.js:314:20)
2022-04-20T17:55:10.588320664Z       at Connection.EventEmitter.emit (domain.js:483:12)
2022-04-20T17:55:10.588323950Z       at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:832:12)
2022-04-20T17:55:10.588327510Z       at Parser.emit (events.js:314:20)
2022-04-20T17:55:10.588330685Z       at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-20T17:55:10.588333958Z       at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
2022-04-20T17:55:10.588337361Z       at Parser.emit (events.js:314:20)
2022-04-20T17:55:10.588340577Z       at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-20T17:55:10.588355654Z       at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12) {
2022-04-20T17:55:10.588359137Z     info: ErrorMessageToken {
2022-04-20T17:55:10.588362352Z       name: 'ERROR',
2022-04-20T17:55:10.588365522Z       event: 'errorMessage',
2022-04-20T17:55:10.588368691Z       number: 102,
2022-04-20T17:55:10.588371882Z       state: 1,
2022-04-20T17:55:10.588374991Z       class: 15,
2022-04-20T17:55:10.588378100Z       message: "Incorrect syntax near 'varchar'.",
2022-04-20T17:55:10.588381718Z       serverName: 'SERVER_NAME',
2022-04-20T17:55:10.588385006Z       procName: '',
2022-04-20T17:55:10.588388078Z       lineNumber: 2
2022-04-20T17:55:10.588391205Z     }
2022-04-20T17:55:10.588394350Z   },
2022-04-20T17:55:10.588397504Z   number: 102,
2022-04-20T17:55:10.588400656Z   lineNumber: 2,
2022-04-20T17:55:10.588403766Z   state: 1,
2022-04-20T17:55:10.588406840Z   class: 15,
2022-04-20T17:55:10.588409966Z   serverName: 'SERVER_NAME',
2022-04-20T17:55:10.588413143Z   procName: '',
2022-04-20T17:55:10.588416343Z   precedingErrors: []
2022-04-20T17:55:10.588421475Z }
2022-04-20T17:55:10.588430140Z x :: RequestError: 
2022-04-20T17:55:10.588433454Z ALTER TABLE [dbo].[complan__t_e_s_t] ALTER COLUMN [12] TYPE varchar;
2022-04-20T17:55:10.588436779Z  - Incorrect syntax near 'varchar'.
2022-04-20T17:55:10.588439945Z     at handleError (/usr/src/app/node_modules/mssql/lib/tedious/request.js:374:15)
2022-04-20T17:55:10.588443400Z     at Connection.emit (events.js:314:20)
2022-04-20T17:55:10.588446570Z     at Connection.EventEmitter.emit (domain.js:483:12)
2022-04-20T17:55:10.588449811Z     at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:832:12)
2022-04-20T17:55:10.588453200Z     at Parser.emit (events.js:314:20)
2022-04-20T17:55:10.588456595Z     at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-20T17:55:10.588459823Z     at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
2022-04-20T17:55:10.588463215Z     at Parser.emit (events.js:314:20)
2022-04-20T17:55:10.588466329Z     at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-20T17:55:10.588469694Z     at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12) {
2022-04-20T17:55:10.588473024Z   code: 'EREQUEST',
2022-04-20T17:55:10.588476267Z   originalError: Error: Incorrect syntax near 'varchar'.
2022-04-20T17:55:10.588479487Z       at handleError (/usr/src/app/node_modules/mssql/lib/tedious/request.js:372:19)
2022-04-20T17:55:10.588488146Z       at Connection.emit (events.js:314:20)
2022-04-20T17:55:10.588491476Z       at Connection.EventEmitter.emit (domain.js:483:12)
2022-04-20T17:55:10.588494915Z       at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:832:12)
2022-04-20T17:55:10.588498232Z       at Parser.emit (events.js:314:20)
2022-04-20T17:55:10.588501366Z       at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-20T17:55:10.588504583Z       at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
2022-04-20T17:55:10.588508222Z       at Parser.emit (events.js:314:20)
2022-04-20T17:55:10.588511331Z       at Parser.EventEmitter.emit (domain.js:483:12)
2022-04-20T17:55:10.588514496Z       at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12) {
2022-04-20T17:55:10.588517783Z     info: ErrorMessageToken {
2022-04-20T17:55:10.588520917Z       name: 'ERROR',
2022-04-20T17:55:10.588524028Z       event: 'errorMessage',
2022-04-20T17:55:10.588527170Z       number: 102,
2022-04-20T17:55:10.588530260Z       state: 1,
2022-04-20T17:55:10.588533348Z       class: 15,
2022-04-20T17:55:10.588536484Z       message: "Incorrect syntax near 'varchar'.",
2022-04-20T17:55:10.588539777Z       serverName: 'SERVER_NAME',
2022-04-20T17:55:10.588543002Z       procName: '',
2022-04-20T17:55:10.588546111Z       lineNumber: 2
2022-04-20T17:55:10.588549233Z     }
2022-04-20T17:55:10.588552315Z   },
2022-04-20T17:55:10.588555421Z   number: 102,
2022-04-20T17:55:10.588558515Z   lineNumber: 2,
2022-04-20T17:55:10.588561590Z   state: 1,
2022-04-20T17:55:10.588564735Z   class: 15,
2022-04-20T17:55:10.588567832Z   serverName: 'SERVER_NAME',
2022-04-20T17:55:10.588570971Z   procName: '',
2022-04-20T17:55:10.588574078Z   precedingErrors: []
2022-04-20T17:55:10.588577197Z }
```

**Comment by wingkwong** [comment]
Able to reproduce. The table is on MSSQL.

**Comment by lvarming** [comment]
I got a similar error I guess. When I try to change the coloumn type I get this error:
`ALTER TABLE [dbo].[Sheet-1] ALTER COLUMN [title] int(); - Incorrect syntax near ')'`

NocoDB used as docker : false
NocoDB version : 0.101.0
Database used in NC_DB URL : MS SQL 14
Project was created by clicking : New Project 
OS on which NocoDB is running : Windows executable

**Comment by dstala** [comment]
We have not noticed much traction with usage of MS SQL Server support & hence we decided to narrow down support mainly to MySQL & PG. Please feel free to connect with us to discuss more on your use-case [here](https://cal.com/nocodb).
