### ISSUE TITLE
Project info access fails in commenter/ viewer mode

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1694]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.84.16**

- copy project info to clipboard fails in commenter/ viewer mode
- was enabled in NC v1

```
projectAclMiddleware :: Forbidden [Error]: projectInfoGet - viewer : Not allowed
    at Function.forbidden (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/catchError.ts:47:11)
    at projectAclMiddleware (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/ncMetaAclMw.ts:63:17)
    at /Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/catchError.ts:6:20
    at Layer.handle [as handle_request] (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/express/lib/router/route.js:137:13)
    at authMiddleware (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/ncMetaAclMw.ts:23:7)
    at /Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/catchError.ts:6:20
    at Layer.handle [as handle_request] (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/express/lib/router/route.js:137:13)
    at exports.default (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/extractProjectIdAndAuthenticate.ts:141:5)
```

**Comment by wingkwong** [comment]
Fixed in ``v0.90.7``.
