### ISSUE TITLE
relation update in editor mode fail

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#1706]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.84.16**

- country hm city relation
- open city table
- switch to editor preview mode
- edit CountryRead field

```
projectAclMiddleware :: Forbidden [Error]: relationDataAdd - editor : Not allowed
    at Function.forbidden (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/catchError.ts:47:11)
    at projectAclMiddleware (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/ncMetaAclMw.ts:63:17)
    at /Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/catchError.ts:6:20
    at Layer.handle [as handle_request] (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/express/lib/router/route.js:137:13)
    at authMiddleware (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/ncMetaAclMw.ts:23:7)
    at /Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/catchError.ts:6:20
    at Layer.handle [as handle_request] (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/express/lib/router/route.js:137:13)
    at exports.default (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/extractProjectIdAndAuthenticate.ts:141:5)
```

![Screenshot 2022-04-16 at 4 41 53 PM](https://user-images.githubusercontent.com/86527202/163672813-695490cc-ff74-48fb-829e-c94429825d36.png)

**Comment by wingkwong** [comment]
Fixed in ``v0.90.7``.
