### ISSUE TITLE
Migration from 0084002 to 0090000 failed (mssql, docker)

### ISSUE THREAD

**Issue by pnose** [nocodb/nocodb#1741]
**Please enter the following details**

please provide the following details :
NocoDB used as docker : true
NocoDB version : 0.90.2
Database used in NC_DB URL  : mssql
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : mssql
OS on which NocoDB is running : Linux
Node.js version if running as node : 
Database version : 15.0.4198.2

**Steps To Reproduce**
1. docker stop; docker rm
2. Update docker image to latest (7acb3a131123)
3. docker run
4. Dashboard isn't shown in frontend ("Cannot GET /")
5. See error

**Expected behavior**
Frontend starting; Dashboard shown; Migration done; No error in log

**Error**
Visit -> http://localhost:8080/dashboard
Mon, 18 Apr 2022 07:22:49 GMT tedious deprecated The default value for `config.options.enableArithAbort` will change from `false` to `true` in the next major version of `tedious`. Set the value to `true` or `false` explicitly to silence this message. at node_modules/mssql/lib/tedious/connection-pool.js:61:23
(node:10) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
Creating REST APIs mssql - > projectdb
┌ Migration from 0084002 to 0090000 failed ────────────────────────────────────┐│                                                                              ││   Error                                                                      ││   -----                                                                      ││   TransactionError: insert into [nc_columns_v2] ([ai], [au], [base_id],      ││   [cc], [cdf], [clen], [column_name], [cop], [created_at], [csn], [ct],      ││   [dt], [dtx], [dtxp], [dtxs], [fk_model_id], [id], [np], [ns], [order],     ││   [pk], [project_id], [pv], [rqd], [system], [title], [uidt], [un],          ││   [unique], [updated_at]) values (DEFAULT, DEFAULT, @p0, DEFAULT, DEFAULT,   ││   DEFAULT, DEFAULT, DEFAULT, CURRENT_TIMESTAMP, DEFAULT, DEFAULT, DEFAULT,   ││   DEFAULT, DEFAULT, DEFAULT, @p1, @p2, DEFAULT, DEFAULT, DEFAULT, DEFAULT,   ││   @p3, DEFAULT, DEFAULT, DEFAULT, @p4, @p5, DEFAULT, DEFAULT,                ││   CURRENT_TIMESTAMP) - Can't acquire connection for the request. There is    ││   another request in progress.                                               ││   at Transaction.acquire                                                     ││   (/usr/src/app/node_modules/mssql/lib/base/transaction.js:63:30)            ││   at Immediate.<anonymous>                                                   ││   (/usr/src/app/node_modules/mssql/lib/tedious/request.js:409:19)            ││   at processImmediate (internal/timers.js:461:21)                            ││                                                                              ││                                                                              ││   Please raise an issue in our github by using following link :              ││   https://github.com/nocodb/nocodb/issues/new?labels=Type%3A%20Bug&templat   ││   e=bug_report.md                                                            ││                                                                              ││   Or contact us in our Discord community by following link :                 ││   https://discord.gg/5RgZmkW ( message @o1lab, @pranavxc or @wingkwong )     ││                                                                              │└──────────────────────────────────────────────────────────────────────────────┘
TransactionError: insert into [nc_columns_v2] ([ai], [au], [base_id], [cc], [cdf], [clen], [column_name], [cop], [created_at], [csn], [ct], [dt], [dtx], [dtxp], [dtxs], [fk_model_id], [id], [np], [ns], [order], [pk], [project_id], [pv], [rqd], [system], [title], [uidt], [un], [unique], [updated_at]) values (DEFAULT, DEFAULT, @p0, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, CURRENT_TIMESTAMP, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, @p1, @p2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, @p3, DEFAULT, DEFAULT, DEFAULT, @p4, @p5, DEFAULT, DEFAULT, CURRENT_TIMESTAMP) - Can't acquire connection for the request. There is another request in progress.
    at Transaction.acquire (/usr/src/app/node_modules/mssql/lib/base/transaction.js:63:30)
    at Immediate.<anonymous> (/usr/src/app/node_modules/mssql/lib/tedious/request.js:409:19)
    at processImmediate (internal/timers.js:461:21) {
  code: 'EREQINPROG'
}

**Comment by pnose** [comment]
Oh, sorry, this seems to be already reported in https://github.com/nocodb/nocodb/issues/1736. Will close it here and follow the other thread.
