### ISSUE TITLE
Bug: Cannot read property 'cn' of undefined

### ISSUE THREAD

**Issue by brakmic** [nocodb/nocodb#178]
Some of my Swagger API calls return this error: 

`Cannot read property 'cn' of undefined`

This is the console output of my local nocodb instance.

```shell
TypeError: Cannot read property 'cn' of undefined
    at _0x40cfce._paginateAndSort (C:\projects\other\nocodb-seed\node_modules\.pnpm\nocodb@0.9.13\node_modules\nocodb\dist\bundle.js:529:36439)
    at _0x40cfce.list (C:\projects\other\nocodb-seed\node_modules\.pnpm\nocodb@0.9.13\node_modules\nocodb\dist\bundle.js:529:16994)
    at _0x4d04a8.list (C:\projects\other\nocodb-seed\node_modules\.pnpm\nocodb@0.9.13\node_modules\nocodb\dist\bundle.js:441:1611)
    at C:\projects\other\nocodb-seed\node_modules\.pnpm\nocodb@0.9.13\node_modules\nocodb\dist\bundle.js:1:99068
    at Layer.handle [as handle_request] (C:\projects\other\nocodb-seed\node_modules\.pnpm\express@4.17.1\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\projects\other\nocodb-seed\node_modules\.pnpm\express@4.17.1\node_modules\express\lib\router\route.js:137:13)
    at _0x4d04a8.middleware (C:\projects\other\nocodb-seed\node_modules\.pnpm\nocodb@0.9.13\node_modules\nocodb\dist\bundle.js:441:8998)
    at Layer.handle [as handle_request] (C:\projects\other\nocodb-seed\node_modules\.pnpm\express@4.17.1\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\projects\other\nocodb-seed\node_modules\.pnpm\express@4.17.1\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\projects\other\nocodb-seed\node_modules\.pnpm\express@4.17.1\node_modules\express\lib\router\route.js:112:3)
```

**Comment by myso42** [comment]
Same here, connecting to MSSQL server. cannot get any data, error on all of my tables

**Comment by pranavxc** [comment]
Please share the API details which throw the error.

**Comment by o1lab** [comment]
Feel free to reopen with more details.
