### ISSUE TITLE
"SSL/TLS required" when running `npx create-nocodb-app`

### ISSUE THREAD

**Issue by ryancwalsh** [nocodb/nocodb#1798]
NocoDB used as docker : false
NocoDB version : latest
Database used in NC_DB URL  : pg
OS on which NocoDB is running : Mac
Node.js version if running as node : node -v v17.8.0

Database version : PostgreSQL Version | 14

**Steps To Reproduce**
1. Create a new empty postgres DB on Render.com (free)
2. In Mac terminal, type `npx create-nocodb-app`
3. Choose "pg" and provide the credentials for the new Render.com postgres DB.
4. Choose to run "As Node.js Project"
5. See error:

```
EXCEPTION OCCURED!! in PGClient @ createDatabaseIfNotExists             ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   MESSAGE:                                                                                                              ║
║   SSL/TLS required                                                                                                      ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   CODE:                                                                                                                 ║
║   28000                                                                                                                 ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   STACK:                                                                                                                ║
║   error: SSL/TLS required                                                                                               ║
║       at Parser.parseErrorMessage (/Users/rcwalsh/code/colonial_lark/node_modules/pg-protocol/dist/parser.js:287:98)
```

**Expected behavior**
Should start the basic app.

**Comment by ryancwalsh** [comment]
I also just tried the same steps as above but after creating a free Postgres DB on Heroku.com.

Then after responding to the prompts of `npx create-nocodb-app`, I get this error:

```

event-loop-stats not found, ignoring event loop metrics...
╔═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                                                             ║
║                                                 EXCEPTION OCCURED!! in PGClient @ createDatabaseIfNotExists                 ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -       ║
║   MESSAGE:                                                                                                                  ║
║   no pg_hba.conf entry for host "76.204.99.175", user "mxzzjwxjbrtxww", database "daj92f867nfeqt", no encryption            ║
║                                                                                                                             ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -       ║
║   CODE:                                                                                                                     ║
║   28000                                                                                                                     ║
║                                                                                                                             ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -       ║
║   STACK:                                                                                                                    ║
║   error: no pg_hba.conf entry for host "76.204.99.175", user "mxzzjwxjbrtxww", database "daj92f867nfeqt", no encryption     ║
║       at Parser.parseErrorMessage (/Users/rcwalsh/code/tropical_swordfish/node_modules/pg-protocol/dist/parser.js:287:98)
```

**Comment by o1lab** [comment]
Please see this [discussion](https://github.com/nocodb/nocodb/discussions/838)

**Comment by ryancwalsh** [comment]
@o1lab Thanks for pointing me there. I've read through it and still don't know how to proceed, though.

Do you agree that it's a bizarre first experience to follow the instructions for `npx create-nocodb-app` and get this SSL error?  It's not clear to me how anyone is successfully using this. 

As I mentioned, I tried not just Render.com but also Heroku, so I know it's not the database's fault.

Thanks for any tips! :-)

**Comment by platform-kit** [comment]
I have also run into this issue with a brand new database (hosted on Render.com). I am able to connect to the database in other contexts - i.e. through TablePlus, or through a node.js script. But not through nocodb's Heroku deployment.

**Comment by 2567910** [comment]
Same here.  If i try to connect to a Digital Ocean DB.

**Comment by o1lab** [comment]
We do not recommend npx any more. Closing this.
