### ISSUE TITLE
Migration from 0084002 to 0090000 (sqlserver)

### ISSUE THREAD

**Issue by titouancreach** [nocodb/nocodb#1855]
Hello, Nocodb broke this morning for us. 
```
2022-04-25T06:58:22.488147876Z Mon, 25 Apr 2022 06:58:22 GMT tedious deprecated The default value for `config.options.enableArithAbort` will change from `false` to `true` in the next major version of `tedious`. Set the value to `true` or `false` explicitly to silence this message. at node_modules/mssql/lib/tedious/connection-pool.js:61:23
2022-04-25T06:58:23.254056076Z Creating REST APIs mssql - > retracted
2022-04-25T06:58:25.830860565Z ┌ Migration from 0084002 to 0090000 failed ────────────────────────────────────┐│                                                                              ││   Error                                                                      ││   -----                                                                      ││   TransactionError: insert into [nc_columns_v2] ([ai], [au], [base_id],      ││   [cc], [cdf], [clen], [column_name], [cop], [created_at], [csn], [ct],      ││   [dt], [dtx], [dtxp], [dtxs], [fk_model_id], [id], [np], [ns], [order],     ││   [pk], [project_id], [pv], [rqd], [system], [title], [uidt], [un],          ││   [unique], [updated_at]) values (DEFAULT, DEFAULT, @p0, DEFAULT, DEFAULT,   ││   DEFAULT, DEFAULT, DEFAULT, CURRENT_TIMESTAMP, DEFAULT, DEFAULT, DEFAULT,││   DEFAULT, DEFAULT, DEFAULT, @p1, @p2, DEFAULT, DEFAULT, DEFAULT, DEFAULT,   ││   @p3, DEFAULT, DEFAULT, DEFAULT, @p4, @p5, DEFAULT, DEFAULT,                ││   CURRENT_TIMESTAMP) - Can't acquire connection for the request. There is    ││   another request in progress.                                               ││   at Transaction.acquire                                                     ││   (/usr/src/app/node_modules/mssql/lib/base/transaction.js:63:30)            ││   at Immediate.<anonymous>                                                   ││   (/usr/src/app/node_modules/mssql/lib/tedious/request.js:409:19)            ││   at processImmediate (internal/timers.js:461:21)                            ││                                                                              ││                                                                              ││   Please raise an issue in our github by using following link :              ││   https://github.com/nocodb/nocodb/issues/new?labels=Type%3A%20Bug&templat   ││   e=bug_report.md                                                            ││                                                                              ││   Or contact us in our Discord community by following link :                 ││   https://discord.gg/5RgZmkW ( message @o1lab, @pranavxc or @wingkwong )     ││                                                                              │└──────────────────────────────────────────────────────────────────────────────┘
2022-04-25T06:58:25.860136082Z TransactionError: insert into [nc_columns_v2] ([ai], [au], [base_id], [cc], [cdf], [clen], [column_name], [cop], [created_at], [csn], [ct], [dt], [dtx], [dtxp], [dtxs], [fk_model_id], [id], [np], [ns], [order], [pk], [project_id], [pv], [rqd], [system], [title], [uidt], [un], [unique], [updated_at]) values (DEFAULT, DEFAULT, @p0, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, CURRENT_TIMESTAMP, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, @p1, @p2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, @p3, DEFAULT, DEFAULT, DEFAULT, @p4, @p5, DEFAULT, DEFAULT, CURRENT_TIMESTAMP) - Can't acquire connection for the request. There is another request in progress.
2022-04-25T06:58:25.860221983Z     at Transaction.acquire (/usr/src/app/node_modules/mssql/lib/base/transaction.js:63:30)
2022-04-25T06:58:25.860246884Z     at Immediate.<anonymous> (/usr/src/app/node_modules/mssql/lib/tedious/request.js:409:19)
2022-04-25T06:58:25.860251684Z     at processImmediate (internal/timers.js:461:21) {
2022-04-25T06:58:25.860255484Z   code: 'EREQINPROG'
2022-04-25T06:58:25.860258984Z }
```

Do you have any workaround to fix this ? 

Thanks very much

**Comment by titouancreach** [comment]
dup of #1790 probably
