### ISSUE TITLE
DATEADD function interval argument issue

### ISSUE THREAD

**Issue by RawmanGrey** [nocodb/nocodb#1865]
DATEADD function throws error if other column referenced as interval argument. Error's message complains that 'column_name' is not a valid syntax for interval type. 

Desired behavior for this function is beyond just accepting columns-variables: it has to work with any nested logic depending on user defined data in other columns, e.g. `DATEADD(NOW(), MAX(column_of_number_type, 3), "hour")`, same as other functions.

This issue is likely related to #1816 

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.90.7**

**Comment by wingkwong** [comment]
Able to reproduce on PG only. @mertmit please take a look.

```bash
  knex:query select CASE
  knex:query       WHEN CAST("dt" AS text) LIKE '%:%' THEN
  knex:query         "dt" + INTERVAL '-1 
  knex:query         month'
  knex:query       ELSE
  knex:query         "dt" + INTERVAL '-1 
  knex:query         month'
  knex:query       END as "Add1Day", CASE
  knex:query       WHEN CAST(NOW() AS text) LIKE '%:%' THEN
  knex:query         NOW() + INTERVAL 'greatest("day",3) 
  knex:query         hour'
  knex:query       ELSE
  knex:query         NOW() + INTERVAL 'greatest("day",3) 
  knex:query         hour'
  knex:query       END as "formula1865", "test_formual"."updated_at" as "UpdatedAt", "test_formual"."dt" as "dt", "test_formual"."day" as "day", "test_formual"."title" as "Title", "test_formual"."id" as "Id", "test_formual"."created_at" as "CreatedAt" from "test_formual" order by "id" asc limit ? undefined +1ms
dataList :: error: select CASE
      WHEN CAST("dt" AS text) LIKE '%:%' THEN
        "dt" + INTERVAL '-1 
        month'
      ELSE
        "dt" + INTERVAL '-1 
        month'
      END as "Add1Day", CASE
      WHEN CAST(NOW() AS text) LIKE '%:%' THEN
        NOW() + INTERVAL 'greatest("day",3) 
        hour'
      ELSE
        NOW() + INTERVAL 'greatest("day",3) 
        hour'
      END as "formula1865", "test_formual"."updated_at" as "UpdatedAt", "test_formual"."dt" as "dt", "test_formual"."day" as "day", "test_formual"."title" as "Title", "test_formual"."id" as "Id", "test_formual"."created_at" as "CreatedAt" from "test_formual" order by "id" asc limit $1 - invalid input syntax for type interval: "greatest("day",3) 
        hour"
    at Parser.parseErrorMessage (/home/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/nocodb/packages/nocodb/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 144,
  severity: 'ERROR',
  code: '22007',
  detail: undefined,
  hint: undefined,
  position: '259',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'datetime.c',
  line: '3803',
  routine: 'DateTimeParseError'
}
```
