### ISSUE TITLE
Feature : Import data from external source

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#2052]
### Request your data sources.
- [x] Airtable
- [ ]

**Comment by dstala** [comment]
- [x] Github

**Comment by dstala** [comment]
- [x] Salesforce

**Comment by dstala** [comment]
- [x] Shopify

**Comment by dstala** [comment]
- [x] Hubspot

**Comment by dstala** [comment]
- [x] Stripe

**Comment by dstala** [comment]
- [x] Jira

**Comment by dstala** [comment]
- [x] Github

**Comment by ivishalgandhi** [comment]
REST API as data source

**Comment by o1lab** [comment]
@ivishalgandhi : could you please expand on your request above or pls send an email to n at nocodb dot com

**Comment by ivishalgandhi** [comment]
@o1lab done

**Comment by bingyupiaoyao** [comment]
csv using \t as the seperator

**Comment by AztrexDX** [comment]
H2 and hsqldb. They are used in many applications for testing and medium level deployment like jira, open office etc.

**Comment by everythingability** [comment]
Google Sheets would be handy...

**Comment by o1lab** [comment]
@everythingability : What is your usecase with google-spreadsheet - I ask since its already a spreadsheet 😅 ?

**Comment by cyrsis** [comment]
Hasura Graphql Please

**Comment by IvanDrag0** [comment]
XML

**Comment by o1lab** [comment]
@IvanDrag0 : could you expand on your usecase with XML - do you mean XML files or like a SOAP API request.

**Comment by IvanDrag0** [comment]
@o1lab I'm referring to XML files. While nocodb can import JSON and CSV, a large number of systems that we're working with use XML for data storage/transfer. To import the data into nocodb, I have to either convert it to JSON (which can be difficult if the XML file is not a simple one) or CSV (which is time consuming and has to be done a number of times if there are multiple levels in the XML.

**Comment by nyura123** [comment]
Notion

**Comment by fdion** [comment]
csv/tsv from clipboard

**Comment by 2600box** [comment]
To be able to import from a web table like wikipedia would be amazing

**Comment by Jadi255** [comment]
Import from Baserow please!!

**Comment by AshleyJackson** [comment]
Other pre-existing tables in the already connected Database (when using external databases).

**Comment by candidexmedia** [comment]
Import from another NocoDB instance

**Comment by catcherxuefeng** [comment]
txt file like MS access

**Comment by 4blacktea** [comment]
splunk

**Comment by yachal-upson** [comment]
NocoDB!
Have I missed something? Can see no simplified 'transfer my base from another instance' option.

**Comment by winnie-zy** [comment]
BigQuery

**Comment by dangerstudios** [comment]
> * [x]  REST API as data source

ah damn, is this not possible?

**Comment by thegausiantheory** [comment]
Oracle

**Comment by Shlok-Panpaliya** [comment]
MongoDB

**Comment by macshinaider** [comment]
mongodb

**Comment by johnnycheetah** [comment]
BigQuery

**Comment by paulmwatson** [comment]
SQL. e.g. a pg_dump

**Comment by Bmixo** [comment]
cockroachdb

**Comment by ben-payme** [comment]
hi @o1lab , 
I'm having an issue with this feature, when clicking to import from air-table I'm getting 404 before it's trying to access air-table
the error: 
ant-design-vue.25ebc081.js:1 FetchError: 404  (URL.DOT.IO/api/v1/db/meta/projects/p_xk565gh5ccb4p/syncs/ds_1brtzxgbhnehzv)
    at async E (VM299 TreeView.137fe96e.js:1:7654)
    at async VM299 TreeView.137fe96e.js:1:9282
    
   after trying to GET
   https://NOCODB.URL.IO/dashboard/NOCODB.URL.IO/api/v1/db/meta/projects/p_xk565gh5ccb4p/syncs/ds_1brtzxgbhnehzv
   
   
   it seems there's something wrong with the structure of the request. I don't understand why it trying to get the URL twice 
   
   Thank you

**Comment by yishenggudou** [comment]
redis

**Comment by yishenggudou** [comment]
elasticsearch

**Comment by yishenggudou** [comment]
cassandra

**Comment by wasdee** [comment]
https://github.com/nocodb/nocodb/discussions/2122#discussioncomment-9735934
> > Airtable seems to have changed the URL structure for the share link i.e.:
> > `https://airtable.com/appAbnDph2OXXXXXXX/shrmCIxvHp2wzBQfE/tbl5gSxxxxxxxx/viwoL1h3waa6xxxxxx`
> > When trying to import them onto NoCoDB this is the error displayed:
> > ![CleanShot 2023-08-31 at 11 15 40](https://private-user-images.githubusercontent.com/5737056/264598073-a28feb07-dc6b-4fc6-a4e1-ee17692238f3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTI3NTcsIm5iZiI6MTcxODA5MjQ1NywicGF0aCI6Ii81NzM3MDU2LzI2NDU5ODA3My1hMjhmZWIwNy1kYzZiLTRmYzYtYTRlMS1lZTE3NjkyMjM4ZjMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMDc1NDE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjNiMjU1NGE2ZDljMjUyZTUyOTg2Njc0OGVjMTNlYTY1ZWYyYWZjNWJiNzk2MmNjZmQzNGYzNDcwZDFlNjhjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nMrBcWB6TquTyNtp8zAofmMsUX6ZUl38iZYTWQRDRVI)
> > Any workaround/solutions?
> 
> Got similar Error to this ![image](https://private-user-images.githubusercontent.com/8089231/338495050-64023498-1efe-4641-b56f-26c024e2f0bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTM5NDQsIm5iZiI6MTcxODA5MzY0NCwicGF0aCI6Ii84MDg5MjMxLzMzODQ5NTA1MC02NDAyMzQ5OC0xZWZlLTQ2NDEtYjU2Zi0yNmMwMjRlMmYwYmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMDgxNDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzAwMjQyZTA3ZWFhZWE5ZTYxZGQyNWNkZDFjMjViYmZkZWJiNzZlM2ZjMGMyODlmODA5NjhiMmNmZWViMjc4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TcQNx-_P9Fsf34rRiLLcA2rbsZ8gSisSzQpQooBIJ8A) ![image](https://private-user-images.githubusercontent.com/8089231/338495208-7a09921e-edfc-492c-b82d-39859770a9d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTM5NDQsIm5iZiI6MTcxODA5MzY0NCwicGF0aCI6Ii84MDg5MjMxLzMzODQ5NTIwOC03YTA5OTIxZS1lZGZjLTQ5MmMtYjgyZC0zOTg1OTc3MGE5ZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMDgxNDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjgyM2RiZTU4NDk1MmExODM4ODk1NzMzNjBhNDEwNGM5YWJkZmI5OGZjZTI4ZmVmODBmZGE3YmQyZDlhZjMzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3Sm3LkkvDfKH9md87GVuqRqETagLpavRxsrkqpkrKY4)
> 
> NocoDB is the latest `develop` branch.
> 
> I set env flag `DEBUG` to true to see log. Here is the log.
> 
> ```
> 2024-06-11 15:08:09 [Nest] 8  - 06/11/2024, 8:08:09 AM     LOG [NestApplication] Nest application successfully started +11ms
> 2024-06-11 15:08:24 [Nest] 8  - 06/11/2024, 8:08:24 AM     LOG [FetchAT] AggregateError
> 2024-06-11 15:08:24 [Nest] 8  - 06/11/2024, 8:08:24 AM     LOG [FetchAT] Object:
> 2024-06-11 15:08:24 {
> 2024-06-11 15:08:24   "message": "Invalid Shared Base ID :: Ensure www.airtable.com/<SharedBaseID> is accessible. Refer https://bit.ly/3x0OdXI for details"
> 2024-06-11 15:08:24 }
> 2024-06-11 15:08:24 
> 2024-06-11 15:08:24 [Nest] 8  - 06/11/2024, 8:08:24 AM     LOG [at-import] Object:
> 2024-06-11 15:08:24 {
> 2024-06-11 15:08:24   "message": "Invalid Shared Base ID :: Ensure www.airtable.com/<SharedBaseID> is accessible. Refer https://bit.ly/3x0OdXI for details"
> 2024-06-11 15:08:24 }
> 2024-06-11 15:08:24 
> 2024-06-11 15:08:24 [Nest] 8  - 06/11/2024, 8:08:24 AM   ERROR [JobsEventService] ---- !! JOB FAILED !! ----
> 2024-06-11 15:08:24 id:1
> 2024-06-11 15:08:24 error:Error (Invalid Shared Base ID :: Ensure www.airtable.com/<SharedBaseID> is accessible. Refer https://bit.ly/3x0OdXI for details)
> 2024-06-11 15:08:24 
> 2024-06-11 15:08:24 stack: Error: Invalid Shared Base ID :: Ensure www.airtable.com/<SharedBaseID> is accessible. Refer https://bit.ly/3x0OdXI for details
> 2024-06-11 15:08:24     at AtImportProcessor.job (/usr/src/app/docker/main.js:2:1491764)
> 2024-06-11 15:08:24     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 2024-06-11 15:08:24     at async QueueService.jobWrapper (/usr/src/app/docker/main.js:2:1440599)
> 2024-06-11 15:08:24     at async run (/usr/src/app/node_modules/p-queue/dist/index.js:163:29)
> ```

**Comment by chris2k20** [comment]
Any news on the REST API as data source? 👁️

**Comment by adwiteeymauriya** [comment]
Libsql from [Turso ](https://turso.tech)

**Comment by sanjaydotpro** [comment]
any update on Rest API as data source, that seem to be most upvoted feature request here

**Comment by flythenimbus** [comment]
Is there a roadmap to understand when these pending ones will be implemented?

**Comment by o1lab** [comment]
https://nocodb.com/docs/product-docs/sync
