### ISSUE TITLE
[import] post import, grid view creation failed

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#2087]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.90.11**

- use `shrlTEKHc0vtbU3Ob` for import
- create grid view

```
gridViewCreate :: TypeError: Cannot set property 'meta' of undefined
    at Function.get (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco-models/Column.ts:474:21)
    at Function.insert (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco-models/View.ts:317:13)
    at gridViewCreate (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/api/gridViewApis.ts:18:16)
    at /Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/catchError.ts:6:14

```

**Comment by dstala** [comment]
not reproduced anymore
