### ISSUE TITLE
[import] default value configuration throws error

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#2102]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.90.11**

- import shrO9PBPyPLTqalcr
- default value 'abcd' configured for single line text column (Table 4)
- default value sent during table creation (using cdf)
![Screenshot 2022-05-21 at 4 38 01 PM](https://user-images.githubusercontent.com/86527202/169649108-94711b13-16bf-4bd2-bd60-48958f8f9054.png)

```
CREATE TABLE "nc_6zz1___Table_1" ( "Name" text NULL, "Notes_" text NULL, "Attachments_" text NULL, "Status_" text NULL, "Checkbox" bool NULL, "MultiSelect" text NULL, "Collaborator" character varying NULL, "Date" timestamp NULL, "PhoneNumber" character varying NULL, "Email" text NULL, "Table_4" text NULL DEFAULT abcd, "Number" decimal NULL DEFAULT 100, "ncRecordId" character varying NOT NULL, "ncRecordHash" character varying NULL, PRIMARY KEY("ncRecordId")); - column "abcd" does not exist

```

**Comment by dstala** [comment]
on MySQL

```POST /api/v1/db/meta/projects/p_izszgpvm4g0hzj/tables 400 623 - 19.221 ms
Error: /* xc */
CREATE TABLE `nc_o42j___Table_1` ( `Name` text NULL, `Notes_` text NULL, `Attachments_` text NULL, `Status_` enum('Todo','In progress','Done') NULL, `Checkbox` tinyint(1) NULL, `MultiSelect` set('Jan','Feb','Mar','Apr') NULL, `Collaborator` varchar(255) NULL, `Date` datetime(6) NULL, `PhoneNumber` varchar(255) NULL, `Email` text NULL, `Table_4` text NULL
    DEFAULT "abcd", `Number` decimal(10,2) NULL
    DEFAULT 100, `ncRecordId` varchar(255) NOT NULL, `ncRecordHash` varchar(255) NULL, PRIMARY
    KEY(`ncRecordId`)); - BLOB, TEXT, GEOMETRY or JSON column 'Table_4' can't have a default value
    at exports.default (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/api/sync/helpers/job.ts:1988:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at /Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco-jobs/EmitteryJobsMgr.ts:25:9
    at async Promise.all (index 0)
    at Emittery.emit (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/emittery/index.js:257:3)```

**Comment by pranavxc** [comment]
We need to wrap the default value with quotes if it's a string literal.
