### ISSUE TITLE
🐛 Bug: [web-hook] error in data payload

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#2103]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.90.11**

Below tests were carried out with discord webhook URL
Use shrO9PBPyPLTqalcr to create reference db
Configure insert webhook trigger & click test webhook

- [ ] {{data.columnName}} for variables of type single line text & long text always yields "Text"/ "LongText" as result. Issue can also be observed in Sample payload 
  
![Screenshot 2022-05-21 at 4 54 38 PM](https://user-images.githubusercontent.com/86527202/169652788-81195a3d-5a8f-40cf-b190-b497ac465765.png)

- [ ] {{data.columnName}} fails for certain special characters in column name (Status@)
  
```
hookTest :: Error: Parse error on line 1:
{{data.Status@}}
-------^
Expecting 'ID', got 'INVALID'
    at Parser.parseError (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/handlebars/lib/handlebars/compiler/parser.js:199:11)
    at Parser.parse (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/handlebars/lib/handlebars/compiler/parser.js:251:22)
    at parseWithoutProcessing (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/handlebars/lib/handlebars/compiler/base.js:24:20)
    at HandlebarsEnvironment.parse (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/handlebars/lib/handlebars/compiler/base.js:30:13)
    at compileInput (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/handlebars/lib/handlebars/compiler/compiler.js:532:19)
    at ret (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/handlebars/lib/handlebars/compiler/compiler.js:546:18)
    at parseBody (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/webhookHelpers.ts:20:58)
    at invokeWebhook (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/webhookHelpers.ts:263:13)
    at hookTest (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/api/hookApis.ts:59:3)
    at /Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/catchError.ts:6:14

``` 

- [ ] use {{}} in body leads to error
  
```
hookTest :: Error: Parse error on line 1:
{{}}
--^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'CLOSE'
    at Parser.parseError (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/handlebars/lib/handlebars/compiler/parser.js:199:11)
    at Parser.parse (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/handlebars/lib/handlebars/compiler/parser.js:251:22)
    at parseWithoutProcessing (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/handlebars/lib/handlebars/compiler/base.js:24:20)
    at HandlebarsEnvironment.parse (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/handlebars/lib/handlebars/compiler/base.js:30:13)
    at compileInput (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/handlebars/lib/handlebars/compiler/compiler.js:532:19)
    at ret (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/handlebars/lib/handlebars/compiler/compiler.js:546:18)
    at parseBody (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/webhookHelpers.ts:20:58)
    at invokeWebhook (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/webhookHelpers.ts:263:13)
    at hookTest (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/api/hookApis.ts:59:3)
    at /Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/helpers/catchError.ts:6:14
POST /api/v1/db/meta/tables/md_lykvbitrn0g70c/hooks/test 400 132 - 4.248 ms

```

**Comment by dstala** [comment]
issue not observed anymore
