### ISSUE TITLE
[LTAR] right click - clear on LTAR field, throws error

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#2105]
Node: **v14.18.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.90.11**

Error can be hidden; 

```
dataUpdate :: Error: Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query. Table: nc_pnfa___Table_2. Columns: .
    at QueryCompiler_SQLite3._prepUpdate (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/knex/lib/query/compiler.js:827:13)
    at QueryCompiler_SQLite3.update (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/knex/lib/query/compiler.js:174:29)
    at QueryCompiler_SQLite3.toSQL (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/knex/lib/query/compiler.js:61:29)
    at Builder.toSQL (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/knex/lib/query/builder.js:97:44)
    at /Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/knex/lib/runner.js:31:36
    at /Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/knex/lib/runner.js:277:24
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at BaseModelSqlv2.updateByPk (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/dataMapper/lib/sql/BaseModelSqlv2.ts:1332:7)
    at dataUpdate (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/noco/meta/api/dataApis/dataAliasApis.ts:73:12)
```

**Comment by o1lab** [comment]
Good to close since the new UI.
