### ISSUE TITLE
MSSQL Error on migration to 0.91.1 .

### ISSUE THREAD

**Issue by pcxnet** [nocodb/nocodb#2201]
Can't load after updating to current version on MSSQL

Copy and Paste Project Info - Tutorials: How to check my Project info? ([YouTube Tutorial](https://www.youtube.com/watch?v=AUSNN-RCwhE) or [Documentation](https://docs.nocodb.com/FAQs#how-to-check-my-project-info-))

```
Node: **v16.14.0**
Arch: **x86_64**
Platform: **linux**
Docker: **false**
Database: **mssql**
ProjectOnRootDB: **false**

NocoDB used as docker : true / false
NocoDB version : 
Database used in NC_DB URL  :  mssql 

```
pp 6007 output: Mon, 30 May 2022 04:51:43 GMT tedious deprecated The default value for `config.options.enableArithAbort` will change from `false` to `true` in the next major version of `tedious`. Set the value to `true` or `false` explicitly to silence this message. at node_modules/mssql/lib/tedious/connection-pool.js:61:23
App 6007 output: migration file "nc_013_sync_source" failed
App 6007 output: migration failed with error: CREATE TABLE [nc_sync_source_v2] ([id] nvarchar(20) not null, [title] nvarchar(255), [type] nvarchar(255), [details] nvarchar(max), [deleted] bit, [enabled] bit default '1', [order] float, [project_id] nvarchar(128), [fk_user_id] nvarchar(128), [created_at] datetime2 not null default CURRENT_TIMESTAMP, [updated_at] datetime2 not null default CURRENT_TIMESTAMP, CONSTRAINT [nc_sync_source_v2_pkey] PRIMARY KEY ([id]), CONSTRAINT [nc_sync_source_v2_project_id_foreign] FOREIGN KEY ([project_id]) REFERENCES [nc_projects_v2] ([id]), CONSTRAINT [nc_sync_source_v2_fk_user_id_foreign] FOREIGN KEY ([fk_user_id]) REFERENCES [nc_users_v2] ([id])) - Could not create constraint or index. See previous errors.

App 6007 output:   originalError: RequestError: CREATE TABLE [nc_sync_source_v2] ([id] nvarchar(20) not null, [title] nvarchar(255), [type] nvarchar(255), [details] nvarchar(max), [deleted] bit, [enabled] bit default '1', [order] float, [project_id] nvarchar(128), [fk_user_id] nvarchar(128), [created_at] datetime2 not null default CURRENT_TIMESTAMP, [updated_at] datetime2 not null default CURRENT_TIMESTAMP, CONSTRAINT [nc_sync_source_v2_pkey] PRIMARY KEY ([id]), CONSTRAINT [nc_sync_source_v2_project_id_foreign] FOREIGN KEY ([project_id]) REFERENCES [nc_projects_v2] ([id]), CONSTRAINT [nc_sync_source_v2_fk_user_id_foreign] FOREIGN KEY ([fk_user_id]) REFERENCES [nc_users_v2] ([id])) - Could not create constraint or index. See previous errors.

**Comment by wingkwong** [comment]
What was your previous version?

**Comment by pcxnet** [comment]
Sorry it was the default installed with npx on my system which was v0.90.11 , but a fresh install in docker, also doesn't work to MSSQL.

**Comment by ggogel** [comment]
I'm trying to deploy nocodb with a new MSSQL database on Azure and still get the error with a new and uninitialized database.

Log:
```
2022-06-28T13:03:41.187171560Z migration file "nc_013_sync_source" failed
2022-06-28T13:03:41.187796898Z migration failed with error: CREATE TABLE [nc_sync_source_v2] ([id] nvarchar(20) not null, [title] nvarchar(255), [type] nvarchar(255), [details] nvarchar(max), [deleted] bit, [enabled] bit default '1', [order] float, [project_id] nvarchar(128), [fk_user_id] nvarchar(128), [created_at] datetime2 not null default CURRENT_TIMESTAMP, [updated_at] datetime2 not null default CURRENT_TIMESTAMP, CONSTRAINT [nc_sync_source_v2_pkey] PRIMARY KEY ([id]), CONSTRAINT [nc_sync_source_v2_project_id_foreign] FOREIGN KEY ([project_id]) REFERENCES [nc_projects_v2] ([id]), CONSTRAINT [nc_sync_source_v2_fk_user_id_foreign] FOREIGN KEY ([fk_user_id]) REFERENCES [nc_users_v2] ([id])) - Could not create constraint or index. See previous errors.
2022-06-28T13:03:41.267685824Z TransactionError: Transaction has been aborted.
2022-06-28T13:03:41.267720826Z     at Transaction._rollback (/usr/src/app/node_modules/mssql/lib/base/transaction.js:241:37)
2022-06-28T13:03:41.267731627Z     at Transaction._rollback (/usr/src/app/node_modules/mssql/lib/tedious/transaction.js:77:11)
2022-06-28T13:03:41.267736027Z     at /usr/src/app/node_modules/mssql/lib/base/transaction.js:225:19
2022-06-28T13:03:41.267740128Z     at new Promise (<anonymous>)
2022-06-28T13:03:41.267744428Z     at Transaction.rollback (/usr/src/app/node_modules/mssql/lib/base/transaction.js:224:12)
2022-06-28T13:03:41.267749828Z     at Transaction_MSSQL.rollback (/usr/src/app/node_modules/knex/lib/dialects/mssql/transaction.js:28:21)
2022-06-28T13:03:41.267753928Z     at Function.transactor.rollback (/usr/src/app/node_modules/knex/lib/transaction.js:277:42)
2022-06-28T13:03:41.267757829Z     at /usr/src/app/node_modules/knex/lib/transaction.js:193:35 {
2022-06-28T13:03:41.267761729Z   code: 'EABORT',
2022-06-28T13:03:41.267765529Z   originalError: RequestError: CREATE TABLE [nc_sync_source_v2] ([id] nvarchar(20) not null, [title] nvarchar(255), [type] nvarchar(255), [details] nvarchar(max), [deleted] bit, [enabled] bit default '1', [order] float, [project_id] nvarchar(128), [fk_user_id] nvarchar(128), [created_at] datetime2 not null default CURRENT_TIMESTAMP, [updated_at] datetime2 not null default CURRENT_TIMESTAMP, CONSTRAINT [nc_sync_source_v2_pkey] PRIMARY KEY ([id]), CONSTRAINT [nc_sync_source_v2_project_id_foreign] FOREIGN KEY ([project_id]) REFERENCES [nc_projects_v2] ([id]), CONSTRAINT [nc_sync_source_v2_fk_user_id_foreign] FOREIGN KEY ([fk_user_id]) REFERENCES [nc_users_v2] ([id])) - Could not create constraint or index. See previous errors.
2022-06-28T13:03:41.267771929Z       at handleError (/usr/src/app/node_modules/mssql/lib/tedious/request.js:374:15)
2022-06-28T13:03:41.267775830Z       at Connection.emit (events.js:314:20)
2022-06-28T13:03:41.267779630Z       at Connection.EventEmitter.emit (domain.js:483:12)
2022-06-28T13:03:41.267797131Z       at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:832:12)
2022-06-28T13:03:41.267801131Z       at Parser.emit (events.js:314:20)
2022-06-28T13:03:41.267804431Z       at Parser.EventEmitter.emit (domain.js:483:12)
2022-06-28T13:03:41.267807832Z       at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
2022-06-28T13:03:41.267811432Z       at Parser.emit (events.js:314:20)
2022-06-28T13:03:41.267814932Z       at Parser.EventEmitter.emit (domain.js:483:12)
2022-06-28T13:03:41.267819032Z       at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12) {
2022-06-28T13:03:41.267822633Z     code: 'EREQUEST',
2022-06-28T13:03:41.267826033Z     originalError: Error: Could not create constraint or index. See previous errors.
2022-06-28T13:03:41.267829433Z         at handleError (/usr/src/app/node_modules/mssql/lib/tedious/request.js:372:19)
2022-06-28T13:03:41.267832933Z         at Connection.emit (events.js:314:20)
2022-06-28T13:03:41.267836333Z         at Connection.EventEmitter.emit (domain.js:483:12)
2022-06-28T13:03:41.267839734Z         at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:832:12)
2022-06-28T13:03:41.267843334Z         at Parser.emit (events.js:314:20)
2022-06-28T13:03:41.267846634Z         at Parser.EventEmitter.emit (domain.js:483:12)
2022-06-28T13:03:41.267850034Z         at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
2022-06-28T13:03:41.267853535Z         at Parser.emit (events.js:314:20)
2022-06-28T13:03:41.267856735Z         at Parser.EventEmitter.emit (domain.js:483:12)
2022-06-28T13:03:41.267860135Z         at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12) {
2022-06-28T13:03:41.267863635Z       info: [ErrorMessageToken]
2022-06-28T13:03:41.267866935Z     },
2022-06-28T13:03:41.267870136Z     number: 1750,
2022-06-28T13:03:41.267873436Z     lineNumber: 1,
2022-06-28T13:03:41.267876736Z     state: 1,
2022-06-28T13:03:41.267880036Z     class: 16,
2022-06-28T13:03:41.267883336Z     serverName: 'nocodb-rqck7-hvtwc',
2022-06-28T13:03:41.267886637Z     procName: '',
2022-06-28T13:03:41.267890537Z     precedingErrors: [ [RequestError] ]
2022-06-28T13:03:41.267894137Z   }
2022-06-28T13:03:41.267897437Z }
```

I tested the versions `0.91.10` and `0.92.0` and both give this error.

I tried the older version `0.90.0` and it works fine.

**Comment by pranavxc** [comment]
@ggogel Can you try the following executable or docker command?

### Docker

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.92.0-pr-2498-20220628-1320
```


### Executables

#### MacOS

```bash
mkdir -p ./0.92.0/pr-2498-20220628-1320 && cd "$_" \
    && curl http://dl.nocodb.com/0.92.0-pr-2498-20220628-1320/Noco-macos-arm64 -o noco -L \
    && chmod +x noco \
    && ./noco
```
#### Linux

```bash
mkdir -p ./0.92.0/pr-2498-20220628-1320 && cd "$_" \
   && curl http://dl.nocodb.com/0.92.0-pr-2498-20220628-1320/Noco-linux-x64 -o noco -L \
   && chmod +x noco \
   && ./noco
```
#### Windows

```bash
iwp http://dl.nocodb.com/0.92.0-pr-2498-20220628-1320/Noco-win-arm64.exe
.\Noco-win-arm64.exe
```

For executables visit [here](https://github.com/nocodb/nocodb-timely/releases/tag/0.92.0-pr-2498-20220628-1320)

**Comment by pranavxc** [comment]
> ALTER TABLE ALTER COLUMN payload failed because one or more objects access this colum

Thanks for the quick response. It's happening due to the default constraint, later I will update the migration to handle that.

**Comment by pranavxc** [comment]
Updated the migration corresponding to the error, please try the following executable or docker.

### Docker 

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.92.0-pr-2498-20220629-0549
```

### Run Executables

#### MacOS

```bash
mkdir -p ./0.92.0/pr-2498-20220629-0549 && cd "$_" \
    && curl http://dl.nocodb.com/0.92.0-pr-2498-20220629-0549/Noco-macos-arm64 -o noco -L \
    && chmod +x noco \
    && ./noco
```
#### Linux

```bash
mkdir -p ./0.92.0/pr-2498-20220629-0549 && cd "$_" \
   && curl http://dl.nocodb.com/0.92.0-pr-2498-20220629-0549/Noco-linux-x64 -o noco -L \
   && chmod +x noco \
   && ./noco
```
#### Windows

```bash
iwp http://dl.nocodb.com/0.92.0-pr-2498-20220629-0549/Noco-win-arm64.exe
.\Noco-win-arm64.exe
```

For executables visit [here](https://github.com/nocodb/nocodb-timely/releases/tag/0.92.0-pr-2498-20220629-0549)

**Comment by ggogel** [comment]
Thanks. 

Now the database gets initialized without errors and NocoDB starts.

**Comment by pranavxc** [comment]
@ggogel Thanks for cofirming
