### ISSUE TITLE
Currency field fails for 'money' data type on PostgreSQL

### ISSUE THREAD

**Issue by mertmit** [nocodb/nocodb#2255]
From [@nil0x42](https://github.com/nil0x42)

**Steps To Reproduce**

1. Go to any Postgres table
2. Create a currency column
3. Change type in database to 'money'
4. Create a record

**Expected Behavior**

Currency cell shows record properly.

**Screenshots**

![image](https://user-images.githubusercontent.com/59797957/171900350-d9bd4fd4-2f1d-4831-be73-6d381ef6e67f.png)

**Comment by nil0x42** [comment]
Hi ! So i my case, as it looks like the `money` type is not recommended, and will be even forbidden in next release, according to proposed fix, which type should i use ? can i switch from one type to another without loosing data ?

**Comment by mertmit** [comment]
Hey @nil0x42, sorry for the delay with this PR we will support `money` but we are going to drop locale and currency code from our side as they are present in money type on postgres. We use `numeric` as default so I recommend using it.
For switch part you can safely change your type to `numeric` without losing data. If you encounter any problems feel free to update.

**Comment by nil0x42** [comment]
Hi ! I tried changing type to Numeric, but it returns error 400.
```
╔═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                                                         ║
║                                                 EXCEPTION OCCURED!! in PGClient @ tableUpdate                           ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   MESSAGE:                                                                                                              ║
║                                                                                                                         ║
║   ALTER TABLE "nc_xk1j__Recipes" ALTER COLUMN "Net a Payer €" TYPE numeric USING Net a Payer €::numeric;                ║
║   ; - syntax error at or near "a"                                                                                       ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   CODE:                                                                                                                 ║
║   42601                                                                                                                 ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   STACK:                                                                                                                ║
║   error:                                                                                                                ║
║   ALTER TABLE "nc_xk1j__Recipes" ALTER COLUMN "Net a Payer €" TYPE numeric USING Net a Payer €::numeric;                ║
║   ; - syntax error at or near "a"                                                                                       ║
║       at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)                         ║
║       at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)                              ║
║       at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)                                      ║
║       at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)                                 ║
║       at Socket.emit (events.js:314:20)                                                                                 ║
║       at Socket.EventEmitter.emit (domain.js:506:15)                                                                    ║
║       at addChunk (_stream_readable.js:297:12)                                                                          ║
║       at readableAddChunk (_stream_readable.js:272:9)                                                                   ║
║       at Socket.Readable.push (_stream_readable.js:213:10)                                                              ║
║       at TCP.onStreamRead (internal/stream_base_commons.js:188:23)                                                      ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║                                                                                                                         ║
║                                                                                                                         ║
╚═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
```

But here, it looks like it's a completely different bug. Generated SQL query did not quote the table name (who contains spaces...) after `USING` keyword.
