### ISSUE TITLE
"The "config.option.port" property must be of type number" and other issues

### ISSUE THREAD

**Issue by marcowy** [nocodb/nocodb#2305]
NocoDB used as docker : true 
NocoDB version : 0.91.7
Database used in NC_DB URL  : ?
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : mssql
OS on which NocoDB is running : Ubuntu 22.04 LTS
Node.js version if running as node : 
Database version : MSSQL Express 12

**Steps To Reproduce**
NocoDB in docker installed
Connect to database was successfull but it didn't import existed tables from existed database.
I tried to create new project but I accidentaly logged out, and cannot logged back in because my password
manager didn't save the password. "Forgot password" option didn't work - said that e-mail plugin is not configured.
So I stopped and removed docker NocdDB container and installed it again.
I created new user again and... was suprised because New project button was missing. Tried to hard-refresh - didn't help.
But it worked in Firefox. So I create new project, entered database connection parameters and error about port emerged:

![image](https://user-images.githubusercontent.com/7999161/172846967-e337a41a-092b-440d-947a-18c6b3722d97.png)
"The "config.option.port" property must be of type number"

Tried it several time, same error each time. No idea what to do next.

**Comment by o1lab** [comment]
1. Need more details - like docker logs.
2. Looks like cache issue in frontend - hard to reproduce. 
3. We will look into it.

**Comment by dstala** [comment]
@marcowy please reopen this issue if still reproducible in latest release with relevant details

**Comment by kyletannv** [comment]
Also faced the `"config.options.port" property must be of type number` error.

Deployed a fresh install of nocodb with Docker Compose, logged in, and attempted to add a new data source.

The database, Microsoft SQL Server Standard (64-bit), is running on Windows Server 2019 Standard (10.0), Version 15.0.2104.1.

I'm not sure if it's at all helpful, but another project has the [exact same error](https://github.com/sqlectron/sqlectron-gui/issues/590), and apparently it's caused by high port numbers. I can confirm that ours is a fairly high port number.

I suspect it's also not an authentication/access issue because the data source connection is the same login as the one used for NC_DB, but just pointed at a different target database.

App UI allows me to successfully "Test Database Connection", but when I click "Submit", it's stuck loading, and the docker logs show an error.

![image](https://github.com/nocodb/nocodb/assets/152343692/915c5f1b-f482-4059-a9aa-ade77c8d167b)

Relevant portion of docker compose logs follow:
```
...
nocodb-sheets-1  | [Nest] 11  - 01/25/2024, 3:55:41 PM     LOG [RouterExplorer] Mapped {/api/v1/db/meta/projects/:baseId/bases/:sourceId, DELETE} route [0/1973]
nocodb-sheets-1  | [Nest] 11  - 01/25/2024, 3:55:41 PM     LOG [RouterExplorer] Mapped {/api/v2/meta/bases/:baseId/sources/:sourceId, DELETE} route +0ms
nocodb-sheets-1  | [Nest] 11  - 01/25/2024, 3:55:41 PM     LOG [NestApplication] Nest application successfully started +15ms
nocodb-sheets-1  | TypeError: The "config.options.port" property must be of type number.
nocodb-sheets-1  |     at new Connection (/usr/src/app/node_modules/tedious/lib/connection.js:693:17)
nocodb-sheets-1  |     at /usr/src/app/node_modules/knex/lib/dialects/mssql/index.js:142:26
nocodb-sheets-1  |     at new Promise (<anonymous>)
nocodb-sheets-1  |     at Client_MSSQL.acquireRawConnection (/usr/src/app/node_modules/knex/lib/dialects/mssql/index.js:137:12)
nocodb-sheets-1  |     at create (/usr/src/app/node_modules/knex/lib/client.js:254:39)
nocodb-sheets-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
nocodb-sheets-1  | ╔══════════════════════════════════════════════════════════════════════════════╗║
                  ║║   EXCEPTION OCCURED!! in MssqlClient @ relationList                          ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   MESSAGE:
                  ║║   The "config.options.port" property must be of type number.                 ║║
                  ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -
                  ║║   CODE:                                                                      ║║   undefined
                  ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   STACK:
                  ║║   TypeError: The "config.options.port" property must be of type number.      ║║   at new Connection
                  ║║   (/usr/src/app/node_modules/tedious/lib/connection.js:693:17)               ║║   at /usr/src/app/node_modules/knex/lib/dialects/mssql/inde
x.js:142:26       ║║   at new Promise (<anonymous>)                                               ║║   at Client_MSSQL.acquireRawConnection
                  ║║   (/usr/src/app/node_modules/knex/lib/dialects/mssql/index.js:137:12)        ║║   at create (/usr/src/app/node_modules/knex/lib/client.js:2
54:39)            ║║   at process.processTicksAndRejections                                       ║║   (node:internal/process/task_queues:95:5)
                  ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║
                  ║║                                                                              ║╚════════════════════════════════════════════════════════════
══════════════════╝
nocodb-sheets-1  | TypeError: The "config.options.port" property must be of type number.
nocodb-sheets-1  |     at new Connection (/usr/src/app/node_modules/tedious/lib/connection.js:693:17)
nocodb-sheets-1  |     at /usr/src/app/node_modules/knex/lib/dialects/mssql/index.js:142:26
nocodb-sheets-1  |     at new Promise (<anonymous>)
nocodb-sheets-1  |     at Client_MSSQL.acquireRawConnection (/usr/src/app/node_modules/knex/lib/dialects/mssql/index.js:137:12)
nocodb-sheets-1  |     at create (/usr/src/app/node_modules/knex/lib/client.js:254:39)
nocodb-sheets-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
nocodb-sheets-1  | ╔══════════════════════════════════════════════════════════════════════════════╗║
                  ║║   ---- !! JOB FAILED !! ----                                                 ║║   id:2
                  ║║   error:TypeError (The "config.options.port" property must be of type        ║║   number.)
                  ║║                                                                              ║║   stack: TypeError: The "config.options.port" property must
 be of type       ║║   number.                                                                    ║║   at new Connection
                  ║║   (/usr/src/app/node_modules/tedious/lib/connection.js:693:17)               ║║   at /usr/src/app/node_modules/knex/lib/dialects/mssql/inde
x.js:142:26       ║║   at new Promise (<anonymous>)                                               ║║   at Client_MSSQL.acquireRawConnection
                  ║║   (/usr/src/app/node_modules/knex/lib/dialects/mssql/index.js:137:12)        ║║   at create (/usr/src/app/node_modules/knex/lib/client.js:2
54:39)            ║║   at process.processTicksAndRejections                                       ║║   (node:internal/process/task_queues:95:5)
                  ║║                                                                              ║╚════════════════════════════════════════════════════════════
══════════════════╝
```

Let me know if any other information might be helpful!

**Comment by kyletannv** [comment]
Update: I think I found a bug! When adding the data source for the first time, use the feature that takes in a connection URL rather than entering it directly into the fields. Maybe the port is parsed as a string, and unless it's edited manually in the "port" input field in the UI, it doesn't get sent as an integer?

If it helps, but the connection string looks like this: `mssql://HOST:PORT?u=USERNAME&p=PASSWORD&db=DB`
