### ISSUE TITLE
Bug: Unable to drop column of a composite primary key in Postgres

### ISSUE THREAD

**Issue by nathanclayton** [nocodb/nocodb#234]
Version: 0.9.24
Environment: Docker (x86)

When attempting to drop a column of a composite primary key in Postgres, it appears that it's not properly terminating separate SQL statements.

To replicate via the UI:
1. Create an empty table with the default columns
2. Add an additional primary key column (e.g. `iduuid` type `uuid`)
3. Try to delete the original `id` column

In this error (below) - you can see that there is no semicolon separating the initial column drop and the second constraint drop.
In addition, the constraint should be dropped prior to the column being dropped.

The error generated is:
```
╔═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║
║
║                                                 EXCEPTION OCCURED!! in PGClient @ tableUpdate
║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
║
║   MESSAGE:
║
║   ALTER TABLE "xa3__test" DROP COLUMN "id"alter TABLE "xa3__test" drop constraint xa3__test_pkey;alter TABLE "xa3__test" add constraint xa3__test_pkey PRIMARY KEY(tmpid); - syntax error at or near "alter"
║
║
║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
║
║   CODE:
║
║   42601
║
║
║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
║
║   STACK:
║
║   error: ALTER TABLE "xa3__test" DROP COLUMN "id"alter TABLE "xa3__test" drop constraint xa3__test_pkey;alter TABLE "xa3__test" add constraint xa3__test_pkey PRIMARY KEY(tmpid); - syntax error at or near "alter"   ║
║       at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
║
║       at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
║
║       at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
║
║       at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
║
║       at Socket.emit (events.js:314:20)
║
║       at Socket.EventEmitter.emit (domain.js:483:12)
║
║       at addChunk (_stream_readable.js:297:12)
║
║       at readableAddChunk (_stream_readable.js:272:9)
║
║       at Socket.Readable.push (_stream_readable.js:213:10)
║
║       at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
║
║
║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
║
║
║
║
║
╚═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
```

**Comment by flypenguin** [comment]
I get this from `journalctl`.

Config:

```yaml
version: "3.6"

services:
  nocodb:
    image: nocodb/nocodb
    networks:
      - traefik
    environment:
      NC_DB: pg://postgres:5432?u=nocodb&p=mypassword
      NC_AUTH_JWT_SECRET: 984f74ce-f149-40e0-9ef2-2a5e8b21049c
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nocodb.entrypoints=websecure"
      - "traefik.http.routers.nocodb.rule=Host(`nocodb.mytld.com`)"
      - "traefik.http.services.nocodb.loadbalancer.server.port=8080"
      - "traefik.http.services.nocodb.loadbalancer.server.scheme=http"
```

Image:

```bash
$ docker pull nocodb/nocodb
Using default tag: latest
latest: Pulling from nocodb/nocodb
Digest: sha256:4f04c7e5321be660664edcd12ae3161becaa4599e9faa739c4f15dad3985a8f6
Status: Image is up to date for nocodb/nocodb:latest
docker.io/nocodb/nocodb:latest
```

Dump:

```
Creating nocodb_nocodb_1 ...
[75B blob data]
[410B blob data]
nocodb_1  | ║                                                                                                                         ║
nocodb_1  | ║                                                 EXCEPTION OCCURED!! in PGClient @ createDatabaseIfNotExists             ║
nocodb_1  | ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
nocodb_1  | ║   MESSAGE:                                                                                                              ║
nocodb_1  | ║   CREATE DATABASE  - syntax error at end of input                                                                       ║
nocodb_1  | ║                                                                                                                         ║
nocodb_1  | ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
nocodb_1  | ║   CODE:                                                                                                                 ║
nocodb_1  | ║   42601                                                                                                                 ║
nocodb_1  | ║                                                                                                                         ║
nocodb_1  | ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
nocodb_1  | ║   STACK:                                                                                                                ║
nocodb_1  | ║   error: CREATE DATABASE  - syntax error at end of input                                                                ║
nocodb_1  | ║       at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)                         ║
nocodb_1  | ║       at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)                              ║
nocodb_1  | ║       at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)                                      ║
nocodb_1  | ║       at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)                                 ║
nocodb_1  | ║       at Socket.emit (events.js:314:20)                                                                                 ║
nocodb_1  | ║       at Socket.EventEmitter.emit (domain.js:483:12)                                                                    ║
nocodb_1  | ║       at addChunk (_stream_readable.js:297:12)                                                                          ║
nocodb_1  | ║       at readableAddChunk (_stream_readable.js:272:9)                                                                   ║
nocodb_1  | ║       at Socket.Readable.push (_stream_readable.js:213:10)                                                              ║
nocodb_1  | ║       at TCP.onStreamRead (internal/stream_base_commons.js:188:23)                                                      ║
nocodb_1  | ║                                                                                                                         ║
nocodb_1  | ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
nocodb_1  | ║                                                                                                                         ║
nocodb_1  | ║                                                                                                                         ║
nocodb_1  | ╚═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
nocodb_1  | error: CREATE DATABASE  - syntax error at end of input
nocodb_1  |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
nocodb_1  |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
nocodb_1  |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
nocodb_1  |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
nocodb_1  |     at Socket.emit (events.js:314:20)
nocodb_1  |     at Socket.EventEmitter.emit (domain.js:483:12)
nocodb_1  |     at addChunk (_stream_readable.js:297:12)
nocodb_1  |     at readableAddChunk (_stream_readable.js:272:9)
nocodb_1  |     at Socket.Readable.push (_stream_readable.js:213:10)
nocodb_1  |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
nocodb_1  |   length: 91,
nocodb_1  |   severity: 'ERROR',
nocodb_1  |   code: '42601',
nocodb_1  |   detail: undefined,
nocodb_1  |   hint: undefined,
nocodb_1  |   position: '17',
nocodb_1  |   internalPosition: undefined,
nocodb_1  |   internalQuery: undefined,
nocodb_1  |   where: undefined,
nocodb_1  |   schema: undefined,
nocodb_1  |   table: undefined,
nocodb_1  |   column: undefined,
nocodb_1  |   dataType: undefined,
nocodb_1  |   constraint: undefined,
nocodb_1  |   file: 'scan.l',
nocodb_1  |   line: '1079',
nocodb_1  |   routine: 'scanner_yyerror'
nocodb_1  | }
nocodb_1  | error: CREATE DATABASE  - syntax error at end of input
nocodb_1  |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
nocodb_1  |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
nocodb_1  |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
nocodb_1  |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
nocodb_1  |     at Socket.emit (events.js:314:20)
nocodb_1  |     at Socket.EventEmitter.emit (domain.js:483:12)
nocodb_1  |     at addChunk (_stream_readable.js:297:12)
nocodb_1  |     at readableAddChunk (_stream_readable.js:272:9)
nocodb_1  |     at Socket.Readable.push (_stream_readable.js:213:10)
nocodb_1  |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
nocodb_1  |   length: 91,
nocodb_1  |   severity: 'ERROR',
nocodb_1  |   code: '42601',
nocodb_1  |   detail: undefined,
nocodb_1  |   hint: undefined,
nocodb_1  |   position: '17',
nocodb_1  |   internalPosition: undefined,
nocodb_1  |   internalQuery: undefined,
nocodb_1  |   where: undefined,
nocodb_1  |   schema: undefined,
nocodb_1  |   table: undefined,
nocodb_1  |   column: undefined,
nocodb_1  |   dataType: undefined,
nocodb_1  |   constraint: undefined,
nocodb_1  |   file: 'scan.l',
nocodb_1  |   line: '1079',
nocodb_1  |   routine: 'scanner_yyerror'
nocodb_1  | }
```
