### ISSUE TITLE
0.91.8 - Import Airtable to MariaDB not working - unauthorized access

### ISSUE THREAD

**Issue by syji35** [nocodb/nocodb#2362]
I just upgraded to 0.91.8 and i Try to import Airtable to a new Project.

With a valid URL and APi Key, I get an "Unauthorized acess".

It's work on  0.91.7.

NocoDB used as docker : true
NocoDB version : 0.91.8
Database used in NC_DB URL  : mysql 
Project was created  by clicking : New Project
Database version : mariadb:10.7.4-focal
```

**Steps To Reproduce**


1. Go to 'Add / Import and click Airtable.'
2. Click on 'Airtable'
3. input API key & Shared Base ID
4. Logs view info retrieve error "Unauthorized acess".

**Expected Behavior**

Works in nocodb 0.91.7

**Comment by o1lab** [comment]
Reproducible : will take a look.

POST /api/v1/db/meta/syncs/nc_iw3bwycsfaczhw/trigger?id=xxxxxxxxxxx 200 2 - 2.607 ms
 n [Error]: Unauthorized access
    at Function.unauthorized (/usr/src/app/docker/main.js:2:36572)
    at /usr/src/app/docker/main.js:2:13739
    at /usr/src/app/docker/main.js:2:35875
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at t.default (/usr/src/app/docker/main.js:2:441404)
GET /api/v1/db/meta/projects/p_ohovcdewtfk8um 401 29 - 2.662 ms
Error: Unauthorized access
    at t.default (/usr/src/app/docker/main.js:2:1378948)
    at processTicksAndRejections (internal/process/task_queues.js:97:5
