### ISSUE TITLE
Docker-compose script fails to launch

### ISSUE THREAD

**Issue by Victor239** [nocodb/nocodb#265]
Using the [MySQL docker-compose](https://github.com/nocodb/nocodb/blob/master/docker-compose/mysql/docker-compose.yml) results in this error:

```
Creating nocodb_xcdb_1 ... done
Creating nocodb_xc_1   ... done
Attaching to nocodb_xcdb_1, nocodb_xc_1
xcdb_1  | 2021-06-10 17:46:41+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.34-1debian10 started.
xcdb_1  | 2021-06-10 17:46:41+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
xcdb_1  | 2021-06-10 17:46:41+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.34-1debian10 started.
xcdb_1  | 2021-06-10T17:46:41.886753Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
xcdb_1  | 2021-06-10T17:46:41.887740Z 0 [Note] mysqld (mysqld 5.7.34) starting as process 1 ...
xcdb_1  | 2021-06-10T17:46:41.889911Z 0 [Note] InnoDB: PUNCH HOLE support available
xcdb_1  | 2021-06-10T17:46:41.889921Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
xcdb_1  | 2021-06-10T17:46:41.889923Z 0 [Note] InnoDB: Uses event mutexes
xcdb_1  | 2021-06-10T17:46:41.889925Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
xcdb_1  | 2021-06-10T17:46:41.889926Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
xcdb_1  | 2021-06-10T17:46:41.889928Z 0 [Note] InnoDB: Using Linux native AIO
xcdb_1  | 2021-06-10T17:46:41.890083Z 0 [Note] InnoDB: Number of pools: 1
xcdb_1  | 2021-06-10T17:46:41.890148Z 0 [Note] InnoDB: Using CPU crc32 instructions
event-loop-stats not found, ignoring event loop metrics...
xcdb_1  | 2021-06-10T17:47:14.444932Z 3 [Note] Access denied for user 'xc'@'172.20.0.3' (using password: YES)
xc_1    | ╔═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
xc_1    | ║                                                                                                                         ║
xc_1    | ║                                                 EXCEPTION OCCURED!! in MysqlClient @ createDatabaseIfNotExists          ║
xc_1    | ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
xc_1    | ║   MESSAGE:                                                                                                              ║
xc_1    | ║   Access denied for user 'xc'@'172.20.0.3' (using password: YES)                                                        ║
xc_1    | ║                                                                                                                         ║
xc_1    | ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
xc_1    | ║   CODE:                                                                                                                 ║
xc_1    | ║   ER_ACCESS_DENIED_ERROR                                                                                                ║
xc_1    | ║                                                                                                                         ║
xc_1    | ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
xc_1    | ║   STACK:                                                                                                                ║
xc_1    | ║   Error: Access denied for user 'xc'@'172.20.0.3' (using password: YES)                                                 ║
xc_1    | ║       at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:712:17)                                 ║
xc_1    | ║       at ClientHandshake.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:28:26)                       ║
xc_1    | ║       at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:425:32)                            ║
xc_1    | ║       at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:75:12)                               ║
xc_1    | ║       at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)                        ║
xc_1    | ║       at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:82:25)                                  ║
xc_1    | ║       at Socket.emit (events.js:314:20)                                                                                 ║
xc_1    | ║       at Socket.EventEmitter.emit (domain.js:483:12)                                                                    ║
xc_1    | ║       at addChunk (_stream_readable.js:297:12)                                                                          ║
xc_1    | ║       at readableAddChunk (_stream_readable.js:272:9)                                                                   ║
xc_1    | ║                                                                                                                         ║
xc_1    | ║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
xc_1    | ║                                                                                                                         ║
xc_1    | ║                                                                                                                         ║
xc_1    | ╚═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
^[[28;188Rxc_1    | Error: Access denied for user 'xc'@'172.20.0.3' (using password: YES)
xc_1    |     at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:712:17)
xc_1    |     at ClientHandshake.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:28:26)
xc_1    |     at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:425:32)
xc_1    |     at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:75:12)
xc_1    |     at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)
xc_1    |     at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:82:25)
xc_1    |     at Socket.emit (events.js:314:20)
xc_1    |     at Socket.EventEmitter.emit (domain.js:483:12)
xc_1    |     at addChunk (_stream_readable.js:297:12)
xc_1    |     at readableAddChunk (_stream_readable.js:272:9) {
xc_1    |   code: 'ER_ACCESS_DENIED_ERROR',
xc_1    |   errno: 1045,
xc_1    |   sqlState: '28000',
xc_1    |   sqlMessage: "Access denied for user 'xc'@'172.20.0.3' (using password: YES)"
xc_1    | }
xc_1    | Error: Access denied for user 'xc'@'172.20.0.3' (using password: YES)
xc_1    |     at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:712:17)
xc_1    |     at ClientHandshake.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:28:26)
xc_1    |     at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:425:32)
xc_1    |     at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:75:12)
xc_1    |     at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)
xc_1    |     at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:82:25)
xc_1    |     at Socket.emit (events.js:314:20)
xc_1    |     at Socket.EventEmitter.emit (domain.js:483:12)
xc_1    |     at addChunk (_stream_readable.js:297:12)
xc_1    |     at readableAddChunk (_stream_readable.js:272:9) {
xc_1    |   code: 'ER_ACCESS_DENIED_ERROR',
xc_1    |   errno: 1045,
xc_1    |   sqlState: '28000',
xc_1    |   sqlMessage: "Access denied for user 'xc'@'172.20.0.3' (using password: YES)"
xc_1    | }
xcdb_1  | 2021-06-10T17:47:41.818889Z 4 [Note] Access denied for user 'root'@'localhost' (using password: NO)
xcdb_1  | 2021-06-10T17:48:11.980025Z 5 [Note] Access denied for user 'root'@'localhost' (using password: NO)
```

**Comment by Victor239** [comment]
I'm not sure, I'm just using the default docker-compose.yml so I think the template needs adjusting.

**Comment by pranavxc** [comment]
It may be because of an existing docker volume so remove it and recreate. 

To remove entire containers along with volume do the following.

```
docker-compose down -v
```

After that you can do

```
docker-compose up
```


Refer : https://stackoverflow.com/a/54850584

**Comment by Victor239** [comment]
Thanks, that worked great! I'm not sure why my other Docker containers conflicted as I'm sure I had them on different ports, but anyway that did the trick.
