### ISSUE TITLE
Bug: Issues Connecting to MSSQL Server

### ISSUE THREAD

**Issue by pratio** [nocodb/nocodb#268]
```
╔═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                                                         ║
║                                                 EXCEPTION OCCURED!! in MssqlClient @ createDatabaseIfNotExists          ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   MESSAGE:                                                                                                              ║
║   Login failed for user 'mssqluser'.                                                            ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   CODE:                                                                                                                 ║
║   ELOGIN                                                                                                                ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   STACK:                                                                                                                ║
║   ConnectionError: Login failed for user 'mssqluser'.                                           ║
║       at Connection.<anonymous> (/usr/src/app/node_modules/mssql/lib/tedious/connection-pool.js:68:17)                  ║
║       at Object.onceWrapper (events.js:421:26)                                                                          ║
║       at Connection.emit (events.js:314:20)                                                                             ║
║       at Connection.EventEmitter.emit (domain.js:483:12)                                                                ║
║       at Connection.message (/usr/src/app/node_modules/tedious/lib/connection.js:2148:18)                               ║
║       at Connection.dispatchEvent (/usr/src/app/node_modules/tedious/lib/connection.js:1279:15)                         ║
║       at MessageIO.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:1139:14)                            ║
║       at MessageIO.emit (events.js:314:20)                                                                              ║
║       at MessageIO.EventEmitter.emit (domain.js:483:12)                                                                 ║
║       at Message.<anonymous> (/usr/src/app/node_modules/tedious/lib/message-io.js:46:14)                                ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║                                                                                                                         ║
║                                                                                                                         ║
╚═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
```

**Comment by pratio** [comment]
I can connect using the client and the credentials are fine

**Comment by o1lab** [comment]
Are you using docker ? And where is mssql located locally or elsewhere?

**Comment by pratio** [comment]
Yes, I'm using docker and mssql is located on Azure. Is that important?

**Comment by o1lab** [comment]
Please join our discord : https://discord.gg/5RgZmkW

I can help you out quickly.

**Comment by o1lab** [comment]
[This had helped before with MSSQL](https://github.com/xgenecloud/xgenecloud/issues/51#issuecomment-756401794)

We use knex to connect to databases. You can edit and modify the connection json via like shown in this [youtube video ](https://youtu.be/rS0NRwRCjx0):

**Comment by pratio** [comment]
Thank you, @o1lab , I'll try to join discord next week.

**Comment by o1lab** [comment]
Feel free to reopen
