### ISSUE TITLE
MSSQL : Dataloader issue

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#2736]
```
RequestError: select * redacted - The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.
    at handleError (/usr/src/app/node_modules/mssql/lib/tedious/request.js:374:15)
    at Connection.emit (events.js:314:20)
    at Connection.EventEmitter.emit (domain.js:506:15)
    at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:832:12)
    at Parser.emit (events.js:314:20)
    at Parser.EventEmitter.emit (domain.js:506:15)
    at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
    at Parser.emit (events.js:314:20)
    at Parser.EventEmitter.emit (domain.js:506:15)
    at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12) {
  code: 'EREQUEST',
  originalError: Error: The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.
      at handleError (/usr/src/app/node_modules/mssql/lib/tedious/request.js:372:19)
      at Connection.emit (events.js:314:20)
      at Connection.EventEmitter.emit (domain.js:506:15)
      at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:832:12)
      at Parser.emit (events.js:314:20)
      at Parser.EventEmitter.emit (domain.js:506:15)
      at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
      at Parser.emit (events.js:314:20)
      at Parser.EventEmitter.emit (domain.js:506:15)
      at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12) {
    info: ErrorMessageToken {
      name: 'ERROR',
      event: 'errorMessage',
      number: 1033,
      state: 1,
      class: 15,
      message: 'The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.',
      serverName: 'spidercost',
      procName: '',
      lineNumber: 1
    }
  },
  number: 1033,
  lineNumber: 1,
  state: 1,
  class: 15,
  serverName: 'spidercost',
  procName: '',
  precedingErrors: []
}
m :: TypeError: DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.

Keys:
1

Values:

```

From user 00Cedge in discord

**Comment by rtr1** [comment]
Possibly related to #2388.

MSSQL wants `TOP` in the parent `SELECT`, like the error goes away if:

`select * from (select ...)`

Is changed to:

`select top 100 percent * from (select ...)`

**Comment by nilsreichardt** [comment]
I'm getting a similar issue:

```
TypeError: DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.

Keys:
16751,16752,16753,16754,16755,16756,16757,16758,16759,16760,16761,16762,16763,16764,16765,16766,16767,16768,16769,16770,16771,16772,16773,16774,16775,16776,16777,16778,16779,16780,16781,16782,16783,16784,16785,16786,16787,16788,16789,16790,16791,16792,16793,16794,16795,16796,16797,16798,16799,16800,16801,16802,16803,16804,16805,16806,16807,16808,16809,16810,16811,16812,16813,16814,16815,16816,16817,16818,16819,16820,16821,16822,16823,16824,16825,16826,16827,16828,16829,16830,16831,16832,16833,16834,16835,16836,16837,16838,16839,16840,16841,16842,16843,16844,16845,16846,16847,16848,16849,16850,16851,16852,16853,16854,16855,16856,16857,16858,16859,16860,16861,16862,16863,16864,16865,16866,16867,16868,16869,16870,16871,16872,16873,16874,16875,16876,16877,16878,16879,16880,16881,16882,16883,16884,16885,16886,16887,16888,16889,16890,16891,16892,16893,16894,16895,16896,16897,16898,16899,16900,16901,16902,16903,16904,16905,16906,16907,16908,16909,16910,16911,16912,16913,16914,16915,16916,16917,16918,16919,16920,16921,16922,16923,16924,16925,16926,16927,16928,16929,16930,16931,16932,16933,16934,16935,16936,16937,16938,16939,16940,16941,16942,16943,16944,16945,16946,16947,16948,16949,16950,16951,16952,16953,16954,16955,16956,16957,16958,16959,16960,16961,16962,16963,16964,16965,16966,16967,16968,16969,16970,16971,16972,16973,16974,16975,16976,16977,16978,16979,16980,16981,16982,16983,16984,16985,16986,16987,16988,16989,16990,16991,16992,16993,16994,16995,16996,16997,16998,16999,17000
```

(This is only a part of the logs, if you need more, I can send you the file with all logs).

```
Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.108.1**
```

**Comment by dstala** [comment]
We have not noticed much traction with usage of MS SQL Server support & hence we decided to narrow down support mainly to MySQL & PG. Please feel free to connect with us to discuss more on your use-case [here](https://cal.com/nocodb).
