### ISSUE TITLE
Select v2: configuring default value for multi select

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#2766]
Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.92.4**

- consider for options configured as a, b, c, d
- doesn't work: set default value as `a,b` [options separated by comma without any additional space after comma]
```
GET /api/v1/db/data/noco/x/md_0uwut02cayvoey/views/vw_8jr05u93l8su7e/count 200 11 - 10.596 ms
╔═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                                                         ║
║                                                 EXCEPTION OCCURED!! in SqliteClient @ tableUpdate                       ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   MESSAGE:                                                                                                              ║
║   ALTER TABLE `nc_c12h__Sheet2`  ADD `title7` text DEFAULT a,b  - SQLITE_ERROR: near ",": syntax error                  ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   CODE:                                                                                                                 ║
║   SQLITE_ERROR                                                                                                          ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   STACK:                                                                                                                ║
║   Error: ALTER TABLE `nc_c12h__Sheet2`  ADD `title7` text DEFAULT a,b  - SQLITE_ERROR: near ",": syntax error           ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║                                                                                                                         ║
║                                                                                                                         ║
╚═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
[Error: ALTER TABLE `nc_c12h__Sheet2`  ADD `title7` text DEFAULT a,b  - SQLITE_ERROR: near ",": syntax error] {
  errno: 1,
  code: 'SQLITE_ERROR'
}
columnAdd :: [Error: ALTER TABLE `nc_c12h__Sheet2`  ADD `title7` text DEFAULT a,b  - SQLITE_ERROR: near ",": syntax error] {
  errno: 1,
  code: 'SQLITE_ERROR'
}
```

- works: set default value as `[a,b]` [options separated by comma & bounded by square braces]
- doesn't work: set default value as `[a, b]` [same as above, with space induced after comma]. No error, but default value is displayed as only `a`

### Expected
- what ever option we intend to support, has to be set in the example. 
- would prefer selecting options using drop down like we do it in the cell
- if it has to be via text input, I would prefer it as comma separated values without explicit square brace bound

**Comment by dstala** [comment]
mysql root db: `a,b` works

**Comment by dstala** [comment]
pg root db: single select, `a` as default
```
╔════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                                                                    ║
║                                                 EXCEPTION OCCURED!! in PGClient @ tableUpdate                                      ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -              ║
║   MESSAGE:                                                                                                                         ║
║                                                                                                                                    ║
║   ALTER TABLE "nc_s_3q__Sheet1" ALTER COLUMN "title54"  SET DEFAULT aa;                                                            ║
║   ; - column "aa" does not exist                                                                                                   ║
║                                                                                                                                    ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -              ║
║   CODE:                                                                                                                            ║
║   42703                                                                                                                            ║
║                                                                                                                                    ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -              ║
║   STACK:                                                                                                                           ║
║   error:                                                                                                                           ║
║   ALTER TABLE "nc_s_3q__Sheet1" ALTER COLUMN "title54"  SET DEFAULT aa;                                                            ║
║   ; - column "aa" does not exist                                                                                                   ║
║       at Parser.parseErrorMessage (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:369:69)   ║
║       at Parser.handlePacket (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:188:21)        ║
║       at Parser.parse (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:103:30)               ║
║       at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/index.ts:7:48)            ║
║       at Socket.emit (node:events:520:28)                                                                                          ║
║       at Socket.emit (node:domain:475:12)                                                                                          ║
║       at addChunk (node:internal/streams/readable:315:12)                                                                          ║
║       at readableAddChunk (node:internal/streams/readable:289:9)                                                                   ║
║       at Socket.Readable.push (node:internal/streams/readable:228:10)                                                              ║
║       at TCP.onStreamRead (node:internal/stream_base_commons:190:23)                                                               ║
║                                                                                                                                    ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -              ║
║                                                                                                                                    ║
║                                                                                                                                    ║
╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
error: 
ALTER TABLE "nc_s_3q__Sheet1" ALTER COLUMN "title54"  SET DEFAULT aa;
; - column "aa" does not exist
    at Parser.parseErrorMessage (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 98,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3194',
  routine: 'errorMissingColumn'
}
columnUpdate :: error: 
ALTER TABLE "nc_s_3q__Sheet1" ALTER COLUMN "title54"  SET DEFAULT aa;
; - column "aa" does not exist
    at Parser.parseErrorMessage (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 98,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3194',
  routine: 'errorMissingColumn'
}
PATCH /api/v1/db/meta/columns/cl_4c4ifpy532ybir 400 119 - 63.100 ms
```
