### ISSUE TITLE
Select v2: reconfiguring option values

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#2774]
Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.92.4**

- create root db project, add single select column
- add options `a`, `b`, `c`, `d`, save
- edit options, rename `a` as `b` and `b` as `a`

```
POST /api/v1/db/meta/audits/rows/4/update 200 452 - 7.567 ms
╔══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                                                                      ║
║                                                 EXCEPTION OCCURED!! in MysqlClient @ tableUpdate                                     ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -                ║
║   MESSAGE:                                                                                                                           ║
║   ALTER TABLE `nc_h330__Sheet1`                                                                                                      ║
║       CHANGE                                                                                                                         ║
║       COLUMN `title5` `title5` enum('a','b','c','d','b') NULL; - Column 'title5' has duplicated value 'b' in ENUM                    ║
║                                                                                                                                      ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -                ║
║   CODE:                                                                                                                              ║
║   ER_DUPLICATED_VALUE_IN_TYPE                                                                                                        ║
║                                                                                                                                      ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -                ║
║   STACK:                                                                                                                             ║
║   Error: ALTER TABLE `nc_h330__Sheet1`                                                                                               ║
║       CHANGE                                                                                                                         ║
║       COLUMN `title5` `title5` enum('a','b','c','d','b') NULL; - Column 'title5' has duplicated value 'b' in ENUM                    ║
║       at Packet.asError (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/mysql2/lib/packets/packet.js:728:17)            ║
║       at Query.execute (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/mysql2/lib/commands/command.js:29:26)            ║
║       at Connection.handlePacket (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/mysql2/lib/connection.js:456:32)       ║
║       at PacketParser.onPacket (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/mysql2/lib/connection.js:85:12)          ║
║       at PacketParser.executeStart (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/mysql2/lib/packet_parser.js:75:16)   ║
║       at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/mysql2/lib/connection.js:92:25)             ║
║       at Socket.emit (node:events:520:28)                                                                                            ║
║       at Socket.emit (node:domain:475:12)                                                                                            ║
║       at addChunk (node:internal/streams/readable:315:12)                                                                            ║
║       at readableAddChunk (node:internal/streams/readable:289:9)                                                                     ║
║                                                                                                                                      ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -                ║
║                                                                                                                                      ║
║                                                                                                                                      ║
╚══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
Error: ALTER TABLE `nc_h330__Sheet1` 
    CHANGE
    COLUMN `title5` `title5` enum('a','b','c','d','b') NULL; - Column 'title5' has duplicated value 'b' in ENUM
    at Packet.asError (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  code: 'ER_DUPLICATED_VALUE_IN_TYPE',
  errno: 1291,
  sqlState: 'HY000',
  sqlMessage: "Column 'title5' has duplicated value 'b' in ENUM",
  sql: 'ALTER TABLE `nc_h330__Sheet1` \n' +
    '    CHANGE\n' +
    "    COLUMN `title5` `title5` enum('a','b','c','d','b') NULL;"
}
columnUpdate :: Error: ALTER TABLE `nc_h330__Sheet1` 
    CHANGE
    COLUMN `title5` `title5` enum('a','b','c','d','b') NULL; - Column 'title5' has duplicated value 'b' in ENUM
    at Packet.asError (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  code: 'ER_DUPLICATED_VALUE_IN_TYPE',
  errno: 1291,
  sqlState: 'HY000',
  sqlMessage: "Column 'title5' has duplicated value 'b' in ENUM",
  sql: 'ALTER TABLE `nc_h330__Sheet1` \n' +
    '    CHANGE\n' +
    "    COLUMN `title5` `title5` enum('a','b','c','d','b') NULL;"
}
PATCH /api/v1/db/meta/columns/cl_g16zcwelvfa69g 400 165 - 45.086 ms
```

**Comment by dstala** [comment]
PG

## Before
![Screenshot 2022-07-21 at 12 30 57 PM](https://user-images.githubusercontent.com/86527202/180150884-0bbdba2c-0878-4ea3-8a9c-2484a5cbcfda.png)
![Screenshot 2022-07-21 at 12 30 50 PM](https://user-images.githubusercontent.com/86527202/180150887-8f160ceb-45f6-4cbb-860b-272e052ea58b.png)

## After
![Screenshot 2022-07-21 at 12 31 37 PM](https://user-images.githubusercontent.com/86527202/180150848-8d6bfb39-4590-47f5-b837-4e6b7f0d1ad9.png)
![Screenshot 2022-07-21 at 12 31 28 PM](https://user-images.githubusercontent.com/86527202/180150856-bdaf084b-a413-4b0f-8d86-bc36758821c8.png)
