### ISSUE TITLE
I'm not able to create a table with the API: `Cannot read properties of undefined (reading 'length')`

### ISSUE THREAD

**Issue by nilsreichardt** [nocodb/nocodb#2809]
**Please enter the following details**

Copy and Paste Project Info - Tutorials: How to check my Project info? ([YouTube Tutorial](https://www.youtube.com/watch?v=AUSNN-RCwhE) or [Documentation](https://docs.nocodb.com/FAQs#how-to-check-my-project-info-))

```
Node: **v16.13.2**
Arch: **x64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.92.4**
```

**Steps To Reproduce**

1. Create a new NocoDB project
2. Make this `POST` request: `http://localhost:8080/api/v1/db/meta/projects/{projectId}/tables` with this body:
```json
{
  "table_name": "string",
  "title": "string"
}
```
See https://all-apis.nocodb.com/#tag/DB-table/operation/db-table-create for more information.

**Expected Behavior**

I have all required parameter in my body. I would expect to be able to create a new table. 

**Screenshots**

https://user-images.githubusercontent.com/24459435/180414424-1051f694-93ee-4003-b257-a485a361aa43.mov

![image](https://user-images.githubusercontent.com/24459435/180413735-cce4f94a-b613-4e02-b0dd-7ec3215b1c4f.png)

```
POST /api/v1/db/meta/projects/p_8bcfvfu03t5a45/tables 401 29 - 6.462 ms
GET /api/v1/db/meta/projects/p_8bcfvfu03t5a45/info 200 156 - 3.397 ms
╔═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                                                         ║
║                                                 EXCEPTION OCCURED!! in SqliteClient @ tableCreate                       ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   MESSAGE:                                                                                                              ║
║   Cannot read properties of undefined (reading 'length')                                                                ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   CODE:                                                                                                                 ║
║   undefined                                                                                                             ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   STACK:                                                                                                                ║
║   TypeError: Cannot read properties of undefined (reading 'length')                                                     ║
║       at A.createTable (/Users/nils/Desktop/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:2:695866)           ║
║       at A.tableCreate (/Users/nils/Desktop/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:2:689830)           ║
║       at t.default.sqlOpPlus (/Users/nils/Desktop/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:2:300795)     ║
║       at C (/Users/nils/Desktop/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:2:1341241)                      ║
║       at async /Users/nils/Desktop/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:2:37085                      ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║                                                                                                                         ║
║                                                                                                                         ║
╚═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
TypeError: Cannot read properties of undefined (reading 'length')
    at A.createTable (/Users/nils/Desktop/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:2:695866)
    at A.tableCreate (/Users/nils/Desktop/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:2:689830)
    at t.default.sqlOpPlus (/Users/nils/Desktop/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:2:300795)
    at C (/Users/nils/Desktop/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:2:1341241)
    at async /Users/nils/Desktop/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:2:37085
C :: TypeError: Cannot read properties of undefined (reading 'length')
    at A.createTable (/Users/nils/Desktop/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:2:695866)
    at A.tableCreate (/Users/nils/Desktop/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:2:689830)
    at t.default.sqlOpPlus (/Users/nils/Desktop/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:2:300795)
    at C (/Users/nils/Desktop/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:2:1341241)
    at async /Users/nils/Desktop/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:2:37085
POST /api/v1/db/meta/projects/p_8bcfvfu03t5a45/tables 400 64 - 28.515 ms
GET /api/v1/db/meta/projects/p_8bcfvfu03t5a45/info 304 - - 11.682 ms
```

**Comment by nilsreichardt** [comment]
When I change my the json body of my request to:
```json
{
    "table_name": "WithScript",
    "title": "WithScript",
    "columns": []
}
```

I'm getting this error:
```json
{
    "msg": "/* xc */\nCREATE TABLE `nc_qept___WithScript` (); - SQLITE_ERROR: near \")\": syntax error"
}
```

**Comment by dstala** [comment]
@nilsreichardt 
You can try adding few columns. Example schema's (in both, we have introduced ID as primary key)

```
let schemaCity = {
  title: "City",
  table_name: "City",
  columns: [
    { title: "ID", column_name: "ID", uidt: "ID", pk: true },
    { title: "Title", column_name: "Title", uidt: "SingleLineText" }
  ]
};
let schemaCountry = {
  title: "Country",
  table_name: "Country",
  columns: [
    { title: "ID", column_name: "ID", uidt: "ID", pk: true },
    { title: "Title", column_name: "Title", uidt: "SingleLineText" }
  ]
};
```

**Comment by nilsreichardt** [comment]
@dstala Yes, thinks works a workaround, thanks!

**Comment by nilsreichardt** [comment]
@o1lab The issue still exists. If it's required to add minimum 1 column, we should mention this in the docs: https://all-apis.nocodb.com/#tag/DB-table/operation/db-table-create

**Comment by nilsreichardt** [comment]
I created #2926 which marks the `columns` field as required 👍 Doesn't mention that it's need to be minimum 1 column but I think this is better than nothing. Any other ideas how to add a note for this on the documentation site?

**Comment by otstanteplz** [comment]
The issue still exists. Nowhere mentioned that not only uidt required, buttitle and column name required too for column
