### ISSUE TITLE
[Vue3] Table rename fails

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3086]
https://github.com/nocodb/nocodb/commit/c0d0dfc0279511691fbf77f1e0825948e8c32972
SQLite XCDB project

- Create `Sheet1` table
- Rename `Sheet1` to `Sheet1x`
- Create `Sheet1` table: fails

```
tableCreate :: BadRequest [Error]: Duplicate table name
    at Function.badRequest (/Users/rajuudava/NocoDB/nocodb-v2/nocodb/packages/nocodb/src/lib/meta/helpers/catchError.ts:41:11)
    at tableCreate (/Users/rajuudava/NocoDB/nocodb-v2/nocodb/packages/nocodb/src/lib/meta/api/tableApis.ts:120:13)
    at /Users/rajuudava/NocoDB/nocodb-v2/nocodb/packages/nocodb/src/lib/meta/helpers/catchError.ts:6:14
```

![Screenshot 2022-08-11 at 5 05 27 PM](https://user-images.githubusercontent.com/86527202/184124928-6de7a14c-30ed-4a6d-88f2-c6a892d48433.png)

**Comment by dstala** [comment]
error scenario details shared with wkw
