### ISSUE TITLE
vue3: mysql root db, table name length validation is disabled

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3277]
- create a table with lengthy name (>50 characters). no error / warning displayed.

```
CREATE TABLE `201234567892012345678920123456789201234567892012345678920123456789` ( `id` int(11) UNSIGNED NOT NULL auto_increment, `title` varchar(45) NULL, `created_at` timestamp NULL
    DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NULL
    DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP, PRIMARY
    KEY(`id`)); - Identifier name '201234567892012345678920123456789201234567892012345678920123456789' is too long
    at Packet.asError (/Users/rajuudava/NocoDB/nocodb-v2/nocodb/packages/nocodb/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/Users/rajuudava/NocoDB/nocodb-v2/nocodb/packages/nocodb/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/Users/rajuudava/NocoDB/nocodb-v2/nocodb/packages/nocodb/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/Users/rajuudava/NocoDB/nocodb-v2/nocodb/packages/nocodb/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/Users/rajuudava/NocoDB/nocodb-v2/nocodb/packages/nocodb/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocodb-v2/nocodb/packages/nocodb/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:537:15)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  code: 'ER_TOO_LONG_IDENT',
  errno: 1059,
  sqlState: '42000',
  sqlMessage: "Identifier name '201234567892012345678920123456789201234567892012345678920123456789' is too long",
  sql: '/* xc */\n' +
    'CREATE TABLE `201234567892012345678920123456789201234567892012345678920123456789` ( `id` int(11) UNSIGNED NOT NULL auto_increment, `title` varchar(45) NULL, `created_at` timestamp NULL\n' +
    '    DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NULL\n' +
    '    DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP, PRIMARY\n' +
    '    KEY(`id`));'
}
```

**Comment by wingkwong** [comment]
Was it created from GUI or via API?

**Comment by dstala** [comment]
GUI

**Comment by wingkwong** [comment]
The changes are included in https://github.com/nocodb/nocodb/pull/3117.
