### ISSUE TITLE
vue3: shared form, bt field - insert record option not visible

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3409]
Expected (`+` on click, as shown in image below)

![Screenshot 2022-08-31 at 9 07 06 AM](https://user-images.githubusercontent.com/86527202/187587355-ed8b29e3-b506-4c77-8a93-5d8e35a49063.png)

**Comment by wingkwong** [comment]
Which table in sakila? Do you mean Link Record is not showing after clicking '+' ?

![image](https://user-images.githubusercontent.com/35857179/187590736-1de08192-eadf-40c3-861f-3107a06b14f3.png)

**Comment by dstala** [comment]
- city table
- share view
- open shared view link in incognito mode
- try to populate country field

**Comment by dstala** [comment]
- address table
- share view
- open shared view link in incognito mode
- try to access `customer list` expand row 

![Screenshot 2022-08-31 at 12 38 51 PM](https://user-images.githubusercontent.com/86527202/187615539-8a8d4152-5eec-448b-8b69-911c24c33f91.png)

  
```
GET /api/v1/db/public/shared-view/fb098c26-3e29-4c02-b8b4-8ed957b5d921/rows?offset=0&filterArrJson=[]&sortArrJson=[] 200 7069 - 58.560 ms
authMiddleware :: Unauthorized [Error]: Unauthorized access
    at Function.unauthorized (/Users/rajuudava/NocoDB/nocodb-v2/nocodb/packages/nocodb/src/lib/meta/helpers/catchError.ts:44:11)
    at authMiddleware (/Users/rajuudava/NocoDB/nocodb-v2/nocodb/packages/nocodb/src/lib/meta/helpers/ncMetaAclMw.ts:22:17)
    at /Users/rajuudava/NocoDB/nocodb-v2/nocodb/packages/nocodb/src/lib/meta/helpers/catchError.ts:6:20
    at Layer.handle [as handle_request] (/Users/rajuudava/NocoDB/nocodb-v2/nocodb/packages/nocodb/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/rajuudava/NocoDB/nocodb-v2/nocodb/packages/nocodb/node_modules/express/lib/router/route.js:144:13)
    at exports.default (/Users/rajuudava/NocoDB/nocodb-v2/nocodb/packages/nocodb/src/lib/meta/helpers/extractProjectIdAndAuthenticate.ts:141:5)
```
