### ISSUE TITLE
vue3: formula WEEKDAY error in PG

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3417]
![Screenshot 2022-08-31 at 4 23 34 PM](https://user-images.githubusercontent.com/86527202/187662836-a28dff0f-fb32-4fb9-9d07-78dac0e0bd90.png)

```
dataList :: error: select (EXTRACT(ISODOW FROM date '2022-07-19') - 1 - 0 % 7 + 7) % 7  as "title5", "Sheet1"."id" as "Id", "Sheet1"."title" as "Title", "Sheet1"."created_at" as "CreatedAt", "Sheet1"."updated_at" as "UpdatedAt" from "Sheet1" order by "id" asc limit 25 - operator does not exist: double precision % integer
    at Parser.parseErrorMessage (/Users/rajuudava/NocoDB/nocodb-v2/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/rajuudava/NocoDB/nocodb-v2/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/rajuudava/NocoDB/nocodb-v2/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocodb-v2/nocodb/packages/nocodb/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:537:15)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 213,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No operator matches the given name and argument type(s). You might need to add explicit type casts.',
  position: '65',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_oper.c',
  line: '726',
  routine: 'op_error'
}

```

**Comment by wingkwong** [comment]
Look fine one my side in develop branch.

![image](https://user-images.githubusercontent.com/35857179/187664552-7c071f83-271d-4bc4-aa88-3d2e4cf2c7d5.png)

```
Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.92.4**
```

**Comment by o1lab** [comment]
Just a note : Weekday wasn't existing prior to vue3 implemenetation.

**Comment by o1lab** [comment]
@wingkwong : let's comment WEEKDAY in formula and see this after the release ?
