### ISSUE TITLE
Bug: failed to import meta data

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#343]
**Please enter the following details**

Background: I have 2 nocodb instances, lets say A and B. I want to migrate from A to B. I exported metadata from A as meta.zip, then i take a snapshot from Database-A to create Database-B. A project in B is also configured. 

**Steps To Reproduce**

1. In B, click ``Import Metadata`` (either in My Projects page or in Metadata Operations)
2. It toasts "Some internal error occurred". 
3. In Network tab (Chrome), it shows ``{msg: "Malformed UTF-8 data"}`` when calling ``xcMetaTablesImportZipToLocalFsAndDb``.

P.S. There is no server logs related to this import action.

**Expected behavior**
The project meta zip can be imported.

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.10.3**

**Comment by wingkwong** [comment]
Not sure if it is related to this line. file should be binary.

https://github.com/nocodb/nocodb/blob/7242b0b1f622f43c4debff68e433071d86444481/packages/nocodb/src/lib/noco/meta/NcMetaMgr.ts#L381

**Comment by fajarhide** [comment]
+1 same error 

```
Error: Malformed UTF-8 data
    at Object.stringify (/usr/src/app/node_modules/crypto-js/core.js:513:24)
    at WordArray.init.toString (/usr/src/app/node_modules/crypto-js/core.js:268:38)
    at /usr/src/app/docker/main.js:2:239082
    at Array.map (<anonymous>)
    at s.projectList (/usr/src/app/docker/main.js:2:238891)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async S.initProjectBuilders (/usr/src/app/docker/main.js:2:31981)
    at async S.init (/usr/src/app/docker/main.js:2:29071)
    at async /usr/src/app/docker/main.js:2:242188
```

**Comment by wingkwong** [comment]
Just FYI. It is failing due to different encryption keys across instances. Currently config is encrypted using some random keys which are generated on the initial run. I believe Pranav C is working on it.

**Comment by fajarhide** [comment]
> Just FYI. It is failing due to different encryption keys across instances. Currently config is encrypted using some random keys which are generated on the initial run. I believe Pranav C is working on it.

thanks your advice @wingkwong, can't wait @pranavxc result solving this problem :)

**Comment by pranavxc** [comment]
Metadata import between 2 instances is fixed in `0.11.6`.


> Note: Import won't work with zip files from the older projects ( < `0.11.6`)

> Note: Import/Export will only transfer metadata and files related to the project and not any table data in the project.
