### ISSUE TITLE
Password Protected Form View shows blank screen

### ISSUE THREAD

**Issue by Darren-Fuerst** [nocodb/nocodb#3627]
NocoDB used as docker : true 
NocoDB version : latest docker
Database used in NC_DB URL  : sqlite3
Project was created  by clicking : New Project 
Database on which spreadsheet is created :  sqlite3 
OS on which NocoDB is running : docker which is running on debian
Node.js version if running as node : 
Database version : 
```

**Steps To Reproduce**

1. Share Form View
2. Enable Password Protection
3. Access View

**Expected Behavior**

I expected to be prompted to put in my password. Instead I get a blank screen.
If I disable the password protection it works as expected.

**Comment by o1lab** [comment]
Following error is seen 

:9604/api/v1/db/public/shared-view/a79c53a2-589c-4244-b935-fe44a5387ffb/meta:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
entry-12d64ae7.mjs:1298 TypeError: Cannot read properties of undefined (reading 'heading')
    at Proxy._sfc_render (index-c4161789.mjs:137:79)
    at renderComponentRoot (entry-12d64ae7.mjs:1579:39)
    at ReactiveEffect.componentUpdateFn [as fn] (entry-12d64ae7.mjs:4536:46)
    at ReactiveEffect.run (entry-12d64ae7.mjs:369:19)
    at instance.update (entry-12d64ae7.mjs:4587:52)
    at setupRenderEffect (entry-12d64ae7.mjs:4590:5)
    at mountComponent (entry-12d64ae7.mjs:4492:5)
    at processComponent (entry-12d64ae7.mjs:4470:9)
    at patch (entry-12d64ae7.mjs:4223:11)
    at mountSuspense (entry-12d64ae7.mjs:1751:3)
