### ISSUE TITLE
🐛 Bug: Webhook Error: You must pass a string or Handlebars AST to Handlebars.compile. You passed [object Object]

### ISSUE THREAD

**Issue by 3699n** [nocodb/nocodb#3932]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a new webook.
2. Add webhook url and request type
3. Paste the sample payload below the field below into the body text box.
```
{
  "data": {
    "Startup Name": "Text",
    "Status": "First Call",
    "Priority": "Low",
    "Lead Found": "2022-10-04T15:07:12.154Z",
    "Industry": "Edtech",
    "Questions and Comments": "Long text",
    "Pitch Deck URL": "https://nocodb.com",
    "Pitch Deck PDF": "[{\"url\":\"https://nocodb.com/dummy.png\",\"title\":\"image.png\",\"mimetype\":\"image/png\",\"size\":0}]",
    "Summary": "Text",
    "Contact Email": "test@nocodb.com",
    "Website": "https://nocodb.com",
    "First Name": "Text",
    "Source": "Network",
    "Country": "UK",
    "Desired Ticket": "$123",
    "Desired Pre-Money Valuation": "$123",
    "Last Name": "Text",
    "DD": "Long text",
    "DD Documents": "[{\"url\":\"https://nocodb.com/dummy.png\",\"title\":\"image.png\",\"mimetype\":\"image/png\",\"size\":0}]",
    "First Email Sent": true,
    "ncRecordId": 1,
    "ncRecordHash": "Text"
  }
}
```
4. Press test webhook
5. Error toast: `Error: You must pass a string or Handlebars AST to Handlebars.compile. You passed [object Object]`

Logs:
```
Oct 04 15:11:40 v :: Error: You must pass a string or Handlebars AST to Handlebars.compile. You passed [object Object]
Oct 04 15:11:40 at Object.compile (/app/code/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:494:11)
Oct 04 15:11:40 at HandlebarsEnvironment.hb.compile (/app/code/node_modules/handlebars/dist/cjs/handlebars.js:39:40)
Oct 04 15:11:40 at l (/app/code/node_modules/nocodb/dist/bundle.js:2:535456)
Oct 04 15:11:40 at u (/app/code/node_modules/nocodb/dist/bundle.js:2:536811)
Oct 04 15:11:40 at d (/app/code/node_modules/nocodb/dist/bundle.js:2:536648)
Oct 04 15:11:40 at t.invokeWebhook (/app/code/node_modules/nocodb/dist/bundle.js:2:538082)
Oct 04 15:11:40 at v (/app/code/node_modules/nocodb/dist/bundle.js:2:1401576)
Oct 04 15:11:40 at runMicrotasks (<anonymous>)
Oct 04 15:11:40 at processTicksAndRejections (node:internal/process/task_queues:96:5)
Oct 04 15:11:40 at async /app/code/node_modules/nocodb/dist/bundle.js:2:37950 {
Oct 04 15:11:40 description: undefined,
Oct 04 15:11:40 fileName: undefined,
Oct 04 15:11:40 lineNumber: undefined,
Oct 04 15:11:40 endLineNumber: undefined,
Oct 04 15:11:40 number: undefined
Oct 04 15:11:40 }
Oct 04 15:11:40 POST /api/v1/db/meta/tables/md_cdrvfg5a6f0bpp/hooks/test 400 100 - 4.317 ms
```

### Desired Behavior

Webhook test should succeed or at least reply with a HTTP error.

### Project Details

NocoDB 0.97.0 running in Docker on Cloudron with Postgres

**Comment by 3699n** [comment]
I just want to add that I receive the same error when I try to use any form of handlebars syntax in the body, except when I just leave the default pre-filled `{{json data}}`. Does #3954 resolve this issue in general?

**Comment by wingkwong** [comment]
@3699n Can you try it with this docker tag `nocodb/nocodb-daily:0.97.0-20221009-0013` ?

**Comment by 3699n** [comment]
Unfortunately I cannot test it on my Cloudron instance. Doesn't support custom images.
