### ISSUE TITLE
🐛 Bug: Unclear how to use Handlebars JSON in Webhook

### ISSUE THREAD

**Issue by 3699n** [nocodb/nocodb#4093]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I'm trying to use Handlebars to include data from my table in a JSON POST webhook. I set the body of my POST request to be the following JSON: 
```
{
  "firstName": "{{ data.FirstName }}",
  "lastName": "{{ data.LastName }}",
  "company": "{{ data.StartupName }}",
  "emails": [
    {
      "value": "{{ data.ContactEmail }}",
      "type": "work"
    }
  ],
  "websites": [
    {
      "value": "{{ data.Website }}"
    }
  ]
}
```
No matter how I try to reference the field, whether data.First_Name, data.FirstName, or data.first_name, the corresponding fields in the body of the request are always empty, and I therefore receive a 400 response from the endpoint. Part of my ERP diagram can be found [here](https://i.imgur.com/HLER9aZ.png).

The [documentation](https://docs.nocodb.com/developer-resources/webhooks/#accessing-data-handlebars) doesn't give an example of how to actually use the handlebars syntax in a request, so it is unclear to me if I am doing it correctly.

Logs when triggering the respective action (After Insert in my case):
```
Oct 14 20:28:43 Error: Request failed with status code 400
Oct 14 20:28:43 at createError (/app/code/node_modules/axios/lib/core/createError.js:16:15)
Oct 14 20:28:43 at settle (/app/code/node_modules/axios/lib/core/settle.js:17:12)
Oct 14 20:28:43 at IncomingMessage.handleStreamEnd (/app/code/node_modules/axios/lib/adapters/http.js:269:11)
Oct 14 20:28:43 at IncomingMessage.emit (node:events:402:35)
Oct 14 20:28:43 at IncomingMessage.emit (node:domain:475:12)
Oct 14 20:28:43 at endReadableNT (node:internal/streams/readable:1343:12)
Oct 14 20:28:43 at processTicksAndRejections (node:internal/process/task_queues:83:21) {
Oct 14 20:28:43 config: {
Oct 14 20:28:43 url: 'https://scout.my.sff.vc/api/customers',
Oct 14 20:28:43 method: 'post',
Oct 14 20:28:43 data: '{"firstName":"","lastName":"","company":"","emails":[{"value":"","type":"work"}],"websites":[{"value":""}]}',
Oct 14 20:28:43 headers: {
Oct 14 20:28:43 Accept: 'application/json, text/plain, */*',
Oct 14 20:28:43 'Content-Type': 'application/json',
Oct 14 20:28:43 'User-Agent': 'axios/0.21.4',
Oct 14 20:28:43 'Content-Length': 107
Oct 14 20:28:43 },
Oct 14 20:28:43 params: { api_key: '  ' },
Oct 14 20:28:43 transformRequest: [ [Function: transformRequest] ],
Oct 14 20:28:43 transformResponse: [ [Function: transformResponse] ],
Oct 14 20:28:43 timeout: 0,
Oct 14 20:28:43 withCredentials: true,
Oct 14 20:28:43 adapter: [Function: httpAdapter],
Oct 14 20:28:43 xsrfCookieName: 'XSRF-TOKEN',
Oct 14 20:28:43 xsrfHeaderName: 'X-XSRF-TOKEN',
Oct 14 20:28:43 maxContentLength: -1,
Oct 14 20:28:43 maxBodyLength: -1,
Oct 14 20:28:43 validateStatus: [Function: validateStatus],
Oct 14 20:28:43 transitional: {
Oct 14 20:28:43 silentJSONParsing: true,
Oct 14 20:28:43 forcedJSONParsing: true,
Oct 14 20:28:43 clarifyTimeoutError: false
Oct 14 20:28:43 }
Oct 14 20:28:43 },
Oct 14 20:28:43 request: <ref *1> ClientRequest {
Oct 14 20:28:43 _events: [Object: null prototype] {
Oct 14 20:28:43 abort: [Function (anonymous)],
Oct 14 20:28:43 aborted: [Function (anonymous)],
Oct 14 20:28:43 connect: [Function (anonymous)],
Oct 14 20:28:43 error: [Function (anonymous)],
Oct 14 20:28:43 socket: [Function (anonymous)],
Oct 14 20:28:43 timeout: [Function (anonymous)],
Oct 14 20:28:43 prefinish: [Function: requestOnPrefinish]
Oct 14 20:28:43 },
Oct 14 20:28:43 _eventsCount: 7,
Oct 14 20:28:43 _maxListeners: undefined,
Oct 14 20:28:43 outputData: [],
Oct 14 20:28:43 outputSize: 0,
Oct 14 20:28:43 writable: true,
Oct 14 20:28:43 destroyed: false,
Oct 14 20:28:43 _last: true,
Oct 14 20:28:43 chunkedEncoding: false,
Oct 14 20:28:43 shouldKeepAlive: false,
Oct 14 20:28:43 maxRequestsOnConnectionReached: false,
Oct 14 20:28:43 _defaultKeepAlive: true,
Oct 14 20:28:43 useChunkedEncodingByDefault: true,
Oct 14 20:28:43 sendDate: false,
Oct 14 20:28:43 _removedConnection: false,
Oct 14 20:28:43 _removedContLen: false,
Oct 14 20:28:43 _removedTE: false,
Oct 14 20:28:43 _contentLength: null,
Oct 14 20:28:43 _hasBody: true,
Oct 14 20:28:43 _trailer: '',
Oct 14 20:28:43 finished: true,
Oct 14 20:28:43 _headerSent: true,
Oct 14 20:28:43 _closed: false,
Oct 14 20:28:43 socket: TLSSocket {
Oct 14 20:28:43 _tlsOptions: [Object],
Oct 14 20:28:43 _secureEstablished: true,
Oct 14 20:28:43 _securePending: false,
Oct 14 20:28:43 _newSessionPending: false,
Oct 14 20:28:43 _controlReleased: true,
Oct 14 20:28:43 secureConnecting: false,
Oct 14 20:28:43 _SNICallback: null,
Oct 14 20:28:43 servername: 'scout.my.sff.vc',
Oct 14 20:28:43 alpnProtocol: false,
Oct 14 20:28:43 authorized: true,
Oct 14 20:28:43 authorizationError: null,
Oct 14 20:28:43 encrypted: true,
Oct 14 20:28:43 _events: [Object: null prototype],
Oct 14 20:28:43 _eventsCount: 10,
Oct 14 20:28:43 connecting: false,
Oct 14 20:28:43 _hadError: false,
Oct 14 20:28:43 _parent: null,
Oct 14 20:28:43 _host: 'scout.my.sff.vc',
Oct 14 20:28:43 _readableState: [ReadableState],
Oct 14 20:28:43 _maxListeners: undefined,
Oct 14 20:28:43 _writableState: [WritableState],
Oct 14 20:28:43 allowHalfOpen: false,
Oct 14 20:28:43 _sockname: null,
Oct 14 20:28:43 _pendingData: null,
Oct 14 20:28:43 _pendingEncoding: '',
Oct 14 20:28:43 server: undefined,
Oct 14 20:28:43 _server: null,
Oct 14 20:28:43 ssl: [TLSWrap],
Oct 14 20:28:43 _requestCert: true,
Oct 14 20:28:43 _rejectUnauthorized: true,
Oct 14 20:28:43 parser: null,
Oct 14 20:28:43 _httpMessage: [Circular *1],
Oct 14 20:28:43 [Symbol(res)]: [TLSWrap],
Oct 14 20:28:43 [Symbol(verified)]: true,
Oct 14 20:28:43 [Symbol(pendingSession)]: null,
Oct 14 20:28:43 [Symbol(async_id_symbol)]: 51598,
Oct 14 20:28:43 [Symbol(kHandle)]: [TLSWrap],
Oct 14 20:28:43 [Symbol(kSetNoDelay)]: false,
Oct 14 20:28:43 [Symbol(lastWriteQueueSize)]: 0,
Oct 14 20:28:43 [Symbol(timeout)]: null,
Oct 14 20:28:43 [Symbol(kBuffer)]: null,
Oct 14 20:28:43 [Symbol(kBufferCb)]: null,
Oct 14 20:28:43 [Symbol(kBufferGen)]: null,
Oct 14 20:28:43 [Symbol(kCapture)]: false,
Oct 14 20:28:43 [Symbol(kBytesRead)]: 0,
Oct 14 20:28:43 [Symbol(kBytesWritten)]: 0,
Oct 14 20:28:43 [Symbol(connect-options)]: [Object],
Oct 14 20:28:43 [Symbol(RequestTimeout)]: undefined
Oct 14 20:28:43 },
Oct 14 20:28:43 _header: 'POST /api/customers?api_key=+ HTTP/1.1\r\n' +
Oct 14 20:28:43 'Accept: application/json, text/plain, */*\r\n' +
Oct 14 20:28:43 'Content-Type: application/json\r\n' +
Oct 14 20:28:43 'User-Agent: axios/0.21.4\r\n' +
Oct 14 20:28:43 'Content-Length: 107\r\n' +
Oct 14 20:28:43 'Host: scout.my.sff.vc\r\n' +
Oct 14 20:28:43 'Connection: close\r\n' +
Oct 14 20:28:43 '\r\n',
Oct 14 20:28:43 _keepAliveTimeout: 0,
Oct 14 20:28:43 _onPendingData: [Function: nop],
Oct 14 20:28:43 agent: Agent {
Oct 14 20:28:43 _events: [Object: null prototype],
Oct 14 20:28:43 _eventsCount: 2,
Oct 14 20:28:43 _maxListeners: undefined,
Oct 14 20:28:43 defaultPort: 443,
Oct 14 20:28:43 protocol: 'https:',
Oct 14 20:28:43 options: [Object: null prototype],
Oct 14 20:28:43 requests: [Object: null prototype] {},
Oct 14 20:28:43 sockets: [Object: null prototype],
Oct 14 20:28:43 freeSockets: [Object: null prototype] {},
Oct 14 20:28:43 keepAliveMsecs: 1000,
Oct 14 20:28:43 keepAlive: false,
Oct 14 20:28:43 maxSockets: Infinity,
Oct 14 20:28:43 maxFreeSockets: 256,
Oct 14 20:28:43 scheduling: 'lifo',
Oct 14 20:28:43 maxTotalSockets: Infinity,
Oct 14 20:28:43 totalSocketCount: 1,
Oct 14 20:28:43 maxCachedSessions: 100,
Oct 14 20:28:43 _sessionCache: [Object],
Oct 14 20:28:43 [Symbol(kCapture)]: false
Oct 14 20:28:43 },
Oct 14 20:28:43 socketPath: undefined,
Oct 14 20:28:43 method: 'POST',
Oct 14 20:28:43 maxHeaderSize: undefined,
Oct 14 20:28:43 insecureHTTPParser: undefined,
Oct 14 20:28:43 path: '/api/customers?api_key=++',
Oct 14 20:28:43 _ended: true,
Oct 14 20:28:43 res: IncomingMessage {
Oct 14 20:28:43 _readableState: [ReadableState],
Oct 14 20:28:43 _events: [Object: null prototype],
Oct 14 20:28:43 _eventsCount: 3,
Oct 14 20:28:43 _maxListeners: undefined,
Oct 14 20:28:43 socket: [TLSSocket],
Oct 14 20:28:43 httpVersionMajor: 1,
Oct 14 20:28:43 httpVersionMinor: 1,
Oct 14 20:28:43 httpVersion: '1.1',
Oct 14 20:28:43 complete: true,
Oct 14 20:28:43 rawHeaders: [Array],
Oct 14 20:28:43 rawTrailers: [],
Oct 14 20:28:43 aborted: false,
Oct 14 20:28:43 upgrade: false,
Oct 14 20:28:43 url: '',
Oct 14 20:28:43 method: null,
Oct 14 20:28:43 statusCode: 400,
Oct 14 20:28:43 statusMessage: 'Bad Request',
Oct 14 20:28:43 client: [TLSSocket],
Oct 14 20:28:43 _consuming: false,
Oct 14 20:28:43 _dumped: false,
Oct 14 20:28:43 req: [Circular *1],
Oct 14 20:28:43 responseUrl: 'https://scout.my.sff.vc/api/customers?api_key=+',
Oct 14 20:28:43 redirects: [],
Oct 14 20:28:43 [Symbol(kCapture)]: false,
Oct 14 20:28:43 [Symbol(kHeaders)]: [Object],
Oct 14 20:28:43 [Symbol(kHeadersCount)]: 14,
Oct 14 20:28:43 [Symbol(kTrailers)]: null,
Oct 14 20:28:43 [Symbol(kTrailersCount)]: 0,
Oct 14 20:28:43 [Symbol(RequestTimeout)]: undefined
Oct 14 20:28:43 },
Oct 14 20:28:43 aborted: false,
Oct 14 20:28:43 timeoutCb: null,
Oct 14 20:28:43 upgradeOrConnect: false,
Oct 14 20:28:43 parser: null,
Oct 14 20:28:43 maxHeadersCount: null,
Oct 14 20:28:43 reusedSocket: false,
Oct 14 20:28:43 host: 'scout.my.sff.vc',
Oct 14 20:28:43 protocol: 'https:',
Oct 14 20:28:43 _redirectable: Writable {
Oct 14 20:28:43 _writableState: [WritableState],
Oct 14 20:28:43 _events: [Object: null prototype],
Oct 14 20:28:43 _eventsCount: 2,
Oct 14 20:28:43 _maxListeners: undefined,
Oct 14 20:28:43 _options: [Object],
Oct 14 20:28:43 _ended: true,
Oct 14 20:28:43 _ending: true,
Oct 14 20:28:43 _redirectCount: 0,
Oct 14 20:28:43 _redirects: [],
Oct 14 20:28:43 _requestBodyLength: 107,
Oct 14 20:28:43 _requestBodyBuffers: [],
Oct 14 20:28:43 _onNativeResponse: [Function (anonymous)],
Oct 14 20:28:43 _currentRequest: [Circular *1],
Oct 14 20:28:43 _currentUrl: 'https://scout.my.sff.vc/api/customers?api_key=+',
Oct 14 20:28:43 [Symbol(kCapture)]: false
Oct 14 20:28:43 },
Oct 14 20:28:43 [Symbol(kCapture)]: false,
Oct 14 20:28:43 [Symbol(kNeedDrain)]: false,
Oct 14 20:28:43 [Symbol(corked)]: 0,
Oct 14 20:28:43 [Symbol(kOutHeaders)]: [Object: null prototype] {
Oct 14 20:28:43 accept: [Array],
Oct 14 20:28:43 'content-type': [Array],
Oct 14 20:28:43 _removedTE: false,
Oct 14 20:28:43 _contentLength: null,
Oct 14 20:28:43 _hasBody: true,
Oct 14 20:28:43 _trailer: '',
Oct 14 20:28:43 finished: true,
Oct 14 20:28:43 _headerSent: true,
Oct 14 20:28:43 _closed: false,
```

### Desired Behavior

The respective fields should be inserted into the JSON request.

### Project Details

NocoDB 0.98.1 running in Docker on Cloudron with Postgres

**Comment by o1lab** [comment]
@pranavxc

**Comment by pranavxc** [comment]
Noticed 2 issues 

1. You have whitespace in `First Name` so the `"{{ data.FirstName }}"` should be something like `"{{ data.[First Name] }}"` or `{{#with [data]}}"{{ [First Name] }}"{{/with}}
2. I think you are inserting directly from the grid in that case insert will happen after you enter the value in the first cell. Assuming the first cell is `First Name`, the`"{{ data.FirstName }}"` will be empty and the rest of them will be part of the update event. To overcome this you have to use the expanded form for submitting data, with expanded form insert will trigger only after clicking submit button.



FYI: For testing, you can do `{{ json data }}` which will print the entire payload as JSON.

**Comment by 3699n** [comment]
Thanks for the reply @pranavxc. I have updated the whitespace as you recommended and used the expanded form to insert the data. Unfortunately, when looking at the NocoDB logs I still receive a 400 bad request from the endpoint, even with the same data manually working just fine. 

I'm trying to investigate this further, but NocoDB is no longer printing the body for the request in the logs, so I can't see what the actual content of the body is just yet.
```
{
  "firstName": "{{ data.[First Name] }}",
  "lastName": "{{ data.[Last Name] }}",
  "company": "{{ data.[Startup Name] }}",
  "emails": [
    {
      "value": "{{ data.[Contact Email] }}",
      "type": "work"
    }
  ],
  "websites": [
    {
      "value": "{{ data.Website }}",
    }
  ]
}
```

**Comment by pranavxc** [comment]
> Thanks for the reply @pranavxc. I have updated the whitespace as you recommended and used the expanded form to insert the data. Unfortunately, when looking at the NocoDB logs I still receive a 400 bad request from the endpoint, even with the same data manually working just fine.
> 
> I'm trying to investigate this further, but NocoDB is no longer printing the body for the request in the logs, so I can't see what the actual content of the body is just yet.
> 
> ```
> {
>   "firstName": "{{ data.[First Name] }}",
>   "lastName": "{{ data.[Last Name] }}",
>   "company": "{{ data.[Startup Name] }}",
>   "emails": [
>     {
>       "value": "{{ data.[Contact Email] }}",
>       "type": "work"
>     }
>   ],
>   "websites": [
>     {
>       "value": "{{ data.Website }}",
>     }
>   ]
> }
> ```


Can you try the following 



```js
{{#with [data]}}
{
  "firstName": "{{ [First Name] }}",
  "lastName": "{{ [Last Name] }}",
  "company": "{{ [Startup Name] }}",
  "emails": [
    {
      "value": "{{ [Contact Email] }}",
      "type": "work"
    }
  ],
  "websites": [
    {
      "value": "{{ [Website] }}",
    }
  ]
}
{{/with}}
```

or

```js
{{#with [data]}}
{
  "firstName": {{ json [First Name] }},
  "lastName": {{ json [Last Name] }},
  "company": {{ json [Startup Name] }},
  "emails": [
    {
      "value": {{ json [Contact Email] }},
      "type": "work"
    }
  ],
  "websites": [
    {
      "value": {{ json [Website] }},
    }
  ]
}
{{/with}}
```


If still failing please share the log as well. Although you can try with `webhook.stite` with a dummy URL with payload `{{ json data }}` to confirm the data.

**Comment by 3699n** [comment]
1. This schema is not persisted even when pressing save. It just reverses to the previous contents of the body when opening up the webhook after saving.
2. Not persisted either

**Comment by 3699n** [comment]
@pranavxc When using a http server to inspect the Webhook POST body when the handle bars body is set to `{{ json data }}` shows the following:
```
[
  {
    "ncRecordId": "rc_e8wx5teb72dzmw"
  }
]
```

This seems incorrect.

**Comment by pranavxc** [comment]
@3699n : Yes it looks wrong, can you share your project metadata? ([How to get project info](https://docs.nocodb.com/faqs/#how-to-check-my-project-info-) or [video](https://www.youtube.com/watch?v=AUSNN-RCwhE) )

Noticed 2 bugs

1. Data payload is wrong(missing fields)
2. HTTP client body not persisting if data is not valid JSON which needs to allow.

**Comment by pranavxc** [comment]
Thanks for sharing the details and one more quick question. Is there an autoincremented primary key in the table?

**Comment by 3699n** [comment]
Yes, they were imported from Airtable using the NocoDB wizard.

-------- Original Message --------

**Comment by pranavxc** [comment]
Thanks for confirming, I've fixed the issue in the following PR #4120. Can you confirm it by using the executable/docker build of the PR from the following - https://github.com/nocodb/nocodb/commit/77bd3c61282c8687e88b09e6da25dc7a1950bab1#comments .

**Comment by 3699n** [comment]
This resolves the issue! Both `{{json data}}` and there original handlebars schema return the corrrect data with the fields filled in:
```
{
  "firstName": "{{ data.[First Name] }}",
  "lastName": "{{ data.[Last Name] }}",
  "company": "{{ data.[Startup Name] }}",
  "emails": [
    {
      "value": "{{ data.[Contact Email] }}",
      "type": "work"
    }
  ],
  "websites": [
    {
      "value": "{{ data.Website }}",
    }
  ]
}
```
Request body of POST request:
```
{
  "firstName": "Steve",
  "lastName": "Adamn",
  "company": "SECOND TRY",
  "emails": [
    {
      "value": "s.adamn@gmail.com",
      "type": "work"
    }
  ],
  "websites": [
    {
      "value": "google.com",
    }
  ]
}
```

**Comment by pranavxc** [comment]
> This resolves the issue! Both `{{json data}}` and the original handlebars schema return the corrrect data with the fields filled in:
> 
> ```
> {
>   "firstName": "{{ data.[First Name] }}",
>   "lastName": "{{ data.[Last Name] }}",
>   "company": "{{ data.[Startup Name] }}",
>   "emails": [
>     {
>       "value": "{{ data.[Contact Email] }}",
>       "type": "work"
>     }
>   ],
>   "websites": [
>     {
>       "value": "{{ data.Website }}",
>     }
>   ]
> }
> ```
> 
> Request body of POST request:
> 
> ```
> {
>   "firstName": "Steve",
>   "lastName": "Adamn",
>   "company": "SECOND TRY",
>   "emails": [
>     {
>       "value": "s.adamn@gmail.com",
>       "type": "work"
>     }
>   ],
>   "websites": [
>     {
>       "value": "google.com",
>     }
>   ]
> }
> ```
> 
> Other Handlebars schemas that are not valid JSON also now save and include the correct data in the request body ex:
> 
> ```
> {{#with [data]}}
> {
>   "firstName": "{{ [First Name] }}",
>   "lastName": "{{ [Last Name] }}",
>   "company": "{{ [Startup Name] }}",
>   "emails": [
>     {
>       "value": "{{ [Contact Email] }}",
>       "type": "work"
>     }
>   ],
>   "websites": [
>     {
>       "value": "{{ [Website] }}",
>     }
>   ]
> }
> {{/with}}
> ```

Thanks for confirming, we will include the change in next release :+1: .
