### ISSUE TITLE
special characters in column names

### ISSUE THREAD

**Issue by cybrwshl** [nocodb/nocodb#411]
NocoDB used as docker : true
NocoDB version : 0.11.6
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project
Database on which spreadsheet is created : pg
OS on which NocoDB is running : linux
Node.js version if running as node : 
Database version : 12.1

**Steps To Reproduce**
1. create a column with column name 'täscht'
2. restart nocodb
3. graphql doesnt start

**Expected behavior**
graphql up and running

**Screenshots**
```
GraphQLError [Object]: Syntax Error: Cannot parse the unexpected character "\u00E4".
    at syntaxError (/usr/src/app/node_modules/graphql/error/syntaxError.js:15:10)
    at readToken (/usr/src/app/node_modules/graphql/language/lexer.js:360:40)
    at Lexer.lookahead (/usr/src/app/node_modules/graphql/language/lexer.js:75:108)
    at Lexer.advance (/usr/src/app/node_modules/graphql/language/lexer.js:58:35)
    at Parser.expectToken (/usr/src/app/node_modules/graphql/language/parser.js:1408:19)
    at Parser.parseName (/usr/src/app/node_modules/graphql/language/parser.js:98:22)
    at Parser.parseInputValueDef (/usr/src/app/node_modules/graphql/language/parser.js:911:21)
    at Parser.optionalMany (/usr/src/app/node_modules/graphql/language/parser.js:1503:28)
    at Parser.parseInputFieldsDefinition (/usr/src/app/node_modules/graphql/language/parser.js:1065:17)
    at Parser.parseInputObjectTypeDefinition (/usr/src/app/node_modules/graphql/language/parser.js:1049:23) {
  locations: [ { line: 12, column: 4 } ]
}
App started successfully.
```

Node: **v12.22.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.11.6**

**Comment by pranavxc** [comment]
We are using the table name alias to generate all the graphql query, type and mutations names related to the table, so the `ä` character may cause some problem in that case. If you can remove that character it should be fine. Anyways we will figure out  some generic approach to handle this kind of scenarios.

**Comment by o1lab** [comment]
Gql is not longer supported - closing this.
