### ISSUE TITLE
🐛 Bug: cannot install and try the nocodb-seed example due to some dep version error of nocodb-sdk

### ISSUE THREAD

**Issue by bambooom** [nocodb/nocodb#4152]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

```
git clone https://github.com/nocodb/nocodb-seed

cd nocodb-seed 

npm install
```

### Desired Behavior

install the dependent packages

### Project Details

npm reporting errors like this, which should be some dependency error for typescript.

```
npm ERR! code 1
npm ERR! path /Users/mn/Project/nocodb-seed/node_modules/nocodb-sdk
npm ERR! command failed
npm ERR! command sh /var/folders/tq/wrf1fgtj1fz9gr163y47v9rh0000gn/T/preinstall-e99a788c.sh
npm ERR! npm ERR! code ERESOLVE
npm ERR! npm ERR! ERESOLVE could not resolve
npm ERR! npm ERR! 
npm ERR! npm ERR! While resolving: nocodb-sdk@0.98.1
npm ERR! npm ERR! Found: typescript@4.8.4
npm ERR! npm ERR! node_modules/typescript
npm ERR! npm ERR!   dev typescript@"^4.0.2" from the root project
npm ERR! npm ERR!   peerOptional typescript@"^3.4.1 || ^4.0.0" from eslint-plugin-functional@3.7.2
npm ERR! npm ERR!   node_modules/eslint-plugin-functional
npm ERR! npm ERR!     dev eslint-plugin-functional@"^3.0.2" from the root project
npm ERR! npm ERR!   2 more (swagger-typescript-api, ts-node)
npm ERR! npm ERR! 
npm ERR! npm ERR! Could not resolve dependency:
npm ERR! npm ERR! dev typedoc@"^0.22.17" from the root project
npm ERR! npm ERR! 
npm ERR! npm ERR! Conflicting peer dependency: typescript@4.7.4
npm ERR! npm ERR! node_modules/typescript
npm ERR! npm ERR!   peer typescript@"4.0.x || 4.1.x || 4.2.x || 4.3.x || 4.4.x || 4.5.x || 4.6.x || 4.7.x" from typedoc@0.22.18
npm ERR! npm ERR!   node_modules/typedoc
npm ERR! npm ERR!     dev typedoc@"^0.22.17" from the root project
npm ERR! npm ERR! 
npm ERR! npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! npm ERR! 
npm ERR! npm ERR! See /Users/mn/.npm/eresolve-report.txt for a full report.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/mn/.npm/_logs/2022-10-22T10_13_18_755Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mn/.npm/_logs/2022-10-22T10_12_28_712Z-debug-0.log
```

What I'm using locally is :

```
$ tsc --v
Version 4.7.4
```

**Comment by o1lab** [comment]
Try npm install nocodb --force

**Comment by bambooom** [comment]
@o1lab  Thanks! I've tried but still failed. It seems that I can't install sqlite3 on my Mac.

```
npm ERR! code 1
npm ERR! path /Users/mn/Project/nocodb-seed/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh /var/folders/tq/wrf1fgtj1fz9gr163y47v9rh0000gn/T/install-eb731878.sh
npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR!   ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c
npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/mn/Project/nocodb-seed/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/mn/Project/nocodb-seed/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
npm ERR! node-pre-gyp info using node@16.17.0 | darwin | arm64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "/Users/mn/Project/nocodb-seed/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node" (not found)
npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.0/napi-v3-darwin-arm64.tar.gz
npm ERR! node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.0/napi-v3-darwin-arm64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.0/napi-v3-darwin-arm64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.0 and node@16.17.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.0/napi-v3-darwin-arm64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.0 | darwin | arm64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.12 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/mn/Project/nocodb-seed/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/mn/Library/Caches/node-gyp/16.17.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/mn/Library/Caches/node-gyp/16.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/mn/Library/Caches/node-gyp/16.17.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/mn/Project/nocodb-seed/node_modules/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.0 | darwin | arm64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
npm ERR! /bin/sh: python: command not found
npm ERR! make: *** [Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/mn/Project/nocodb-seed/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/mn/Project/nocodb-seed/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
npm ERR! gyp ERR! cwd /Users/mn/Project/nocodb-seed/node_modules/sqlite3
npm ERR! gyp ERR! node -v v16.17.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/mn/Project/nocodb-seed/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/mn/Project/nocodb-seed/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/mn/Project/nocodb-seed/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1093:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Darwin 21.6.0
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/mn/Project/nocodb-seed/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/mn/Project/nocodb-seed/node_modules/sqlite3
npm ERR! node-pre-gyp ERR! node -v v16.17.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mn/.npm/_logs/2022-10-22T10_20_45_653Z-debug-0.log
```

**Comment by o1lab** [comment]
node-gyp is an error most face when running nodejs for the first time. Please google on how to fix it.

**Comment by o1lab** [comment]
Between, I was able to do 

`npx create-nocodb-app` -> this showed an error
`npm install --save nocodb --force` -> fixed it
`node index.js` -> worked

**Comment by bambooom** [comment]
@o1lab  Thanks for your reply. I'll try to fix that. But can I ask for your nodejs & npm version?
And I still think you'd better fix the dep version problem as using `--force` to install is not a normal way to do this.

**Comment by bambooom** [comment]
I googled about node-gyp, but cann't understand how to fix it. And I found that if I install sqlite3@5.0.0, the same error will appear.  So why nocodb is fixed at sqlite3@5.0.0?

https://github.com/nocodb/nocodb/blob/develop/packages/nocodb/package.json#L183

Is it related with M1/M1 pro chip? 
https://github.com/TryGhost/node-sqlite3/issues/1538

**Comment by o1lab** [comment]
node : 16.14
npm : 8.3.1

**Comment by wingkwong** [comment]
Handled in https://github.com/nocodb/nocodb/pull/4112
