### ISSUE TITLE
🐛 Bug: Error during changing backend DB

### ISSUE THREAD

**Issue by stepanof** [nocodb/nocodb#4262]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Hello team!
I want to change postgres database under the nocodb and faced error.

I made postgres dump:
```
docker exec -it <postgres_container> /bin/bash
	pg_dump -h 127.0.0.1  -p 5432 -d root_db -U postgres -Fd -f path/to/pg_dump_folder
exit
```
In new postgres base I created user "nocodb_app" and run:
```
CREATE DATABASE root_db;
GRANT ALL PRIVILEGES ON DATABASE root_db TO "nocodb_app";
GRANT ALL PRIVILEGES ON DATABASE postgres TO "nocodb_app";
alter user "nocodb_app" superuser createrole createdb REPLICATION BYPASSRLS;
```
Then I run migration command:
```
pg_restore -Fd --single-transaction -s -O -h <new_postgres_host> -U postgres -p 5000 -d root_db path/to/pg_dump_folder
```

Everything work correctly and without errors, dump was restored successfully.

Then I change connection string 
from
`NC_DB: "pg://root_db:5432?u=nocodb_app&p=<password>&d=root_db&application_name=nocodb"`
to
`NC_DB: "pg://<new_postgres_host>:5000?u=nocodb_app&p=<password>=root_db&application_name=nocodb"`
in **docker-compose.yaml** and restart nocodb container.

Then Im getting migration error in logs:
```
App started successfully.
Visit -> http://localhost:8080/dashboard
migration file "project" failed
migration failed with error: create table "nc_projects" ("id" varchar(128), "title" varchar(255), "status" varchar(255), "description" text, "config" text, "meta" text, "created_at" timestamptz, "updated_at" timestamptz) - relation "nc_projects" already exists
error: create table "nc_projects" ("id" varchar(128), "title" varchar(255), "status" varchar(255), "description" text, "config" text, "meta" text, "created_at" timestamptz, "updated_at" timestamptz) - relation "nc_projects" already exists
    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 105,
  severity: 'ERROR',
  code: '42P07',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'heap.c',
  line: '1200',
  routine: 'heap_create_with_catalog'
}
```

And also I can't use application because 404 error
![image](https://user-images.githubusercontent.com/68236577/199479399-712b3ace-56a2-49ea-abc8-97cca54f9d62.png)

I tried to set 
`NC_MIGRATIONS_DISABLED: 'true'`
in **docker-compose.yaml** but it didn't help.

### Desired Behavior

After migration Nocodb should see that all tables including "nc_projects" already exists and shouldn't try to migrate again.
WebApp should work correctly.

### Project Details

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.98.2**

**Comment by stepanof** [comment]
oh, it was my mistake... I used option '-s' for `pg_restore `command.
Close issue, sorry.
