### ISSUE TITLE
🐛 Bug: Update row Failed on table with multiple primary key

### ISSUE THREAD

**Issue by syji35** [nocodb/nocodb#4357]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a table in postgresql for example, like this :   

```
CREATE TABLE "test_pk" (
	"n_ej" VARCHAR NOT NULL,
	"n_poste_ej" INTEGER NOT NULL,
        "montant" DOUBLE PRECISION NULL DEFAULT NULL,
        PRIMARY KEY ("n_ej", "n_poste_ej")
)
```
And insert some data.

2.  Create a new project in nocodb with this table.  
3. Try to update column "montant".  An error message appear and Http 400 on PATCH api.

Screen error : 
![image](https://user-images.githubusercontent.com/45880189/201049438-8b010394-b72c-4706-b760-b000eaf58b6d.png)

Request error in console:
![image](https://user-images.githubusercontent.com/45880189/201049852-8113d6da-51e1-4d95-8227-86f0bca0ac0b.png)

Error logs: 
```
TypeError: Cannot read properties of undefined (reading 'NEj')
    at t.BaseModelSqlv2._extractPksValues (/usr/src/app/docker/main.js:1:1184365)
    at t.BaseModelSqlv2.afterUpdate (/usr/src/app/docker/main.js:1:1181761)
    at t.BaseModelSqlv2.updateByPk (/usr/src/app/docker/main.js:1:1175016)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _ (/usr/src/app/docker/main.js:1:1524154)
    at async /usr/src/app/docker/main.js:1:39692
_ :: TypeError: Cannot read properties of undefined (reading 'NEj')
    at t.BaseModelSqlv2._extractPksValues (/usr/src/app/docker/main.js:1:1184365)
    at t.BaseModelSqlv2.afterUpdate (/usr/src/app/docker/main.js:1:1181761)
    at t.BaseModelSqlv2.updateByPk (/usr/src/app/docker/main.js:1:1175016)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _ (/usr/src/app/docker/main.js:1:1524154)
    at async /usr/src/app/docker/main.js:1:39692
PATCH /api/v1/db/data/noco/p_6nbw71rs5jw4u2/md_v3apdfu8vuvh6k/views/vw_1ozt34ja1j2j6j/1500988902___1 400 61 - 106.792 ms
```

### Desired Behavior

Updating rows with  multiple primary keys should work

### Project Details

NocoDB Version : 0.98.4
NocoDB in docker

**Comment by wingkwong** [comment]
Able to reproduce.
