### ISSUE TITLE
🐛 Bug: NocoDB can't sync data if multiple many-to-many relations with constraints named the same exist

### ISSUE THREAD

**Issue by Amonlol** [nocodb/nocodb#4442]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

This occurs in postgres (haven't tested in other dbms'es, but I think it's reoccurring problem)
1. Create 3 tables with any data
2. Create 2 more tables to resolve many-to-many relationship
3. Create relationships 1st table to 3rd in 4th table, 2nd table to 3rd in 5th table with constraints named the same (see db code below)
4. Get the following error: R :: TypeError: Cannot read properties of undefined (reading 'id')

```
--Bug example in postgres:
--First create tables to store data
CREATE TABLE my_data1
(
pk_my_data1_id serial primary key,
my_data1_text text
);

CREATE TABLE my_data2
(
pk_my_data2_id serial primary key,
my_data2_text text
);

CREATE TABLE my_data3
(
pk_my_data3_id serial primary key,
my_data3_text text
);

--Then create resolving m-m relationship tables
CREATE TABLE link_1to3
(
pk_link_id serial primary key,
fk_link_1 integer,
fk_link_3 integer
);

ALTER TABLE link_1to3
ADD CONSTRAINT fk_link1
FOREIGN KEY (fk_link_1)
REFERENCES my_data1;

ALTER TABLE link_1to3
ADD CONSTRAINT fk_link2
FOREIGN KEY (fk_link_3)
REFERENCES my_data3;
```
After that sync data in noco
![image](https://user-images.githubusercontent.com/72953500/202919375-3e7aeef4-53c7-44ae-82f6-5007ebd62152.png)

```
--Then add second m-m table
CREATE TABLE link_2to3
(
pk_link_id serial primary key,
fk_link_2 integer,
fk_link_3 integer
);

ALTER TABLE link_2to3
ADD CONSTRAINT fk_link1
FOREIGN KEY (fk_link_2)
REFERENCES my_data2;

ALTER TABLE link_2to3
ADD CONSTRAINT fk_link2
FOREIGN KEY (fk_link_3)
REFERENCES my_data3;
```

Try to sync data again
![image](https://user-images.githubusercontent.com/72953500/202919220-ed75ba36-5134-4748-bef7-ae2430a63a70.png)

### Desired Behavior

Noco should sync data and show new relationships

### Project Details

NocoDB used as docker : true
NocoDB version : 
Database used in NC_DB URL  : pg 15.0 (one db for data only)
Project was created by clicking : New Project by connecting to external database
Database on which spreadsheet is created : pg 15.0 (another db for metadata only)
OS on which NocoDB is running : Ubuntu Server 20.04
Database version : PostgeSQL 15.0

**Comment by happyfloat** [comment]
Just testing Nocodb for the first time and also running into this issue when trying to connect/sync with my existing database.

**Comment by jimhuds** [comment]
Also having this issue. Database was created in Directus.

**Comment by lsrugo** [comment]
I am getting the same error message `Cannot read properties of undefined (reading 'id')` when syncing metadata and I think it's the same bug. Using SQLite for NC_DB and external data source.
Here is the full log message (not sure why it's all on one line):
```
╔══════════════════════════════════════════════════════════════════════════════╗║                                                                              ║║   ---- !! JOB FAILED !! ----                                                 ║║   id:4                                                                       ║║   error:TypeError (Cannot read properties of undefined (reading 'id'))       ║║                                                                              ║║   stack: TypeError: Cannot read properties of undefined (reading 'id')       ║║   at /snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1621368   ║║   at async                                                                   ║║   /snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1704161      ║║   at async Promise.all (index 0)                                             ║║   at async NcHelp.executeOperations                                          ║║   (/snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1704126)    ║║   at async MetaDiffsService.syncBaseMeta                                     ║║   (/snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1621856)    ║║   at async MetaDiffsService.baseMetaDiffSync                                 ║║   (/snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1622271)    ║║   at async MetaSyncProcessor.job                                             ║║   (/snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1376131)    ║║   at async QueueService.jobWrapper                                           ║║   (/snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1260872)    ║║   at async run                                                               ║║   (/snapshot/pkg-executable/node_modules/p-queue/dist/index.js:163:29)       ║║                                                                              ║╚══════════════════════════════════════════════════════════════════════════════╝
```

**Comment by salim-b** [comment]
As [this great StackOverflow answer](https://stackoverflow.com/a/38720073/7196903) explains

> Constraint names are unique only within the object on which they are defined.
> 
> Two different tables (or domains) can have constraints with the same name.
> 
> The exception to that rule are constraints that are implemented by an index (primary key, unique and exclusion constraints). The index that implements the constraint has to have the same name as the constraint, and indexes share a namespace with tables, views, sequences and composite types, which means that no two such objects in the same schema can have the same name.

NocoDB must not assume constraint names ([`pg_constraint.conname`](https://www.postgresql.org/docs/9.1/catalog-pg-constraint.html)) to be unique.
