### ISSUE TITLE
🐛 Bug: migration file "nc_013_sync_source" failed | when trying to upgrade nocodb version from 0.90.11 to 0.100.2 (docker)

### ISSUE THREAD

**Issue by nelajc** [nocodb/nocodb#4651]
App started successfully.
Visit -> http://localhost:8080/dashboard
migration file "nc_013_sync_source" failed
migration failed with error: create table `nc_sync_source_v2` (`id` varchar(20) not null, `title` varchar(255), `type` varchar(255), `details` text, `deleted` boolean, `enabled` boolean default '1', `order` float(8, 2), `project_id` varchar(128), `fk_user_id` varchar(128), `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP) - Table 'nc_sync_source_v2' already exists
Error: create table `nc_sync_source_v2` (`id` varchar(20) not null, `title` varchar(255), `type` varchar(255), `details` text, `deleted` boolean, `enabled` boolean default '1', `order` float(8, 2), `project_id` varchar(128), `fk_user_id` varchar(128), `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP) - Table 'nc_sync_source_v2' already exists
    at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9) {
  code: 'ER_TABLE_EXISTS_ERROR',
  errno: 1050,
  sqlState: '42S01',
  sqlMessage: "Table 'nc_sync_source_v2' already exists",
  sql: "create table `nc_sync_source_v2` (`id` varchar(20) not null, `title` varchar(255), `type` varchar(255), `details` text, `deleted` boolean, `enabled` boolean default '1', `order` float(8, 2), `project_id` varchar(128), `fk_user_id` varchar(128), `created_at` timestamp not null default CURRENT_TIMESTAMP, `updated_at` timestamp not null default CURRENT_TIMESTAMP)"
}

- docker version > 20.10.16
- mysql image > mysql:8.0.28
- nocodb image from 0.90.11 (working) to 0.100.2 (migration error)
- tried to update nocodb version via docker-compose by just changing the nocodb image version
- mounted /usr/app/data

**Comment by o1lab** [comment]
@pranavxc

**Comment by nelajc** [comment]
is it possible to upgrade? or not for now? appreciate to hear from you guys..

**Comment by pranavxc** [comment]
@nelajc can you manually drop the following 2 tables and try the upgrade again.

> nc_sync_source_v2
> nc_sync_logs_v2

Although if possible can u share the entire docker log?

**Comment by nelajc** [comment]
> @nelajc can you manually drop the following 2 tables and try the upgrade again?
> 
> > nc_sync_source_v2
> > nc_sync_logs_v2
> 
> If possible, can you share the entire docker log?

ok. hold on will try this in few days. thanks for the update

**Comment by wingkwong** [comment]
Closing due to inactivity - feel free to reopen if necessary.
