### ISSUE TITLE
🐛 Bug:  SyntaxError: Unexpected token } in JSON  --> breaks and lost all data in table

### ISSUE THREAD

**Issue by guigui42** [nocodb/nocodb#4682]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I have just started a new Docker instance of NocoDB.

I create a new Table Test1

![image](https://user-images.githubusercontent.com/2376010/208975934-3997c33a-7cb5-4598-828d-37abbef12b44.png)

Add a column of type Attachment
![image](https://user-images.githubusercontent.com/2376010/208976020-9bb9c610-d241-4a40-96fc-5b485015a23a.png)

Click on the new column and upload a file : 
![image](https://user-images.githubusercontent.com/2376010/208976135-06c78335-6cc1-47b7-9cbd-b5fcbe989ac5.png)

Add a new column of type Attachment again : 
![image](https://user-images.githubusercontent.com/2376010/208976250-d0e6e9f5-0b69-4f81-ba01-30808455d0fd.png)

Click on the new column and upload a new file (or same) : 
![image](https://user-images.githubusercontent.com/2376010/208976347-a5bd0ee1-3d40-445c-bf03-93fae878ca87.png)

At the bottom right, click on Gallery : 
![image](https://user-images.githubusercontent.com/2376010/208976443-258cc2ef-316c-40a5-8e5a-b069b70f0858.png)
![image](https://user-images.githubusercontent.com/2376010/208976494-c28d2f1a-55c2-4bc8-ab3f-fa57ca2c0230.png)

And we get the error messages : 
![image](https://user-images.githubusercontent.com/2376010/208977701-49cc94ea-1092-4e1d-bfb0-e02065ecced0.png)

After that error, the whole table is broken and all data is lost. When trying to add more data to the same table, changes are never registered and it stays empty, making the table unusable.

![image](https://user-images.githubusercontent.com/2376010/208978952-37d8539e-e5fd-4171-96ca-add691093793.png)

In the logs : 

```
12/21/2022 5:55:56 PM
GET /api/v1/db/data/noco/p_w36nl9r00oh1lu/md_nmuqezvep3guln/views/vw_skmo8kp9nxa43n?offset=0&limit=25 200 574 - 46.368 ms
12/21/2022 5:55:56 PM
GET /dashboard/favicon.ico 304 - - 5.564 ms
12/21/2022 5:55:56 PM
SyntaxError: Unexpected token } in JSON at position 194
12/21/2022 5:55:56 PM
    at JSON.parse (<anonymous>)
12/21/2022 5:55:56 PM
    at /usr/src/app/docker/main.js:1:1203797
12/21/2022 5:55:56 PM
    at Array.forEach (<anonymous>)
12/21/2022 5:55:56 PM
    at t.BaseModelSqlv2._convertAttachmentType (/usr/src/app/docker/main.js:1:1203726)
12/21/2022 5:55:56 PM
    at t.BaseModelSqlv2.convertAttachmentType (/usr/src/app/docker/main.js:1:1204002)
12/21/2022 5:55:56 PM
    at t.BaseModelSqlv2.readByPk (/usr/src/app/docker/main.js:1:1163054)
12/21/2022 5:55:56 PM
    at runMicrotasks (<anonymous>)
12/21/2022 5:55:56 PM
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
12/21/2022 5:55:56 PM
    at async t.BaseModelSqlv2.updateByPk (/usr/src/app/docker/main.js:1:1186571)
12/21/2022 5:55:56 PM
    at async _ (/usr/src/app/docker/main.js:1:1542965)
12/21/2022 5:55:56 PM
_ :: SyntaxError: Unexpected token } in JSON at position 194
12/21/2022 5:55:56 PM
    at JSON.parse (<anonymous>)
12/21/2022 5:55:56 PM
    at /usr/src/app/docker/main.js:1:1203797
12/21/2022 5:55:56 PM
    at Array.forEach (<anonymous>)
12/21/2022 5:55:56 PM
    at t.BaseModelSqlv2._convertAttachmentType (/usr/src/app/docker/main.js:1:1203726)
12/21/2022 5:55:56 PM
    at t.BaseModelSqlv2.convertAttachmentType (/usr/src/app/docker/main.js:1:1204002)
12/21/2022 5:55:56 PM
    at t.BaseModelSqlv2.readByPk (/usr/src/app/docker/main.js:1:1163054)
12/21/2022 5:55:56 PM
    at runMicrotasks (<anonymous>)
12/21/2022 5:55:56 PM
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
12/21/2022 5:55:56 PM
    at async t.BaseModelSqlv2.updateByPk (/usr/src/app/docker/main.js:1:1186571)
12/21/2022 5:55:56 PM
    at async _ (/usr/src/app/docker/main.js:1:1542965)
12/21/2022 5:55:56 PM
PATCH /api/v1/db/data/noco/p_w36nl9r00oh1lu/md_nmuqezvep3guln/views/vw_skmo8kp9nxa43n/1 400 52 - 80.104 ms
12/21/2022 5:55:56 PM
GET /api/v1/db/meta/galleries/vw_skmo8kp9nxa43n 304 - - 3.076 ms
12/21/2022 5:55:56 PM
GET /api/v1/db/data/noco/p_w36nl9r00oh1lu/md_nmuqezvep3guln/views/vw_skmo8kp9nxa43n?offset=0&limit=25 200 98 - 6.207 ms
12/21/2022 5:55:56 PM
SyntaxError: Unexpected token } in JSON at position 194
12/21/2022 5:55:56 PM
    at JSON.parse (<anonymous>)
12/21/2022 5:55:56 PM
    at /usr/src/app/docker/main.js:1:1203797
12/21/2022 5:55:56 PM
    at Array.forEach (<anonymous>)
12/21/2022 5:55:56 PM
    at t.BaseModelSqlv2._convertAttachmentType (/usr/src/app/docker/main.js:1:1203726)
12/21/2022 5:55:56 PM
    at t.BaseModelSqlv2.convertAttachmentType (/usr/src/app/docker/main.js:1:1204002)
12/21/2022 5:55:56 PM
    at t.BaseModelSqlv2.readByPk (/usr/src/app/docker/main.js:1:1163054)
12/21/2022 5:55:56 PM
    at runMicrotasks (<anonymous>)
12/21/2022 5:55:56 PM
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
12/21/2022 5:55:56 PM
    at async t.BaseModelSqlv2.updateByPk (/usr/src/app/docker/main.js:1:1186571)
12/21/2022 5:55:56 PM
    at async _ (/usr/src/app/docker/main.js:1:1542965)
12/21/2022 5:55:56 PM
_ :: SyntaxError: Unexpected token } in JSON at position 194
12/21/2022 5:55:56 PM
    at JSON.parse (<anonymous>)
12/21/2022 5:55:56 PM
    at /usr/src/app/docker/main.js:1:1203797
12/21/2022 5:55:56 PM
    at Array.forEach (<anonymous>)
12/21/2022 5:55:56 PM
    at t.BaseModelSqlv2._convertAttachmentType (/usr/src/app/docker/main.js:1:1203726)
12/21/2022 5:55:56 PM
    at t.BaseModelSqlv2.convertAttachmentType (/usr/src/app/docker/main.js:1:1204002)
12/21/2022 5:55:56 PM
    at t.BaseModelSqlv2.readByPk (/usr/src/app/docker/main.js:1:1163054)
12/21/2022 5:55:56 PM
    at runMicrotasks (<anonymous>)
12/21/2022 5:55:56 PM
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
12/21/2022 5:55:56 PM
    at async t.BaseModelSqlv2.updateByPk (/usr/src/app/docker/main.js:1:1186571)
12/21/2022 5:55:56 PM
    at async _ (/usr/src/app/docker/main.js:1:1542965)
12/21/2022 5:55:56 PM
PATCH /api/v1/db/data/noco/p_w36nl9r00oh1lu/md_nmuqezvep3guln/views/vw_skmo8kp9nxa43n/1 400 52 - 5.041 ms
12/21/2022 5:55:58 PM
GET /api/v1/db/meta/views/vw_cio87b1522fkrk/columns 304 - - 3.643 ms
12/21/2022 5:55:58 PM
GET /api/v1/db/meta/grids/vw_cio87b1522fkrk/grid-columns 304 - - 3.499 ms
12/21/2022 5:55:58 PM
GET /api/v1/db/meta/views/vw_cio87b1522fkrk/filters 304 - - 6.229 ms
12/21/2022 5:55:58 PM
GET /api/v1/db/meta/views/vw_cio87b1522fkrk/sorts 304 - - 6.148 ms
12/21/2022 5:55:58 PM
GET /api/v1/db/data/noco/p_w36nl9r00oh1lu/md_nmuqezvep3guln/views/vw_cio87b1522fkrk?offset=0&limit=25 200 98 - 13.579 ms
```

### Desired Behavior

Not having this error ;) 

### Project Details

Docker version 20.10.22, build 3a2c30b

NocoDB v 0.100.2

PG database 15.1-1.pgdg110+1

**Comment by wingkwong** [comment]
Handled in https://github.com/nocodb/nocodb/pull/4612.
