### ISSUE TITLE
🐛 Bug: Kanban goes blank permanently after editing row

### ISSUE THREAD

**Issue by 3699n** [nocodb/nocodb#4691]
### Please confirm if bug report does NOT exists already ?

- [x] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Open Kanban view.
2. Click on a card to open the detailed view
3. Make a few small edits (in my case check a checkbox and change a singleselect)
4. Press "Save & Exit"

![image](https://user-images.githubusercontent.com/7414843/209293144-b9496020-a6a7-4323-9580-75f416849041.png)

Refreshing or restarting the browser does not fix the issue, so it seems permanent. All other views still work fine.

Logs:
```
Dec 23 07:31:06 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201177
Dec 23 07:31:06 at Array.forEach (<anonymous>)
Dec 23 07:31:06 at t.BaseModelSqlv2._convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201106)
Dec 23 07:31:06 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201347
Dec 23 07:31:06 at Array.map (<anonymous>)
Dec 23 07:31:06 at t.BaseModelSqlv2.convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201334)
Dec 23 07:31:06 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1199423)
Dec 23 07:31:06 at runMicrotasks (<anonymous>)
Dec 23 07:31:06 at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 23 07:31:06 SyntaxError: Unexpected token } in JSON at position 305
Dec 23 07:31:06 at JSON.parse (<anonymous>)
Dec 23 07:31:06 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201177
Dec 23 07:31:06 at Array.forEach (<anonymous>)
Dec 23 07:31:06 at t.BaseModelSqlv2._convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201106)
Dec 23 07:31:06 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201347
Dec 23 07:31:06 at Array.map (<anonymous>)
Dec 23 07:31:06 at t.BaseModelSqlv2.convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201334)
Dec 23 07:31:06 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1199423)
Dec 23 07:31:06 at runMicrotasks (<anonymous>)
Dec 23 07:31:06 at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 23 07:31:06 GET /api/v1/db/data/noco/p_xigvfcuzfn6rq1/md_r239ic6rr25fxp/views/vw_76j9d4u64zmnxg/group/cl_gvfabxzwi2ard3 200 2 - 93.448 ms
Dec 23 07:31:08 PATCH /api/v1/db/meta/views/vw_76j9d4u64zmnxg/columns/kvc_pkrsccdi2eaw2v 200 2 - 6.558 ms
Dec 23 07:31:08 GET /api/v1/db/meta/views/vw_76j9d4u64zmnxg/columns 200 8052 - 4.887 ms
Dec 23 07:31:08 GET /api/v1/db/meta/kanbans/vw_76j9d4u64zmnxg 304 - - 2.741 ms
Dec 23 07:31:08 GET /api/v1/db/meta/kanbans/vw_76j9d4u64zmnxg 200 2097 - 2.956 ms
Dec 23 07:31:08 GET /api/v1/db/meta/kanbans/vw_76j9d4u64zmnxg 200 2097 - 4.567 ms
Dec 23 07:31:08 SyntaxError: Unexpected token } in JSON at position 305
Dec 23 07:31:08 at JSON.parse (<anonymous>)
Dec 23 07:31:08 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201177
Dec 23 07:31:08 at Array.forEach (<anonymous>)
Dec 23 07:31:08 at t.BaseModelSqlv2._convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201106)
Dec 23 07:31:08 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201347
Dec 23 07:31:08 at Array.map (<anonymous>)
Dec 23 07:31:08 at t.BaseModelSqlv2.convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201334)
Dec 23 07:31:08 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1199423)
Dec 23 07:31:08 at runMicrotasks (<anonymous>)
Dec 23 07:31:08 at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 23 07:31:08 SyntaxError: Unexpected token } in JSON at position 305
Dec 23 07:31:08 at JSON.parse (<anonymous>)
Dec 23 07:31:08 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201177
Dec 23 07:31:08 at Array.forEach (<anonymous>)
Dec 23 07:31:08 at t.BaseModelSqlv2._convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201106)
Dec 23 07:31:08 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201347
Dec 23 07:31:08 at Array.map (<anonymous>)
Dec 23 07:31:08 at t.BaseModelSqlv2.convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201334)
Dec 23 07:31:08 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1199423)
Dec 23 07:31:08 at runMicrotasks (<anonymous>)
Dec 23 07:31:08 at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 23 07:31:08 GET /api/v1/db/data/noco/p_xigvfcuzfn6rq1/md_r239ic6rr25fxp/views/vw_76j9d4u64zmnxg/group/cl_gvfabxzwi2ard3 304 - - 58.126 ms
Dec 23 07:31:08 SyntaxError: Unexpected token } in JSON at position 305
Dec 23 07:31:08 at JSON.parse (<anonymous>)
Dec 23 07:31:08 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201177
Dec 23 07:31:08 at Array.forEach (<anonymous>)
Dec 23 07:31:08 at t.BaseModelSqlv2._convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201106)
Dec 23 07:31:08 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201347
Dec 23 07:31:08 at Array.map (<anonymous>)
Dec 23 07:31:08 at t.BaseModelSqlv2.convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201334)
Dec 23 07:31:08 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1199423)
Dec 23 07:31:08 at runMicrotasks (<anonymous>)
Dec 23 07:31:08 at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 23 07:31:08 SyntaxError: Unexpected token } in JSON at position 305
Dec 23 07:31:08 at JSON.parse (<anonymous>)
Dec 23 07:31:08 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201177
Dec 23 07:31:08 at Array.forEach (<anonymous>)
Dec 23 07:31:08 at t.BaseModelSqlv2._convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201106)
Dec 23 07:31:08 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201347
Dec 23 07:31:08 at Array.map (<anonymous>)
Dec 23 07:31:08 at t.BaseModelSqlv2.convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201334)
Dec 23 07:31:08 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1199423)
Dec 23 07:31:08 at runMicrotasks (<anonymous>)
Dec 23 07:31:08 at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 23 07:31:08 GET /api/v1/db/data/noco/p_xigvfcuzfn6rq1/md_r239ic6rr25fxp/views/vw_76j9d4u64zmnxg/group/cl_gvfabxzwi2ard3 200 2 - 237.352 ms
Dec 23 07:31:08 SyntaxError: Unexpected token } in JSON at position 305
Dec 23 07:31:08 at JSON.parse (<anonymous>)
Dec 23 07:31:08 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201177
Dec 23 07:31:08 at Array.forEach (<anonymous>)
Dec 23 07:31:08 at t.BaseModelSqlv2._convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201106)
Dec 23 07:31:08 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201347
Dec 23 07:31:08 at Array.map (<anonymous>)
Dec 23 07:31:08 at t.BaseModelSqlv2.convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201334)
Dec 23 07:31:08 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1199423)
Dec 23 07:31:08 at runMicrotasks (<anonymous>)
Dec 23 07:31:08 at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 23 07:31:08 SyntaxError: Unexpected token } in JSON at position 305
Dec 23 07:31:08 at JSON.parse (<anonymous>)
Dec 23 07:31:08 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201177
Dec 23 07:31:08 at Array.forEach (<anonymous>)
Dec 23 07:31:08 at t.BaseModelSqlv2._convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201106)
Dec 23 07:31:08 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201347
Dec 23 07:31:08 at Array.map (<anonymous>)
Dec 23 07:31:08 at t.BaseModelSqlv2.convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201334)
Dec 23 07:31:08 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1199423)
Dec 23 07:31:08 at runMicrotasks (<anonymous>)
Dec 23 07:31:08 at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 23 07:31:08 GET /api/v1/db/data/noco/p_xigvfcuzfn6rq1/md_r239ic6rr25fxp/views/vw_76j9d4u64zmnxg/group/cl_gvfabxzwi2ard3 200 2 - 223.176 ms
```

### Desired Behavior

It should save properly and not break the Kanban view.

### Project Details

Node: **v16.13.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.100.2**

Running in Docker on Cloudron

**Comment by wingkwong** [comment]
It seems something wrong with `convertAttachmentType` and recently we've fixed similar issues (in develop branch). Can you verify it on the following tag?

```
nocodb/nocodb-daily:0.100.2-20221223-0602
```

**Comment by 3699n** [comment]
I also just noticed that the Row which I edited (resulting in this issue) has now disappeared from all other views and search.

**Comment by wingkwong** [comment]
Can you delete the problematic kanban view to see if it brings the rows back?

**Comment by 3699n** [comment]
I just restarted NocoDB and now all the Data / Rows are gone :(

**Comment by 3699n** [comment]
It might be relevant to note that I imported the data from Airtable.

**Comment by wingkwong** [comment]
You've filtered out `swinto`. Is it intended?

**Comment by 3699n** [comment]
Oh no that was an accident. Sorry. Rows are still there, except the one that caused the issue.

**Comment by 3699n** [comment]
Since the issue seems to be related to attachments, I am also using the Backblaze B2 storage provider for attachments.

**Comment by 3699n** [comment]
After deleting the old view Kanban view and creating a new kanban view, it seems to be working again.

**Comment by wingkwong** [comment]
Thanks for confirming. So it seems that there is something wrong with the attachment in the Kanban view. Can you verify that the issue happens only after editing or just after creating a kanban view (probably try refreshing the page as well)? 

If you know the exact steps to reproduce the issue, can you try on the following tag to see if it fixes the issue?

```
nocodb/nocodb-daily:0.100.2-20221223-0602
```

**Comment by 3699n** [comment]
Hmm, when I now try to sort the new Kanban view by descending date, it seems to break the view again. Unfortunately I won't be able to try the tag, because Cloudron doesn't support arbitrary docker images.
```
Dec 23 08:05:24 GET /api/v1/db/data/noco/p_xigvfcuzfn6rq1/md_r239ic6rr25fxp/views/vw_7sv7zll8792u2w?offset=0&limit=25 200 29562 - 197.056 ms
Dec 23 08:05:24 GET /api/v1/db/meta/kanbans/vw_7sv7zll8792u2w 304 - - 1.535 ms
Dec 23 08:05:24 SyntaxError: Unexpected token } in JSON at position 305
Dec 23 08:05:24 at JSON.parse (<anonymous>)
Dec 23 08:05:24 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201177
Dec 23 08:05:24 at Array.forEach (<anonymous>)
Dec 23 08:05:24 at t.BaseModelSqlv2._convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201106)
Dec 23 08:05:24 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201347
Dec 23 08:05:24 at Array.map (<anonymous>)
Dec 23 08:05:24 at t.BaseModelSqlv2.convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201334)
Dec 23 08:05:24 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1199423)
Dec 23 08:05:24 at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 23 08:05:24 at async /app/code/node_modules/nocodb/dist/bundle.js:1:1541912
Dec 23 08:05:24 SyntaxError: Unexpected token } in JSON at position 305
Dec 23 08:05:24 at JSON.parse (<anonymous>)
Dec 23 08:05:24 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201177
Dec 23 08:05:24 at Array.forEach (<anonymous>)
Dec 23 08:05:24 at t.BaseModelSqlv2._convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201106)
Dec 23 08:05:24 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201347
Dec 23 08:05:24 at Array.map (<anonymous>)
Dec 23 08:05:24 at t.BaseModelSqlv2.convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201334)
Dec 23 08:05:24 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1199423)
Dec 23 08:05:24 at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 23 08:05:24 at async /app/code/node_modules/nocodb/dist/bundle.js:1:1541912
Dec 23 08:05:24 GET /api/v1/db/data/noco/p_xigvfcuzfn6rq1/md_r239ic6rr25fxp/views/vw_7sv7zll8792u2w/group/cl_gvfabxzwi2ard3 304 - - 61.796 ms
Dec 23 08:05:24 SyntaxError: Unexpected token } in JSON at position 305
Dec 23 08:05:24 at JSON.parse (<anonymous>)
Dec 23 08:05:24 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201177
Dec 23 08:05:24 at Array.forEach (<anonymous>)
Dec 23 08:05:24 at t.BaseModelSqlv2._convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201106)
Dec 23 08:05:24 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201347
Dec 23 08:05:24 at Array.map (<anonymous>)
Dec 23 08:05:24 at t.BaseModelSqlv2.convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201334)
Dec 23 08:05:24 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1199423)
Dec 23 08:05:24 at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 23 08:05:24 at async /app/code/node_modules/nocodb/dist/bundle.js:1:1541912
Dec 23 08:05:24 SyntaxError: Unexpected token } in JSON at position 305
Dec 23 08:05:24 at JSON.parse (<anonymous>)
Dec 23 08:05:24 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201177
Dec 23 08:05:24 at Array.forEach (<anonymous>)
Dec 23 08:05:24 at t.BaseModelSqlv2._convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201106)
Dec 23 08:05:24 at /app/code/node_modules/nocodb/dist/bundle.js:1:1201347
Dec 23 08:05:24 at Array.map (<anonymous>)
Dec 23 08:05:24 at t.BaseModelSqlv2.convertAttachmentType (/app/code/node_modules/nocodb/dist/bundle.js:1:1201334)
Dec 23 08:05:24 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1199423)
Dec 23 08:05:24 at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 23 08:05:24 at async /app/code/node_modules/nocodb/dist/bundle.js:1:1541912
Dec 23 08:05:24 GET /api/v1/db/data/noco/p_xigvfcuzfn6rq1/md_r239ic6rr25fxp/views/vw_7sv7zll8792u2w/group/cl_gvfabxzwi2ard3 304 - - 78.148 ms
Dec 23 08:05:30 GET /dashboard 301 185 - 9.307 ms
```

**Comment by wingkwong** [comment]
@3699n Are you able to reproduce the issue on the latest version (0.101.2)?
