### ISSUE TITLE
🐛 Bug: Formula field: miscellaneous observations

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#4768]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- [x] MOD(({number} / 10), 2) : no data gets loaded in column; `number` field was of datatype `number`

```
error: select MOD((CAST("number" as DOUBLE PRECISION)) / (CAST(10 as DOUBLE PRECISION)) ,2) as "formula", "nc_k6bn___Sheet-1"."id" as "Id", "nc_k6bn___Sheet-1"."created_at" as "CreatedAt", "nc_k6bn___Sheet-1"."updated_at" as "UpdatedAt", "nc_k6bn___Sheet-1"."number" as "number" from "nc_k6bn___Sheet-1" order by "id" asc limit 25 - function mod(double precision, integer) does not exist
    at Parser.parseErrorMessage (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 222,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
  position: '8',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_func.c',
  line: '523',
  routine: 'ParseFuncOrColumn'
}
dataList :: InternalServerError: Internal Server Error, check server log for more details
    at Function.internalServerError (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/helpers/catchError.ts:50:11)
    at getDataList (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/api/dataApis/dataAliasApis.ts:128:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at dataList (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/api/dataApis/dataAliasApis.ts:17:12)
    at /Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/helpers/catchError.ts:6:14
```

- [x] Use of `-` in column name leads to error during formula creation
similar observation when using a `+` in column name. didn't try for other symbols.
![Screenshot 2023-01-07 at 2 35 43 PM](https://user-images.githubusercontent.com/86527202/211142842-9803a29d-2328-44cb-9a68-748b95f458a9.png)

### Desired Behavior

Work as expected

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.101.0-beta.0**

**Comment by sptv2reg** [comment]
I'm not sure if this is related but with the latest version I've started to receive errors like this:

![image](https://user-images.githubusercontent.com/103186488/211186296-129ed621-401b-4e3f-b454-c947927d9417.png)

This is the formula that I'm using:

`
IF(OR((LEN(CONCAT({SearchConf}, "-")) == 1), ({SearchConf} == {LastSearchConf})), "1", "0")
`

The whole system is actually broken because of this. The rows are not shown any longer (they will reappear if I delete the formula field).

**Comment by wingkwong** [comment]
@sptv2reg Please provide the following info.

1. Your [Project Info](https://docs.nocodb.com/FAQs#how-to-check-my-project-info-)
2. Column type for `SearchConf` and `LastSearchConf`
3. Sample data  for `SearchConf` and `LastSearchConf`

**Comment by sptv2reg** [comment]
Sorry, was actually looking for some version info but couldn't find it. Thanks for guide:

`
Node: **v18.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.101.0-beta.0**
`

SearchConf is LongText
LastSearchConf = SingleLineText

SampleData - attached

[test_data_csv.csv](https://github.com/nocodb/nocodb/files/10367966/test_data_csv.csv)
