### ISSUE TITLE
🐛 Bug: Can´t update higher than 0.100.2 

### ISSUE THREAD

**Issue by WeT-Klb** [nocodb/nocodb#4819]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When i delete my docker container and try to install the letest one the container won´t start. The console on my Qnap showing this:
`Visit -> http://localhost:8080/dashboard
migration file "nc_023_multiple_source" failed
migration failed with error: alter table `nc_sync_source_v2` add `base_id` varchar(20) - Duplicate column name 'base_id'
Error: alter table `nc_sync_source_v2` add `base_id` varchar(20) - Duplicate column name 'base_id'
    at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  code: 'ER_DUP_FIELDNAME',
  errno: 1060,
  sqlState: '42S21',
  sqlMessage: "Duplicate column name 'base_id'",
  sql: 'alter table `nc_sync_source_v2` add `base_id` varchar(20)'
}
`
When i return back to 0.100.2 the containers will work like it is suppoesed to do.

### Desired Behavior

The latest docker image should be installed and running

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2** (MariaDB 10.5.8)
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.100.2**

**Comment by o1lab** [comment]
@mertmit

**Comment by mertmit** [comment]
Looks like there have been an error in migration, can you please manually:
remove `base_id` column from `nc_sync_source_v2`

After this please retry migrating your instance.

Side-note:
New columns added with `nc_023_multiple_source` migration are in below table (please make sure you don't have those 3 columns before migrating)
| Table | Columns |
|-------|---------|
| nc_sync_source_v2      | base_id        |
| nc_bases_v2     | enabled and order         |

**Comment by WeT-Klb** [comment]
If you tell me how to do that. 
With phpMyAdmin i found nc_sync_source_v2 - it has column "base_id".
nc_bases_v2 only has columns enabled and order too.
But I have no idea how to remove them with phpMyAdmin.

**Comment by WeT-Klb** [comment]
Ok - I deleted `enabled` and `oder` from `nc_bases_v2` and I deleted `base_id` from `sync_source_v2` including the foreign key.
Now when i install 0.101.2 i get this message:

`Visit -> http://localhost:8080/dashboard
migration file "nc_023_multiple_source" failed
migration failed with error: alter table `nc_audit_v2` drop foreign key `nc_audit_v2_base_id_foreign` - Can't DROP FOREIGN KEY `nc_audit_v2_base_id_foreign`; check that it exists
Error: alter table `nc_audit_v2` drop foreign key `nc_audit_v2_base_id_foreign` - Can't DROP FOREIGN KEY `nc_audit_v2_base_id_foreign`; check that it exists
    at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  code: 'ER_CANT_DROP_FIELD_OR_KEY',
  errno: 1091,
  sqlState: '42000',
  sqlMessage: "Can't DROP FOREIGN KEY `nc_audit_v2_base_id_foreign`; check that it exists",
  sql: 'alter table `nc_audit_v2` drop foreign key `nc_audit_v2_base_id_foreign`'
}`

What to do now?

**Comment by WeT-Klb** [comment]
Today i tried to upgrade to 0.104.0 - but still no success.
This is the console report:

Visit -> http://localhost:8080/dashboard
migration file "nc_023_multiple_source" failed
migration failed with error: alter table `nc_sync_source_v2` add `base_id` varchar(20) - Duplicate column name 'base_id'
Error: alter table `nc_sync_source_v2` add `base_id` varchar(20) - Duplicate column name 'base_id'
    at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  code: 'ER_DUP_FIELDNAME',
  errno: 1060,
  sqlState: '42S21',
  sqlMessage: "Duplicate column name 'base_id'",
  sql: 'alter table `nc_sync_source_v2` add `base_id` varchar(20)'
}

**Comment by WeT-Klb** [comment]
Here the same result with 0.104.1:

Visit -> http://localhost:8080/dashboard
migration file "nc_023_multiple_source" failed
migration failed with error: alter table `nc_sync_source_v2` add `base_id` varchar(20) - Duplicate column name 'base_id'
Error: alter table `nc_sync_source_v2` add `base_id` varchar(20) - Duplicate column name 'base_id'
    at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  code: 'ER_DUP_FIELDNAME',
  errno: 1060,
  sqlState: '42S21',
  sqlMessage: "Duplicate column name 'base_id'",
  sql: 'alter table `nc_sync_source_v2` add `base_id` varchar(20)'
}

**Comment by WeT-Klb** [comment]
And here with 0.104.2:


Visit -> http://localhost:8080/dashboard
migration file "nc_023_multiple_source" failed
migration failed with error: alter table `nc_sync_source_v2` add `base_id` varchar(20) - Duplicate column name 'base_id'
Error: alter table `nc_sync_source_v2` add `base_id` varchar(20) - Duplicate column name 'base_id'
    at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  code: 'ER_DUP_FIELDNAME',
  errno: 1060,
  sqlState: '42S21',
  sqlMessage: "Duplicate column name 'base_id'",
  sql: 'alter table `nc_sync_source_v2` add `base_id` varchar(20)'
}

**Comment by o1lab** [comment]
cc : @mertmit

**Comment by mertmit** [comment]
@WeT-Klb can you please try adding `nc_023_multiple_source` to your `xc_knex_migrationsv2` table. Looks like this migration applied on your database.

Batch column should be the same value with highest or greater than highest

![image](https://user-images.githubusercontent.com/59797957/215255930-bbd261c8-4aac-45af-b53c-38acb99cd881.png)

Please try to add `nc_023_multiple_source` and try to boot instance if similar error raises for `nc_024_barcode_column_type` and `nc_025_add_row_height ` you can follow same steps for it (if you have doubts please update the issue)

Feel free to contact me via Discord if you need real-time help (you can either @ me on our server, or DM directly)
<img width="342" alt="image" src="https://user-images.githubusercontent.com/59797957/215256215-b5745d21-0e5e-442c-9ec5-4e7eae09ed72.png">



There was a pretty similar error report which we solved recently in our discord, for reference: https://discord.com/channels/661905455894888490/982675629721923595/threads/1068571250433196147

**Comment by WeT-Klb** [comment]
Indeed I need help here - i sent message in Discord.
