### ISSUE TITLE
🐛 Bug: Cannot add formula based on Lookup columns

### ISSUE THREAD

**Issue by pedrorito** [nocodb/nocodb#4864]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I'm adding a new formula column which depends on Lookup columns and gives the error "Invalid formula".
My formula column name is "Locations" and the Lookup column name is "Locations_External" from table "External".
To test out, my formula is simply "{Locations_External}" and it gives the error. I can add other columns from other type.

### Desired Behavior

I should be able to add Formulas which depend on Lookup columns. I have other tables with that implemented already.

### Project Details

NocoDB used as docker : true
NocoDB version : 0.101.2
Database used in NC_DB URL : pg
Project was created by clicking : New Project
Database on which spreadsheet is created : pg
OS on which NocoDB is running: Ubuntu
Database version: postgres:13.4
Docker logs output
```
error: select (select STRING_AGG( , ',') from "nc_icn7___External" as "__nc_formula0" inner join "nc_icn7___nc_m2m_ch9i88942d" as "__nc1" on "__nc1"."table1_id" = "__nc_formula0"."ncRecordId" inner join "nc_icn7___nc_m2m_snmm2qcteh" as "__nc3" on "__nc3"."table1_id" = "__nc_formula0"."ncRecordId" inner join "nc_icn7___Locations" as "__nc_formula2" on "__nc_formula2"."ncRecordId" = "__nc3"."table2_id" inner join "nc_icn7___Locations" as "__nc_formula2" on "__nc_formula2"."ncRecordId" = "__nc_formula0"."ncRecordId" where "__nc1"."table2_id" = "nc_icn7___Services"."ncRecordId") from "nc_icn7___Services" - syntax error at or near ","
    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 90,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '28',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1176',
  routine: 'scanner_yyerror'
}
Error: Formula error: select (select STRING_AGG( , ',') from "nc_icn7___External" as "__nc_formula0" inner join "nc_icn7___nc_m2m_ch9i88942d" as "__nc1" on "__nc1"."table1_id" = "__nc_formula0"."ncRecordId" inner join "nc_icn7___nc_m2m_snmm2qcteh" as "__nc3" on "__nc3"."table1_id" = "__nc_formula0"."ncRecordId" inner join "nc_icn7___Locations" as "__nc_formula2" on "__nc_formula2"."ncRecordId" = "__nc3"."table2_id" inner join "nc_icn7___Locations" as "__nc_formula2" on "__nc_formula2"."ncRecordId" = "__nc_formula0"."ncRecordId" where "__nc1"."table2_id" = "nc_icn7___Services"."ncRecordId") from "nc_icn7___Services" - syntax error at or near ","
    at t.default (/usr/src/app/docker/main.js:1:231281)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async j (/usr/src/app/docker/main.js:1:1513557)
    at async /usr/src/app/docker/main.js:1:18140
j :: n [Error]: Invalid Formula
    at Function.badRequest (/usr/src/app/docker/main.js:1:18805)
    at j (/usr/src/app/docker/main.js:1:1513632)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /usr/src/app/docker/main.js:1:18140
PATCH /api/v1/db/meta/columns/cl_ut8s81vrfxscqu 400 25 - 99.607 ms
```

**Comment by dstala** [comment]
PG table - City `has many` `Sectors`

![Screenshot 2023-01-18 at 11 40 40 AM](https://user-images.githubusercontent.com/86527202/213097715-332626fb-5c37-4179-9ca8-df95ba5b4cb0.png)
![Screenshot 2023-01-18 at 11 40 58 AM](https://user-images.githubusercontent.com/86527202/213097721-077f2376-c2fc-48cf-a5cf-cd7bbea7e661.png)

Lookup columns in City table
- population array <source field datatype Number>
- sector name <source field datatype SingleLineText>

Able to create formula using field {sector name}
Attempt to create formula using field {population array} throws error


```
error: select (select STRING_AGG("__nc_formula0"."population" , ',') from "nc_m1ne___sector" as "__nc_formula0" where "__nc_formula0"."nc_m1ne___city_id" = "nc_m1ne___city"."id") from "nc_m1ne___city" - function string_agg(bigint, unknown) does not exist
    at Parser.parseErrorMessage (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 220,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
  position: '16',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_func.c',
  line: '523',
  routine: 'ParseFuncOrColumn'
}
Error: Formula error: select (select STRING_AGG("__nc_formula0"."population" , ',') from "nc_m1ne___sector" as "__nc_formula0" where "__nc_formula0"."nc_m1ne___city_id" = "nc_m1ne___city"."id") from "nc_m1ne___city" - function string_agg(bigint, unknown) does not exist
    at formulaQueryBuilderv2 (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/formulav2/formulaQueryBuilderv2.ts:844:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at columnAdd (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/api/columnApis.ts:535:9)
    at /Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/helpers/catchError.ts:6:14
columnAdd :: BadRequest [Error]: Invalid Formula
    at Function.badRequest (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/helpers/catchError.ts:41:11)
    at columnAdd (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/api/columnApis.ts:538:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/helpers/catchError.ts:6:14
```

**Comment by wingkwong** [comment]
@dstala are you able to reproduce on latest develop branch?

![image](https://user-images.githubusercontent.com/35857179/214764410-018f89f7-8c63-4adf-a2cd-38994b49d86d.png)

**Comment by pedrorito** [comment]
I tried in 0.104.2, still same problem.
It's enough to make a simple formula as `{Locations_External}`, where "Locations_External" is a Lookup, to reproduce the error.

**Comment by wingkwong** [comment]
@dstala please share the base for me to reproduce.

**Comment by dstala** [comment]
> @dstala please share the base for me to reproduce.

Use Lookup column over a numerical field on `has many` side [ result is an array ] in a formula

**Comment by wingkwong** [comment]
Able to reproduce and got the problem. Will fix that soon.
