### ISSUE TITLE
🐛 Bug: Unable to remove data-source if a lookup column was created

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#4871]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Add a PG data source (empty). Create Country `has many` City. Add any lookup field
Try to remove data-source from team & settings menu

```
baseDelete :: error: delete from "nc_columns_v2" where "fk_model_id" = $1 - update or delete on table "nc_columns_v2" violates foreign key constraint "nc_col_lookup_v2_fk_lookup_column_id_foreign" on table "nc_col_lookup_v2"
    at Parser.parseErrorMessage (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 370,
  severity: 'ERROR',
  code: '23503',
  detail: 'Key (id)=(cl_mgqun9bbynkty7) is still referenced from table "nc_col_lookup_v2".',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'nc_col_lookup_v2',
  column: undefined,
  dataType: undefined,
  constraint: 'nc_col_lookup_v2_fk_lookup_column_id_foreign',
  file: 'ri_triggers.c',
  line: '3283',
  routine: 'ri_ReportViolation'
}

```

### Desired Behavior

Delete data-source

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.101.2**

**Comment by dstala** [comment]
@mertmit for this, let us just unlink database from data-source list from NocoDB. we needn't delete database.

**Comment by o1lab** [comment]
+ to be verified for all virtual fields
