### ISSUE TITLE
🐛 Bug: Immediate Authorization Failure Using Postgres Docker Compose

### ISSUE THREAD

**Issue by shaydin** [nocodb/nocodb#4878]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Using the provided Docker Compose file for Postgres, attempt to spin up a Noco Docker stack.
- Containers will create, start, and show healthy
- Containers and stack look good in Portainer
- Attempt to access <IPADDRESS>:8080 and get met with This Site Can't Be Reached error
- View logs in Portainer for nocodb_nocodb_1 container and see password auth failures for the user/pw in the untouched docker-compose file
- This happens with modified usernames and/or passwords with and without special characters. 

### Desired Behavior

At minimum, the provided docker compose file should spin up successfully and without auth failures. Ideally updating the credentials in the compose file will yield a successful deployment with the ability to begin using the app.

### Project Details

NocoDB used as docker: true
NocoDB Version: version pulled from docker compose
Database used: pg
OS on which NocoDB is running: Debian 11, Docker 20.10.22
All other info N/A
Log:
App started successfully.
Visit -> http://localhost:8080/dashboard
]╔══════════════════════════════════════════════════════════════════════════════╗║                                                                              ║║   EXCEPTION OCCURED!! in PGClient @ createDatabaseIfNotExists                ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   MESSAGE:                                                                   ║║   password authentication failed for user "postgres"                         ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   CODE:                                                                      ║║   28P01                                                                      ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   STACK:                                                                     ║║   error: password authentication failed for user "postgres"                  ║║   at Parser.parseErrorMessage                                                ║║   (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)              ║║   at Parser.handlePacket                                                     ║║   (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)              ║║   at Parser.parse                                                            ║║   (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)               ║║   at Socket.<anonymous>                                                      ║║   (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)                ║║   at Socket.emit (node:events:513:28)                                        ║║   at Socket.emit (node:domain:489:12)                                        ║║   at addChunk (node:internal/streams/readable:315:12)                        ║║   at readableAddChunk (node:internal/streams/readable:289:9)                 ║║   at Socket.Readable.push (node:internal/streams/readable:228:10)            ║║   at TCP.onStreamRead (node:internal/stream_base_commons:190:23)             ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║                                                                              ║║                                                                              ║╚══════════════════════════════════════════════════════════════════════════════╝
error: password authentication failed for user "postgres"
    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 104,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '326',
  routine: 'auth_failed'
}
error: password authentication failed for user "postgres"
    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 104,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '326',
  routine: 'auth_failed'
}

**Comment by wingkwong** [comment]
I just use that docker-compose.yml to start locally, it is working fine. I couldn't see that error. When you modified username and password (namely `POSTGRES_USER` and `POSTGRES_PASSWORD`), did you also modified `NC_DB` as well?

**Comment by shaydin** [comment]
I initially did not modify NC_DB, and later did modify it to match what I had customized. But again, I see this error on a fresh download of the pg version of the docker-compose file no matter what I do.

**Comment by wingkwong** [comment]
Have you added `-v` when you call `docker-compose down` after changing the password? Besides, you may try to connect to your postgres to check if it is still using the old password. If so, that means you are still reading the old env. Try to add `-v` flag to remove the volume and recreate the container.

**Comment by o1lab** [comment]
Moving this to discussion
