### ISSUE TITLE
in cst timezone，datetime column can't input correctly，saved date is less  8hour than selected in page

### ISSUE THREAD

**Issue by qjcjerry** [nocodb/nocodb#492]
Please enter the following details
please provide the following details :
NocoDB used as docker : false
NocoDB version :
Database used in NC_DB URL : mysql
Project was created by clicking : New Project
Database on which spreadsheet is created : mysql
OS on which NocoDB is running : macos
Node.js version if running as node : 14.17.4
Database version : 5.7.9

Steps To Reproduce

create a table;
add acolumn as datetime type;
add a row, select a datetime and save;
select datatime in database;
Expected behavior,save as selected.
![image](https://user-images.githubusercontent.com/6712585/130443374-52317fe6-8180-4be9-888c-70123994e6e6.png)

**Comment by qjcjerry** [comment]
Error: update `xa2__timing` set `starttime` = '2021-08-23T02:00:00.000Z' where `id` = '4' - Incorrect datetime value: '2021-08-23T02:00:00.000Z' for column 'starttime' at row 1
    at Packet.asError (/Users/Jerry/Documents/WebstormProjects/nocodb-seed/node_modules/mysql2/lib/packets/packet.js:722:17)
    at Query.execute (/Users/Jerry/Documents/WebstormProjects/nocodb-seed/node_modules/mysql2/lib/commands/command.js:28:26)
    at Connection.handlePacket (/Users/Jerry/Documents/WebstormProjects/nocodb-seed/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/Users/Jerry/Documents/WebstormProjects/nocodb-seed/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/Users/Jerry/Documents/WebstormProjects/nocodb-seed/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/Jerry/Documents/WebstormProjects/nocodb-seed/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9) {
  code: 'ER_TRUNCATED_WRONG_VALUE',
  errno: 1292,
  sqlState: '22007',
  sqlMessage: "Incorrect datetime value: '2021-08-23T02:00:00.000Z' for column 'starttime' at row 1",
  sql: "update `xa2__timing` set `starttime` = '2021-08-23T02:00:00.000Z' where `id` = '4'"

**Comment by o1lab** [comment]
We're relooking into this.

**Comment by o1lab** [comment]
There is timezone used in 
- database  
- one in user browser. 

Both have to be in sync
