### ISSUE TITLE
🐛 Bug: [SQLite] f :: TypeError: Cannot set properties of undefined (setting 'meta')

### ISSUE THREAD

**Issue by dav1app** [nocodb/nocodb#5048]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I found this error while seeking for the performance issues that I'm facing (probably due to SQLite + slow VPS disks).

- Run the docker instance. In my case, I've set it on Digital Ocean Apps.
- Make a migration from Airtable.
- Try opening the tabs.
- Just keep an eye on the logs. I placed the full log below
- Also notice a huge performance issue after deploying it directly from the Docker image. I believe it is addressed in #4992 

### Desired Behavior

No error

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.104.3**

### Attachments

```
] [2023-02-06 21:25:30] GET /dashboard/_nuxt/index.4c961bc9.css 304 - - 3.014 ms
[nocodb-nocodb] [2023-02-06 21:25:30] GET /dashboard/_nuxt/index.47e0b0a9.js 304 - - 1.403 ms
[nocodb-nocodb] [2023-02-06 21:25:30] GET /dashboard/_nuxt/link.953b5c3c.js 304 - - 1.452 ms
[nocodb-nocodb] [2023-02-06 21:25:30] GET /dashboard/_nuxt/chevron-left.0ba3d00f.js 304 - - 1.406 ms
[nocodb-nocodb] [2023-02-06 21:25:30] GET /dashboard/_nuxt/chevron-right.3af018f8.js 304 - - 2.790 ms
[nocodb-nocodb] [2023-02-06 21:25:31] GET /api/v1/db/data/noco/p_otz1ga9rx1ghav/Token/recBKOqbDMpfRRZqK 200 1710 - 100.311 ms
[nocodb-nocodb] [2023-02-06 21:25:31] GET /api/v1/db/data/noco/p_otz1ga9rx1ghav/md_vwwj5gmuv122u8/recBKOqbDMpfRRZqK/mm/Institution?limit=10&offset=0&where= 200 1594 - 50.602 ms
[nocodb-nocodb] [2023-02-06 21:25:31] GET /api/v1/db/data/noco/p_otz1ga9rx1ghav/md_vwwj5gmuv122u8/recBKOqbDMpfRRZqK/mm/Cybersecurity%20Audit?limit=10&offset=0&where= 200 98 - 34.290 ms
[nocodb-nocodb] [2023-02-06 21:25:31] GET /api/v1/db/data/noco/p_otz1ga9rx1ghav/md_vwwj5gmuv122u8/recBKOqbDMpfRRZqK/mm/Chain?limit=10&offset=0&where= 200 397 - 27.392 ms
[nocodb-nocodb] [2023-02-06 21:25:43] GET /api/v1/db/meta/tables/md_ui0zp4jgmvm7fz 304 - - 4.161 ms
[nocodb-nocodb] [2023-02-06 21:25:44] f :: TypeError: Cannot set properties of undefined (setting 'meta')
[nocodb-nocodb] [2023-02-06 21:25:44]     at Function.getByTitleOrId (/usr/src/app/docker/main.js:1:30332)
[nocodb-nocodb] [2023-02-06 21:25:44]     at async t.getViewAndModelFromRequestByAliasOrId (/usr/src/app/docker/main.js:1:152617)
[nocodb-nocodb] [2023-02-06 21:25:44]     at async f (/usr/src/app/docker/main.js:1:1622873)
[nocodb-nocodb] [2023-02-06 21:25:44]     at async /usr/src/app/docker/main.js:1:27561
[nocodb-nocodb] [2023-02-06 21:25:44] GET /api/v1/db/data/noco/p_otz1ga9rx1ghav/md_ui0zp4jgmvm7fz/views/vw_geamf75pkwze5h?offset=0&limit=25 400 61 - 4.851 ms
[nocodb-nocodb] [2023-02-06 21:25:44] GET /api/v1/db/meta/grids/vw_geamf75pkwze5h/grid-columns 200 7560 - 1.840 ms
[nocodb-nocodb] [2023-02-06 21:25:44] GET /api/v1/db/meta/tables/md_ui0zp4jgmvm7fz/views 200 819 - 3.231 ms
[nocodb-nocodb] [2023-02-06 21:25:44] GET /api/v1/db/meta/grids/vw_8suu7l30o7xg4n/grid-columns 200 3320 - 2.236 ms
[nocodb-nocodb] [2023-02-06 21:25:44] GET /api/v1/db/meta/views/vw_8suu7l30o7xg4n/filters 200 2 - 80.385 ms
[nocodb-nocodb] [2023-02-06 21:25:44] GET /api/v1/db/meta/views/vw_8suu7l30o7xg4n/sorts 200 21 - 8.995 ms
[nocodb-nocodb] [2023-02-06 21:25:44] GET /api/v1/db/data/noco/p_otz1ga9rx1ghav/md_ui0zp4jgmvm7fz/views/vw_8suu7l30o7xg4n?offset=0&limit=25 200 5749 - 244.479 ms
[nocodb-nocodb] [2023-02-06 21:25:44] GET /api/v1/db/meta/views/vw_8suu7l30o7xg4n/columns 200 3320 - 3.026 ms
[nocodb-nocodb] [2023-02-06 21:25:45] GET /api/v1/db/meta/views/vw_8suu7l30o7xg4n/filters 200 2 - 2.940 ms
[nocodb-nocodb] [2023-02-06 21:25:45] GET /api/v1/db/meta/audits/comments/count?ids[]=rec0AGgT5KuuCAAbb&ids[]=rec0hfKbcsFer6fYs&ids[]=rec0nBGqYhuNzu5wF&ids[]=rec11CIBZRxT9NUCe&ids[]=rec13XO4VGxGrhf0r&ids[]=rec1Gm32JmWhGzt0b&ids[]=rec1KkxtuJkuKKObY&ids[]=rec1NIq3LfvLiRURD&ids[]=rec1ddIr5TCsBNqXk&ids[]=rec1pCvvBJqsihGhV&ids[]=rec2WZ1OBfglDtsL6&ids[]=rec3githJOAbdfVxq&ids[]=rec3jxOX4C2A5glAn&ids[]=rec3lVwh1GK8EVsuo&ids[]=rec3uXMfiCHngEsjl&ids[]=rec3ws3fzVTowyA2y&ids[]=rec3x0JwG9TnhrseG&ids[]=rec47Ot3BfdbySTVd&ids[]=rec4VVt1nzAnIAvNG&ids[]=rec4b187rdSNCtlxF&ids[]=rec4eGwGpqerdhL5U&ids[]=rec4xBCJ54s4Y1A2w&ids[]=rec5UFTCr70mjKa67&ids[]=rec5Vju9UbWfxZLk2&ids[]=rec5WD8iTk8gv8rWv&fk_model_id=md_ui0zp4jgmvm7fz 200 2 - 4.987 ms
[nocodb-nocodb] [2023-02-06 21:25:46] GET /api/v1/db/meta/tables/md_r1ol63p6tgf721 304 - - 11.658 ms
[nocodb-nocodb] [2023-02-06 21:25:48] GET /api/v1/db/meta/tables/md_iydkrv4fbditub 304 - - 9.900 ms
[nocodb-nocodb] [2023-02-06 21:25:48] GET /api/v1/db/meta/tables/md_iydkrv4fbditub/views 200 840 - 3.211 ms
[nocodb-nocodb] [2023-02-06 21:25:48] f :: TypeError: Cannot set properties of undefined (setting 'meta')
[nocodb-nocodb] [2023-02-06 21:25:48]     at Function.getByTitleOrId (/usr/src/app/docker/main.js:1:30332)
[nocodb-nocodb] [2023-02-06 21:25:48]     at async t.getViewAndModelFromRequestByAliasOrId (/usr/src/app/docker/main.js:1:152617)
[nocodb-nocodb] [2023-02-06 21:25:48]     at async f (/usr/src/app/docker/main.js:1:1622873)
[nocodb-nocodb] [2023-02-06 21:25:48]     at async /usr/src/app/docker/main.js:1:27561
```

**Comment by brotherko** [comment]
I can confirm having same issue with digitalocean database

**Comment by o1lab** [comment]
Please can you use the latest build @brotherko @dav1app

**Comment by nikhilmuz** [comment]
Same issue, and the latest build gives 503 errors.

**Comment by kekonn** [comment]
I also am running into this issue, I am self hosting and using sqlite as a database. I am getting the error when calling externally (from an angular application) but not when calling though the Swagger.

**Comment by Lizard-King101** [comment]
looks like an invalid baseName provided to the SDK call.

**Comment by o1lab** [comment]
Feel free to reopen the issue if the problem exists in latest. There have been 30,000+ Airtable migrations that have happened on NocoDB successfully.
