### ISSUE TITLE
🔦 Feature: Thumbnail generator for image uploaded

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#5207]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/5435402/221282916-d270b3c4-5e45-47a3-a0a5-0802b01e46fb.png">

### Suggested Solution

.

**Comment by aashishagrawall** [comment]
@o1lab  do we need generate thumbnail automatically for image uploaded ?

**Comment by TheRushingWookie** [comment]
This would be a really useful feature!

**Comment by TheRushingWookie** [comment]
There is also a ticket tracking the nocodb issue where it shows all many to many relations as 1 X Items like 
[#](https://private-user-images.githubusercontent.com/3181551/296655653-5a544433-6dfc-42f4-93df-520004e31745.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNjc2MjQsIm5iZiI6MTcwNTM2NzMyNCwicGF0aCI6Ii8zMTgxNTUxLzI5NjY1NTY1My01YTU0NDQzMy02ZGZjLTQyZjQtOTNkZi01MjAwMDRlMzE3NDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMDEwODQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTAwNmE1N2E4MDhmYmQzNzkxYTc0Yjk1Zjk1ZDg4ODBiNWU0MjJmNDQ5ZmRiMjFhNTVkZDg1MjBiNzUxZTFiMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3DlM1b5wkZOuMDuMg3XcpdlrkDA4APZrJkpqsvQL2Ss)
https://github.com/nocodb/nocodb/issues/6722

**Comment by salim-b** [comment]
@dstala @DarkPhoenix2704 This is supposed to be fixed by https://github.com/nocodb/nocodb/pull/8974, which should be included in NocoDB v0.251.3, right?

I just tested 0.251.3 and the **full images** are still loaded for grid view instead of thumbnails. I configured Backblaze B2 as storage backend, if that matters.

**Comment by salim-b** [comment]
> Can you share the url of both the thumbnail and original image

Original URL (valid): https://rdb-attachments.s3.eu-central-003.backblazeb2.com/nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-lmgyxl_j7Sl6.jpg

Thumbnail URL (invalid): https://rdb-attachments.s3.eu-central-003.backblazeb2.com/nc/thumbnails/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-lmgyxl_j7Sl6.jpg/tiny.jpg

I just checked all files in the corresponding `rdb-attachments` bucket, there are *no* thumbnails, i.e. they were never written to the object store.

**Comment by DarkPhoenix2704** [comment]
Is there any logs you can provide from the instance?

**Comment by salim-b** [comment]
> Is there any logs you can provide from the instance?

Yup, relevant log excerpt:

```
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   ERROR [ThumbnailGeneratorProcessor] Failed to generate thumbnails
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   ERROR [ThumbnailGeneratorProcessor] TypeError: Invalid URL
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   DEBUG [GlobalExceptionFilter] Cannot GET /dashboard/dltemp/15v8By6F80pge0Yp/1722013800000/nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-73zg19_KQzZs.png
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot GET /dashboard/dltemp/15v8By6F80pge0Yp/1722013800000/nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-73zg19_KQzZs.png
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:141:14)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   DEBUG [GlobalExceptionFilter] Cannot GET /dashboard/dltemp/LeTpXgjLlXZJKAg1/1722013800000/nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-lmgyxl_j7Sl6.jpg
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot GET /dashboard/dltemp/LeTpXgjLlXZJKAg1/1722013800000/nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-lmgyxl_j7Sl6.jpg
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:141:14)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   DEBUG [GlobalExceptionFilter] Cannot GET /nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-73zg19_KQzZs.png
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot GET /nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-73zg19_KQzZs.png
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:141:14)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   DEBUG [GlobalExceptionFilter] Cannot GET /nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-lmgyxl_j7Sl6.jpg
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot GET /nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-lmgyxl_j7Sl6.jpg
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:141:14)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
```

**Comment by DarkPhoenix2704** [comment]
Created an issue to track this issue. Will look into this

https://github.com/nocodb/nocodb/issues/9087
