### ISSUE TITLE
🐛 Bug: Docker build missing dependency 

### ISSUE THREAD

**Issue by alexiskattan** [nocodb/nocodb#5216]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1) git clone https://github.com/nocodb/nocodb
2) cd ./packages/nocodb
3) npm run build
4) npm run docker:build
5) docker build .
6) docker run...
7)
[2023-02-27 03:06:20] Error: Cannot find module 'nocodb-sdk'
[2023-02-27 03:06:20] Require stack:
[2023-02-27 03:06:20] - /usr/src/app/docker/main.js
[2023-02-27 03:06:20]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
[2023-02-27 03:06:20]     at Function.Module._load (node:internal/modules/cjs/loader:866:27)
[2023-02-27 03:06:20]     at Module.require (node:internal/modules/cjs/loader:1093:19)
[2023-02-27 03:06:20]     at require (node:internal/modules/cjs/helpers:108:18)
[2023-02-27 03:06:20]     at Object.<anonymous> (/usr/src/app/docker/main.js:1:1188)
[2023-02-27 03:06:20]     at a (/usr/src/app/docker/main.js:1:352)
[2023-02-27 03:06:20]     at Object.<anonymous> (/usr/src/app/docker/main.js:1:156378)
[2023-02-27 03:06:20]     at a (/usr/src/app/docker/main.js:1:352)
[2023-02-27 03:06:20]     at Object.<anonymous> (/usr/src/app/docker/main.js:1:825440)
[2023-02-27 03:06:20]     at a (/usr/src/app/docker/main.js:1:352) {
[2023-02-27 03:06:20]   code: 'MODULE_NOT_FOUND',
[2023-02-27 03:06:20]   requireStack: [ '/usr/src/app/docker/main.js' ]
[2023-02-27 03:06:20] }
[2023-02-27 03:06:04] node:internal/modules/cjs/loader:1024
[2023-02-27 03:06:04]   throw err;

### Desired Behavior

Be able to rebuild the docker image from scratch and deploy it

### Project Details

latest for all

**Comment by wingkwong** [comment]
> Error: Cannot find module 'nocodb-sdk'

You need to build `nocodb-sdk` first.

**Comment by alexiskattan** [comment]
Do I need to add that in the Dockerfile?

Sorry I'm pretty new with Docker and it has been a steep learning curve.

**Comment by wingkwong** [comment]
No need. You may ping me at Discord (`wkw#3278`).

**Comment by alexiskattan** [comment]
Thank you.  Just end you a friend request.

**Comment by apratico** [comment]
Hi!  I have the same issue.. Could someone help me?

**Comment by wingkwong** [comment]
@apratico DM me at Discord (`wkw#3278`)
