### ISSUE TITLE
🐛 Bug: Filter on rollup error's out in PG

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#5232]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- connect to PG sakila (I used default docker postgres databaase)
- customer table, create rollup column 
![Screenshot 2023-03-02 at 11 52 11 AM](https://user-images.githubusercontent.com/86527202/222347516-a784d964-f1db-4c16-a1b6-9d26cdcbefd5.png)
- add filter using this rollup column : count > 25

backend error logged below

```
GET /api/v1/db/data/noco/p_y12a76ylsamw2c/md_vv5e11p5bmbai6/views/vw_mcyu6cdeymz3jb?offset=0&limit=25 500 66 - 24.956 ms
PATCH /api/v1/db/meta/filters/fi_ato90gy78fqsdr 200 - - 32.549 ms
error: select (select count("__nc_rollup"."rental_date") from "rental" as "__nc_rollup" where "customer"."customer_id" = "__nc_rollup"."customer_id") as "Number of rentals", "customer"."customer_id" as "CustomerId", "customer"."store_id" as "StoreId", "customer"."first_name" as "FirstName", "customer"."last_name" as "LastName", "customer"."email" as "Email", "customer"."address_id" as "AddressId", "customer"."activebool" as "Activebool", "customer"."create_date" as "CreateDate", "customer"."last_update" as "LastUpdate", "customer"."active" as "Active" from "customer" where (((('' < (select count("__nc_rollup"."rental_date") from "rental" as "__nc_rollup" where "customer"."customer_id" = "__nc_rollup"."customer_id"))))) order by "customer_id" asc limit 25 - invalid input syntax for integer: ""
    at Parser.parseErrorMessage (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 91,
  severity: 'ERROR',
  code: '22P02',
  detail: undefined,
  hint: undefined,
  position: '578',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'int8.c',
  line: '99',
  routine: 'scanint8'
}
dataList :: InternalServerError: Internal Server Error, check server log for more details
    at Function.internalServerError (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/helpers/catchError.ts:433:11)
    at getDataList (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/api/dataApis/dataAliasApis.ts:133:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at dataList (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/api/dataApis/dataAliasApis.ts:19:24)
    at /Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/helpers/catchError.ts:374:14
GET /api/v1/db/data/noco/p_y12a76ylsamw2c/md_vv5e11p5bmbai6/views/vw_mcyu6cdeymz3jb?offset=0&limit=25 500 66 - 85.084 ms
PATCH /api/v1/db/meta/filters/fi_ato90gy78fqsdr 200 - - 21.515 ms
```

### Desired Behavior

should work

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.105.3**

**Comment by dstala** [comment]
We have an UT test associated with this scenario that currently fails with PG
