### ISSUE TITLE
🐛 Bug: filtering a view on a date field causes 500 error

### ISSUE THREAD

**Issue by wunter8** [nocodb/nocodb#5308]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

* Create a new table with a date column
* Filter the table based on the date column
  * the default operation is `is equal` with an empty value, which causes a string comparison with the date, which fails
  * I want to filter where the date field is blank, but `is blank` also adds a string comparison in the SQL query, which fails

You can see in the network requests that the filter request caused a server 500 error

Here is the server log for the `is equal` operator:
```
nocodb-nocodb-1 | POST /api/v1/db/meta/views/vw_bjj0rp6h8pu2aq/filters 200 351 - 15.863 ms
nocodb-nocodb-1 | error: select "nc_xz14___Test"."id" as "Id", "nc_xz14___Test"."Name" as "Name", "nc_xz14___Test"."Due Date" as "Due Date", "nc_xz14___Test"."Done" as "Done" from "nc_xz14___Test" where (((("Due Date" = '')))) order by "id" asc limit 25 - invalid input syntax for type date: ""
nocodb-nocodb-1 | at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
nocodb-nocodb-1 | at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
nocodb-nocodb-1 | at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
nocodb-nocodb-1 | at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
nocodb-nocodb-1 | at Socket.emit (node:events:513:28)
nocodb-nocodb-1 | at Socket.emit (node:domain:489:12)
nocodb-nocodb-1 | at addChunk (node:internal/streams/readable:315:12)
nocodb-nocodb-1 | at readableAddChunk (node:internal/streams/readable:289:9)
nocodb-nocodb-1 | at Socket.Readable.push (node:internal/streams/readable:228:10)
nocodb-nocodb-1 | at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
nocodb-nocodb-1 | length: 109,
nocodb-nocodb-1 | severity: 'ERROR',
nocodb-nocodb-1 | code: '22007',
nocodb-nocodb-1 | detail: undefined,
nocodb-nocodb-1 | hint: undefined,
nocodb-nocodb-1 | position: '196',
nocodb-nocodb-1 | internalPosition: undefined,
nocodb-nocodb-1 | internalQuery: undefined,
nocodb-nocodb-1 | where: undefined,
nocodb-nocodb-1 | schema: undefined,
nocodb-nocodb-1 | table: undefined,
nocodb-nocodb-1 | column: undefined,
nocodb-nocodb-1 | dataType: undefined,
nocodb-nocodb-1 | constraint: undefined,
nocodb-nocodb-1 | file: 'datetime.c',
nocodb-nocodb-1 | line: '4056',
nocodb-nocodb-1 | routine: 'DateTimeParseError'
nocodb-nocodb-1 | }
nocodb-nocodb-1 | g :: r [Error]: Internal Server Error, check server log for more details
nocodb-nocodb-1 | at Function.internalServerError (/usr/src/app/docker/main.js:1:35424)
nocodb-nocodb-1 | at /usr/src/app/docker/main.js:1:1555323
nocodb-nocodb-1 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
nocodb-nocodb-1 | at async g (/usr/src/app/docker/main.js:1:1554854)
nocodb-nocodb-1 | at async /usr/src/app/docker/main.js:1:34617
nocodb-nocodb-1 | GET /api/v1/db/data/noco/p_3n2p7emplceanb/md_ejcllo7wzg0y2l/views/vw_bjj0rp6h8pu2aq?offset=0&limit=25 500 66 - 27.376 ms
```

The problem seems to be **invalid input syntax for type date: ""**. The SQL query is trying to compare the date field to an empty string `where (((("Due Date" = ''))))` which is not allowed.

Here is the server log for the `is blank` operator:
```
nocodb-nocodb-1 | error: select "nc_xz14___Test"."id" as "Id", "nc_xz14___Test"."Name" as "Name", "nc_xz14___Test"."Due Date" as "Due Date", "nc_xz14___Test"."Done" as "Done" from "nc_xz14___Test" where (((("Due Date" is null or "Due Date" = '')))) order by "id" asc limit 25 - invalid input syntax for type date: ""
nocodb-nocodb-1 | at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
nocodb-nocodb-1 | at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
nocodb-nocodb-1 | at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
nocodb-nocodb-1 | at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
nocodb-nocodb-1 | at Socket.emit (node:events:513:28)
nocodb-nocodb-1 | at Socket.emit (node:domain:489:12)
nocodb-nocodb-1 | at addChunk (node:internal/streams/readable:315:12)
nocodb-nocodb-1 | at readableAddChunk (node:internal/streams/readable:289:9)
nocodb-nocodb-1 | at Socket.Readable.push (node:internal/streams/readable:228:10)
nocodb-nocodb-1 | at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
nocodb-nocodb-1 | length: 109,
nocodb-nocodb-1 | severity: 'ERROR',
nocodb-nocodb-1 | code: '22007',
nocodb-nocodb-1 | detail: undefined,
nocodb-nocodb-1 | hint: undefined,
nocodb-nocodb-1 | position: '218',
nocodb-nocodb-1 | internalPosition: undefined,
nocodb-nocodb-1 | internalQuery: undefined,
nocodb-nocodb-1 | where: undefined,
nocodb-nocodb-1 | schema: undefined,
nocodb-nocodb-1 | table: undefined,
nocodb-nocodb-1 | column: undefined,
nocodb-nocodb-1 | dataType: undefined,
nocodb-nocodb-1 | constraint: undefined,
nocodb-nocodb-1 | file: 'datetime.c',
nocodb-nocodb-1 | line: '4056',
nocodb-nocodb-1 | routine: 'DateTimeParseError'
nocodb-nocodb-1 | }
nocodb-nocodb-1 | g :: r [Error]: Internal Server Error, check server log for more details
nocodb-nocodb-1 | at Function.internalServerError (/usr/src/app/docker/main.js:1:35424)
nocodb-nocodb-1 | at /usr/src/app/docker/main.js:1:1555323
nocodb-nocodb-1 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
nocodb-nocodb-1 | at async g (/usr/src/app/docker/main.js:1:1554854)
nocodb-nocodb-1 | at async /usr/src/app/docker/main.js:1:34617
nocodb-nocodb-1 | GET /api/v1/db/data/noco/p_3n2p7emplceanb/md_ejcllo7wzg0y2l/views/vw_bjj0rp6h8pu2aq?offset=0&limit=25 500 66 - 31.410 ms
```

### Desired Behavior

I would like to filter rows that do/don't have a due date

This might be fixed here already? https://github.com/nocodb/nocodb/pull/5185

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.105.3**

### Attachments

![image](https://user-images.githubusercontent.com/8421688/225368059-90786df6-9201-4e4d-9672-202e75bbf4a0.png)

**Comment by wingkwong** [comment]
Yes. This has been fixed in the above-mentioned PR. In fact, `is equal` will be migrated to `is` + `exact date`. This would be available in the upcoming release. Stay tuned.

<img width="554" alt="image" src="https://user-images.githubusercontent.com/35857179/225508563-19a888c1-60be-4cbd-aa4b-765681bafa73.png">
