### ISSUE TITLE
🐛 Bug: Adding postgres data-source without CREATE ON DATABASE permission

### ISSUE THREAD

**Issue by data-envoy** [nocodb/nocodb#5398]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create a postgres user with adequate permissions, for e.g. 

```
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_user WHERE usename = 'noco_data') THEN
    CREATE USER noco_data WITH PASSWORD 'password'; 
  END IF;
END $$;

GRANT USAGE  ON SCHEMA public TO noco_data;
GRANT SELECT ON all tables IN SCHEMA public TO noco_data;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE table_1 TO noco_data;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE table_2 TO noco_data;
```

In the nocodb UI go to Settings > Data Sources > Add the postgres database with the restricted user.

The following error is returned

```
╔══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                                                          ║
║                                                 EXCEPTION OCCURED!! in PGClient @ createDatabaseIfNotExists              ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║
║   MESSAGE:                                                                                                               ║
║   CREATE SCHEMA IF NOT EXISTS "public"  AUTHORIZATION "noco_data"  - permission denied for database postgres             ║
║                                                                                                                          ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║
║   CODE:                                                                                                                  ║
║   42501                                                                                                                  ║
║                                                                                                                          ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║
║   STACK:                                                                                                                 ║
║   error: CREATE SCHEMA IF NOT EXISTS "public"  AUTHORIZATION "noco_data"  - permission denied for database postgres      ║
║       at Parser.parseErrorMessage (/home/default/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:369:69)   ║
║       at Parser.handlePacket (/home/default/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:188:21)        ║
║       at Parser.parse (/home/default/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:103:30)               ║
║       at Socket.<anonymous> (/home/default/nocodb/packages/nocodb/node_modules/pg-protocol/src/index.ts:7:48)            ║
║       at Socket.emit (node:events:512:28)                                                                                ║
║       at Socket.emit (node:domain:489:12)                                                                                ║
║       at addChunk (node:internal/streams/readable:324:12)                                                                ║
║       at readableAddChunk (node:internal/streams/readable:297:9)                                                         ║
║       at Socket.Readable.push (node:internal/streams/readable:234:10)                                                    ║
║       at TCP.onStreamRead (node:internal/stream_base_commons:190:23)                                                     ║
║                                                                                                                          ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║
║                                                                                                                          ║
║                                                                                                                          ║
╚══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
error: CREATE SCHEMA IF NOT EXISTS "public"  AUTHORIZATION "noco_data"  - permission denied for database postgres
    at Parser.parseErrorMessage (/home/default/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/default/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/default/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/default/nocodb/packages/nocodb/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:512:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 99,
  severity: 'ERROR',
  code: '42501',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'aclchk.c',
  line: '3650',
  routine: 'aclcheck_error'
}
```

### Desired Behavior

If the schema already exists, then don't run `CREATE SCHEMA IF NOT EXISTS` as this requires the user to have permissions to `CREATE ON DATABASE`.

### Project Details

Node: **v19.5.0**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.106.0-beta.0**

**Comment by dstala** [comment]
@data-envoy Can you reach me on discord (dstala). We can get on a call to discuss further
