### ISSUE TITLE
🐛 Bug: Can't login, because connection terminated

### ISSUE THREAD

**Issue by LWJerri** [nocodb/nocodb#5417]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Being in session for a long time.
2. Close the tab and go about your business.
3. after 1-2 days, open the nokoDB page.
4. Try to log in and get this error.

### Desired Behavior

Fix this problem so that I can log in the first time and not get an error, press "Log in" again and only then log in.

### Project Details

Node: **v16.19.1**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.105.3**

### Attachments

![image](https://user-images.githubusercontent.com/50290430/229768494-9a4ebde2-30aa-4cc9-8706-412023113fa9.png)

**Comment by Sov3rain** [comment]
Hello there, we are experiencing the same issue, with the error message (from server our server logs):

```
node:internal/process/promises:279
triggerUncaughtException(err, true /* fromPromise */);
^
Error: update "nc_users_v2" set "email" = $1, "refresh_token" = $2, "token_version" = $3, "updated_at" = CURRENT_TIMESTAMP where "id" = $4 - Connection terminated unexpectedly
at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)
at Object.onceWrapper (node:events:627:28)
at Connection.emit (node:events:513:28)
at Connection.emit (node:domain:489:12)
at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:57:12)
at Socket.emit (node:events:513:28)
at Socket.emit (node:domain:489:12)
at TCP.<anonymous> (node:net:301:12)
```

This is pretty bad because our instance is crashing.

### Project Details
Node: N/A
Arch: N/A
Platform: Deployed on Railway.app
Docker: true
RootDB: pg
PackageVersion: 0.106.0

**Comment by LWJerri** [comment]
> Hello there, we are experiencing the same issue, with the error message (from our server logs):
> 
> ```
> node:internal/process/promises:279
> triggerUncaughtException(err, true /* fromPromise */);
> ^
> Error: update "nc_users_v2" set "email" = $1, "refresh_token" = $2, "token_version" = $3, "updated_at" = CURRENT_TIMESTAMP where "id" = $4 - Connection terminated unexpectedly
> at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)
> at Object.onceWrapper (node:events:627:28)
> at Connection.emit (node:events:513:28)
> at Connection.emit (node:domain:489:12)
> at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:57:12)
> at Socket.emit (node:events:513:28)
> at Socket.emit (node:domain:489:12)
> at TCP.<anonymous> (node:net:301:12)
> ```
> 
> This is pretty bad because our instance is crashing.
> 
> ### Project Details
> Node: N/A Arch: N/A Platform: Deployed on Railway.app Docker: true RootDB: pg PackageVersion: 0.106.0

Does this bug still appear in the latest version?

**Comment by Sov3rain** [comment]
Just upgraded to 106.1 this morning, will let you all know after further testing.

**Comment by Sov3rain** [comment]
Bumping, I encountered the issue this morning again.

```
node:internal/process/promises:279
triggerUncaughtException(err, true /* fromPromise */);
^
Error: update "nc_users_v2" set "email" = $1, "refresh_token" = $2, "token_version" = $3, "updated_at" = CURRENT_TIMESTAMP where "id" = $4 - Connection terminated unexpectedly
at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)
at Object.onceWrapper (node:events:627:28)
at Connection.emit (node:events:513:28)
at Connection.emit (node:domain:489:12)
at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:57:12)
at Socket.emit (node:events:513:28)
at Socket.emit (node:domain:489:12)
at TCP.<anonymous> (node:net:301:12)
```

I must add some details here. We use Noco in a team where 2 users shares the same account. It seems to appear when someone is logged in on a computer and the other one try to connect 48h+ later on another PC. Does it ring some bell?

**Comment by LWJerri** [comment]
Also +1 error:

```
2023-04-24T09:25:38.847581654Z GET /dashboard/_nuxt/error-component.ce1bb191.js 200 1564 - 6.674 ms
2023-04-24T09:25:40.733689781Z l :: Error: select * from "nc_users_v2" limit $1 - Connection terminated unexpectedly
2023-04-24T09:25:40.733724701Z at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)
2023-04-24T09:25:40.733728741Z at Object.onceWrapper (node:events:627:28)
2023-04-24T09:25:40.733731701Z at Connection.emit (node:events:513:28)
2023-04-24T09:25:40.733734061Z at Connection.emit (node:domain:552:15)
2023-04-24T09:25:40.733736581Z at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:57:12)
2023-04-24T09:25:40.733739221Z at Socket.emit (node:events:513:28)
2023-04-24T09:25:40.733741701Z at Socket.emit (node:domain:552:15)
2023-04-24T09:25:40.733744061Z at TCP.<anonymous> (node:net:301:12)
2023-04-24T09:25:40.733746901Z at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
2023-04-24T09:25:40.749170157Z GET /api/v1/db/meta/nocodb/info 400 85 - 14.622 ms
```

**Comment by wingkwong** [comment]
@Sov3rain @LWJerri would like to know more info on db. is it hosting on cloud or what kind of dbs are you using?

**Comment by Sov3rain** [comment]
Hey, for my part I'm using 2 PostgresQL DBs (1 for metadata, 1 for data) hosted on railway.app, so yeah, cloud based stuff.

**Comment by wingkwong** [comment]
@Sov3rain @LWJerri Can you try on this image?

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.107.4-pr-5737-20230525-0958
```

**Comment by wingkwong** [comment]
@Sov3rain You can fork that repo and change first lien of Dockerfile from

```
FROM nocodb/nocodb:latest
```

to

```
FROM nocodb/nocodb-timely:0.107.4-pr-5737-20230525-0958
```

then deploy by choosing your forked repo

**Comment by wingkwong** [comment]
I'm also wondering if this issue is due to Railway DB or not. I've a hypothesis that if the application / DB are not in use for a while, then they will be put on idle state. Once there is someone using it again, another connection is established so the previous one terminated unexpectedly. 

I just provisioned a PG DB and connected using above image. Will check the result after 2 days.

**Comment by LWJerri** [comment]
> @Sov3rain @LWJerri Can you try on this image?
> 
> ```
> docker run -d -p 8888:8080 nocodb/nocodb-timely:0.107.4-pr-5737-20230525-0958
> ```

Okay, I try this build, but we need some time to see effect changes.

**Comment by LWJerri** [comment]
> I use my own server with full rights, which is CapRover, and through it created the database and the NocoDB.
> 
> My database is PSQL v14.5 and I don't see any errors in logs.

My `DATABASE_URL` value is `postgresql://user:pass@srv-captain--noco-db:5432/db?schema=public&connection_limit=9500`

**Comment by Sov3rain** [comment]
@wingkwong I successfully deployed the image and created an account. I will be away from my computer for a whole week, so I will be able to check the result on the 5th of June.

**Comment by wingkwong** [comment]
seems ok fro my side

**Comment by Sov3rain** [comment]
@wingkwong Sorry to report that it seems like it's not working.

![InkedScreenshot_2](https://github.com/nocodb/nocodb/assets/10755450/16c4068d-a06c-4129-95fe-84e6eb040cda)

**Comment by LWJerri** [comment]
> Oh... I can't use test build...
> 
> ![image](https://user-images.githubusercontent.com/50290430/240920202-953cfce8-f20c-4ba3-88fb-36744840d645.png)

I'm still getting this error from the last release.

**Comment by LWJerri** [comment]
@wingkwong

**Comment by LWJerri** [comment]
Hello? Any news?
