### ISSUE TITLE
Error when using PATCH `http://localhost:8080/api/v1/db/data/bulk/{orgs}/{projectName}/{tableName}`: `Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`

### ISSUE THREAD

**Issue by nilsreichardt** [nocodb/nocodb#5467]
## Description

I'm trying to use the `http://localhost:8080/api/v1/db/data/bulk/{orgs}/{projectName}/{tableName}` endpoint with the PATCH method. However, when I'm sending this request, I'm getting a `Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?` error.

```
POST /api/v1/db/data/noco/p_4sx6id6jexdbr4/md_yedna0mjfs2eqo/views/vw_439ltuz737ycb5 200 95 - 22.205 ms
GET /api/v1/db/data/noco/ShowcaseBug/md_yedna0mjfs2eqo/views/vw_439ltuz737ycb5/count 200 11 - 6.432 ms
 KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/Users/nils/Projects/nocodb-seed/node_modules/knex/lib/client.js:307:26)
    at async Runner.ensureConnection (/Users/nils/Projects/nocodb-seed/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/Users/nils/Projects/nocodb-seed/node_modules/knex/lib/execution/runner.js:30:19)
    at async Function.get (/Users/nils/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:1:34926)
    at async t.BaseModelSqlv2.selectObject (/Users/nils/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:1:979275)
    at async t.BaseModelSqlv2.readByPk (/Users/nils/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:1:958444)
    at async t.BaseModelSqlv2.bulkUpdate (/Users/nils/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:1:987448)
    at async l (/Users/nils/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:1:1839622)
    at async Object.t.bulkDataUpdate (/Users/nils/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:1:1839900)
    at async /Users/nils/Projects/nocodb-seed/node_modules/nocodb/dist/bundle.js:1:2032257 {
  sql: undefined,
  bindings: undefined
}
PATCH /api/v1/db/data/bulk/noco/p_4sx6id6jexdbr4/md_yedna0mjfs2eqo 400 116 - 60024.432 ms
```

https://apis.nocodb.com/#tag/DB-Table-Row/operation/db-table-row-bulk-update

## Steps to reproduce

1. Create a project
2. Make a `PATCH` call to `http://localhost:8080/api/v1/db/data/bulk/{orgs}/{projectName}/{tableName}`

## Demo

https://user-images.githubusercontent.com/24459435/231819499-e8a9fa6a-e34c-444c-8a7f-d6448968305b.mp4

## Additional information

```
Node: **v16.13.2**
Arch: **x64**
Platform: **darwin**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.106.0-beta.1**
```

**Comment by o1lab** [comment]
Did you see this happen before ? Looks like its working with us.

If you have any logs DM us. Also pls try with latest version.

**Comment by nilsreichardt** [comment]
Still having the error after upgrading to `0.106.0`. I have never used this endpoint, so not sure if it has worked before.

**Comment by dstala** [comment]
@nilsreichardt can you share some details on how you are using this endpoint? data & parameters passed & number of records that you are trying to do bulk update?

**Comment by nilsreichardt** [comment]
```
curl --location --request PATCH 'http://localhost:8080/api/v1/db/data/bulk/noco/p_4sx6id6jexdbr4/md_k78er01y3vcj7p' \
--header 'xc-auth: ...' \
--header 'Content-Type: application/json' \
--data '[
    {
        "Id": 1,
        "Username": "nilsreichardt"
    }
]'
```

**Comment by wingkwong** [comment]
@nilsreichardt I'm able to reproduce now. Will take a look.
