### ISSUE TITLE
🐛 Bug: Formula error

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#5478]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Store a number as formula

```
error: select $1 as "__dry_run_alias" from "nc_gq9l___Sheet-1" - could not determine data type of parameter $1
    at Parser.parseErrorMessage (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 111,
  severity: 'ERROR',
  code: '42P18',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1359',
  routine: 'exec_parse_message'
}
Error: Formula error: select $1 as "__dry_run_alias" from "nc_gq9l___Sheet-1" - could not determine data type of parameter $1
    at formulaQueryBuilderv2 (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/db/sql-data-mapper/lib/sql/formulav2/formulaQueryBuilderv2.ts:907:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.columnUpdate (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/services/column.svc.ts:132:11)
    at columnUpdate (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/controllers/column.ctl.ts:33:5)
    at /Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/helpers/catchError.ts:391:14
columnUpdate :: BadRequest [Error]: Invalid Formula
    at Function.badRequest (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/helpers/catchError.ts:449:11)
    at Object.columnUpdate (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/services/column.svc.ts:144:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at columnUpdate (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/controllers/column.ctl.ts:33:5)
    at /Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/helpers/catchError.ts:391:14
PATCH /api/v1/db/meta/columns/cl_tg4v84c5xnvhjn 400 25 - 72.213 ms
GET /api/v1/db/meta/projects/p_l3d8iu505di7fk/info 200 110 - 5.068 ms
```

### Desired Behavior

Used to work earlier

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.106.0**

### Attachments

![Screenshot 2023-04-15 at 9 57 31 AM](https://user-images.githubusercontent.com/86527202/232182895-830a860f-2611-4c7b-bf77-1ecd1c587006.png)

**Comment by dstala** [comment]
issue observed only with older version of pg
