### ISSUE TITLE
🐛 Bug: Email plugin is not found after upgrade

### ISSUE THREAD

**Issue by dgleba** [nocodb/nocodb#5543]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Upgrade docker nocodb from 0.90.11 to 105.3.

I get this error:

![image](https://user-images.githubusercontent.com/4622715/234676882-64b89c16-7fcc-4869-8501-65073071b3ef.png)

and:

![image](https://user-images.githubusercontent.com/4622715/234677451-d9d92b8c-4615-4ab0-a564-98ffbe114955.png)

logs:
```
nocodb_1  | SMTP test error ::  Error: Missing credentials for "PLAIN"
nocodb_1  |     at SMTPConnection._formatError (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
nocodb_1  |     at SMTPConnection.login (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:438:38)
nocodb_1  |     at /usr/src/app/node_modules/nodemailer/lib/smtp-transport/index.js:271:32
nocodb_1  |     at SMTPConnection.<anonymous> (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:209:17)
nocodb_1  |     at Object.onceWrapper (node:events:627:28)
nocodb_1  |     at SMTPConnection.emit (node:events:513:28)
nocodb_1  |     at SMTPConnection.emit (node:domain:489:12)
nocodb_1  |     at SMTPConnection._actionEHLO (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:1319:14)
nocodb_1  |     at SMTPConnection._processResponse (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:947:20)
nocodb_1  |     at SMTPConnection._onData (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:749:14) {
nocodb_1  |   code: 'EAUTH',
nocodb_1  |   command: 'API'
nocodb_1  | }
nocodb_1  | d :: Error: SMTP test failed, please check server log for more details.
nocodb_1  |     at t.default.test (/usr/src/app/docker/main.js:1:1028030)
nocodb_1  |     at runMicrotasks (<anonymous>)
nocodb_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
nocodb_1  |     at async Object.t.pluginTest (/usr/src/app/docker/main.js:1:1803381)
nocodb_1  |     at async d (/usr/src/app/docker/main.js:1:1993346)
nocodb_1  |     at async /usr/src/app/docker/main.js:1:14818
nocodb_1  | POST /api/v1/db/meta/plugins/test 400 69 - 35.055 ms
```

Note:
I also upgraded from 105.3 to 106.1 and the error persists.

Also:
This same email setup is working in another nocodb instance on another server. It started at 105.3 and I upgraded to 106.1.

### Desired Behavior

smtp module from app store should send a password reset email.

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.106.1**

**Comment by dgleba** [comment]
I copied my original 0.90.11 installation again to another test installation. 
This time I updated one major version step at a time.

```
    # image: nocodb/nocodb:0.90.11 
    # image: nocodb/nocodb:0.91.10 
    # image: nocodb/nocodb:0.92.4
    # image: nocodb/nocodb:0.96.4
    image: nocodb/nocodb:0.98.4
```
These mail settings work in another nocodb on a different server that started at 105.3
```
NC_SMTP_FROM=no-reply@sxxx.com
NC_SMTP_HOST=10.xxxx.x76
NC_SMTP_PORT=25
#NC_SMTP_USERNAME=
#NC_SMTP_PASSWORD=
NC_SMTP_SECURE=
NC_SMTP_IGNORE_TLS=true
```

I hoped it might migrate things better. I hoped I could get a hint of how to address this issue.

I still get the mail error.

If I export the tables using MySQL mysqldump, can I import only some of the tables to get the project copied over?

**Comment by o1lab** [comment]
We will look into it. Thanks for the details.

Do you suspect any version breaking this ?

**Comment by dgleba** [comment]
I did a poor job of documenting the steps and how the email behaved, so I don't have a good record of which version problems started.

I ran `export` inside the container.
It has quotes around `true` - NC_SMTP_IGNORE_TLS='true'
Is that OK?
When I edit the smtp in app store it showed it disabled.

```
export NC_SMTP_FROM='no-reply@sxxx.com'
export NC_SMTP_HOST='1x.x.6'
export NC_SMTP_IGNORE_TLS='true'
export NC_SMTP_PASSWORD=''
export NC_SMTP_PORT='25'
export NC_SMTP_SECURE=''
export NC_SMTP_USERNAME=''

```

**Comment by dgleba** [comment]
There are a number of things to consider here.

1. in 0.90 I could not get email to work with my internal mail server. Using just IP, from, port, and ignore TLS. Secure is a required field - I am not sure how that played in it. 
2. I used mailjet as a workaround. It worked, but has other concerns like I used a gmail `from` address due to other issues.
3. I can use my internal server in later versions like 105 and 106. But those were not upgraded from 0.90. They started at 105.3.

I just made another copy of my 0.90 installation.
I upgraded it to 0.91.10. email works with mailjet. But I can't figure out how to get it to work with my internal mail server.

**Comment by dgleba** [comment]
I made a minimal install like the one that works in the other location.
I got an email error.

So, this is confusing. It may not be a nocodb issue. 
Seems like coincidence.
I had the install that worked in the other location, and I assumed it would work the same at this location.
There may be corporate network or email server differences between the two locations.

I will keep digging.

```
nocodb_1   | SMTP test error ::  Error: Missing credentials for "PLAIN"
nocodb_1   |     at SMTPConnection._formatError (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
nocodb_1   |     at SMTPConnection.login (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:438:38)
nocodb_1   |     at /usr/src/app/node_modules/nodemailer/lib/smtp-transport/index.js:271:32
nocodb_1   |     at SMTPConnection.<anonymous> (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:209:17)
nocodb_1   |     at Object.onceWrapper (node:events:627:28)
nocodb_1   |     at SMTPConnection.emit (node:events:513:28)
nocodb_1   |     at SMTPConnection.emit (node:domain:489:12)
nocodb_1   |     at SMTPConnection._actionEHLO (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:1319:14)
nocodb_1   |     at SMTPConnection._processResponse (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:947:20)
nocodb_1   |     at SMTPConnection._onData (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:749:14) {
nocodb_1   |   code: 'EAUTH',
nocodb_1   |   command: 'API'
nocodb_1   | }
nocodb_1   | d :: Error: SMTP test failed, please check server log for more details.
nocodb_1   |     at t.default.test (/usr/src/app/docker/main.js:1:1028030)
nocodb_1   |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
nocodb_1   |     at async Object.t.pluginTest (/usr/src/app/docker/main.js:1:1803381)
nocodb_1   |     at async d (/usr/src/app/docker/main.js:1:1993346)
nocodb_1   |     at async /usr/src/app/docker/main.js:1:14818
nocodb_1   | POST /api/v1/db/meta/plugins/test 400 69 - 66.204 ms
nocodb_1   | PATCH /api/v1/db/meta/plugins/nc_sas54rges9nfer 200 1803 - 15.407 ms
nocodb_1   | GET /api/v1/db/meta/plugins 200 26533 - 3.025 ms
```

```
version: '3.6'
services:
  nocodb:
    # http://10.4.71.231:9096
    image: nocodb/nocodb:0.106.1
    ports:
      - "9096:8080"
    restart: always
    environment:
      - NC_DB=pg://dbp:5432?u=postgres&p=postp&d=dkrdb
    volumes:
      - ../data/noco_data:/usr/app/data/
  dbp:
    image: "postgres:15-alpine"
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=dbp
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postp
      - POSTGRES_DB=dkrdb
    ports:
      - "25432:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - pgdata:/var/lib/postgresql/data
  adminer:
    # http://10.4.71.231:9196/  
    image: adminer:4.7
    restart: always
    ports:
      - 9196:8080
volumes:
  pgdata:
```

**Comment by dgleba** [comment]
Closing this.
see #5559
