### ISSUE TITLE
🐛 Bug: Invalid request body when importing from Airtable

### ISSUE THREAD

**Issue by thesauravmitra** [nocodb/nocodb#5553]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Using a Postgres base, use the Import from Airtable option to migrate the database over.
While on a "Form" step (or potentially after the last one), an error shows as "Invalid request body".
Checking the logs on the server, I see the following:
```
d [Error]: Invalid request body
    at Function.ajvValidationError (/usr/src/app/docker/main.js:1:21237)
    at t.validatePayload (/usr/src/app/docker/main.js:1:1443260)
    at Object.t.columnUpdate (/usr/src/app/docker/main.js:1:1810794)
    at re (/usr/src/app/docker/main.js:1:1918131)
    at async /usr/src/app/docker/main.js:1:1934451
    at async t.default (/usr/src/app/docker/main.js:1:1933164)
    at async /usr/src/app/docker/main.js:1:2064651
    at async Promise.all (index 0)
    at async Emittery.emit (/usr/src/app/node_modules/emittery/index.js:257:3) {
  errors: [
    {
      instancePath: '/description',
      schemaPath: '#/components/schemas/StringOrNull/oneOf/0/maxLength',
      keyword: 'maxLength',
      params: [Object],
      message: 'must NOT have more than 255 characters'
    },
    {
      instancePath: '/description',
      schemaPath: '#/components/schemas/StringOrNull/oneOf/1/type',
      keyword: 'type',
      params: [Object],
      message: 'must be null'
    },
    {
      instancePath: '/description',
      schemaPath: '#/components/schemas/StringOrNull/oneOf',
      keyword: 'oneOf',
      params: [Object],
      message: 'must match exactly one schema in oneOf'
    }
  ]
}
```

### Desired Behavior

Successful import

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.106.1**

**Comment by dstala** [comment]
there are few fixes gone in related to airtable import in release v0.202.5; please reopen this ticket if you still face issue during import.
