### ISSUE TITLE
Question: Trouble sending email using our internal mail server

### ISSUE THREAD

**Issue by dgleba** [nocodb/nocodb#5559]
### Steps to reproduce ?

Setup smtp mail as I do for other apps like Metabase and python.

I have tried with `ignore TLS`  `off` and `on`.

![image](https://user-images.githubusercontent.com/4622715/235015376-b20d7433-4453-4141-a4ab-1d75f39d8661.png)

Error:
```
nocodb_1  | 2023-04-27T23:51:30.901395081Z SMTP test error ::  Error: Missing credentials for "PLAIN"
nocodb_1  | 2023-04-27T23:51:30.901423181Z     at SMTPConnection._formatError (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
nocodb_1  | 2023-04-27T23:51:30.901449581Z     at SMTPConnection.login (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:438:38)
nocodb_1  | 2023-04-27T23:51:30.901455581Z     at /usr/src/app/node_modules/nodemailer/lib/smtp-transport/index.js:271:32
nocodb_1  | 2023-04-27T23:51:30.901460981Z     at SMTPConnection.<anonymous> (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:209:17)
nocodb_1  | 2023-04-27T23:51:30.901467981Z     at Object.onceWrapper (node:events:627:28)
nocodb_1  | 2023-04-27T23:51:30.901473181Z     at SMTPConnection.emit (node:events:513:28)
nocodb_1  | 2023-04-27T23:51:30.901478381Z     at SMTPConnection.emit (node:domain:489:12)
nocodb_1  | 2023-04-27T23:51:30.901483281Z     at SMTPConnection._actionEHLO (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:1319:14)
nocodb_1  | 2023-04-27T23:51:30.901488481Z     at SMTPConnection._processResponse (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:947:20)
nocodb_1  | 2023-04-27T23:51:30.901505081Z     at SMTPConnection._onData (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:749:14) {
nocodb_1  | 2023-04-27T23:51:30.901522881Z   code: 'EAUTH',
nocodb_1  | 2023-04-27T23:51:30.901528681Z   command: 'API'
nocodb_1  | 2023-04-27T23:51:30.901533581Z }
nocodb_1  | 2023-04-27T23:51:30.901925681Z d :: Error: SMTP test failed, please check server log for more details.
nocodb_1  | 2023-04-27T23:51:30.901936881Z     at t.default.test (/usr/src/app/docker/main.js:1:1028030)
nocodb_1  | 2023-04-27T23:51:30.901942181Z     at runMicrotasks (<anonymous>)
nocodb_1  | 2023-04-27T23:51:30.901947481Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
nocodb_1  | 2023-04-27T23:51:30.901971381Z     at async Object.t.pluginTest (/usr/src/app/docker/main.js:1:1803381)
nocodb_1  | 2023-04-27T23:51:30.901977981Z     at async d (/usr/src/app/docker/main.js:1:1993346)
nocodb_1  | 2023-04-27T23:51:30.901983181Z     at async /usr/src/app/docker/main.js:1:14818
nocodb_1  | 2023-04-27T23:51:30.902763482Z POST /api/v1/db/meta/plugins/test 400 69 - 39.348 ms
```

### Desired Behavior

Send email like python does below:

I typically use internal mail server `IP address` and ` a fake sender email` to send emails from many programs internally.

I can't figure out how to do the same in nocodb.

Can someone help out?

This python works.
```
mkdir ~/tmp; outfile=~/tmp/testemail1a1218.py
cat << 'HEREDOC' > $outfile
smtp_server = "1.xx.6"  
sender_email = "no-reply@sxxe.com"  
receiver_email = ["dgx@sxx.com"]
subject_text  = 'Test 2023-04-27 from d #6'
bodytext = "Testing. \n Please reply to d@sxxe.com and let me know if you get this. \n\n "
#
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
msg = MIMEMultipart()
part1 = MIMEText(bodytext, 'plain')
msg.attach(part1)
msg['From'] = sender_email
msg['To'] = ", ".join(receiver_email)
msg['Subject'] = subject_text
server = smtplib.SMTP(smtp_server)
server.sendmail(sender_email, receiver_email, msg.as_string())
HEREDOC
python3 $outfile
```

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.106.1**

**Comment by lupa18** [comment]
Same here

**Comment by aretaon** [comment]
Similar issue here. Trying to reach the internal smtp server that accepts anonymous authentication but requires SSL/port 465 results in `SMTP test error ::  Error: Missing credentials for "PLAIN"` even though anonymous authentication should be possible  (see #520):

```
[Nest] 11  - 08/22/2023, 3:14:09 PM   ERROR [i] SMTP test failed, please check server log for more details.
Error: SMTP test failed, please check server log for more details.
    at t.default.test (/usr/src/app/docker/main.js:1:1060308)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async d.pluginTest (/usr/src/app/docker/main.js:1:1217601)
    at async pluginTest (/usr/src/app/docker/main.js:1:111577)
SMTP test error ::  Error: Missing credentials for "PLAIN"
    at SMTPConnection._formatError (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)
    at SMTPConnection.login (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:444:38)
    at /usr/src/app/node_modules/nodemailer/lib/smtp-transport/index.js:272:32
    at SMTPConnection.<anonymous> (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:213:17)
    at Object.onceWrapper (node:events:627:28)
    at SMTPConnection.emit (node:events:513:28)
    at SMTPConnection.emit (node:domain:489:12)
    at SMTPConnection._actionEHLO (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:1331:14)
    at SMTPConnection._processResponse (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:953:20)
    at SMTPConnection._onData (/usr/src/app/node_modules/nodemailer/lib/smtp-connection/index.js:755:14) {
  code: 'EAUTH',
  command: 'API'
```

**Comment by dgleba** [comment]
For my situation I believe it was an odd configuration in our corporate network that led to behaviours that didn't make sense. I don't think it was a nocodb issue in my case.

Don't let this comment stop others from answering. 

Still, you might be better served making a new issue. You could refer to this as a reference to show your research.

**Comment by dstala** [comment]
Closing this as it's issue noticed in earlier release of NocoDB. Please reopen this thread / create a new issue if you still face similar issue with latest release.
