### ISSUE TITLE
invalid database parameters

### ISSUE THREAD

**Issue by gmhafiz** [nocodb/nocodb#563]
NocoDB used as docker : true
NocoDB version : 0.11.39
Database used in NC_DB URL  : mysql
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : mysql
OS on which NocoDB is running :  Linux
Node.js version if running as node : n/a
Database version : mysql5.7

**Steps To Reproduce**

1. Start  mysql5.7 at 3307
```bash
docker run --name mysql-test -p 3307:3306 -e MYSQL_ROOT_PASSWORD=password -d mysql:5.7   
```

2. Check it is running
```
docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED         STATUS         PORTS                                                  NAMES
fd144f84246d   mysql:5.7              "docker-entrypoint.s…"   3 seconds ago   Up 2 seconds   33060/tcp, 0.0.0.0:3307->3306/tcp, :::3307->3306/tcp   mysql-test
```
```
docker exec -it mysql-test bash
mysqladmin -u root -p  status
Enter password: 
Uptime: 376  Threads: 1  Questions: 3  Slow queries: 0  Opens: 105  Flush tables: 1  Open tables: 98  Queries per second avg: 0.007

```

3. Run nocodb
```
docker run --name nocodb --rm -p 8080:8080 \
    -e NC_DB="mysql2://localhost:3307?u=root&p=password&d=d1" \
    -e NC_AUTH_JWT_SECRET="569a1821-0a93-45e8-87ab-eb857f20a010" \
    nocodb/nocodb:latest
```
I get

```
^[[32;141R╔═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                                                         ║
║                                                 EXCEPTION OCCURED!! in MysqlClient @ createDatabaseIfNotExists          ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   MESSAGE:                                                                                                              ║
║   connect ECONNREFUSED 127.0.0.1:3307                                                                                   ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   CODE:                                                                                                                 ║
║   ECONNREFUSED                                                                                                          ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   STACK:                                                                                                                ║
║   Error: connect ECONNREFUSED 127.0.0.1:3307                                                                            ║
║       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)                                                   ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║                                                                                                                         ║
║                                                                                                                         ║
╚═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
Error: connect ECONNREFUSED 127.0.0.1:3307
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3307,
  fatal: true
}
Error: connect ECONNREFUSED 127.0.0.1:3307
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3307,
  fatal: true
}


```

4. Try another way
```
docker run --name nocodb2 --rm -p 8081:8080 \
    -e NC_DB="mysql2://host.docker.internal:3307?u=root&p=password&d=d2" \
    -e NC_AUTH_JWT_SECRET="569a1821-0a93-45e8-87ab-eb857f20a010" \
    nocodb/nocodb:latest
```

```
^[[32;141R╔═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                                                         ║
║                                                 EXCEPTION OCCURED!! in MysqlClient @ createDatabaseIfNotExists          ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   MESSAGE:                                                                                                              ║
║   getaddrinfo ENOTFOUND host.docker.internal                                                                            ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   CODE:                                                                                                                 ║
║   ENOTFOUND                                                                                                             ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║   STACK:                                                                                                                ║
║   Error: getaddrinfo ENOTFOUND host.docker.internal                                                                     ║
║       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)                                                     ║
║                                                                                                                         ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -   ║
║                                                                                                                         ║
║                                                                                                                         ║
╚═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
Error: getaddrinfo ENOTFOUND host.docker.internal
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'host.docker.internal',
  fatal: true
}
Error: getaddrinfo ENOTFOUND host.docker.internal
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'host.docker.internal',
  fatal: true
}


```

Using `mysql2://0.0.0.0:3307` fails too.

**Expected behavior**

Should be able to see my database data

**Comment by pranavxc** [comment]
Try with `--net=host`

```shell
docker run --name nocodb2 --rm -p 8081:8080 \
    -e NC_DB="mysql2://host.docker.internal:3307?u=root&p=password&d=d2" \
    -e NC_AUTH_JWT_SECRET="569a1821-0a93-45e8-87ab-eb857f20a010" \
    --net=host \
    nocodb/nocodb:latest
```

Refer : https://docs.docker.com/network/host/

**Comment by gmhafiz** [comment]
Why didn't I think of it before!

It works. Thanks.

```
docker run --name nocodb2 --rm -p 8081:8080 \
    -e NC_DB="mysql2://localhost:3307?u=root&p=password&d=d2" \
    -e NC_AUTH_JWT_SECRET="569a1821-0a93-45e8-87ab-eb857f20a010" \
    --net=host \
    nocodb/nocodb:latest
```
