### ISSUE TITLE
🐛 Bug: after updated (docker) to 0.107.0 I get multiple errors

### ISSUE THREAD

**Issue by FerLSanchez** [nocodb/nocodb#5679]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Update a working container in 0.106.1 to 0.107.0

Once it boots up again, even I can log in, I get this error:
ERROR [n] Malformed UTF-8 data
Error: Malformed UTF-8 data
    at Object.stringify (/usr/src/app/node_modules/crypto-js/core.js:523:24)
    at WordArray.init.toString (/usr/src/app/node_modules/crypto-js/core.js:278:38)
    at f.getConnectionConfig (/usr/src/app/docker/main.js:1:756558)
    at Function.get (/usr/src/app/docker/main.js:1:1266343)
    at b.getDataList (/usr/src/app/docker/main.js:1:1119421)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async b.dataList (/usr/src/app/docker/main.js:1:1117708)
    at async p.dataList (/usr/src/app/docker/main.js:1:52716)

after a while, also this one:
ERROR [n] Invalid refresh token
Error: Invalid refresh token
    at Function.badRequest (/usr/src/app/docker/main.js:1:646501)
    at S.refreshToken (/usr/src/app/docker/main.js:1:1228807)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async P.refreshToken (/usr/src/app/docker/main.js:1:175256)
    at async /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17

and then when navigating:
ERROR [n] Cannot GET /favicon.ico
NotFoundException: Cannot GET /favicon.ico
    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:136:14)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:140:7)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:140:7)

### Desired Behavior

Everything continues working as expected.

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.107.0**

**Comment by o1lab** [comment]
Thanks for reporting. 0.107+ has nestjs framework for backend and hence couple of beta releases. We are checking this now.

**Comment by pranavxc** [comment]
Looks like related to NC_AUTH_JWT_SECRET, did you change the token while migrating?

**Comment by FerLSanchez** [comment]
No, never changed. In fact, I just checked (and maybe I did wrong) but never used this environment variable since the beginning (my instalation starts at 0.8?.?) . :/

**Comment by pranavxc** [comment]
Just to confirm can you share the command you tried ?

**Comment by FerLSanchez** [comment]
What do you mean by command? I update my containers with watchtower (containrrr/watchtower:latest), so basically is a compose down and up. Then the nocodb webpage is able to navigate and even to login, but when trying to retrieve data, it shows empty.

The errors I shared are there since the beginning, I have logs at 4AM when it updated...

**Comment by pranavxc** [comment]
> What do you mean by command? I update my containers with watchtower (containrrr/watchtower:latest), so basically is a compose down and up. Then the nocodb webpage is able to navigate and even to login, but when trying to retrieve data, it shows empty.
> 
> The errors I shared are there since the beginning, I have logs at 4AM when it updated...

thanks for sharing the details, let's continue chanting in our discord channel - https://discord.gg/5RgZmkW (user - @pranavxc )

**Comment by FerLSanchez** [comment]
Pinged you there! Thank you very much!
