### ISSUE TITLE
🐛 Bug: [Nest] ERROR [i] Missing refresh token

### ISSUE THREAD

**Issue by GiantCrocodile** [nocodb/nocodb#5817]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

After updating from previous version to latest version, I get this error in the docker logs:

```
[Nest] 1 - 06/05/2023, 4:43:37 PM ERROR [i] Missing refresh token
Error: Missing refresh token
at t.NcError.badRequest (/app/code/node_modules/nocodb/dist/bundle.js:1:649372)
at k.refreshToken (/app/code/node_modules/nocodb/dist/bundle.js:1:1245325)
at j.refreshToken (/app/code/node_modules/nocodb/dist/bundle.js:1:174280)
at /app/code/node_modules/@nestjs/core/router/router-execution-context.js:38:29
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async /app/code/node_modules/@nestjs/core/router/router-execution-context.js:46:28
at async /app/code/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

Just open the logon page and check the logging of the docker container. Issue didn't occur in previous versions of nocodb.

### Desired Behavior

No error thrown

### Project Details

Node: **v18.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.108.1**

**Comment by GiantCrocodile** [comment]
I can use the app (login works). The error just occurs every time I open the logon page. I don't see an impact from it.

**Comment by GiantCrocodile** [comment]
Doesn't seem to be completely fixed @pranavxc. After updating to 109.0.1, I get this:

```
Jun 14 12:20:59 [Nest] 1 - 06/14/2023, 10:20:59 AM ERROR [i] Missing refresh token
Jun 14 12:20:59 Error: Missing refresh token
Jun 14 12:20:59 at /app/code/node_modules/@nestjs/core/router/router-execution-context.js:38:29
Jun 14 12:20:59 at async /app/code/node_modules/@nestjs/core/router/router-execution-context.js:46:28
Jun 14 12:20:59 at async /app/code/node_modules/@nestjs/core/router/router-proxy.js:9:17
Jun 14 12:20:59 at j.refreshToken (/app/code/node_modules/nocodb/dist/bundle.js:1:174433)
Jun 14 12:20:59 at k.refreshToken (/app/code/node_modules/nocodb/dist/bundle.js:1:1246586)
Jun 14 12:20:59 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jun 14 12:20:59 at t.NcError.badRequest (/app/code/node_modules/nocodb/dist/bundle.js:1:649568)
Jun 14 17:45:01 [Nest] 1 - 06/14/2023, 3:45:01 PM ERROR [i] Missing refresh token
Jun 14 17:45:01 Error: Missing refresh token
Jun 14 17:45:01 at /app/code/node_modules/@nestjs/core/router/router-execution-context.js:38:29
Jun 14 17:45:01 at async /app/code/node_modules/@nestjs/core/router/router-execution-context.js:46:28
Jun 14 17:45:01 at async /app/code/node_modules/@nestjs/core/router/router-proxy.js:9:17
Jun 14 17:45:01 at j.refreshToken (/app/code/node_modules/nocodb/dist/bundle.js:1:174433)
Jun 14 17:45:01 at k.refreshToken (/app/code/node_modules/nocodb/dist/bundle.js:1:1246586)
Jun 14 17:45:01 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jun 14 17:45:01 at t.NcError.badRequest (/app/code/node_modules/nocodb/dist/bundle.js:1:649568)
Jun 17 00:08:07 [Nest] 1 - 06/16/2023, 10:08:07 PM ERROR [i] Missing refresh token
Jun 17 00:08:07 Error: Missing refresh token
Jun 17 00:08:07 at /app/code/node_modules/@nestjs/core/router/router-execution-context.js:38:29
Jun 17 00:08:07 at async /app/code/node_modules/@nestjs/core/router/router-execution-context.js:46:28
Jun 17 00:08:07 at async /app/code/node_modules/@nestjs/core/router/router-proxy.js:9:17
Jun 17 00:08:07 at j.refreshToken (/app/code/node_modules/nocodb/dist/bundle.js:1:174433)
Jun 17 00:08:07 at k.refreshToken (/app/code/node_modules/nocodb/dist/bundle.js:1:1246586)
Jun 17 00:08:07 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jun 17 00:08:07 at t.NcError.badRequest (/app/code/node_modules/nocodb/dist/bundle.js:1:649568)
Jun 17 00:08:22 [Nest] 1 - 06/16/2023, 10:08:22 PM ERROR [i] Invalid credentials
Jun 17 00:08:22 Error: Invalid credentials
Jun 17 00:08:22 at m.validate (/app/code/node_modules/nocodb/dist/bundle.js:1:1266489)
Jun 17 00:08:22 at t.NcError.badRequest (/app/code/node_modules/nocodb/dist/bundle.js:1:649568)
```

**Comment by dstala** [comment]
@GiantCrocodile Try v0.111.0; if you are still able to reproduce this issue, reopen. Thanks!
