### ISSUE TITLE
🐛 Bug: Auto increment field `ID` not ignored if sent in API payload

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#5871]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Issue observed in PG
- Insert a record from API with Auto increment field `Id` set to 1
- Try to insert a new record from UI after this

```
error: insert into "Sheet1" ("SingleLineText") values ('aaa') returning "Id" as "Id" - duplicate key value violates unique constraint "Sheet1_pkey"
    at Parser.parseErrorMessage (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 185,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key ("Id")=(1) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'Sheet1',
  column: undefined,
  dataType: undefined,
  constraint: 'Sheet1_pkey',
  file: 'nbtinsert.c',
  line: '663',
  routine: '_bt_check_unique'
}
[Nest] 18736  - 06/12/2023, 4:32:33 PM   ERROR [GlobalExceptionFilter] insert into "Sheet1" ("SingleLineText") values ('aaa') returning "Id" as "Id" - duplicate key value violates unique constraint "Sheet1_pkey"
error: insert into "Sheet1" ("SingleLineText") values ('aaa') returning "Id" as "Id" - duplicate key value violates unique constraint "Sheet1_pkey"
    at Parser.parseErrorMessage (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Desired Behavior

Ignore if auto-increment field in API request

### Project Details

v0.108.1

**Comment by shashankvish** [comment]
Hey, I have tested it and couldn't catch up with the error, is the issue fixed as I have tried importing both data fields Id, and SingleTextLine through JSON and after that inserting new records through UI worked.
