### ISSUE TITLE
Error on Frontend init (oauth2 client ID)

### ISSUE THREAD

**Issue by Mystery86HH** [nocodb/nocodb#5971]
By starting the Frontend container an error Abort the first start. Any idea?

Container log:

2023-06-27T11:17:27.220652924Z [Nest] 9  - 06/27/2023, 11:17:27 AM     LOG [NestFactory] Starting Nest application...
2023-06-27T11:17:27.276572444Z [Nest] 9  - 06/27/2023, 11:17:27 AM     LOG [InstanceLoader] PassportModule dependencies initialized +57ms
2023-06-27T11:17:27.276813049Z [Nest] 9  - 06/27/2023, 11:17:27 AM     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
2023-06-27T11:17:27.276869879Z [Nest] 9  - 06/27/2023, 11:17:27 AM     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
2023-06-27T11:17:27.277075335Z [Nest] 9  - 06/27/2023, 11:17:27 AM     LOG [InstanceLoader] o dependencies initialized +0ms
2023-06-27T11:17:27.300053612Z [Nest] 9  - 06/27/2023, 11:17:27 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +23ms
2023-06-27T11:17:27.300296498Z [Nest] 9  - 06/27/2023, 11:17:27 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +1ms
2023-06-27T11:17:27.304019999Z (node:9) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
2023-06-27T11:17:27.304228509Z 
2023-06-27T11:17:27.304257832Z Please migrate your code to use AWS SDK for JavaScript (v3).
2023-06-27T11:17:27.304299760Z For more information, check the migration guide at https://a.co/7PzMCcy
2023-06-27T11:17:27.304338336Z (Use `node --trace-warnings ...` to show where the warning was created)
2023-06-27T11:17:28.322622348Z [Nest] 9  - 06/27/2023, 11:17:28 AM   ERROR [ExceptionHandler] OAuth2Strategy requires a clientID option
2023-06-27T11:17:28.322886763Z TypeError: OAuth2Strategy requires a clientID option
2023-06-27T11:17:28.322923284Z     at _.OAuth2Strategy (/usr/src/app/node_modules/passport-oauth2/lib/strategy.js:87:34)
2023-06-27T11:17:28.322967071Z     at new Strategy (/usr/src/app/node_modules/passport-google-oauth20/lib/strategy.js:52:18)
2023-06-27T11:17:28.322998233Z     at new MixinStrategy (/usr/src/app/node_modules/@nestjs/passport/dist/passport/passport.strategy.js:32:13)
2023-06-27T11:17:28.323037310Z     at new _ (/usr/src/app/docker/main.js:1:1266272)
2023-06-27T11:17:28.323064041Z     at InstanceWrapper.useFactory [as metatype] (/usr/src/app/docker/main.js:1:1268241)
2023-06-27T11:17:28.323103385Z     at Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:354:55)
2023-06-27T11:17:28.323133769Z     at callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:56:45)
2023-06-27T11:17:28.323168010Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-06-27T11:17:28.323200443Z     at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:136:24)
2023-06-27T11:17:28.323229265Z     at async Injector.loadInstance (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:61:13)

**Comment by Mystery86HH** [comment]
Closed
