### ISSUE TITLE
Changing ID type fails

### ISSUE THREAD

**Issue by OmgImAlexis** [nocodb/nocodb#603]
**Please enter the following details**

NocoDB used as docker: `false`
NocoDB version: `0.11.40`
Database used in NC_DB URL: `pg`
Project was created by clicking: `New Project`
Database on which spreadsheet is created: `pg`
OS on which NocoDB is running: `WSL(Ubuntu on Windows 10)`
Node.js version if running as node: `v16.6.1`
Database version: `PostgreSQL 14.0`

**Steps To Reproduce**
1. Create new table with "id" selected
2. Edit id type
3. Profit?

**Expected behavior**
The type to be correctly changed.

<details>
<summary>Logs</summary>

```
Within DB_TABLE_UPDATE handler {
  api: 'tableUpdate',
  env: 'dev',
  dbAlias: 'db',
  project_id: 'vault_syDr',
  args: {
    tn: 'xa1__test',
    _tn: 'test',
    originalColumns: [ [Object] ],
    columns: [ [Object] ]
  },
  sqlOpPlus: true
}
{
  api: 'tableUpdate',
  env: 'dev',
  dbAlias: 'db',
  project_id: 'vault_syDr',
  args: {
    tn: 'xa1__test',
    _tn: 'test',
    originalColumns: [ [Object] ],
    columns: [ [Object] ]
  },
  sqlOpPlus: true
}
╔══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                                                                  ║
║                                                 EXCEPTION OCCURED!! in PGClient @ tableUpdate                                    ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -            ║
║   MESSAGE:                                                                                                                       ║
║                                                                                                                                  ║
║   ALTER TABLE "xa1__test" ALTER COLUMN "id" TYPE uuid;                                                                           ║
║                                                                                                                                  ║
║   ALTER TABLE "xa1__test" ALTER COLUMN "id"  DROP NOT NULL;                                                                      ║
║                                                                                                                                  ║
║   ALTER TABLE "xa1__test" ALTER COLUMN "id"  SET DEFAULT uuid_generate_v1() ;                                                    ║
║   ;alter TABLE "xa1__test" drop constraint IF EXISTS "xa1__test_pkey"; - column "id" cannot be cast automatically to type uuid   ║
║                                                                                                                                  ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -            ║
║   CODE:                                                                                                                          ║
║   42804                                                                                                                          ║
║                                                                                                                                  ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -            ║
║   STACK:                                                                                                                         ║
║   error:                                                                                                                         ║
║   ALTER TABLE "xa1__test" ALTER COLUMN "id" TYPE uuid;                                                                           ║
║                                                                                                                                  ║
║   ALTER TABLE "xa1__test" ALTER COLUMN "id"  DROP NOT NULL;                                                                      ║
║                                                                                                                                  ║
║   ALTER TABLE "xa1__test" ALTER COLUMN "id"  SET DEFAULT uuid_generate_v1() ;                                                    ║
║   ;alter TABLE "xa1__test" drop constraint IF EXISTS "xa1__test_pkey"; - column "id" cannot be cast automatically to type uuid   ║
║       at Parser.parseErrorMessage (/home/xo/code/OmgImAlexis/dooku/node_modules/pg-protocol/dist/parser.js:287:98)               ║
║       at Parser.handlePacket (/home/xo/code/OmgImAlexis/dooku/node_modules/pg-protocol/dist/parser.js:126:29)                    ║
║       at Parser.parse (/home/xo/code/OmgImAlexis/dooku/node_modules/pg-protocol/dist/parser.js:39:38)                            ║
║       at Socket.<anonymous> (/home/xo/code/OmgImAlexis/dooku/node_modules/pg-protocol/dist/index.js:11:42)                       ║
║       at Socket.emit (node:events:394:28)                                                                                        ║
║       at Socket.emit (node:domain:475:12)                                                                                        ║
║       at addChunk (node:internal/streams/readable:312:12)                                                                        ║
║       at readableAddChunk (node:internal/streams/readable:287:9)                                                                 ║
║       at Socket.Readable.push (node:internal/streams/readable:226:10)                                                            ║
║       at TCP.onStreamRead (node:internal/stream_base_commons:190:23)                                                             ║
║                                                                                                                                  ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -            ║
║                                                                                                                                  ║
║                                                                                                                                  ║
╚══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
error: 
ALTER TABLE "xa1__test" ALTER COLUMN "id" TYPE uuid;

ALTER TABLE "xa1__test" ALTER COLUMN "id"  DROP NOT NULL;

ALTER TABLE "xa1__test" ALTER COLUMN "id"  SET DEFAULT uuid_generate_v1() ;
;alter TABLE "xa1__test" drop constraint IF EXISTS "xa1__test_pkey"; - column "id" cannot be cast automatically to type uuid
    at Parser.parseErrorMessage (/home/xo/code/OmgImAlexis/dooku/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/xo/code/OmgImAlexis/dooku/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/xo/code/OmgImAlexis/dooku/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/xo/code/OmgImAlexis/dooku/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:394:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 169,
  severity: 'ERROR',
  code: '42804',
  detail: undefined,
  hint: 'You might need to specify "USING id::uuid".',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '11634',
  routine: 'ATPrepAlterColumnType'
}
error: 
ALTER TABLE "xa1__test" ALTER COLUMN "id" TYPE uuid;

ALTER TABLE "xa1__test" ALTER COLUMN "id"  DROP NOT NULL;

ALTER TABLE "xa1__test" ALTER COLUMN "id"  SET DEFAULT uuid_generate_v1() ;
;alter TABLE "xa1__test" drop constraint IF EXISTS "xa1__test_pkey"; - column "id" cannot be cast automatically to type uuid
    at Parser.parseErrorMessage (/home/xo/code/OmgImAlexis/dooku/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/xo/code/OmgImAlexis/dooku/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/xo/code/OmgImAlexis/dooku/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/xo/code/OmgImAlexis/dooku/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:394:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 169,
  severity: 'ERROR',
  code: '42804',
  detail: undefined,
  hint: 'You might need to specify "USING id::uuid".',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '11634',
  routine: 'ATPrepAlterColumnType'
}
POST /dashboard/?q=sqlOpPlus_tableUpdate 500 348 - 7.638 ms
```
</details>

**Comment by wingkwong** [comment]
Related to https://github.com/nocodb/nocodb/discussions/232 & https://github.com/nocodb/nocodb/discussions/396.

**Comment by dstala** [comment]
duplicate; to be tracked under https://github.com/nocodb/nocodb/discussions/232

**Comment by OmgImAlexis** [comment]
Why is this marker as a feature? This is a bug.
