### ISSUE TITLE
🐛 Bug: TypeError while importing airtable database

### ISSUE THREAD

**Issue by chadek** [nocodb/nocodb#6096]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Running Nocodb with latest bin on debian 12 with a psql backend.

I tried to import an airtable db with various type of data and I ended up with an a huge blob inside logs ended up by the following type error crashing the Nocodb process: 
```
TypeError: ((intermediate value)(intermediate value)(intermediate value) || []).map is not a function
```
Here is the traceback with the begining of the blob. I might provide the wall thing if needed.

```
Jul 29 18:54:50  nocodb[308293]: scription":"Foreign Key to Column"},"color":{"type":"string","description":"Option Color","example":"#cfdffe"},"order":{"type":"number","description":"The order among the options",>
Jul 29 18:54:50  nocodb[308293]:                                                                                                                                                                                     >
Jul 29 18:54:50  nocodb[308293]: TypeError: ((intermediate value)(intermediate value)(intermediate value) || []).map is not a function
Jul 29 18:54:50  nocodb[308293]:     at /snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:1:956930
Jul 29 18:54:50  nocodb[308293]:     at new Promise (<anonymous>)
Jul 29 18:54:50  nocodb[308293]:     at o.<anonymous> (/snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:1:956815)
Jul 29 18:54:50  nocodb[308293]:     at o.emit (node:events:527:28)
Jul 29 18:54:50  nocodb[308293]:     at o.emit (node:domain:475:12)
Jul 29 18:54:50  nocodb[308293]:     at addChunk (node:internal/streams/readable:315:12)
Jul 29 18:54:50  nocodb[308293]:     at readableAddChunk (node:internal/streams/readable:289:9)
Jul 29 18:54:50  nocodb[308293]:     at o.Readable.push (node:internal/streams/readable:228:10)
Jul 29 18:54:50  nocodb[308293]:     at Statement.<anonymous> (/snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:1:945595)
Jul 29 18:54:50  systemd[1]: nocodb.service: Main process exited, code=exited, status=1/FAILURE
```

### Desired Behavior

A working import without crashing the wall Nocodb process

### Project Details

Node: **v16.16.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.109.5**
Runing on debian 12, deployed using [this ansible role](https://galaxy.ansible.com/chadek/nocodb)

**Comment by dstala** [comment]
@chadek there are some fixes gone in to strengthen airtable import in our last release. please reopen this issue if you still face problems with import.
