### ISSUE TITLE
🐛 Bug: migration issue

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#6181]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

```
[Nest] 53928  - 08/15/2023, 9:58:15 AM   ERROR [ExceptionHandler] base.isMeta is not a function
TypeError: base.isMeta is not a function
    at Object.default_1 [as handler] (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/version-upgrader/ncMinimalDbUpgrader.ts:19:15)
    at async Function.upgrade (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/version-upgrader/NcUpgrader.ts:79:15)
    at async InstanceWrapper.useFactory [as metatype] (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/modules/global/init-meta-service.provider.ts:59:5)
    at async Injector.instantiateClass (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/@nestjs/core/injector/injector.js:355:37)
    at async callback (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/@nestjs/core/injector/injector.js:56:34)
    at async Injector.resolveConstructorParams (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/@nestjs/core/injector/injector.js:136:24)
    at async Injector.loadInstance (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/@nestjs/core/injector/injector.js:61:13)
    at async Injector.loadProvider (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/@nestjs/core/injector/injector.js:88:9)
    at async /Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 3)
[nodemon] app crashed - waiting for file changes before starting...
```

### Desired Behavior

x

### Project Details

new-ui

**Comment by dstala** [comment]
[noco-migration-test.db.zip](https://github.com/nocodb/nocodb/files/12341215/noco-migration-test.db.zip)

**Comment by o1lab** [comment]
Need the steps on how this happened
