### ISSUE TITLE
🐛 Bug: while primary key values contain "/" symbol, expand the row to get Record not found banner.

### ISSUE THREAD

**Issue by Afsalmc** [nocodb/nocodb#6202]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

While Primary key values contain "/" symbol, expand the row to get Record not found banner.

### Desired Behavior

Rows should expand regardless of the value of primary key.

### Project Details

Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.109.6**

### Attachments

docker logs shows :

```Nest] 11  - 08/21/2023, 11:12:01 AM   ERROR [i] Cannot GET /api/v1/db/data/noco/p_gcht7dh17qylek/Api/GET%20/api/v./insuranceplans//benefits
NotFoundException: Cannot GET /api/v1/db/data/noco/p_gcht7dh17qylek/Api/GET%20/api/v./insuranceplans//benefits
    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:136:14)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:140:7)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:140:7)
```

**Comment by Afsalmc** [comment]
I see a similar issue https://github.com/nocodb/nocodb/issues/4704
