### ISSUE TITLE
🐛 Bug: Unable to update an entry with timestampz and milliseconds as primary key

### ISSUE THREAD

**Issue by arturohu** [nocodb/nocodb#6551]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

DB: PostgreSQL 15 (TimescaleDB 2.12)

Steps:
1. Create table
    ```sql
    CREATE TABLE mttest.test (
	    id text NOT NULL,
	    "time" timestamptz NOT NULL,
	    ok bool NOT NULL DEFAULT false,
	    CONSTRAINT test_pkey PRIMARY KEY ("time", id)
    );
    CREATE INDEX test_time_index_idx ON mttest.test USING btree ("time" DESC);
    ```
2. Insert data
    ```sql
    INSERT INTO mttest.test (id,"time",ok) VALUES
	     ('a','2023-10-03 06:55:49.508+00',false),
	     ('b','2023-10-03 06:55:49.000+00',false); -- no milliseconds
    ```

3. Set column "ok" from NocoDB of id "a" to "true".

### Desired Behavior

The row with id "a" should be updated as well as the other one.

It seems to be because of the milliseconds rounding during the fetch from NocoDB.

### Project Details

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.111.4**

### Attachments

![image](https://github.com/nocodb/nocodb/assets/41362321/989abff9-0c85-43a9-aacd-7580a0ab74b7)

**Comment by dstala** [comment]
```
TypeError: Cannot read properties of null (reading 'Id')
    at BaseModelSqlv2._extractPksValues (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/db/BaseModelSqlv2.ts:3507:11)
    at BaseModelSqlv2.afterUpdate (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/db/BaseModelSqlv2.ts:3421:21)
    at BaseModelSqlv2.updateByPk (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/db/BaseModelSqlv2.ts:2428:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatasService.dataUpdate (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/services/datas.service.ts:101:12)
    at async DataAliasController.dataUpdate (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/controllers/data-alias.controller.ts:156:12)
[Nest] 55577  - 10/20/2023, 9:29:45 AM   ERROR [GlobalExceptionFilter] Cannot read properties of null (reading 'Id')
TypeError: Cannot read properties of null (reading 'Id')
    at BaseModelSqlv2._extractPksValues (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/db/BaseModelSqlv2.ts:3507:11)
    at BaseModelSqlv2.afterUpdate (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/db/BaseModelSqlv2.ts:3421:21)
    at BaseModelSqlv2.updateByPk (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/db/BaseModelSqlv2.ts:2428:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatasService.dataUpdate (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/services/datas.service.ts:101:12)
    at async DataAliasController.dataUpdate (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/controllers/data-alias.controller.ts:156:12)
```
