### ISSUE TITLE
🐛 Bug:   routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331

### ISSUE THREAD

**Issue by tracure1337** [nocodb/nocodb#6555]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I get these errors. But all my other docker apps work with the mail server and TLS at 587.

Mail only works when disabling "secure".

![image](https://github.com/nocodb/nocodb/assets/43231640/72d2b9f1-eae8-4588-b91c-941a427bfaa3)

```
nocodb_1   | SMTP test error ::  [Error: 139902298934576:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:
nocodb_1   | ] {
nocodb_1   |   library: 'SSL routines',
nocodb_1   |   function: 'ssl3_get_record',
nocodb_1   |   reason: 'wrong version number',
nocodb_1   |     at t.default.test (/usr/src/app/docker/main.js:1:1109187)
nocodb_1   |     at runMicrotasks (<anonymous>)
nocodb_1   |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
nocodb_1   |     at async m.pluginTest (/usr/src/app/docker/main.js:1:1293562)
nocodb_1   |     at async pluginTest (/usr/src/app/docker/main.js:1:116354)
nocodb_1   | SMTP test error ::  [Error: 139902298934576:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:
```

### Desired Behavior

Sending mail encrypted.

### Project Details

NocodDB used as docker. Latest version.

**Comment by johnmaguire** [comment]
I'm also affected by this error. Is it really only possible to connect to SMTP over plaintext?

```
nocodb     | SMTP test error ::  [Error: C03C11EBC97F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
nocodb     | ] {
nocodb     |   library: 'SSL routines',
nocodb     |   reason: 'wrong version number',
nocodb     |   code: 'ESOCKET',
nocodb     |   command: 'CONN'
nocodb     | }
nocodb     | [Nest] 8  - 01/22/2025, 8:14:07 AM   ERROR [GlobalExceptionFilter] SMTP test failed, please check server log for more details.
nocodb     | Error: SMTP test failed, please check server log for more details.
nocodb     |     at SMTP.test (/usr/src/app/docker/main.js:2114:246348)
nocodb     |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
nocodb     |     at async PluginsService.pluginTest (/usr/src/app/docker/main.js:2533:138538)
nocodb     |     at async PluginsController.pluginTest (/usr/src/app/docker/main.js:184:152315)
```

**Comment by javielico** [comment]
Chipping in, I've the same issue.

**Comment by johnmaguire** [comment]
@javielico FYI, port 465 worked where 587 did not. For Gmail, port 465 uses implicit TLS while port 587 uses STARTTLS.

![Image](https://github.com/user-attachments/assets/a098e47e-cc39-40b1-b98a-86a97bdf803b)

**Comment by dstala** [comment]
to be tracked along with #9556
