### ISSUE TITLE
🐛 Bug: Authorization Issue (Digital Ocean / DockerHUB)

### ISSUE THREAD

**Issue by DrazCro1** [nocodb/nocodb#6671]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I have installed clean version on Digital Ocean, after installation I have registered account and once it opens super admin account I got error that I dont have premissions. Sometimes I can login as a normal user, sometimes app says that user does not exist. I think this is server issue on DigitalOcean, 

 failed: WebSocket is closed before the connection is established.

https://starfish-app-v5wyb.ondigitalocean.app/socket.io/?EIO=4&transport=polling&t=OiVXuK7&sid=j_5KtsHTyxZuh-lUAAAA

### Desired Behavior

Status codes_ 401 , 400

### Project Details

odb-nocodb] [2023-10-11 16:30:54] UnauthorizedException: Unauthorized
[nocodb-nocodb] [2023-10-11 16:30:54]     at GlobalGuard.handleRequest (/usr/src/app/node_modules/@nestjs/passport/dist/auth.guard.js:60:30)
[nocodb-nocodb] [2023-10-11 16:30:54]     at /usr/src/app/node_modules/@nestjs/passport/dist/auth.guard.js:44:124
[nocodb-nocodb] [2023-10-11 16:30:54]     at /usr/src/app/node_modules/@nestjs/passport/dist/auth.guard.js:83:24
[nocodb-nocodb] [2023-10-11 16:30:54]     at allFailed (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:111:18)
[nocodb-nocodb] [2023-10-11 16:30:54]     at attempt (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:180:28)
[nocodb-nocodb] [2023-10-11 16:30:54]     at strategy.fail (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:302:9)
[nocodb-nocodb] [2023-10-11 16:30:54]     at /usr/src/app/node_modules/passport-jwt/lib/strategy.js:106:33
[nocodb-nocodb] [2023-10-11 16:30:54]     at /usr/src/app/node_modules/jsonwebtoken/verify.js:171:14
[nocodb-nocodb] [2023-10-11 16:30:54]     at getSecret (/usr/src/app/node_modules/jsonwebtoken/verify.js:97:14)
[nocodb-nocodb] [2023-10-11 16:30:54]     at module.exports [as verify] (/usr/src/app/node_modules/jsonwebtoken/verify.js:101:10) {
[nocodb-nocodb] [2023-10-11 16:31:24]     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
[nocodb-nocodb] [2023-10-11 16:31:24]     at /usr/src/app/node_modules/express/lib/router/index.js:286:9
[nocodb-nocodb] [2023-10-11 16:31:24]     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
[nocodb-nocodb] [2023-10-11 16:31:24]     at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
[nocodb-nocodb] [2023-10-11 16:31:24]     at next (/usr/src/app/node_modules/express/lib/router/route.js:136:14)
[nocodb-nocodb] [2023-10-11 16:31:24]     at next (/usr/src/app/node_modules/express/lib/router/route.js:140:7)
[nocodb-nocodb] [2023-10-11 16:31:24]     at next (/usr/src/app/node_modules/express/lib/router/route.js:140:7)
[nocodb-nocodb] [2023-10-11 16:31:25] [Nest] 6  - 10/11/2023, 4:31:25 PM   DEBUG [GlobalExceptionFilter] Cannot GET /.git/config
[nocodb-nocodb] [2023-10-11 16:31:25] [Nest] 6  - 10/11/2023, 4:31:25 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot GET /.git/config
[nocodb-nocodb] [2023-10-11 16:31:25]     at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
[nocodb-nocodb] [2023-10-11 16:31:25]     at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
[nocodb-nocodb] [2023-10-11 16:31:25]     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
[nocodb-nocodb] [2023-10-11 16:31:25]     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
[nocodb-nocodb] [2023-10-11 16:31:25]     at /usr/src/app/node_modules/express/lib/router/index.js:286:9
[nocodb-nocodb] [2023-10-11 16:31:25]     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
[nocodb-nocodb] [2023-10-11 16:31:25]     at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
[nocodb-nocodb] [2023-10-11 16:31:25]     at next (/usr/src/app/node_modules/express/lib/router/route.js:136:14)
[nocodb-nocodb] [2023-10-11 16:31:25]     at next (/usr/src/app/node_modules/express/lib/router/route.js:140:7)
[nocodb-nocodb] [2023-10-11 16:31:25]     at next (/usr/src/app/node_modules/express/lib/router/route.js:140:7)
[nocodb-nocodb] [2023-10-11 16:30:54]   response: { message: 'Unauthorized', statusCode: 401 },
[nocodb-nocodb] [2023-10-11 16:30:54]   status: 401,
[nocodb-nocodb] [2023-10-11 16:30:54]   options: {}
[nocodb-nocodb] [2023-10-11 16:30:54] }
[nocodb-nocodb] [2023-10-11 16:30:55] UnauthorizedException: Unauthorized
[nocodb-nocodb] [2023-10-11 16:30:55]     at GlobalGuard.handleRequest (/usr/src/app/node_modules/@nestjs/passport/dist/auth.guard.js:60:30)
[nocodb-nocodb] [2023-10-11 16:30:55]     at /usr/src/app/node_modules/@nestjs/passport/dist/auth.guard.js:44:124
[nocodb-nocodb] [2023-10-11 16:30:55]     at /usr/src/app/node_modules/@nestjs/passport/dist/auth.guard.js:83:24
[nocodb-nocodb] [2023-10-11 16:30:55]     at allFailed (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:111:18)
[nocodb-nocodb] [2023-10-11 16:30:55]     at attempt (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:180:28)
[nocodb-nocodb] [2023-10-11 16:30:55]     at strategy.fail (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:302:9)
[nocodb-nocodb] [2023-10-11 16:30:55]     at /usr/src/app/node_modules/passport-jwt/lib/strategy.js:106:33
[nocodb-nocodb] [2023-10-11 16:30:55]     at /usr/src/app/node_modules/jsonwebtoken/verify.js:171:14
[nocodb-nocodb] [2023-10-11 16:30:55]     at getSecret (/usr/src/app/node_modules/jsonwebtoken/verify.js:97:14)
[nocodb-nocodb] [2023-10-11 16:30:55]     at module.exports [as verify] (/usr/src/app/node_modules/jsonwebtoken/verify.js:101:10) {
[nocodb-nocodb] [2023-10-11 16:30:55]   response: { message: 'Unauthorized', statusCode: 401 },
[nocodb-nocodb] [2023-10-11 16:30:55]   status: 401,
[nocodb-nocodb] [2023-10-11 16:30:55]   options: {}
[nocodb-nocodb] [2023-10-11 16:30:55] }

**Comment by dstala** [comment]
Closing this as this was on older version of NocoDB. Issues related to DO deployment have been fixed & if you see any issue with latest release, please reopen this thread
