### ISSUE TITLE
🐛 Bug: Exception error (force close NocoDB)

### ISSUE THREAD

**Issue by haranobuhardo** [nocodb/nocodb#6698]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I'm not sure whether people can reproduce this, but I did nothing with my NocoDB, just use it as it is, and updated from 0.1x version to the latest 0.202.4 version, and this thing start happening.

### Desired Behavior

The error occurred randomly, sometimes it is okay, sometimes it is not (the exception error -> force quit NocoDB -> can't connect to DB -> wait for steady state again) 
Sometimes the error occurred when I try to access the table inside NocoDB's Base, sometimes it is because of a API call.

I've monitored the docker container, and it produce this logs:

```
[Nest] 9  - 10/16/2023, 1:55:50 PM     LOG [DatasService] error: password authentication failed for user "postgres"
/usr/src/app/node_modules/pg-protocol/dist/parser.js:287
        const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);
                                                                                                 ^

error: password authentication failed for user "postgres"
    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 104,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '323',
  routine: 'auth_failed'
}
```

### Project Details

- NocoDB used as docker: true
- NocoDB version: 0.202.4
- Database used in NC_DB URL: pg
- Project was created by clicking: New Project
- Database on which spreadsheet is created: pg
- Database version: Postgresql 15

**Comment by dstala** [comment]
closing this thread as its on a older version. please reopen this ticket if you still see this on latest version
