### ISSUE TITLE
🐛 Bug: Duplicate column name

### ISSUE THREAD

**Issue by kamenkadmitry** [nocodb/nocodb#6709]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When adding a new field in a new table, the system gives an error that this field is a duplicate. "Duplicate column name" Although this field does not exist at all and has never existed. 
Any field stops adding, no matter what type of field you choose, the error is the same. Duplicate field

### Desired Behavior

So that when adding a field is added.

### Project Details

Docker Compose . NocoDB v.0.202.4 based Postgres 14. Debian 12

**Comment by dstala** [comment]
@kamenkadmitry can you help us with a screenshot / error logs ? i tried on latest docker & adding new fields was fine. Does issue still persist on page reload?

**Comment by kamenkadmitry** [comment]
Yes, after restarting the page the problem persists. It turned out that the problem only exists when using the Cyrillic alphabet. If you give the column a name in English, then everything works as it should.
![firefox_T33FfUHmNN](https://github.com/nocodb/nocodb/assets/81700662/ad7174b3-bdf3-4c81-8bc6-a35689d58726)

**Comment by kamenkadmitry** [comment]
[Nest] 11  - 10/17/2023, 12:28:11 PM   DEBUG [GlobalExceptionFilter] Cannot GET /.git/config
[Nest] 11  - 10/17/2023, 12:28:11 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot GET /.git/config
    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:136:14)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:140:7)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:140:7)
[Nest] 11  - 10/17/2023, 12:56:35 PM   DEBUG [GlobalExceptionFilter] Cannot GET /+CSCOE+/logon.html
[Nest] 11  - 10/17/2023, 12:56:35 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot GET /+CSCOE+/logon.html
    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:136:14)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:140:7)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:140:7)
[Nest] 11  - 10/17/2023, 1:27:26 PM   DEBUG [GlobalExceptionFilter] Cannot POST /goform/set_LimitClient_cfg
[Nest] 11  - 10/17/2023, 1:27:26 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot POST /goform/set_LimitClient_cfg
    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:136:14)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:140:7)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:140:7)

**Comment by kamenkadmitry** [comment]
When the error appears in the browser console, I get the following output /

Firefox cannot connect to the server wss://mysite.com/socket.io/?EIO=4&transport=websocket&sid=188CfWmy5mHI_aZPAAD-.

I changed the domain to a nonexistent one. Judging by the error it is necessary to proxy Websocket ?

**Comment by kamenkadmitry** [comment]
New circumstances. When adding a column name in Cyrillic, the first column is added without problems. And the subsequent columns say that it is a duplicate and such a column already exists

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/commit/aa5cc48c0ab4b2d04b786d4ce9aed5150ad7a773
