### ISSUE TITLE
🐛 Bug: AjvError: Invalid request body when importing from Airtable

### ISSUE THREAD

**Issue by mhdismail** [nocodb/nocodb#6867]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

The error occurs when importing from Airtable, it's a relatively big base with 12 tables and multiple forms.

The table schema, views, forms.. are all imported normally, the data import fails, check attached image.

### Desired Behavior

It should import the base from airtable successfully, no errors.

### Project Details

Docker: true
Nocodb version: v2.0.4 (and v2.0.5)
Database: PG
Node.js version: v18
Database version: 15

### Attachments

<img width="1724" alt="Screenshot 2023-11-02 at 1 45 01 PM" src="https://github.com/nocodb/nocodb/assets/4080121/b440afa0-0211-4e01-b69f-964908881a32">

**Comment by mhdismail** [comment]
Does anyone have any idea why this is happening? Maybe I can look into it and fix the issue.

**Comment by dstala** [comment]
One issue that I could see was with importing form view with lengthy description. Form view description in NocoDB is currently limited to 255 characters. We need to either change limit (OR) truncate description while importing from Airtable


```
error: insert into "nc_form_view_v2" ("base_id", "created_at", "fk_view_id", "heading", "show_blank_form", "source_id", "subheading", "submit_another_form", "success_msg", "updated_at") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) - value too long for type character varying(255)
    at Parser.parseErrorMessage (/Users/rajuudava/NocoDB/nocohub/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/rajuudava/NocoDB/nocohub/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/rajuudava/NocoDB/nocohub/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocohub/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 99,
  severity: 'ERROR',
  code: '22001',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'varchar.c',
  line: '632',
  routine: 'varchar'
}
```

**Comment by dstala** [comment]
@mhdismail there were some fixes done recently. can you try it out again with v0.204.1? let us know if issue persists

**Comment by dstala** [comment]
Closing this thread. Reopen if issue persists with latest release.
