### ISSUE TITLE
🐛 Bug: 8080 Port occupied node:events:515       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by githubmyname** [nocodb/nocodb#6891]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

8080 Port occupied 
deepin v23 linux
Noco-linux-x64 https://github.com/nocodb/nocodb/releases/download/0.202.5/Noco-linux-x64

If there is another program occupying port 8080, it will not automatically run the sequence +1 port number, but will report an error.

```
node:events:515
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (node:net:1422:16)
    at listenInCluster (node:net:1470:12)
    at Server.listen (node:net:1558:7)
    at Function.listen (/snapshot/pkg-executable/node_modules/express/lib/application.js:635:24)
    at /snapshot/pkg-executable/index.js:7:28
    at Object.<anonymous> (/snapshot/pkg-executable/index.js:13:3)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1449:8)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:64:3)
    at Function.runMain (pkg/prelude/bootstrap.js:1980:13)
    at node:internal/main/run_main_module:17:47 {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 8080
}

Node.js v18.5.0
```

### Desired Behavior

+1 port number, normal operation

### Project Details

Node: **v18.5.0**
Arch: **x64**
Platform: **Deepin v23 linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.202.5**

### Attachments

![图片](https://github.com/nocodb/nocodb/assets/149666360/2fc14154-2eab-4b6c-b783-6e3d058826f8)

**Comment by o1lab** [comment]
You will have to provide 'PORT' as env variable otherwise. [Read the docs](https://docs.nocodb.com/getting-started/self-hosted/environment-variables/).

**Comment by githubmyname** [comment]
> You will have to provide 'PORT' as env variable otherwise. [Read the docs](https://docs.nocodb.com/getting-started/self-hosted/environment-variables/).


thank
