### ISSUE TITLE
Not a valid syntax - Error when filtering columns with column names containing "-"

### ISSUE THREAD

**Issue by numberpi** [nocodb/nocodb#690]
Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.11.46**

**Steps To Reproduce**
1. Add a column with name _Vorgangs-NR_
2. Try adding any kind of filter
3. Error in log file

**Expected behavior**
Should support special characters in column names or prevent naming of columns like that.

**Error**
```
Error: (Vorgangs-NR,is,null) : not a valid syntax
    at /usr/src/app/docker/main.js:2:180392
    at Array.forEach (<anonymous>)
    at o (/usr/src/app/docker/main.js:2:179706)
    at Builder.xwhere (/usr/src/app/docker/main.js:2:183722)
    at l.countByPk (/usr/src/app/docker/main.js:2:361219)
    at l.count (/usr/src/app/docker/main.js:2:636191)
    at /usr/src/app/docker/main.js:2:28341
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at l.middleware (/usr/src/app/docker/main.js:2:639770)

```

**Comment by wingkwong** [comment]
Closing as it has been fixed in ``0.83.0``.

![image](https://user-images.githubusercontent.com/35857179/151648628-ec4672f5-a3f0-4565-a554-525079b5b779.png)
