### ISSUE TITLE
🐛 Bug: Import excel throw 42701 Error

### ISSUE THREAD

**Issue by xJkit** [nocodb/nocodb#6998]
### Please confirm if bug report does NOT exists already ?

- [x] I confirm there is no existing issue for this

### Steps to reproduce ?

import the excel file as provided. It throw an error.

The Web UI says "The column already exists." which is really confusing.

According to the server messages, it indicates that the column `field` specified more than once. However, there is no field called `field`. All of fields are renamed. 

Please check the attachments for screenshot and excel example for more detail.

```
error: /* xc */
CREATE TABLE "nc_y35o___商品清單" ( "ID" bigint NOT NULL, "SKU" bool NULL DEFAULT false, "field" character varying NULL, "field" text NULL, "field" bigint NULL, "field" date NULL, "field" date NULL, "field" date NULL, "created_at" timestamp NULL DEFAULT now(), "updated_at" timestamp NULL DEFAULT now(), PRIMARY KEY("ID")); - column "field" specified more than once
    at Parser.parseErrorMessage (/Users/jaychung/Documents/Workspace/js/beru_whitesun_lars/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/jaychung/Documents/Workspace/js/beru_whitesun_lars/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/jaychung/Documents/Workspace/js/beru_whitesun_lars/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/jaychung/Documents/Workspace/js/beru_whitesun_lars/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9)
    at Readable.push (node:internal/streams/readable:286:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 103,
  severity: 'ERROR',
  code: '42701',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '2406',
  routine: 'MergeAttributes'
}
[Nest] 16428  - 11/16/2023, 6:38:52 PM   ERROR [GlobalExceptionFilter] /* xc */
CREATE TABLE "nc_y35o___商品清單" ( "ID" bigint NOT NULL, "SKU" bool NULL DEFAULT false, "field" character varying NULL, "field" text NULL, "field" bigint NULL, "field" date NULL, "field" date NULL, "field" date NULL, "created_at" timestamp NULL DEFAULT now(), "updated_at" timestamp NULL DEFAULT now(), PRIMARY KEY("ID")); - column "field" specified more than once
error: /* xc */
CREATE TABLE "nc_y35o___商品清單" ( "ID" bigint NOT NULL, "SKU" bool NULL DEFAULT false, "field" character varying NULL, "field" text NULL, "field" bigint NULL, "field" date NULL, "field" date NULL, "field" date NULL, "created_at" timestamp NULL DEFAULT now(), "updated_at" timestamp NULL DEFAULT now(), PRIMARY KEY("ID")); - column "field" specified more than once
    at Parser.parseErrorMessage (/Users/jaychung/Documents/Workspace/js/beru_whitesun_lars/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/jaychung/Documents/Workspace/js/beru_whitesun_lars/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/jaychung/Documents/Workspace/js/beru_whitesun_lars/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/jaychung/Documents/Workspace/js/beru_whitesun_lars/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9)
    at Readable.push (node:internal/streams/readable:286:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Desired Behavior

All data should imported correctly.

### Project Details

Node: **v20.9.0**
Arch: **x64**
Platform: **darwin**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.202.5**

### Attachments

![CleanShot 2023-11-16 at 18 47 31](https://github.com/nocodb/nocodb/assets/18704345/fbd2cbb5-99d7-4433-a53c-b3034aecdf4e)

![CleanShot 2023-11-16 at 18 43 48](https://github.com/nocodb/nocodb/assets/18704345/87f8904c-dd07-4321-90c4-a026c0210bf6)

![CleanShot 2023-11-16 at 18 45 47](https://github.com/nocodb/nocodb/assets/18704345/b28257c2-a925-4f1d-b01b-c752eadffa4b)

### Excel file

[test.xlsx](https://github.com/nocodb/nocodb/files/13376568/test.xlsx)

**Comment by wingkwong** [comment]
@xJkit in the next release, you can set `NC_SANITIZE_COLUMN_NAME=false` to support chinese words.

**Comment by xJkit** [comment]
Thanks for your hard work.
