### ISSUE TITLE
🐛 Bug: [MSSQL] Changing multiple rows at once throws SQL Error when using SQL Server

### ISSUE THREAD

**Issue by MatthewLount** [nocodb/nocodb#7012]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Try copying from an airtable, excel sheet, or multiple rows of text from notepad, and paste them into a column with multiple items in it... 

I copied these 2 names and pasted from the top row:
  James Smithsonian
  John Smith

It throws an error:
"There was a syntax error in your SQL query".
![image](https://github.com/nocodb/nocodb/assets/94880394/51605c9d-adea-4bd1-bca9-ff035820ddf3)

Error information from running Docker process:
[Nest] 11  - 11/16/2023, 9:14:29 PM   ERROR [GlobalExceptionFilter] update [nc_jjah___Capital Requests] set [id] = @p0, [Main_Contact] = @p1 where [id] = @p2;select @@rowcount - Cannot update identity column 'id'.
Error: update [nc_jjah___Capital Requests] set [id] = @p0, [Main_Contact] = @p1 where [id] = @p2;select @@rowcount - Cannot update identity column 'id'.
    at RequestTokenHandler.onErrorMessage (/usr/src/app/node_modules/tedious/lib/token/handler.js:287:21)
    at Readable.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:18:33)
    at Readable.emit (node:events:514:28)
    at Readable.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at next (node:internal/streams/from:98:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Desired Behavior

Ability to paste multiple rows at once is pretty well a must-have... 
Optimally, when nocodb throws an SQL error, it should also reload the cells it failed to update, so users aren't confused about what data is actually in the database and what got rejected.

### Project Details

NocoDB used as docker: true
NocoDB version: 0.202.7
Database used in NC_DB URL: mssql
Project was created by: New Project
Database on which spreadsheet is created: mssql
OS on which NocoDB is running: Ubuntu (via WSL 2 on Windows 10 x64)
Node.js version: N/A
Database Version: SQL Server 13.0.5233.0

**Comment by dstala** [comment]
We have not noticed much traction with usage of MS SQL Server support & hence we decided to narrow down support mainly to MySQL & PG. Please feel free to connect with us to discuss more on your use-case [here](https://cal.com/nocodb).
