### ISSUE TITLE
🐛 Bug: Upgrade to 0.202.9 causes NocoDB to crash when visualizing a Grid View with Group By

### ISSUE THREAD

**Issue by progamax** [nocodb/nocodb#7205]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Have a Table with a Grid View and a Group By on it
- Upgrade to 0.202.9 (from 0.202.8 in my case)
- Try to open this Grid View

### Desired Behavior

Should not crash

### Project Details

NocoDB as Node project. v0.202.9

### Attachments

**Log :**
[Nest] 48184  - 12/12/2023 00:13:09   ERROR [GlobalExceptionFilter] Cannot read properties of null (reading 'title')
TypeError: Cannot read properties of null (reading 'title')
    at D:\wilful_crane\node_modules\nocodb\dist\bundle.js:2:541954
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BaseModelSqlv2.substituteColumnIdsWithColumnTitles (D:\wilful_crane\node_modules\nocodb\dist\bundle.js:2:542018)
    at async BaseModelSqlv2.execAndParse (D:\wilful_crane\node_modules\nocodb\dist\bundle.js:2:541383)
    at async BaseModelSqlv2.groupBy (D:\wilful_crane\node_modules\nocodb\dist\bundle.js:2:489309)
    at async DatasService.getDataGroupBy (D:\wilful_crane\node_modules\nocodb\dist\bundle.js:2:1630385)
    at async DatasService.dataGroupBy (D:\wilful_crane\node_modules\nocodb\dist\bundle.js:2:1627275)
    at async DataAliasController.dataGroupBy (D:\wilful_crane\node_modules\nocodb\dist\bundle.js:2:366362)

I think this is related to https://github.com/nocodb/nocodb/pull/7060 changes

**Comment by progamax** [comment]
Hi @mertmit, I use a Mysql 8.0 database

**Comment by mertmit** [comment]
I couldn't reproduce this. Can you share what is the type of field you are trying to group by?

**Comment by mertmit** [comment]
If your group by field type is BT, can you try this build:
`docker run -d -p 8888:8080 nocodb/nocodb-timely:0.202.9-pr-7146-20231204-0725`
There was [an issue ](https://github.com/nocodb/nocodb/pull/7146)resolved but not yet released, I think might be same with yours.
If build is working for you, your issue should be fixed by next release, please let me know the result.

**Comment by progamax** [comment]
Yes that's the type of my field. And the build solves my issue, thanks !
