### ISSUE TITLE
🐛 Bug: [MariaDB] Attempting to duplicate a table gives "stack: TypeError: Cannot read properties of null (reading 'id')"

### ISSUE THREAD

**Issue by tjoneslo** [nocodb/nocodb#7313]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Similar to #7039, I'm attempting to duplicate an existing table through the UI. It fails with an short "failed" message and no details. I'm not clear as to what or why it failed. 

The nocodb logs have the following error:

```

╔══════════════════════════════════════════════════════════════════════════════╗
║                                                                              ║
║   ---- !! JOB FAILED !! ----                                                 ║
║   id:1                                                                       ║
║   error:TypeError (Cannot read properties of undefined (reading 'id'))       ║
║                                                                              ║
║   stack: TypeError: Cannot read properties of undefined (reading 'id')       ║
║   at ImportService.importModels (/usr/src/app/docker/main.js:2:1459572)      ║
║   at process.processTicksAndRejections                                       ║
║   (node:internal/process/task_queues:95:5)                                   ║
║   at async DuplicateProcessor.duplicateModel                                 ║
║   (/usr/src/app/docker/main.js:2:1437749)                                    ║
║   at async QueueService.jobWrapper (/usr/src/app/docker/main.js:2:1363866)   ║
║   at async run (/usr/src/app/node_modules/p-queue/dist/index.js:163:29)      
║                                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝
```

### Desired Behavior

The table is duplicated: with and without data, with or without the additional views)

### Project Details

NocoDB as Docker: True
NocoDB Version: 0.203.0
Database used: Postgres 12

**Comment by tjoneslo** [comment]
Possible related problems
#7231 - applies to MariaDB, 
#7199 - Not manually creating a table, but simply duplicate a table
#7039 - Not sure, but similar error message.

**Comment by dstala** [comment]
Worked fine over staging (PG). Need to check in MariaDB

**Comment by o1lab** [comment]
We strongly advise using postgres with NocoDB as we no longer can support all underlying databases as NocoDb's default database.
