### ISSUE TITLE
🐛 Bug: Invalid formula IF ... == TRUE() or FALSE()

### ISSUE THREAD

**Issue by Sunatley** [nocodb/nocodb#7399]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. I created the "Test" field with the bool type
2. Created the "Formula" field with the formula type:
IF({Test} == TRUE(), "Yes", "No")
or
IF({Test} == FALSE(), "No", "Yes")
3. I got an error: Invalid formula

### Desired Behavior

I want to check for True/False and return a specific value

### Project Details

Node: **v18.5.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.203.2**

**Comment by dstala** [comment]
```
error: select CASE 
	WHEN (CASE WHEN "title7" = 1 THEN true ELSE false END ) THEN 'Yes'
	ELSE 'No'
 END as "__dry_run_alias" from "nc_t7gh___Features" - operator does not exist: boolean = integer
    at Parser.parseErrorMessage (/Users/rajuudava/NocoDB/nocohub/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/rajuudava/NocoDB/nocohub/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/rajuudava/NocoDB/nocohub/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocohub/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 202,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No operator matches the given name and argument types. You might need to add explicit type casts.',
  position: '40',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_oper.c',
  line: '647',
  routine: 'op_error'
}
Error: Formula error: select CASE 
	WHEN (CASE WHEN "title7" = 1 THEN true ELSE false END ) THEN 'Yes'
	ELSE 'No'
 END as "__dry_run_alias" from "nc_t7gh___Features" - operator does not exist: boolean = integer
    at formulaQueryBuilderv2 (/Users/rajuudava/NocoDB/nocohub/packages/nocodb/src/db/formulav2/formulaQueryBuilderv2.ts:1179:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ColumnsService.columnAdd (/Users/rajuudava/NocoDB/nocohub/packages/nocodb/src/services/columns.service.ts:1699:11)
    at async ColumnsController.columnAdd (/Users/rajuudava/NocoDB/nocohub/packages/nocodb/src/controllers/columns.controller.ts:37:12)
```

**Comment by dstala** [comment]
Fixed; should be available in next release
