### ISSUE TITLE
🐛 Bug: Failed to duplicate base

### ISSUE THREAD

**Issue by LXj9atnQ** [nocodb/nocodb#7428]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When I'm trying to duplicate base, there is an error:
_Failed to duplicate project_

Error from docker:
- !! JOB FAILED !! ----                                                 
║║   id:1                                                                       
║║   error:TypeError (Cannot read properties of undefined (reading 'id'))       
║║                                                                              
║║   stack: TypeError: Cannot read properties of undefined (reading 'id')       
║║   at ImportService.importModels (/usr/src/app/docker/main.js:2:1465664)      
║║   at process.processTicksAndRejections                                       
║║   (node:internal/process/task_queues:95:5)                                   
║║   at async DuplicateProcessor.duplicateBase                                  
║║   (/usr/src/app/docker/main.js:2:1442249)                                    
║║   at async QueueService.jobWrapper (/usr/src/app/docker/main.js:2:1369528)   
║║   at async run (/usr/src/app/node_modules/p-queue/dist/index.js:163:29)

### Desired Behavior

Create base duplicate

### Project Details

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.204.0**

**Comment by mertmit** [comment]
Hi @LXj9atnQ, can you try to duplicate tables one by one and find which one is failing and share which column types are present within that table?

**Comment by dstala** [comment]
@LXj9atnQ some of table duplication bugs are fixed of late. reopen this thread if you still face this issue.

**Comment by mr-v-v-v** [comment]
Why does this issue still exist?

I can't copy some bases.

And why GPT gave me such hack which helped me:

1) do query in db:
ALTER TABLE nc_col_formula_v2 ALTER COLUMN formula DROP NOT NULL;
2) make copy of base
3) Find problems, do query:

SELECT *
FROM nc_col_formula_v2
WHERE formula IS NULL;

4) remove these records:
DELETE FROM nc_col_formula_v2
WHERE id IN ('<id from query #3>', '<id from query #3'>,...) ;

5) Restore table structure:

ALTER TABLE nc_col_formula_v2 ALTER COLUMN formula SET NOT NULL;

**Comment by DarkPhoenix2704** [comment]
Hi @mr-v-v-v 

Do you have any invalid formula in any of the tables in the base?

**Comment by mr-v-v-v** [comment]
@DarkPhoenix2704 , may be. But how I can find it? I didn't find.  Looks like it was before, but for some reasons this still blocks copying of the database.

And this is not trivial for the user :)

Why does the problem with forumals block copying of the database and does not even give any hints that there are problems in the formula?

**Comment by DarkPhoenix2704** [comment]
Would you be able to share the base, where I can reproduce the issue? I can share my email.

**Comment by dg72dg** [comment]
Hi @dstala ! Seems like I have the same issue when duplicate the database. Error message: Cannot read properties of undefined (reading 'id')
