### ISSUE TITLE
🐛 Bug: Invalid time string

### ISSUE THREAD

**Issue by bestpika** [nocodb/nocodb#7461]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a table.
1. Click to add new row.

### Desired Behavior

I should be able to add new data, but it's showing an error message directly, and I'm helpless.
From the error message, it is apparent that there is a problem with the time string sent by nocodb.

### Project Details

Using the nocodb/nocodb:latest image created a docker instance.
The connected database is SQL Server 2019.

### Attachments

![image](https://github.com/nocodb/nocodb/assets/5698157/d4564628-8c5f-4432-abb1-b87b788b1d22)

Docker log:

```sh
Error: insert into [dbo].[Table-1] ([created_at], [created_by], [updated_at], [updated_by]) output inserted.[id] as [ct4aaww27woie7y] values ('2024-01-19 07:16:49+00:00', 'usimtj4v35oqep03', NULL, NULL) - Conversion failed when converting date and/or time from character string.
    at RequestTokenHandler.onErrorMessage (/usr/src/app/node_modules/tedious/lib/token/handler.js:287:21)
    at Readable.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:18:33)
    at Readable.emit (node:events:517:28)
    at Readable.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:335:12)
    at readableAddChunk (node:internal/streams/readable:308:9)
    at Readable.push (node:internal/streams/readable:245:10)
    at next (node:internal/streams/from:98:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by bestpika** [comment]
I can confirm that this issue is caused by setting `NC_SANITIZE_COLUMN_NAME` to false.

**Comment by bestpika** [comment]
Finally, I have to remove the entire BASE and reconnect to the database before I can input data normally...

**Comment by TommyLeung-gj** [comment]
No,it's because of the suffix in timestamp "+00:00"，but I don't know how to remove it

**Comment by kyletannv** [comment]
I'm getting the same error. Can confirm that if I copy the query into a database editor, it gives me the same issue until I remove the "+00:00" suffix.

**Comment by kyletannv** [comment]
Update: I'm currently working around this issue by using the `nocodb/nocodb:0.202.10` image. Later ones may also work, haven't tried.

**Comment by dstala** [comment]
We have not noticed much traction with usage of MS SQL Server support & hence we decided to narrow down support mainly to MySQL & PG. Please feel free to connect with us to discuss more on your use-case [here](https://cal.com/nocodb).
