### ISSUE TITLE
🐛 Bug: Error when Upgrading to 0.204.0 with Airtable Collaborator Field

### ISSUE THREAD

**Issue by TobiasDax** [nocodb/nocodb#7489]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When i try to update to 0.204.0 the docker container crashes with the following error. This happens regardless if i upgrade from 0.203.0 or 0.203.2, both lower versions work without any error.

The table with the error is one that i automatically imported from Airtable, the `created by` Field is the `Collaborators` Filed from Airtable.

```
(node:11) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
[ncXcdbCreatedAndUpdatedSystemFieldsUpgrader 1706026240073] Upgrading model 'Fehler'(mm1gyxkg54lsun0) from base 'OVS'(pxrot28i14r389y}) failed
[ncXcdbCreatedAndUpdatedSystemFieldsUpgrader 1706026240102] Upgrading model 'Materialsammlung'(mn3un89m6l5z53w) from base 'OVS'(pxrot28i14r389y}) failed
[ncXcdbCreatedAndUpdatedSystemFieldsUpgrader 1706026240104] Upgrading model 'My Decks'(mpwhf2dneb1mlp3) from base 'Magic'(pun220z9pzjpwd1}) failed
[ncXcdbCreatedAndUpdatedSystemFieldsUpgrader 1706026240105] Upgrading model 'Terry Pratchett'(md_7ii7f3r2lk1r4v) from base 'Books'(p_e48yhhk9xe7za9}) failed
[ncXcdbCreatedAndUpdatedSystemFieldsUpgrader 1706026240112] Upgrading model 'Videoproduktion'(m6w1unqyj04gpuw) from base 'OVS'(pxrot28i14r389y}) failed
[ncXcdbCreatedAndUpdatedSystemFieldsUpgrader 1706026240113] Upgrading model 'Craig Alanson'(md_77qm4c4ikzpt2w) from base 'Books'(p_e48yhhk9xe7za9}) failed
[ncXcdbCreatedAndUpdatedSystemFieldsUpgrader 1706026240114] Upgrading model 'Stundenproduktion'(mlfq2jrj1rlmpiq) from base 'OVS'(pxrot28i14r389y}) failed
[ncXcdbCreatedAndUpdatedSystemFieldsUpgrader 1706026240115] Upgrading model 'Warhammer - Faction Lists'(md_1sgi1n5tgy58ql) from base 'Books'(p_e48yhhk9xe7za9}) failed
[Nest] 11  - 01/23/2024, 5:10:40 PM   ERROR [ExceptionHandler] ALTER TABLE `nc_xro8___Fehler`  ADD `created_by` varchar   - SQLITE_ERROR: duplicate column name: created_by
Error: ALTER TABLE `nc_xro8___Fehler`  ADD `created_by` varchar   - SQLITE_ERROR: duplicate column name: created_by
[ncXcdbCreatedAndUpdatedSystemFieldsUpgrader 1706026239602] Skipped deleted base source 'bd8d4uz40yrejah' - undefined
[ncXcdbCreatedAndUpdatedSystemFieldsUpgrader 1706026239608] Upgrading base Musik(p0nkfvame72bppq,brxqyt3d9rxinxa) (5/5)
[ncXcdbCreatedAndUpdatedSystemFieldsUpgrader 1706026239609] Upgraded base 'Musik'(p0nkfvame72bppq,brxqyt3d9rxinxa) (5/5)
[ncXcdbCreatedAndUpdatedSystemFieldsUpgrader 1706026239694] Upgrading base Magic(pun220z9pzjpwd1,bbftztdyvdo5yjk) (4/5)
[ncXcdbCreatedAndUpdatedSystemFieldsUpgrader 1706026239723] Upgrading base Books(p_e48yhhk9xe7za9,ds_xz2aq416mq4doc) (1/5)
[ncXcdbCreatedAndUpdatedSystemFieldsUpgrader 1706026239808] Upgrading base OVS(pxrot28i14r389y,bszo86yjo01inn4) (2/5)
ALTER TABLE `nc_i92h__Warhammer - Faction Lists`  ADD `created_at` datetime  ;ALTER TABLE `nc_i92h__Warhammer - Faction Lists`  ADD `updated_at` datetime  ;ALTER TABLE `nc_i92h__Warhammer - Faction Lists`  ADD `created_by` varchar  ;ALTER TABLE `nc_i92h__Warhammer - Faction Lists`  ADD `updated_by` varchar  ;
ALTER TABLE `nc_o1fh___My Decks`  ADD `created_by` varchar  ;ALTER TABLE `nc_o1fh___My Decks`  ADD `updated_by` varchar  ;
ALTER TABLE `nc_i92h__Terry Pratchett`  ADD `created_by` varchar  ;ALTER TABLE `nc_i92h__Terry Pratchett`  ADD `updated_by` varchar  ;
ALTER TABLE `nc_i92h__Craig Alanson`  ADD `created_by` varchar  ;ALTER TABLE `nc_i92h__Craig Alanson`  ADD `updated_by` varchar  ;
ALTER TABLE `nc_xro8___Stundenproduktion`  ADD `created_at` datetime  ;ALTER TABLE `nc_xro8___Stundenproduktion`  ADD `updated_at` datetime  ;ALTER TABLE `nc_xro8___Stundenproduktion`  ADD `created_by` varchar  ;ALTER TABLE `nc_xro8___Stundenproduktion`  ADD `updated_by` varchar  ;
ALTER TABLE `nc_xro8___Videoproduktion`  ADD `created_at` datetime  ;ALTER TABLE `nc_xro8___Videoproduktion`  ADD `updated_at` datetime  ;ALTER TABLE `nc_xro8___Videoproduktion`  ADD `created_by` varchar  ;ALTER TABLE `nc_xro8___Videoproduktion`  ADD `updated_by` varchar  ;
╔══════════════════════════════════════════════════════════════════════════════╗║                                                                              ║║   EXCEPTION OCCURED!! in SqliteClient @ tableUpdate                          ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   MESSAGE:                                                                   ║║   ALTER TABLE `nc_xro8___Fehler`  ADD `created_by` varchar   -               ║║   SQLITE_ERROR: duplicate column name: created_by                            ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   CODE:                                                                      ║║   SQLITE_ERROR                                                               ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   STACK:                                                                     ║║   Error: ALTER TABLE `nc_xro8___Fehler`  ADD `created_by` varchar   -        ║║   SQLITE_ERROR: duplicate column name: created_by                            ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║                                                                              ║║                                                                              ║╚══════════════════════════════════════════════════════════════════════════════╝
[Error: ALTER TABLE `nc_xro8___Fehler`  ADD `created_by` varchar   - SQLITE_ERROR: duplicate column name: created_by] {
  errno: 1,
  code: 'SQLITE_ERROR'
}
╔══════════════════════════════════════════════════════════════════════════════╗║                                                                              ║║   EXCEPTION OCCURED!! in SqliteClient @ tableUpdate                          ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   MESSAGE:                                                                   ║║   Transaction query already complete, run with DEBUG=knex:tx for more info   ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   CODE:                                                                      ║║   undefined                                                                  ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   STACK:                                                                     ║║   Error: Transaction query already complete, run with DEBUG=knex:tx for      ║║   more info                                                                  ║║   at completedError                                                          ║║   (/usr/src/app/node_modules/knex/lib/execution/transaction.js:396:9)        ║║   at /usr/src/app/node_modules/knex/lib/execution/transaction.js:362:24      ║║   at new Promise (<anonymous>)                                               ║║   at trxClient.query                                                         ║║   (/usr/src/app/node_modules/knex/lib/execution/transaction.js:358:12)       ║║   at Runner.query                                                            ║║   (/usr/src/app/node_modules/knex/lib/execution/runner.js:123:36)            ║║   at ensureConnectionCallback (/usr/src/app/node_modules/knex/lib/executio   ║║   n/internal/ensure-connection-callback.js:13:17)                            ║║   at Runner.ensureConnection                                                 ║║   (/usr/src/app/node_modules/knex/lib/execution/runner.js:300:20)            ║║   at async Runner.run                                                        ║║   (/usr/src/app/node_modules/knex/lib/execution/runner.js:30:19)             ║║   at async SqliteClient.tableUpdate (/usr/src/app/docker/main.js:2:877600)   ║║   at async SqlMgrv2.sqlOpPlus (/usr/src/app/docker/main.js:2:960871)         ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║                                                                              ║║                                                                              ║╚══════════════════════════════════════════════════════════════════════════════╝
Error: Transaction query already complete, run with DEBUG=knex:tx for more info
    at completedError (/usr/src/app/node_modules/knex/lib/execution/transaction.js:396:9)
    at /usr/src/app/node_modules/knex/lib/execution/transaction.js:362:24
    at new Promise (<anonymous>)
    at trxClient.query (/usr/src/app/node_modules/knex/lib/execution/transaction.js:358:12)
    at Runner.query (/usr/src/app/node_modules/knex/lib/execution/runner.js:123:36)
    at ensureConnectionCallback (/usr/src/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/execution/runner.js:300:20)
    at async Runner.run (/usr/src/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async SqliteClient.tableUpdate (/usr/src/app/docker/main.js:2:877600)
    at async SqlMgrv2.sqlOpPlus (/usr/src/app/docker/main.js:2:960871)
┌ Migration from 0111002 to 0111005 failed ────────────────────────────────────┐│                                                                              ││   Error                                                                      ││   -----                                                                      ││   Error: ALTER TABLE `nc_xro8___Fehler`  ADD `created_by` varchar   -        ││   SQLITE_ERROR: duplicate column name: created_by                            ││                                                                              ││                                                                              ││   Please raise an issue in our github by using following link :              ││   https://github.com/nocodb/nocodb/issues/new?labels=Type%3A%20Bug&templat   ││   e=bug_report.md                                                            ││                                                                              ││   Or contact us in our Discord community by following link :                 ││   https://discord.gg/5RgZmkW ( message @o1lab, @pranavxc or @wingkwong )     ││                                                                              │└──────────────────────────────────────────────────────────────────────────────┘
[Nest] 11  - 01/23/2024, 5:10:40 PM     LOG [NestFactory] Starting Nest application...
[Nest] 11  - 01/23/2024, 5:10:40 PM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +1ms
[Nest] 11  - 01/23/2024, 5:10:40 PM     LOG [InstanceLoader] PassportModule dependencies initialized +0ms
[Nest] 11  - 01/23/2024, 5:10:40 PM     LOG [InstanceLoader] MulterModule dependencies initialized +1ms
[Nest] 11  - 01/23/2024, 5:10:40 PM     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
[Nest] 11  - 01/23/2024, 5:10:40 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 11  - 01/23/2024, 5:10:40 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 11  - 01/23/2024, 5:10:40 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 11  - 01/23/2024, 5:10:40 PM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +1ms
```

Also, if i delete the column (i dont need it since the whole table was only to test airtable import) the error goes away.

So i guess steps to reproduce are
1. Create a Airtable databas with a collobarotor field
2. Import into noco 0.203.0
3. update to 0.204.0

### Desired Behavior

Would be great if the Airtable Collaborators field was automatically mapped to the new Users field, but since this has been imported for months it should just continue to work as a text field

### Project Details

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.204.0**

**Comment by o1lab** [comment]
Please do not use sqlite3 for production. Default to postgres.
