### ISSUE TITLE
🐛 Bug: Cmd+J is not working in oss

### ISSUE THREAD

**Issue by rameshmane7218** [nocodb/nocodb#7563]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Script path is not accessible

```js
GET http://localhost:8888/js/typesense-docsearch.js net::ERR_ABORTED 404 (Not Found)

entry.e4ac8d40.js:1 ReferenceError: docsearch is not defined
    at entry.e4ac8d40.js:206:134115
    at entry.e4ac8d40.js:1:34096
    at Da (entry.e4ac8d40.js:1:14878)
    at or (entry.e4ac8d40.js:1:14957)
    at Ou.t.__weh.t.__weh (entry.e4ac8d40.js:1:33976)
    at Fc (entry.e4ac8d40.js:1:16305)
    at d3 (entry.e4ac8d40.js:1:16612)
```

### Desired Behavior

should work properly 

### Project Details

-

**Comment by rameshmane7218** [comment]
Merged with PR #7564
