### ISSUE TITLE
🐛 Bug: TypeError: Cannot read properties of undefined (reading 'getChildColumn'

### ISSUE THREAD

**Issue by TheRushingWookie** [nocodb/nocodb#7615]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

* Imported a very large DB from Airtable with lots of one to many relationships
* Clicking on any of the foreign key tables leads to the error
```
[Nest] 27291  - 02/13/2024, 5:53:22 AM   ERROR [DatasService] TypeError: Cannot read properties of undefined (reading 'getChildColumn')
[Nest] 27291  - 02/13/2024, 5:53:22 AM   ERROR [GlobalExceptionFilter] Please check server log for more details
Error: Please check server log for more details
    at NcError.internalServerError (/snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1006328)
    at /snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1720636
    at async Promise.all (index 1)
    at async DatasService.getDataList (/snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1720342)
    at async DatasService.dataList (/snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:1718188)
    at async DataAliasController.dataList (/snapshot/pkg-executable/node_modules/nocodb/dist/bundle.js:2:366748)
```

I'll try to create a better repro

### Desired Behavior

* The table should load and show the data

### Project Details

Node: **v18.5.0**
Arch: **arm64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.204.0**

### Attachments

<img width="360" alt="image" src="https://github.com/nocodb/nocodb/assets/3181551/0eda560a-5073-414e-aeb9-24e76626fbf7">

**Comment by TheRushingWookie** [comment]
I've added some debug logging and found its because of some RollupColumns have null fk related fields.
The error is thrown after trying to handle this column object:
```
column Column {
  id: 'cl9ulg0geqce12f',
  source_id: 'b5oe4w5x6qnfqkg',
  base_id: 'pzl1z2u06qvb1th',
  fk_model_id: 'm3yi8lkipk4nrub',
  title: 'XXXXX',
  column_name: 'XXXX',
  uidt: 'Rollup',
  dt: 'varchar',
  np: null,
  ns: null,
  clen: null,
  cop: '2',
  pk: 0,
  pv: null,
  rqd: 0,
  un: null,
  ct: null,
  ai: 0,
  unique: null,
  cdf: null,
  cc: null,
  csn: null,
  dtx: 'string',
  dtxp: '',
  dtxs: '',
  au: 0,
  validate: null,
  virtual: null,
  deleted: null,
  system: 0,
  order: 3,
  created_at: '2024-02-13 02:54:43+00:00',
  updated_at: '2024-02-13 02:54:43+00:00',
  meta: null,
  description: null,
  colOptions: RollupColumn {
    id: 'rlewhk540wp2i33i',
    fk_column_id: 'cl9ulg0geqce12f',
    fk_relation_column_id: null,
    fk_rollup_column_id: null,
    rollup_function: null,
    deleted: null,
    created_at: '2024-02-13 02:54:43+00:00',
    updated_at: '2024-02-13 02:54:43+00:00'
  }
}
```

**Comment by TheRushingWookie** [comment]
I think it might be related to https://github.com/nocodb/nocodb/commit/a6d746556ea324fd03acc2e173b73f8b3fdb2176#diff-12cd31b6ecb5583139cbce68cc55ec9d5eef9dcf55868b913523b45b829dbd35R1180-R1181

If ncRelationColumn is undefined, ncRollupColumnId will probably be wrong

**Comment by TheRushingWookie** [comment]
Reimporting did not cause the bug to reappear so maybe this was a race condition

**Comment by ktx-kirtan** [comment]
I am facing the same issue

**Comment by dstala** [comment]
On this- we tried and were unable to reproduce this issue locally. It would help if you can please share an airtable base in which this issue is reproducible.
