### ISSUE TITLE
📚 Doc: Incomplete documentation for `api/v1/db/meta/projects/{baseId}/bases/`+`api/v1/db/meta/projects/`

### ISSUE THREAD

**Issue by erem2k** [nocodb/nocodb#7957]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Current publicly available documentation for Source/Base creation REST endpoints is incomplete - it's impossible to POST a base with source, or just a source with example request bodies provided.

Specifically, despite server returning 200 code request fails to get processed internally with:
```
[Nest] 8604  - 2024-03-24 19:40:20   ERROR [JobsEventService] ---- !! JOB FAILED !! ----
id:3
error:Error (Invalid request body)

stack: Error: Invalid request body
    at NcError.ajvValidationError (C:\snapshot\pkg-executable\node_modules\nocodb\dist\bundle.js:2:1025468)
    at C:\snapshot\pkg-executable\node_modules\nocodb\dist\bundle.js:2:1013031
    at SourcesService.baseCreate (C:\snapshot\pkg-executable\node_modules\nocodb\dist\bundle.js:2:1866648)
    at SourceCreateProcessor.job (C:\snapshot\pkg-executable\node_modules\nocodb\dist\bundle.js:2:1544363)
    at QueueService.jobWrapper (C:\snapshot\pkg-executable\node_modules\nocodb\dist\bundle.js:2:1415251)
    at C:\snapshot\pkg-executable\node_modules\nocodb\dist\bundle.js:2:1415735
    at run (C:\snapshot\pkg-executable\node_modules\p-queue\dist\index.js:157:104)
    at PQueue._tryToStartAnother (C:\snapshot\pkg-executable\node_modules\p-queue\dist\index.js:105:17)
    at C:\snapshot\pkg-executable\node_modules\p-queue\dist\index.js:171:18
    at new Promise (<anonymous>)
```

This seems to be caused primarily by missing `config` key in the example, which is not documented anywhere except the source code.

### Desired Behavior

* Source/Base endpoint documentation should include more detailed description of `config` key for supported connection types.
* Request body should be checked before response is dispatched.

### Project Details

Node: **v18.5.0**
Arch: **x64**
Platform: **win32**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.204.9**

**Comment by o1lab** [comment]
Please use v3 apis.
