### ISSUE TITLE
🔦 Feature: Allow rollup also for linked formula fields

### ISSUE THREAD

**Issue by Jean28518** [nocodb/nocodb#7975]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

- Assume we have a warehouse system with two tables: articles and warehouse movement
- The warehouse table has a one to many link to warehouse movements
- The warehouse movements table has a checkmark: (Fulfilled)
- I created a formula in warehouse movement which wether shows the amount of the article movement or 0  (current warehouse effect)
- I want to calculate the current amount in the warehouse of an article (but only the fulfilled warehouse movements). (Rollup in articles, Link to that funktion warehouse effect)

### Suggested Solution

There are two solutions to address this problem:
- Allow the rollup feature also for linked function fields
- Or maybe an even nicer feature would be allow setting filters to a rollup field, which checks e.g. if the linked field is true.

### Additional Context

With such a feature nocodb tables could become so much more functionality. In my opinion the current implementation of the rollup field is a good start but it could have much more potential :)

**Comment by EngiBenchi** [comment]
Yes this one is high on my list as well. I even made a small example for it. 
imagine a list with people and there day of birth than you can calculate there age:
![People_birthdate](https://github.com/nocodb/nocodb/assets/20003780/05bb2205-8e20-4fca-a126-53c87aa0a751)
And you want to have some demographics:
![Demographics](https://github.com/nocodb/nocodb/assets/20003780/b6d4e574-bf3c-4140-88f4-f42660372fce)
As for now you can't use the calculated value in the rollup field

**Comment by 360Creators** [comment]
Me too - bump

**Comment by levinside** [comment]
up

**Comment by dstala** [comment]
Use of formula is now supported in rollup fields. Please let us know if you see any issues with this.

**Comment by levinside** [comment]
@dstala Should I wait till next Release to see this update on my self-hosted instance?

**Comment by dstala** [comment]
here https://github.com/nocodb/nocodb/releases/tag/0.260.4

**Comment by 360Creators** [comment]
@dstala I have a formula field that is a currency called `Line Item total`.
When I go to my `Invoices` table to rollup those Line Items, I'm happy to see that the `Formula` can now be rolled up. However, I only see `Count` as an aggregate function, while I need to `Sum`.

Also, I noticed that if I do the Count, it throws an error to check server logs. I think it's because some records in the invoices are not linked yet to the line items.

```
2025-02-06T11:54:33.673362293Z [Nest] 8  - 02/06/2025, 11:54:33 AM   ERROR ;5;3m[DatasService] Error: select * from (select (select count(`__nc_rollup`.`id`) from `nc_utq4___Line Items` as `__nc_rollup` inner join `nc_utq4___nc_m2m_Line Items_Invoices` on `nc_utq4___nc_m2m_Line Items_Invoices`.`nc_utq4___Line Items_id` = `__nc_rollup`.`id` where `nc_utq4___nc_m2m_Line Items_Invoices`.`nc_utq4___Invoices_id` = `nc_utq4___Invoices`.`id`) as `cszhbkb4rvjxrhz`, (select count((`Quantity` * (select sum(`__nc_formula0`.`Cost_of_Service`) from `nc_utq4___Services` as `__nc_formula0` inner join `nc_utq4___nc_m2m_Line Items_Services` as `__nc1` on `__nc1`.`nc_utq4___Services_id` = `__nc_formula0`.`id` where `__nc1`.`nc_utq4___Line Items_id` = `nc_utq4___Line Items`.`id`) )) from `nc_utq4___Line Items` as `__nc_rollup` inner join `nc_utq4___nc_m2m_Line Items_Invoices` on `nc_utq4___nc_m2m_Line Items_Invoices`.`nc_utq4___Line Items_id` = `__nc_rollup`.`id` where `nc_utq4___nc_m2m_Line Items_Invoices`.`nc_utq4___Invoices_id` = `nc_utq4___Invoices`.`id`) as `ctocdsycuebzsq0`, `nc_utq4___Invoices`.`id` as `c1x1yu2pybts0bn`, `nc_utq4___Invoices`.`Invoice_ID` as `cu99jr7bi0c1t2n` from `nc_utq4___Invoices` order by `nc_order` asc limit 100) __nc_alias - SQLITE_ERROR: no such column: nc_utq4___Line Items.id
2025-02-06T11:54:33.673667684Z [Nest] 8  - 02/06/2025, 11:54:33 AM   ERROR ;5;3m[GlobalExceptionFilter] Please check server log for more details
2025-02-06T11:54:33.673690373Z Error: Please check server log for more details
2025-02-06T11:54:33.673699533Z     at NcError.internalServerError (/usr/src/app/docker/main.js:1553:41690)
2025-02-06T11:54:33.673708113Z     at /usr/src/app/docker/main.js:2547:58652
2025-02-06T11:54:33.673716152Z     at async Promise.all (index 1)
2025-02-06T11:54:33.673724372Z     at async DatasService.getDataList (/usr/src/app/docker/main.js:2547:58259)
2025-02-06T11:54:33.673732402Z     at async DatasService.dataList (/usr/src/app/docker/main.js:2547:55796)
2025-02-06T11:54:33.673740642Z     at async DataAliasController.dataList (/usr/src/app/docker/main.js:184:58108)
```
