### ISSUE TITLE
🐛 Bug: Barcode is blank returns error

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#8020]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

```
Warning : `mailSend` failed, Please configure emailClient configuration.
[11:20:25.886] ERROR (262): error: select "__nc_root"."id" as "cfqfnyl420v6gxg", "__nc_root"."title" as "cry00fc7e5s1ihp", "__nc_root"."Budget" as "c8l8pj22zwxgi5i", "__nc_root"."Producer" as "c3zkwa1x4qxwj8i", "__nc_root"."title14" as "cb8x3p9mnqd6v01", "__nc_root"."title15" as "cchfgwzl9mior5y", "__nc_root"."title" as "cjvwmij0q5e1e80", "__nc_1"."c36qtrwwau0ggl3", "__nc_3"."cl2w7y35fr2r06k", (select count(distinct "__nc_rollup"."Age") from "nc_fy2p___Actors" as "__nc_rollup" inner join "nc_fy2p___nc_m2m_5fo5j0g674" on "nc_fy2p___nc_m2m_5fo5j0g674"."table2_id" = "__nc_rollup"."id" where "nc_fy2p___nc_m2m_5fo5j0g674"."table1_id" = "__nc_root"."id") as "cb34f5pw98ybvnf", (select count("__nc_rollup"."id") from "nc_fy2p___Actors" as "__nc_rollup" inner join "nc_fy2p___nc_m2m_5fo5j0g674" on "nc_fy2p___nc_m2m_5fo5j0g674"."table2_id" = "__nc_rollup"."id" where "nc_fy2p___nc_m2m_5fo5j0g674"."table1_id" = "__nc_root"."id") as "clzn4dffno10xmp", (select count("id") as "count" from "nc_fy2p___Films" where (((("title16" is null or "title16" = ''))))) as "__nc_count" from (select * from "nc_fy2p___Films" where (((("title16" is null or "title16" = '')))) order by "id" asc limit 25 offset 0) as "__nc_root" LEFT OUTER JOIN LATERAL (select coalesce(json_agg("__nc_0"."c5m6d1629qy7blh"),'[]'::json) as "c36qtrwwau0ggl3" from (select "__nc_4"."title" as "c5m6d1629qy7blh" from (select * from "nc_fy2p___nc_m2m_5fo5j0g674" as "__nc_5" where "__nc_5"."table1_id" = "__nc_root"."id") as "__nc_6" left join "nc_fy2p___Actors" as "__nc_4" on "__nc_4"."id" = "__nc_6"."table2_id") as "__nc_0") as "__nc_1" ON true LEFT OUTER JOIN LATERAL (select coalesce(json_agg("__nc_2"."clg3mhopn4xrjlg"),'[]'::json) as "cl2w7y35fr2r06k" from (select "__nc_7"."Age" as "clg3mhopn4xrjlg" from (select * from "nc_fy2p___nc_m2m_5fo5j0g674" as "__nc_8" where "__nc_8"."table1_id" = "__nc_root"."id") as "__nc_9" left join "nc_fy2p___Actors" as "__nc_7" on "__nc_7"."id" = "__nc_9"."table2_id") as "__nc_2") as "__nc_3" ON true order by "__nc_root"."id" asc - column "title16" does not exist
    at Parser.parseErrorMessage (/Users/rajuudava/NocoDB/nocohub/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/rajuudava/NocoDB/nocohub/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/rajuudava/NocoDB/nocohub/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocohub/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:517:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Socket.Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    req: {
      "id": "6a574719-4665-4ce2-9394-b53305393183",
      "method": "GET",
      "url": "/api/v1/db/data/noco/pmknhgt01j9691q/mfzo00t7mzs109g/views/vwsvh48h1fmgwb7r?offset=0&limit=25",
      "clientId": "018b03a5-c462-7cfa-b808-272f2678fd34"
    }
    context: "GlobalExceptionFilter"
    workspaceId: "w6qroduh"
    projectId: "pmknhgt01j9691q"
    ip: "::1"
    id: "usk9p2vem1fsgx2f"
    path: "/api/v1/db/data/noco/pmknhgt01j9691q/mfzo00t7mzs109g/views/vwsvh48h1fmgwb7r"
    clientId: "018b03a5-c462-7cfa-b808-272f2678fd34"

```

### Desired Behavior

x

### Project Details

0.204.9

**Comment by rohittp0** [comment]
The grouping seems to be working in the latest develop branch

### Using Date Time Field

<img width="1512" alt="image" src="https://github.com/nocodb/nocodb/assets/45072928/2c569707-1339-40f9-9d19-3558ff6d2423">

### Using Date Field

<img width="1512" alt="image" src="https://github.com/nocodb/nocodb/assets/45072928/dcaeaf94-82d8-41a8-8808-7425a1d452a7">

### Using Time Field

<img width="1512" alt="image" src="https://github.com/nocodb/nocodb/assets/45072928/89e2f4dc-3e67-4ad2-8159-060c2bc7e343">
