### ISSUE TITLE
columns with a dot in the name cause an error

### ISSUE THREAD

**Issue by marco-santulli** [nocodb/nocodb#819]
if a column name contains a dot, you get an error and the table doesn't get opened:

error: select "newtable"."account" as "Account", "newtable"."Customer Name" as "Customer Name", "newtable"."Tax number1 md" as "Tax number1 md", "newtable"."Tax number2 md" as "Tax number2 md", "newtable"."Assignment" as "Assignment", "newtable"."Document Number" as "Document Number", "newtable"."Document Type" as "Document Type", "newtable"."Posting Key" as "Posting Key", "newtable"."Document Date" as "Document Date", "newtable"."Net Due Date" as "Net Due Date", "newtable"."Payment terms" as "Payment terms", "newtable"."Payment Method" as "Payment Method", "newtable"."Document Currency" as "Document Currency", "newtable"._**"Amount in Doc"."Curr"."" as "Amount in Doc. Curr."**_, "newtable"."TE- Empl" as "TE- Empl", "newtable"."Sales Manager" as "Sales Manager", "newtable"."department" as "Department", "newtable"."id" as "Id" from "newtable" order by "Id" asc limit $1 - zero-length delimited identifier at or near """"
    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:506:15)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 112,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '647',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,

**Comment by dstala** [comment]
@marco-santulli please reopen this issue if it still persists on your end

**Comment by o1lab** [comment]
Provide the base info from three dot base menu.
