### ISSUE TITLE
🐛 Bug: Unable to create data with json array by using openapi through swagger

### ISSUE THREAD

**Issue by Bleoo** [nocodb/nocodb#8226]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I created a json field, and I wanna create a row through swagger openapi. I found that the json array could not be submitted successfully, and there was an error log.

<img width="560" alt="image" src="https://github.com/nocodb/nocodb/assets/11569795/000afd5d-b20f-4438-a31b-fbdd6466d2c1">

<img width="694" alt="image" src="https://github.com/nocodb/nocodb/assets/11569795/156f7f1a-264e-42c6-8f28-30099d19b2be">

<img width="1542" alt="image" src="https://github.com/nocodb/nocodb/assets/11569795/8671467a-7e3e-4cb0-8279-ea5db185812b">

```
[Nest] 11  - 04/09/2024, 4:00:29 AM   ERROR [GlobalExceptionFilter] insert into "nc_0_u8___Table-1" ("content", "created_at", "created_by", "title", "updated_at", "updated_by") values ($1, $2, $3, $4, $5, $6) returning "id" as "Id" - invalid input syntax for type json
error: insert into "nc_0_u8___Table-1" ("content", "created_at", "created_by", "title", "updated_at", "updated_by") values ($1, $2, $3, $4, $5, $6) returning "id" as "Id" - invalid input syntax for type json
    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Desired Behavior

json array can be submited

### Project Details

Node: **v20.11.1**
Arch: **arm64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.205.1**

**Comment by pranavxc** [comment]
Fixed in #8664
