### ISSUE TITLE
🐛 Bug: RedisCacheMgr.set Cannot convert object to primitive value

### ISSUE THREAD

**Issue by victorserbu2709** [nocodb/nocodb#8259]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

with the release 0.205.1 I start application with NC_SMTP_* environment variables.
but it doesn't start

```
 [Nest] 6  - 04/12/2024, 9:51:10 AM   ERROR [ExceptionHandler] Cannot convert object to primitive value
 TypeError: Cannot convert object to primitive value
     at RedisCacheMgr.set (/usr/src/app/docker/index.js:2:271859)
     at NocoCache.set (/usr/src/app/docker/index.js:2:279160)
     at Plugin.get (/usr/src/app/docker/index.js:2:1342049)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async NcPluginMgrv2.initPluginsFromEnv (/usr/src/app/docker/index.js:2:1008826)
     at async NcPluginMgrv2.init (/usr/src/app/docker/index.js:2:1008220)
     at async InstanceWrapper.useFactory [as metatype] (/usr/src/app/docker/index.js:2:1412768)
     at async Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:369:37)
     at async callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:65:34)
     at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:144:24)

```

### Desired Behavior

start
### Project Details

release 0.205.1

**Comment by pranavxc** [comment]
Discord thread - https://discord.com/channels/661905455894888490/1227781111258677257

**Comment by pranavxc** [comment]
@victorserbu2709 Are you facing this issue on every boot with the latest version of docker image ?

**Comment by iamkarshe** [comment]
I got this issue when I initialized project with `npx` command + chose **A Node.js project.** 

I got no issue while I used Docker command.

`docker run -d --name nocodb -p 9002:8080 nocodb/nocodb:latest`

**Comment by victorserbu2709** [comment]
Hello @pranavxc, i was creating docker images using build-local-docker-image.sh.
I applied https://github.com/nocodb/nocodb/pull/8260 and it works now. thanks
