### ISSUE TITLE
Follow Production setup got an error: Malformed UTF-8 data

### ISSUE THREAD

**Issue by 109km** [nocodb/nocodb#829]
I'm following the production setup:

```
docker run -d -p 8080:8080 \
    -e NC_DB="mysql2://host.docker.internal:3306?u=root&p=password&d=d1" \
    -e NC_AUTH_JWT_SECRET="569a1821-0a93-45e8-87ab-eb857f20a010" \
    nocodb/nocodb:latest
```
Got this error from docker:
```
Error: Malformed UTF-8 data
    at Object.stringify (/usr/src/app/node_modules/crypto-js/core.js:523:24)
    at WordArray.init.toString (/usr/src/app/node_modules/crypto-js/core.js:278:38)
    at /usr/src/app/docker/main.js:2:324962
    at Array.map (<anonymous>)
    at n.projectList (/usr/src/app/docker/main.js:2:324771)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async P.initProjectBuilders (/usr/src/app/docker/main.js:2:35140)
    at async P.init (/usr/src/app/docker/main.js:2:32145)
    at async /usr/src/app/docker/main.js:2:328718
```

Versions I'm using:
```
Docker version : Docker version 20.10.10
OS: macOS Monterey
Mysql version: 8.0
```

And I also tried
```
npx create-nocodb-app
```
Everything works well.

**Comment by pranavxc** [comment]
You need to use the `NC_AUTH_JWT_SECRET` in both instances since we are encrypting DB config with JWT secret.

**Comment by o1lab** [comment]
```NC_DB="mysql2://host.docker.internal:3306?u=root&p=password&d=d1"```

This has to be connection string to your own database.

Feel free to reopen if you are facing issues still.

**Comment by nadeemEp** [comment]
Hi everyone, i am facing the same error in my local when i try to build a connection with MySql. some times it occurs either its working fine.
