### ISSUE TITLE
🐛 Bug: Installation using windows executable and postgres-db does not work

### ISSUE THREAD

**Issue by jon-m-l** [nocodb/nocodb#8350]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Download Windows execcutable
2. Create postgres database, make "user" to the owner of the database, check connection via "user"
3. Open cmd
4. Set DATABASE_URL="jdbc:postgresql://host:port/db?user=user&password=pw"
5. Run nocodb-exe from cmd

### Desired Behavior

NocoDB should set up using the specified postgres-db.

### Project Details

Node: **v18.5.0**
Arch: **x64**
Platform: **win32**
Docker: **false**
Postgres: 15/16
PackageVersion: **0.205.1**

### Attachments

[Nest] 3364  - 2024-04-26 11:15:34   ERROR [ExceptionHandler] Error: Database not supported
Error: Error: Database not supported
    at NcConfig.create (C:\snapshot\pkg-executable\node_modules\nocodb\dist\bundle.js:2:1970931)
    at async InstanceWrapper.useFactory [as metatype] (C:\snapshot\pkg-executable\node_modules\nocodb\dist\bundle.js:2:1412239)
    at async Injector.instantiateClass (C:\snapshot\pkg-executable\node_modules\@nestjs\core\injector\injector.js:369:37)
    at async callback (C:\snapshot\pkg-executable\node_modules\@nestjs\core\injector\injector.js:65:34)
    at async Injector.resolveConstructorParams (C:\snapshot\pkg-executable\node_modules\@nestjs\core\injector\injector.js:144:24)
    at async Injector.loadInstance (C:\snapshot\pkg-executable\node_modules\@nestjs\core\injector\injector.js:70:13)
    at async Injector.loadProvider (C:\snapshot\pkg-executable\node_modules\@nestjs\core\injector\injector.js:97:9)
    at async C:\snapshot\pkg-executable\node_modules\@nestjs\core\injector\instance-loader.js:56:13
    at async Promise.all (index 3)
    at async InstanceLoader.createInstancesOfProviders (C:\snapshot\pkg-executable\node_modules\@nestjs\core\injector\instance-loader.js:55:9)

**Comment by sanwacompany** [comment]
I have the same issue here

**Comment by armgong** [comment]
@jon-m-l  @sanwacompany 
create .env file (in same dir of  nocodb.exe ) ,  put this line in it , problem slove .
NC_DB=pg://127.0.0.1:5432?u=postgres&p=postgres&d=nocodb

**Comment by sanwacompany** [comment]
> @jon-m-l @sanwacompany create .env file (in same dir of nocodb.exe ) , put this line in it , problem slove . NC_DB=pg://127.0.0.1:5432?u=postgres&p=postgres&d=nocodb

Thank you. Previously, I tried using the PostgreSQL from another project for NocoDB, but I couldn't get it to work, so I encountered this error. Now I've given up on that approach and set up a dedicated service for NocoDB in the compose file, which resolved the issue.
