### ISSUE TITLE
[Feature] Add comments to table columns

### ISSUE THREAD

**Issue by TacEtarip** [nocodb/nocodb#846]
Right now I created in the front-end an extra input for the comment but in the back-end I can not find how to modify the ALTER TABLE SQL command to inclute this comment. It seems to use an external library.

**Need for this feature**
For data base documentation.

** Extra Info

I did futher research and it seems that in a library called nc-help the sql statement is created for tableUpdate. In that library seems to have an option to pass a comment, how do I give it to it?.

When I pass a null to `sqlClient[op](null);` I get this.

TypeError: Cannot read property 'tn' of null at _0x453165.tableUpdate (/tmp/workspace/nocodb/packages/nocodb/node_modules/nc-help/dist/main/main.js:1:262211) at SqlMgr.sqlOpPlus (/tmp/workspace/nocodb/packages/nocodb/src/lib/sqlMgr/SqlMgr.ts:781:55) at SqlMgr.handleRequest (/tmp/workspace/nocodb/packages/nocodb/src/lib/sqlMgr/SqlMgr.ts:1253:20) at /tmp/workspace/nocodb/packages/nocodb/src/lib/noco/meta/NcMetaMgr.ts:236:22

**Comment by sudoexec** [comment]
As for now, how can I delete a comment? Can't found any buttons for doing that.

**Comment by salim-b** [comment]
> As for now, how can I delete a comment? Can't found any buttons for doing that.

I think comment deletion is not implemented yet, see https://github.com/nocodb/nocodb/issues/7600.

**Comment by dstala** [comment]
Description is now supported for Table, Fields & Views. I believe that suffice this use case. Please reopen if you think otherwise.
