### ISSUE TITLE
🐛 Bug: error when trying to open data source tab

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#8477]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

```
message: Cannot read properties of undefined (reading 'value')

TypeError: Cannot read properties of undefined (reading 'value')
    at onCreateBaseClick (http://localhost:3000/_nuxt/components/project/AllTables.vue:87:36)
    at callWithErrorHandling (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-NX2X6RUO.js?v=c9e56c96:184:18)
    at callWithAsyncErrorHandling (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-NX2X6RUO.js?v=c9e56c96:192:17)
    at HTMLDivElement.invoker (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-4SDL7GPP.js?v=c9e56c96:818:5)
```

### Desired Behavior

-

### Project Details

Node: **v18.19.1**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.205.0**

**Comment by dstala** [comment]
In PG

```
message: Cannot read properties of undefined (reading 'value')

TypeError: Cannot read properties of undefined (reading 'value')
    at watch.immediate (http://localhost:3000/_nuxt/components/dashboard/settings/DataSources.vue:212:42)
    at callWithErrorHandling (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-NX2X6RUO.js?v=c9e56c96:184:18)
    at callWithAsyncErrorHandling (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-NX2X6RUO.js?v=c9e56c96:192:17)
    at job (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-NX2X6RUO.js?v=c9e56c96:1708:9)
    at flushPreFlushCbs (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-NX2X6RUO.js?v=c9e56c96:327:7)
    at updateComponentPreRender (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-NX2X6RUO.js?v=c9e56c96:5114:5)
    at ReactiveEffect.componentUpdateFn [as fn] (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-NX2X6RUO.js?v=c9e56c96:5032:11)
    at ReactiveEffect.run (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-TUZK3G5J.js?v=c9e56c96:1334:23)
    at instance.update (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-NX2X6RUO.js?v=c9e56c96:5096:52)
    at updateComponent (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-NX2X6RUO.js?v=c9e56c96:4923:18)
```
