### ISSUE TITLE
🐛 Bug: lookup columns is missing after source table copied

### ISSUE THREAD

**Issue by lorrod** [nocodb/nocodb#8530]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Create table with linked columns, create lookup columns, rename linked column, then create a clone of source base.

### Desired Behavior

Copied table has wrong name of linked column ‘{LOOKUP_TABLE_NAME}s’ and missing linked column.

### Project Details

Project Details
Node: v20.12.1
Arch: x64
Platform: linux
Docker: true
RootDB: pg
PackageVersion: 0.207.2
Test email from plugin page is working: yes

**Comment by ivantey** [comment]
Hi there,

Good day! I'm facing a similar issue as described in this ticket (#8530) on my project.

Rolling back to a previous version would be quite difficult for me. Is it possible to fix this issue?

Thanks a lot!

**Comment by dstala** [comment]
@ivantey @lorrod I was able to reproduce this issue for self-links (link relation to same table) -- and issue wasn't seen when connecting to other tables. could you please confirm if your scenario is same?

**Comment by dstala** [comment]
@mertmit error noticed is 
```
[Nest] 59639  - 05/20/2024, 12:14:55 PM   ERROR [JobsEventService] ---- !! JOB FAILED !! ----
id:7
error:Error (Lookup column not found in related table)

stack: Error: Lookup column not found in related table
    at validateLookupPayload (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/helpers/columnHelpers.ts:304:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ColumnsService.columnAdd (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/services/columns.service.ts:1545:11)
    at async ImportService.importModels (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/modules/jobs/jobs/export-import/import.service.ts:885:32)
    at async DuplicateProcessor.duplicateModel (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/modules/jobs/jobs/export-import/duplicate.processor.ts:182:19)
    at async QueueService.jobWrapper (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/modules/jobs/fallback/fallback-queue.service.ts:96:22)
    at async run (/Users/rajuudava/NocoDB/nocodb/node_modules/.pnpm/p-queue@6.6.2/node_modules/p-queue/dist/index.js:163:29)

```
