### ISSUE TITLE
🐛 Bug: Cannot connect to Google Cloud Storage

### ISSUE THREAD

**Issue by despens** [nocodb/nocodb#8534]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create Bucket on Google Cloud Storage, such as 'my_bucket'
2. In the bucket's Permissions tab, create service user with permissions to read and write to this bucket (role 'Legacy Bucket Owner'). The service user's email will be something like <name_you_choose>@<project_id>.iam.gserviceaccount.com 
3. In IAM → Service accounts, export the service user's key. (As JSON and PK12 key file.)
4. Paste in nocodb UI for Google Cloud Storage:
    - Bucket Name: my_bucket
    - Client Email: <name_you_choose>@<project_id>.iam.gserviceaccount.com
    - Project ID: <project_id>
    - Private Key: either
        - decrypted PK12 key file, or
        - complete JSON keyfile

nocodb will always respond with an error on the UI level:

> error:1E08010C:DECODER routines::unsupported

<details>
<summary>Docker log</summary>

```
nocodb-1  | [Nest] 10  - 05/20/2024, 2:13:51 PM   ERROR [MissingDBError] Error: error:1E08010C:DECODER routines::unsupported
nocodb-1  | [Nest] 10  - 05/20/2024, 2:13:51 PM   ERROR [GlobalExceptionFilter] error:1E08010C:DECODER routines::unsupported
nocodb-1  | Error: error:1E08010C:DECODER routines::unsupported
nocodb-1  |     at Sign.sign (node:internal/crypto/sig:128:29)
nocodb-1  |     at Object.sign (/usr/src/app/node_modules/jwa/index.js:152:45)
nocodb-1  |     at Object.jwsSign [as sign] (/usr/src/app/node_modules/jws/lib/sign-stream.js:32:24)
nocodb-1  |     at GoogleToken._GoogleToken_requestToken (/usr/src/app/node_modules/gtoken/build/src/index.js:235:27)
nocodb-1  |     at GoogleToken._GoogleToken_getTokenAsyncInner (/usr/src/app/node_modules/gtoken/build/src/index.js:180:97)
nocodb-1  |     at GoogleToken._GoogleToken_getTokenAsync (/usr/src/app/node_modules/gtoken/build/src/index.js:160:173)
nocodb-1  |     at GoogleToken.getToken (/usr/src/app/node_modules/gtoken/build/src/index.js:110:102)
nocodb-1  |     at JWT.refreshTokenNoCache (/usr/src/app/node_modules/google-auth-library/build/src/auth/jwtclient.js:173:36)
nocodb-1  |     at JWT.refreshToken (/usr/src/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:166:24)
nocodb-1  |     at JWT.getRequestMetadataAsync (/usr/src/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:312:28)
```

</details>

### Desired Behavior

The exported key should be accepted and a connection to the bucket established.

Alternatively, provide detailed instructions on what data is expected in the "Configure Google Cloud Storage" dialog.

### Project Details

```
NocoDB used as docker : true
NocoDB version : 207.1
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project
Database on which spreadsheet is created : pg
OS on which NocoDB is running : Alpine Linux (docker)
Node.js version if running as node : 
Database version : Postgres 15
```

**Comment by dstala** [comment]
@pranavxc see if we can get any clue from the logs pasted here for the issue.

**Comment by despens** [comment]
@pranavxc Let me know if you need any other type of log or information, I'm happy to provide.

**Comment by despens** [comment]
Can confirm this still applies to release 0.250.2

**Comment by despens** [comment]
I have tried the following variations of making the Google service account's private key available to nocodb:

- in pk12 format with all possible combinations of
  - with original line breaks
  - as a single line
  - including `-----BEGIN PRIVATE KEY-----` and `-----END PRIVATE KEY-----`
- in JSON format
  - as downloaded from cloud console, including line breaks
  - with line breaks removed
  - with original escaped line breaks `\n` in under the key `private_key`
  - with `\n` escaped line breaks removed from the key `private_key`

Perhaps I am still doing something wrong, but since the JSON format key that is easily exported from the Google cloud console contains all info that nocodb needs except the bucket name, I would suggest for nocodb to support that format to remove a lot of guesswork for users trying to set this up.

**Comment by DarkPhoenix2704** [comment]
@dstala This seems already fixed. We had merged a pr which fixes issues related to gcs

**Comment by dstala** [comment]
Please reopen this ticket if issues persists. Closing this thread for now

**Comment by smithcoin** [comment]
I am seeing the same behavior trying to connect to GCS

`2025-11-19T10:08:41.126459842Z [Nest] 8  - 11/19/2025, 10:08:41 AM   ERROR ;5;3m[MissingDBError] Error: error:1E08010C:DECODER routines::unsupported`

I am running the application in docker. 

- json key doesn't work
- neither does the pk12 format in any possible combination

**Comment by despens** [comment]
@dstala, @DarkPhoenix2704 I think this feature might just require correct documentation. I also wasn't able to set up GCS for storage, Google just doesn't really use the categories of "client email" and "private key" for storage, which leaves users at a loss what to fill into the nocodb form.
