### ISSUE TITLE
🐛 Bug: Failed to load list: Something went wrong

### ISSUE THREAD

**Issue by cyberkd** [nocodb/nocodb#8630]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Select a field in the table with the Links data type that is connected as one to one. 
2. Trying to perform a search in both English and Latin, we get the error **Failed to load list: Something went wrong**.

![firefox_HInVlXK55U](https://github.com/nocodb/nocodb/assets/123419418/7269ce42-fb0d-488a-b2aa-2c134c105988)

It is also worth noting that the search with the use of krill is not performed. The search is only possible if it is performed using the Latin alphabet. 

The error message is received in any case, as when writing in Latin (it works) so it is in Cyrillic (does not work)

### Desired Behavior

A search must be performed on all pages in the linked table in both Cyrillic and Latin.

### Project Details

NocoDB: Docker True
NocoDB: Version 0.207.3
NocoDB DB Type: Mysql 8.0

### Attachments

Logs in the container

[Nest] 7  - 06/01/2024, 6:47:54 PM   ERROR [GlobalExceptionFilter] Cannot read properties of null (reading 'uidt')
TypeError: Cannot read properties of null (reading 'uidt')
    at t.getRefColumnIfAlias (/usr/src/app/docker/main.js:2:1014067)
    at b (/usr/src/app/docker/main.js:2:573273)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async b (/usr/src/app/docker/main.js:2:572275)
    at async t.default (/usr/src/app/docker/main.js:2:572060)
    at async BaseModelSqlv2.getExcludedOneToOneChildrenList (/usr/src/app/docker/main.js:2:491253)
    at async DataAliasNestedService.ooExcludedList (/usr/src/app/docker/main.js:2:1800450)
    at async DataAliasNestedController.ooExcludedList (/usr/src/app/docker/main.js:2:338373)
[Nest] 7  - 06/01/2024, 6:47:54 PM   ERROR [GlobalExceptionFilter] Cannot read properties of null (reading 'uidt')

**Comment by dstala** [comment]
@pranavxc issue is reproducible when connected to external DB (tried with sakila mysql db : actor one-to-one film)

**Comment by dinesh-hills** [comment]
I face this exact same issue while search on linked records list.

**Comment by dinesh-hills** [comment]
Is there any version in which the search is stable?

**Comment by dstala** [comment]
not reproducible anymore. reopen this thread if issue noticed in latest release
