### ISSUE TITLE
🐛 Bug: Unable to connect to MySQL database via Datasources; Access Denied error

### ISSUE THREAD

**Issue by MagnusHL** [nocodb/nocodb#8727]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

	1.	Go to Datasources in NocoDB.
	2.	Add a new MySQL database connection with the appropriate credentials.
	3.	Attempt to connect to the MySQL database.

### Desired Behavior

The MySQL database should connect successfully, similar to how the MSSQL database connection works, without any access denied errors.

### Project Details

Node: **v20.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.250.0**

### Attachments

![CleanShot 2024-06-13 at 15 54 44@2x](https://github.com/nocodb/nocodb/assets/6343677/f512360f-bdb1-4599-b200-60d18bfd20b2)

`[Nest] 9  - 06/13/2024, 1:47:12 PM   ERROR [JobsEventService] ---- !! JOB FAILED !! ----
id:1
error:Error (create database if not exists `r50`  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci - Access denied for user 'kunde'@'%' to database 'r50')

stack: Error: create database if not exists `r50`  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci - Access denied for user 'kunde'@'%' to database 'r50'
    at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)`

mysql client works
`mysql --host=localhost --port=33306 --protocol=tcp -u kunde -pXXXXXX --database=r50 -e "select * FROM firma564_shop_beleg_kopf"`

**Comment by deaw0003** [comment]
I have the same issue.

**Comment by BojanKomazec** [comment]
This is also an issue for me as I want to grant nocodb user a limited access only to certain tables in database. If I grant nocodb user permissions to create a database (`create database if not exists`) then I can't revoke its permissions on certain tables in that database.
