### ISSUE TITLE
🐛 Bug: Cannot connect to legacy MySQL

### ISSUE THREAD

**Issue by despens** [nocodb/nocodb#8776]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Connect to new remote data source via nocodb interface.
2. Connection test successful.
3. Submit the new remote connection.
4. Meta Sync correctly shows remote tables.
5. Click sync.
6. Nocodb hangs syncing.
7. After reloading the page, the remote database connection briefly vanishes from the base, on next reload it appears again.

I'm able to connect to the mysql database using mysql-client from within the nocodb container.

Remote version:
```
# mysql --version
mysql  Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64) using readline 6.3
```

<details>
<summary>Docker log </summary>

```
nocodb-1  | 
╔══════════════════════════════════════════════════════════════════════════════╗
║                                                                              ║
║   EXCEPTION OCCURED!! in MysqlClient @ columnList                            ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║
║   - - - - - - - - - - - - - - - - - - - - - -                                ║
║   MESSAGE:                                                                   ║
║   SELECT                                                                     ║
║   c.table_name as tn,                                                        ║
║   c.column_name as cn,                                                       ║
║   c.data_type as dt,                                                         ║
║   c.column_type as ct,                                                       ║
║   c.character_maximum_length as clen,                                        ║
║   c.numeric_precision as np,                                                 ║
║   c.numeric_scale as ns,                                                     ║
║   c.datetime_precision as dp,                                                ║
║   c.ordinal_position as cop,                                                 ║
║   c.column_key as ck,                                                        ║
║   c.extra as ext, -- gives ai                                                ║
║   c.column_default as cdf,                                                   ║
║   c.is_nullable as nrqd,                                                     ║
║   c.privileges as priv,                                                      ║
║   c.column_comment as cc,                                                    ║
║   --       c.generation_expression,                                          ║
║   c.character_set_name as csn,                                               ║
║   c.collation_name as clnn,                                                  ║
║   ct.CONSTRAINT_TYPE as cst                                                  ║
║   FROM                                                                       ║
║   information_schema.COLUMNS as c                                            ║
║   Left join(                                                                 ║
║   select                                                                     ║
║   tc.CONSTRAINT_NAME,                                                        ║
║   tc.TABLE_NAME,                                                             ║
║   tc.CONSTRAINT_SCHEMA,                                                      ║
║   tc.CONSTRAINT_TYPE,                                                        ║
║   s.COLUMN_NAME                                                              ║
║   from                                                                       ║
║   information_schema.TABLE_CONSTRAINTS as tc                                 ║
║   LEFT JOIN information_schema.STATISTICS as s ON                            ║
║   s.table_schema = tc.CONSTRAINT_SCHEMA                                      ║
║   and s.TABLE_NAME = tc.TABLE_NAME                                           ║
║   and s.INDEX_NAME = tc.CONSTRAINT_NAME                                      ║
║   and tc.CONSTRAINT_TYPE != 'UNIQUE'                                         ║
║   and tc.CONSTRAINT_TYPE != 'FOREIGN KEY'                                    ║
║   where                                                                      ║
║   tc.CONSTRAINT_SCHEMA = 'REDACTED'                                           ║
║   and s.TABLE_NAME = 'REDACTED'                                          ║
║   ) ct on                                                                    ║
║   c.TABLE_SCHEMA = ct.CONSTRAINT_SCHEMA                                      ║
║   AND c.TABLE_NAME = ct.TABLE_NAME                                           ║
║   AND c.COLUMN_NAME = ct.COLUMN_NAME                                         ║
║   WHERE                                                                      ║
║   c.table_schema = 'REDACTED'                                                 ║
║   and c.TABLE_NAME = 'REDACTED'                                          ║
║   ORDER BY                                                                   ║
║   c.table_name,                                                              ║
║   c.ordinal_position - Unknown column 'c.datetime_precision' in 'field       ║
║   list'                                                                      ║
║                                                                              ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║
║   - - - - - - - - - - - - - - - - - - - - - -                                ║
║   CODE:                                                                      ║
║   ER_BAD_FIELD_ERROR                                                         ║
║                                                                              ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║
║   - - - - - - - - - - - - - - - - - - - - - -                                ║
║   STACK:                                                                     ║
║   Error: SELECT                                                              ║
║   c.table_name as tn,                                                        ║
║   c.column_name as cn,                                                       ║
║   c.data_type as dt,                                                         ║
║   c.column_type as ct,                                                       ║
║   c.character_maximum_length as clen,                                        ║
║   c.numeric_precision as np,                                                 ║
║   c.numeric_scale as ns,                                                     ║
║   c.datetime_precision as dp,                                                ║
║   c.ordinal_position as cop,                                                 ║
║   c.column_key as ck,                                                        ║
║   c.extra as ext, -- gives ai                                                ║
║   c.column_default as cdf,                                                   ║
║   c.is_nullable as nrqd,                                                     ║
║   c.privileges as priv,                                                      ║
║   c.column_comment as cc,                                                    ║
║   --       c.generation_expression,                                          ║
║   c.character_set_name as csn,                                               ║
║   c.collation_name as clnn,                                                  ║
║   ct.CONSTRAINT_TYPE as cst                                                  ║
║   FROM                                                                       ║
║   information_schema.COLUMNS as c                                            ║
║   Left join(                                                                 ║
║   select                                                                     ║
║   tc.CONSTRAINT_NAME,                                                        ║
║   tc.TABLE_NAME,                                                             ║
║   tc.CONSTRAINT_SCHEMA,                                                      ║
║   tc.CONSTRAINT_TYPE,                                                        ║
║   s.COLUMN_NAME                                                              ║
║   from                                                                       ║
║   information_schema.TABLE_CONSTRAINTS as tc                                 ║
║   LEFT JOIN information_schema.STATISTICS as s ON                            ║
║   s.table_schema = tc.CONSTRAINT_SCHEMA                                      ║
║   and s.TABLE_NAME = tc.TABLE_NAME                                           ║
║   and s.INDEX_NAME = tc.CONSTRAINT_NAME                                      ║
║   and tc.CONSTRAINT_TYPE != 'UNIQUE'                                         ║
║   and tc.CONSTRAINT_TYPE != 'FOREIGN KEY'                                    ║
║   where                                                                      ║
║   tc.CONSTRAINT_SCHEMA = 'REDACTED'                                           ║
║   and s.TABLE_NAME = 'REDACTED'                                          ║
║   ) ct on                                                                    ║
║   c.TABLE_SCHEMA = ct.CONSTRAINT_SCHEMA                                      ║
║   AND c.TABLE_NAME = ct.TABLE_NAME                                           ║
║   AND c.COLUMN_NAME = ct.COLUMN_NAME                                         ║
║   WHERE                                                                      ║
║   c.table_schema = 'REDACTED'                                                 ║
║   and c.TABLE_NAME = 'REDACTED'                                          ║
║   ORDER BY                                                                   ║
║   c.table_name,                                                              ║
║   c.ordinal_position - Unknown column 'c.datetime_precision' in 'field       ║
║   list'                                                                      ║
║   at Packet.asError                                                          ║
║   (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:728:17)            ║
║   at Query.execute                                                           ║
║   (/usr/src/app/node_modules/mysql2/lib/commands/command.js:29:26)           ║
║   at Connection.handlePacket                                                 ║
║   (/usr/src/app/node_modules/mysql2/lib/connection.js:481:34)                ║
║   at PacketParser.onPacket                                                   ║
║   (/usr/src/app/node_modules/mysql2/lib/connection.js:97:12)                 ║
║   at PacketParser.executeStart                                               ║
║   (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)              ║
║   at Socket.<anonymous>                                                      ║
║   (/usr/src/app/node_modules/mysql2/lib/connection.js:104:25)                ║
║   at Socket.emit (node:events:518:28)                                        ║
║   at Socket.emit (node:domain:488:12)                                        ║
║   at addChunk (node:internal/streams/readable:559:12)                        ║
║   at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)     ║
║                                                                              ║
║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║
║   - - - - - - - - - - - - - - - - - - - - - -                                ║
║                                                                              ║
║                                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝
nocodb-1  | Error: SELECT
nocodb-1  |       c.table_name as tn,
nocodb-1  |       c.column_name as cn,
nocodb-1  |       c.data_type as dt,
nocodb-1  |       c.column_type as ct,
nocodb-1  |       c.character_maximum_length as clen,
nocodb-1  |       c.numeric_precision as np,
nocodb-1  |       c.numeric_scale as ns,
nocodb-1  |       c.datetime_precision as dp,
nocodb-1  |       c.ordinal_position as cop,
nocodb-1  |       c.column_key as ck,
nocodb-1  |       c.extra as ext, -- gives ai
nocodb-1  |       c.column_default as cdf,
nocodb-1  |       c.is_nullable as nrqd,
nocodb-1  |       c.privileges as priv,
nocodb-1  |       c.column_comment as cc,
nocodb-1  | --       c.generation_expression,
nocodb-1  |       c.character_set_name as csn,
nocodb-1  |       c.collation_name as clnn,
nocodb-1  |       ct.CONSTRAINT_TYPE as cst
nocodb-1  |      FROM
nocodb-1  |       information_schema.COLUMNS as c
nocodb-1  |     Left join(
nocodb-1  |               select
nocodb-1  |                       tc.CONSTRAINT_NAME,
nocodb-1  |                       tc.TABLE_NAME,
nocodb-1  |                       tc.CONSTRAINT_SCHEMA,
nocodb-1  |                       tc.CONSTRAINT_TYPE,
nocodb-1  |                       s.COLUMN_NAME
nocodb-1  |               from
nocodb-1  |                       information_schema.TABLE_CONSTRAINTS as tc
nocodb-1  |               LEFT JOIN information_schema.STATISTICS as s ON
nocodb-1  |                       s.table_schema = tc.CONSTRAINT_SCHEMA
nocodb-1  |                       and s.TABLE_NAME = tc.TABLE_NAME
nocodb-1  |                       and s.INDEX_NAME = tc.CONSTRAINT_NAME
nocodb-1  |                       and tc.CONSTRAINT_TYPE != 'UNIQUE'
nocodb-1  |                       and tc.CONSTRAINT_TYPE != 'FOREIGN KEY'
nocodb-1  |               where
nocodb-1  |                       tc.CONSTRAINT_SCHEMA = 'REDACTED'
nocodb-1  |                       and s.TABLE_NAME = 'REDACTED'
nocodb-1  |       ) ct on
nocodb-1  |       c.TABLE_SCHEMA = ct.CONSTRAINT_SCHEMA
nocodb-1  |       AND c.TABLE_NAME = ct.TABLE_NAME
nocodb-1  |       AND c.COLUMN_NAME = ct.COLUMN_NAME
nocodb-1  |     WHERE
nocodb-1  |       c.table_schema = 'REDACTED'
nocodb-1  |       and c.TABLE_NAME = 'REDACTED'
nocodb-1  |     ORDER BY
nocodb-1  |       c.table_name,
nocodb-1  |       c.ordinal_position - Unknown column 'c.datetime_precision' in 'field list'
nocodb-1  |     at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:728:17)
nocodb-1  |     at Query.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:29:26)
nocodb-1  |     at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:481:34)
nocodb-1  |     at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:97:12)
nocodb-1  |     at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)
nocodb-1  |     at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:104:25)
nocodb-1  |     at Socket.emit (node:events:518:28)
nocodb-1  |     at Socket.emit (node:domain:488:12)
nocodb-1  |     at addChunk (node:internal/streams/readable:559:12)
nocodb-1  |     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
nocodb-1  |   code: 'ER_BAD_FIELD_ERROR',
nocodb-1  |   errno: 1054,
nocodb-1  |   sqlState: '42S22',
nocodb-1  |   sqlMessage: "Unknown column 'c.datetime_precision' in 'field list'",
nocodb-1  |   sql: 'SELECT\n' +
nocodb-1  |     '      c.table_name as tn,\n' +
nocodb-1  |     '      c.column_name as cn,\n' +
nocodb-1  |     '      c.data_type as dt,\n' +
nocodb-1  |     '      c.column_type as ct,\n' +
nocodb-1  |     '      c.character_maximum_length as clen,\n' +
nocodb-1  |     '      c.numeric_precision as np,\n' +
nocodb-1  |     '      c.numeric_scale as ns,\n' +
nocodb-1  |     '      c.datetime_precision as dp,\n' +
nocodb-1  |     '      c.ordinal_position as cop,\n' +
nocodb-1  |     '      c.column_key as ck,\n' +
nocodb-1  |     '      c.extra as ext, -- gives ai\n' +
nocodb-1  |     '      c.column_default as cdf,\n' +
nocodb-1  |     '      c.is_nullable as nrqd,\n' +
nocodb-1  |     '      c.privileges as priv,\n' +
nocodb-1  |     '      c.column_comment as cc,\n' +
nocodb-1  |     '--       c.generation_expression,\n' +
nocodb-1  |     '      c.character_set_name as csn,\n' +
nocodb-1  |     '      c.collation_name as clnn,\n' +
nocodb-1  |     '      ct.CONSTRAINT_TYPE as cst\n' +
nocodb-1  |     '     FROM\n' +
nocodb-1  |     '      information_schema.COLUMNS as c\n' +
nocodb-1  |     '    Left join(\n' +
nocodb-1  |     '              select\n' +
nocodb-1  |     '                      tc.CONSTRAINT_NAME,\n' +
nocodb-1  |     '                      tc.TABLE_NAME,\n' +
nocodb-1  |     '                      tc.CONSTRAINT_SCHEMA,\n' +
nocodb-1  |     '                      tc.CONSTRAINT_TYPE,\n' +
nocodb-1  |     '                      s.COLUMN_NAME\n' +
nocodb-1  |     '              from\n' +
nocodb-1  |     '                      information_schema.TABLE_CONSTRAINTS as tc\n' +
nocodb-1  |     '              LEFT JOIN information_schema.STATISTICS as s ON\n' +
nocodb-1  |     '                      s.table_schema = tc.CONSTRAINT_SCHEMA\n' +
nocodb-1  |     '                      and s.TABLE_NAME = tc.TABLE_NAME\n' +
nocodb-1  |     '                      and s.INDEX_NAME = tc.CONSTRAINT_NAME\n' +
nocodb-1  |     "                      and tc.CONSTRAINT_TYPE != 'UNIQUE'\n" +
nocodb-1  |     "                      and tc.CONSTRAINT_TYPE != 'FOREIGN KEY'\n" +
nocodb-1  |     '              where\n' +
nocodb-1  |     "                      tc.CONSTRAINT_SCHEMA = 'REDACTED'\n" +
nocodb-1  |     "                      and s.TABLE_NAME = 'REDACTED'\n" +
nocodb-1  |     '      ) ct on\n' +
nocodb-1  |     '      c.TABLE_SCHEMA = ct.CONSTRAINT_SCHEMA\n' +
nocodb-1  |     '      AND c.TABLE_NAME = ct.TABLE_NAME\n' +
nocodb-1  |     '      AND c.COLUMN_NAME = ct.COLUMN_NAME\n' +
nocodb-1  |     '    WHERE\n' +
nocodb-1  |     "      c.table_schema = 'REDACTED'\n" +
nocodb-1  |     "      and c.TABLE_NAME = 'REDACTED'\n" +
nocodb-1  |     '    ORDER BY\n' +
nocodb-1  |     '      c.table_name,\n' +
nocodb-1  |     '      c.ordinal_position'
nocodb-1  | }
nocodb-1  | [Nest] 15  - 06/17/2024, 2:52:52 PM   ERROR [JobsEventService] ---- !! JOB FAILED !! ----
nocodb-1  | id:4
nocodb-1  | error:Error (SELECT
nocodb-1  |       c.table_name as tn,
nocodb-1  |       c.column_name as cn,
nocodb-1  |       c.data_type as dt,
nocodb-1  |       c.column_type as ct,
nocodb-1  |       c.character_maximum_length as clen,
nocodb-1  |       c.numeric_precision as np,
nocodb-1  |       c.numeric_scale as ns,
nocodb-1  |       c.datetime_precision as dp,
nocodb-1  |       c.ordinal_position as cop,
nocodb-1  |       c.column_key as ck,
nocodb-1  |       c.extra as ext, -- gives ai
nocodb-1  |       c.column_default as cdf,
nocodb-1  |       c.is_nullable as nrqd,
nocodb-1  |       c.privileges as priv,
nocodb-1  |       c.column_comment as cc,
nocodb-1  | --       c.generation_expression,
nocodb-1  |       c.character_set_name as csn,
nocodb-1  |       c.collation_name as clnn,
nocodb-1  |       ct.CONSTRAINT_TYPE as cst
nocodb-1  |      FROM
nocodb-1  |       information_schema.COLUMNS as c
nocodb-1  |     Left join(
nocodb-1  |               select
nocodb-1  |                       tc.CONSTRAINT_NAME,
nocodb-1  |                       tc.TABLE_NAME,
nocodb-1  |                       tc.CONSTRAINT_SCHEMA,
nocodb-1  |                       tc.CONSTRAINT_TYPE,
nocodb-1  |                       s.COLUMN_NAME
nocodb-1  |               from
nocodb-1  |                       information_schema.TABLE_CONSTRAINTS as tc
nocodb-1  |               LEFT JOIN information_schema.STATISTICS as s ON
nocodb-1  |                       s.table_schema = tc.CONSTRAINT_SCHEMA
nocodb-1  |                       and s.TABLE_NAME = tc.TABLE_NAME
nocodb-1  |                       and s.INDEX_NAME = tc.CONSTRAINT_NAME
nocodb-1  |                       and tc.CONSTRAINT_TYPE != 'UNIQUE'
nocodb-1  |                       and tc.CONSTRAINT_TYPE != 'FOREIGN KEY'
nocodb-1  |               where
nocodb-1  |                       tc.CONSTRAINT_SCHEMA = 'REDACTED'
nocodb-1  |                       and s.TABLE_NAME = 'REDACTED'
nocodb-1  |       ) ct on
nocodb-1  |       c.TABLE_SCHEMA = ct.CONSTRAINT_SCHEMA
nocodb-1  |       AND c.TABLE_NAME = ct.TABLE_NAME
nocodb-1  |       AND c.COLUMN_NAME = ct.COLUMN_NAME
nocodb-1  |     WHERE
nocodb-1  |       c.table_schema = 'REDACTED'
nocodb-1  |       and c.TABLE_NAME = 'REDACTED'
nocodb-1  |     ORDER BY
nocodb-1  |       c.table_name,
nocodb-1  |       c.ordinal_position - Unknown column 'c.datetime_precision' in 'field list')
nocodb-1  | 
nocodb-1  | stack: Error: SELECT
nocodb-1  |       c.table_name as tn,
nocodb-1  |       c.column_name as cn,
nocodb-1  |       c.data_type as dt,
nocodb-1  |       c.column_type as ct,
nocodb-1  |       c.character_maximum_length as clen,
nocodb-1  |       c.numeric_precision as np,
nocodb-1  |       c.numeric_scale as ns,
nocodb-1  |       c.datetime_precision as dp,
nocodb-1  |       c.ordinal_position as cop,
nocodb-1  |       c.column_key as ck,
nocodb-1  |       c.extra as ext, -- gives ai
nocodb-1  |       c.column_default as cdf,
nocodb-1  |       c.is_nullable as nrqd,
nocodb-1  |       c.privileges as priv,
nocodb-1  |       c.column_comment as cc,
nocodb-1  | --       c.generation_expression,
nocodb-1  |       c.character_set_name as csn,
nocodb-1  |       c.collation_name as clnn,
nocodb-1  |       ct.CONSTRAINT_TYPE as cst
nocodb-1  |      FROM
nocodb-1  |       information_schema.COLUMNS as c
nocodb-1  |     Left join(
nocodb-1  |               select
nocodb-1  |                       tc.CONSTRAINT_NAME,
nocodb-1  |                       tc.TABLE_NAME,
nocodb-1  |                       tc.CONSTRAINT_SCHEMA,
nocodb-1  |                       tc.CONSTRAINT_TYPE,
nocodb-1  |                       s.COLUMN_NAME
nocodb-1  |               from
nocodb-1  |                       information_schema.TABLE_CONSTRAINTS as tc
nocodb-1  |               LEFT JOIN information_schema.STATISTICS as s ON
nocodb-1  |                       s.table_schema = tc.CONSTRAINT_SCHEMA
nocodb-1  |                       and s.TABLE_NAME = tc.TABLE_NAME
nocodb-1  |                       and s.INDEX_NAME = tc.CONSTRAINT_NAME
nocodb-1  |                       and tc.CONSTRAINT_TYPE != 'UNIQUE'
nocodb-1  |                       and tc.CONSTRAINT_TYPE != 'FOREIGN KEY'
nocodb-1  |               where
nocodb-1  |                       tc.CONSTRAINT_SCHEMA = 'REDACTED'
nocodb-1  |                       and s.TABLE_NAME = 'REDACTED'
nocodb-1  |       ) ct on
nocodb-1  |       c.TABLE_SCHEMA = ct.CONSTRAINT_SCHEMA
nocodb-1  |       AND c.TABLE_NAME = ct.TABLE_NAME
nocodb-1  |       AND c.COLUMN_NAME = ct.COLUMN_NAME
nocodb-1  |     WHERE
nocodb-1  |       c.table_schema = 'REDACTED'
nocodb-1  |       and c.TABLE_NAME = 'REDACTED'
nocodb-1  |     ORDER BY
nocodb-1  |       c.table_name,
nocodb-1  |       c.ordinal_position - Unknown column 'c.datetime_precision' in 'field list'
nocodb-1  |     at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:728:17)
nocodb-1  |     at Query.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:29:26)
nocodb-1  |     at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:481:34)
nocodb-1  |     at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:97:12)
nocodb-1  |     at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)
nocodb-1  |     at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:104:25)
nocodb-1  |     at Socket.emit (node:events:518:28)
nocodb-1  |     at Socket.emit (node:domain:488:12)
nocodb-1  |     at addChunk (node:internal/streams/readable:559:12)
nocodb-1  |     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
nocodb-1  | [Nest] 15  - 06/17/2024, 2:54:07 PM   DEBUG [GlobalExceptionFilter] Cannot GET /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application
nocodb-1  | [Nest] 15  - 06/17/2024, 2:54:07 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot GET /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application
nocodb-1  |     at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
nocodb-1  |     at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
nocodb-1  |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
nocodb-1  |     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
nocodb-1  |     at /usr/src/app/node_modules/express/lib/router/index.js:286:9
nocodb-1  |     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
nocodb-1  |     at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
nocodb-1  |     at next (/usr/src/app/node_modules/express/lib/router/route.js:141:14)
nocodb-1  |     at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
nocodb-1  |     at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
```

</details>

### Desired Behavior

Connection test successful, but actual connection fails.

### Project Details

```
NocoDB used as docker : trueNocoDB version : 0.250.2
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : mysql
OS on which NocoDB is running : docker (Alpine Linux)
Node.js version if running as node : 
Database version : PostgreSQL 15
```

**Comment by despens** [comment]
[MySQL 5.6 release notes mention](https://downloads.mysql.com/docs/mysql-5.6-relnotes-en.pdf) the introduction of `datetime_precision`, upgrading to any 5.6 or above version should help.

Perhaps nocodb should list the earliest supported versions of RDMSs?

**Comment by despens** [comment]
@o1lab may I ask what was the chosen solution to close the issue?

**Comment by o1lab** [comment]
@despens : Our previous docs mentioned we only supported 5.7+ version. We are updating the new docs for this.

What cloud were you on to have 5.6+ version - was that version because of legacy application?

**Comment by despens** [comment]
@o1lab Thanks for the info! Yes I was and am using nocodb to explore and migrate databases of legacy applications. Being able to connect to postgres, MySQL, MariaDB and sqlite databases with a good user interface is great. This is not for applications on commercial cloud vendors, but for internal applications. I'm using the self-hosted version of nocodb.
