### ISSUE TITLE
🐛 Bug:  Pop up prompt "this.xlsx.read is not a function". When I import, this content pops up.

### ISSUE THREAD

**Issue by sleepyddl** [nocodb/nocodb#8887]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. From [ https://github.com/nocodb/nocodb/archive/refs/tags/0.251.0.zip ]( https://github.com/nocodb/nocodb/archive/refs/tags/0.251.0.zip ) Download source code.
2. run `pnpm bootstrap`
3. run `pnpm start:frontend`
4. run `pnpm start:backend`
5. Registration and login
6. Bases - getting started - importData - Excel ， The file was uploaded in this path, and when the Import button was clicked, an error window popped up
7. Error messages on UI 
![image](https://github.com/nocodb/nocodb/assets/43658905/55767f77-a307-41c5-97bb-d52c276a2645)

8. Error messages on the console
```TypeError: this.xlsx.read is not a function
    at ExcelTemplateAdapter.init (ExcelTemplateAdapter.ts:56:25)
    at parseAndExtractData (QuickImport.vue:483:31)
    at handlePreImport (QuickImport.vue:168:13)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at emit (runtime-core.esm-bundler.js:726:5)
    at runtime-core.esm-bundler.js:7824:45
    at handleClick2 (button.js:103:7)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
```

### Desired Behavior

Resolve errors when importing Excel.

### Project Details

Node: **v18.19.1**
Arch: **x64**
Platform: **win32**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.250.2**

**Comment by dstala** [comment]
- works fine in production
- issue noticed in self-hosted instance
