### ISSUE TITLE
🐛 Bug: Portainer:  getaddrinfo ENOTFOUND host.docker.internal

### ISSUE THREAD

**Issue by F041** [nocodb/nocodb#8945]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

following: https://github.com/nocodb/nocodb/issues/8932
if I go to the IP:8080 I get 

[Nest] 8  - 07/05/2024, 9:46:16 AM   ERROR [ExceptionHandler] Error: getaddrinfo ENOTFOUND host.docker.internal
    at async Promise.all (index 3)
    at async Injector.loadProvider (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:97:9)
    at async /usr/src/app/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:144:24)
Error: Error: getaddrinfo ENOTFOUND host.docker.internal
    at async Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:369:37)
    at async Injector.loadInstance (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:70:13)
    at async callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:65:34)
    at async InstanceWrapper.useFactory [as metatype] (/usr/src/app/docker/main.js:2:1724327)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at NcConfig.create (/usr/src/app/docker/main.js:2:2091016)

and the the containers exits.

It seems related to https://github.com/nocodb/nocodb/issues/7340 , but then I'd specify it in the main page https://github.com/nocodb/nocodb

### Desired Behavior

not getting a ERR_CONNECTION_REFUSED to the IP:8080

### Project Details

VPS with Ubuntu

**Comment by mertmit** [comment]
Hi @F041,
This is usually related to linux behavior of docker. In linux host.docker.internal is not automatically binded to host so instead you should either add `--add-host=host.docker.internal:host-gateway` as argument or you should replace host.docker.internal with 172.17.0.1

Good you've mentioned please confirm from your side I will make sure we add it to our README.

**Comment by F041** [comment]
second solution
`[Nest] 8  - 07/05/2024, 3:04:23 PM   ERROR [ExceptionHandler] Error: connect ECONNREFUSED 172.17.0.1:5432
`
first solution
`[dumb-init] --add-host=host.docker.internal:host-gateway: No such file or directory 
`
leads to https://github.com/nocodb/nocodb/issues/7340

**Comment by mertmit** [comment]
Are you using docker-compose, if so is it possible for you to share it without confidential parts.
If it is not possible please make sure your PG database is accessible on your machine (try simple psql connection)

**Comment by F041** [comment]
SOLVED: I used 
```
git clone https://github.com/nocodb/nocodb
cd nocodb/docker-compose/pg
```
and ofcourse  I installed docker-compose via 
`sudo apt  install docker-compose 
`
So the problem comes from portainer app template I used: https://raw.githubusercontent.com/Lissy93/portainer-templates/main/templates.json
