### ISSUE TITLE
An error occurred linking the mino plugin🐛 Bug: 

### ISSUE THREAD

**Issue by vitaaaaa1** [nocodb/nocodb#9001]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Test error when setting nocodb link minio :"You must specify at least one part"
The following is detailed error information:
[Nest] 8  - 07/15/2024, 6:05:48 AM   ERROR [MissingDBError] S3Error: You must specify at least one part
[Nest] 8  - 07/15/2024, 6:05:48 AM   ERROR [GlobalExceptionFilter] You must specify at least one part
S3Error: You must specify at least one part
    at parseError (/usr/src/app/node_modules/minio/dist/main/internal/xml-parser.js:47:13)
    at Object.parseResponseError (/usr/src/app/node_modules/minio/dist/main/internal/xml-parser.js:94:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.makeRequestStreamAsync (/usr/src/app/node_modules/minio/dist/main/internal/client.js:491:19)
    at async Client.completeMultipartUpload (/usr/src/app/node_modules/minio/dist/main/internal/client.js:1162:17)
    at async /usr/src/app/node_modules/minio/dist/main/internal/client.js:1458:14
    at async Promise.all (index 1)
    at async Client.uploadStream (/usr/src/app/node_modules/minio/dist/main/internal/client.js:1412:20)

### Desired Behavior

Test error when setting nocodb link minio :"You must specify at least one part"

### Project Details

minio version:"RELEASE.2023-10-24T04-42-36Z ",install by docker

### Attachments

![image](https://github.com/user-attachments/assets/18a7b66d-db89-4ed5-a1e0-f19809868aa0)

**Comment by DarkPhoenix2704** [comment]
Duplicate of https://github.com/nocodb/nocodb/issues/9099
