### ISSUE TITLE
🐛 Bug: Thumbnail generation failing

### ISSUE THREAD

**Issue by DarkPhoenix2704** [nocodb/nocodb#9087]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

> Original URL (valid): https://rdb-attachments.s3.eu-central-003.backblazeb2.com/nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-lmgyxl_j7Sl6.jpg

> Thumbnail URL (invalid): https://rdb-attachments.s3.eu-central-003.backblazeb2.com/nc/thumbnails/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-lmgyxl_j7Sl6.jpg/tiny.jpg

> I just checked all files in the corresponding `rdb-attachments` bucket, there are *no* thumbnails, i.e. they were never written to the object store.

### Desired Behavior

```
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   ERROR [ThumbnailGeneratorProcessor] Failed to generate thumbnails
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   ERROR [ThumbnailGeneratorProcessor] TypeError: Invalid URL
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   DEBUG [GlobalExceptionFilter] Cannot GET /dashboard/dltemp/15v8By6F80pge0Yp/1722013800000/nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-73zg19_KQzZs.png
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot GET /dashboard/dltemp/15v8By6F80pge0Yp/1722013800000/nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-73zg19_KQzZs.png
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:141:14)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   DEBUG [GlobalExceptionFilter] Cannot GET /dashboard/dltemp/LeTpXgjLlXZJKAg1/1722013800000/nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-lmgyxl_j7Sl6.jpg
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot GET /dashboard/dltemp/LeTpXgjLlXZJKAg1/1722013800000/nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-lmgyxl_j7Sl6.jpg
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:141:14)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   DEBUG [GlobalExceptionFilter] Cannot GET /nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-73zg19_KQzZs.png
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot GET /nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-73zg19_KQzZs.png
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:141:14)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   DEBUG [GlobalExceptionFilter] Cannot GET /nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-lmgyxl_j7Sl6.jpg
2024-07-26T15:08:49Z app[1781991a690708] cdg [info][Nest] 335  - 07/26/2024, 3:08:49 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot GET /nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-lmgyxl_j7Sl6.jpg
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:141:14)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-26T15:08:49Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)

```

### Project Details

.

**Comment by DarkPhoenix2704** [comment]
@salim-b Can you verify if it's working for new attachments in this build

```bash
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.251.3-pr-9088-20240726-1825
```

**Comment by salim-b** [comment]
@DarkPhoenix2704 It's still not working with this PR. Logs from adding a new attachment:

```
2024-07-27T12:18:38Z app[1781991a690708] cdg [info][Nest] 348  - 07/27/2024, 12:18:38 PM   ERROR [ThumbnailGeneratorProcessor] Failed to generate thumbnails
2024-07-27T12:18:38Z app[1781991a690708] cdg [info][Nest] 348  - 07/27/2024, 12:18:38 PM   ERROR [ThumbnailGeneratorProcessor] TypeError: Invalid URL
2024-07-27T12:18:38Z app[1781991a690708] cdg [info][Nest] 348  - 07/27/2024, 12:18:38 PM   DEBUG [GlobalExceptionFilter] Cannot GET /dashboard/dltemp/TLoDyFE5Opw24HU9/1722090000000/nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-oxry69_GR4xA.jpg
2024-07-27T12:18:38Z app[1781991a690708] cdg [info][Nest] 348  - 07/27/2024, 12:18:38 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot GET /dashboard/dltemp/TLoDyFE5Opw24HU9/1722090000000/nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-oxry69_GR4xA.jpg
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:141:14)
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-27T12:18:38Z app[1781991a690708] cdg [info][Nest] 348  - 07/27/2024, 12:18:38 PM   DEBUG [GlobalExceptionFilter] Cannot GET /nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-oxry69_GR4xA.jpg
2024-07-27T12:18:38Z app[1781991a690708] cdg [info][Nest] 348  - 07/27/2024, 12:18:38 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot GET /nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-oxry69_GR4xA.jpg
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:141:14)
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-27T12:18:38Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
```

**Comment by salim-b** [comment]
@DarkPhoenix2704 I've also tested the latest daily build (`nocodb/nocodb-daily:0.251.3-20240728-1203`) as this PR has been merged meanwhile. Still the same results:

```
2024-07-28T16:21:09Z app[1781991a690708] cdg [info][Nest] 346  - 07/28/2024, 4:21:09 PM   ERROR [ThumbnailGeneratorProcessor] Failed to generate thumbnails
2024-07-28T16:21:09Z app[1781991a690708] cdg [info][Nest] 346  - 07/28/2024, 4:21:09 PM   ERROR [ThumbnailGeneratorProcessor] TypeError: Invalid URL
2024-07-28T16:21:09Z app[1781991a690708] cdg [info][Nest] 346  - 07/28/2024, 4:21:09 PM   DEBUG [GlobalExceptionFilter] Cannot GET /dashboard/dltemp/QOYPDi3R_vju4Fg-/1722191400000/nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-73mxov_8SF3J.png
2024-07-28T16:21:09Z app[1781991a690708] cdg [info][Nest] 346  - 07/28/2024, 4:21:09 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot GET /dashboard/dltemp/QOYPDi3R_vju4Fg-/1722191400000/nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-73mxov_8SF3J.png
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:141:14)
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-28T16:21:09Z app[1781991a690708] cdg [info][Nest] 346  - 07/28/2024, 4:21:09 PM   DEBUG [GlobalExceptionFilter] Cannot GET /nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-73mxov_8SF3J.png
2024-07-28T16:21:09Z app[1781991a690708] cdg [info][Nest] 346  - 07/28/2024, 4:21:09 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot GET /nc/uploads/noco/p75yos47mu8fs8b/mx5tkjg13vlbjr3/ccpxnishddejjt2/wallhaven-73mxov_8SF3J.png
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:141:14)
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-28T16:21:09Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
```

Please re-open.

**Comment by DarkPhoenix2704** [comment]
hey @salim-b. Can you message me on discord, I need some more information

This is my discord ID `@darkphoenix2704`

**Comment by langyamu** [comment]
I encountered this error with the Windows version as well.
![image](https://github.com/user-attachments/assets/425e379a-aaa9-4342-a40f-42dd23610ebe)
![image](https://github.com/user-attachments/assets/2731dee3-b427-4da5-8481-3e77f250f5a4)

**Comment by salim-b** [comment]
I have just tested `nocodb/nocodb-timely:0.251.3-pr-9101-20240729-1221` which includes https://github.com/nocodb/nocodb/pull/9101. Thumbnail generation still fails with the error:

```
2024-07-30T20:46:13Z app[1781991a690708] cdg [info][Nest] 350  - 07/30/2024, 8:46:13 PM   ERROR [ThumbnailGeneratorProcessor] Failed to generate thumbnails for /nc/uploads/noco/pkcjzkrd63iskdc/mirrk7sidlh8j8g/ctbqx10hn4qk5lg/wallhaven-73zg19_sngd4.png
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]TypeError: Invalid URL
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at new URL (node:internal/url:797:36)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at ThumbnailGeneratorProcessor.getFileData (/usr/src/app/docker/main.js:2:1700297)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at ThumbnailGeneratorProcessor.generateThumbnail (/usr/src/app/docker/main.js:2:1699500)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at async /usr/src/app/docker/main.js:2:1699109
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at async Promise.all (index 0)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at async ThumbnailGeneratorProcessor.job (/usr/src/app/docker/main.js:2:1699297)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at async QueueService.jobWrapper (/usr/src/app/docker/main.js:2:1550202)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at async run (/usr/src/app/node_modules/p-queue/dist/index.js:163:29)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info][Nest] 350  - 07/30/2024, 8:46:13 PM   DEBUG [GlobalExceptionFilter] Cannot GET /dashboard/dltemp/9uumKUO8WVlZ_NPS/1722379800000/nc/uploads/noco/pkcjzkrd63iskdc/mirrk7sidlh8j8g/ctbqx10hn4qk5lg/wallhaven-73zg19_sngd4.png
2024-07-30T20:46:13Z app[1781991a690708] cdg [info][Nest] 350  - 07/30/2024, 8:46:13 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot GET /dashboard/dltemp/9uumKUO8WVlZ_NPS/1722379800000/nc/uploads/noco/pkcjzkrd63iskdc/mirrk7sidlh8j8g/ctbqx10hn4qk5lg/wallhaven-73zg19_sngd4.png
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:141:14)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info][Nest] 350  - 07/30/2024, 8:46:13 PM   DEBUG [GlobalExceptionFilter] Cannot GET /nc/uploads/noco/pkcjzkrd63iskdc/mirrk7sidlh8j8g/ctbqx10hn4qk5lg/wallhaven-73zg19_sngd4.png
2024-07-30T20:46:13Z app[1781991a690708] cdg [info][Nest] 350  - 07/30/2024, 8:46:13 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot GET /nc/uploads/noco/pkcjzkrd63iskdc/mirrk7sidlh8j8g/ctbqx10hn4qk5lg/wallhaven-73zg19_sngd4.png
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:141:14)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
2024-07-30T20:46:13Z app[1781991a690708] cdg [info]    at next (/usr/src/app/node_modules/express/lib/router/route.js:145:7)
```

**Comment by mertmit** [comment]
@salim-b can you please copy & paste the cell that failed to generate thumbnail, 
error suggests the path is provided as url lets see if attachment object is correct

**Comment by DarkPhoenix2704** [comment]
@mertmit This is the path given by @salim-b 


```
[
  {
    "url": "https://xxxxxxxxx.s3.eu-central-003.backblazeb2.com/nc/uploads/noco/pkcjzkrd63iskdc/mirrk7sidlh8j8g/ctbqx10hn4qk5lg/wallhaven-73zg19_sngd4.png",
    "title": "wallhaven-73zg19.png",
    "mimetype": "image/png",
    "size": 18379272,
    "width": 7680,
    "height": 4320
  }
]

```


https://github.com/nocodb/nocodb/issues/5914#issuecomment-2005008734

He uses this trigger for updating the url manually

**Comment by salim-b** [comment]
I can confirm that https://github.com/nocodb/nocodb/pull/9104 fixed this issue by testing the `nocodb/nocodb-timely:0.251.3-pr-9104-20240731-1149` build. 🎉
