### ISSUE TITLE
Minio plugin: You must specify at least one part error

### ISSUE THREAD

**Issue by mattalxndr** [nocodb/nocodb#9099]
### Discussed in https://github.com/nocodb/nocodb/discussions/8425

<div type='discussions-op-text'>

<sup>Originally posted by **Tatametheus** May  7, 2024</sup>
Install both nocodb and minio in docker. Endpoint and ports are local ip ports.
```
[Nest] 11  - 05/08/2024, 11:40:58 AM   ERROR [MissingDBError] S3Error: You must specify at least one part
[Nest] 11  - 05/08/2024, 11:40:58 AM   ERROR [GlobalExceptionFilter] You must specify at least one part
S3Error: You must specify at least one part
    at parseError (/usr/src/app/node_modules/minio/dist/main/internal/xml-parser.js:47:13)
    at Object.parseResponseError (/usr/src/app/node_modules/minio/dist/main/internal/xml-parser.js:94:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.makeRequestStreamAsync (/usr/src/app/node_modules/minio/dist/main/internal/client.js:491:19)
    at async Client.completeMultipartUpload (/usr/src/app/node_modules/minio/dist/main/internal/client.js:1162:17)
    at async /usr/src/app/node_modules/minio/dist/main/internal/client.js:1458:14
    at async Promise.all (index 1)
    at async Client.uploadStream (/usr/src/app/node_modules/minio/dist/main/internal/client.js:1412:20)
```</div>

**Comment by DarkPhoenix2704** [comment]
Fixed in https://github.com/nocodb/nocodb/pull/9104
