### ISSUE TITLE
🐛 Bug: MySQL Error on GroupBy

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#9133]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

https://discord.com/channels/661905455894888490/661905455894888493/1268549986858041446

Hi, I connected to mysql database and when I try to group in a view, I get the following error:
message: Cannot read properties of undefined (reading '0')

TypeError: Cannot read properties of undefined (reading '0')
    at q (http://172.20.33.80:8080/dashboard/_nuxt/CYwlXk2Y.js:5:69001)
    at Js (http://172.20.33.80:8080/dashboard/_nuxt/CsKyRz2p.js:14:1346)
    at ka (http://172.20.33.80:8080/dashboard/_nuxt/CsKyRz2p.js:14:1417)
    at yN (http://172.20.33.80:8080/dashboard/_nuxt/CsKyRz2p.js:14:45351)
    at P (http://172.20.33.80:8080/dashboard/_nuxt/iIVJIWEd.js:1:2179)
    at h (http://172.20.33.80:8080/dashboard/_nuxt/iIVJIWEd.js:1:2320)
    at Js (http://172.20.33.80:8080/dashboard/_nuxt/CsKyRz2p.js:14:1346)
    at ka (http://172.20.33.80:8080/dashboard/_nuxt/CsKyRz2p.js:14:1417)
    at yN (http://172.20.33.80:8080/dashboard/_nuxt/CsKyRz2p.js:14:45351)
    at r (http://172.20.33.80:8080/dashboard/_nuxt/iIVJIWEd.js:1:4336)

### Desired Behavior

No error

### Project Details

251.3

**Comment by DarkPhoenix2704** [comment]
Fixed by @pranavxc in a groupby pr
