### ISSUE TITLE
🐛 Bug: XMinioInvalidObjectName 

### ISSUE THREAD

**Issue by anskibe** [nocodb/nocodb#9203]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

just tried to upload jpg to self-hosted minio 

S:\.nocodb\source\nocodb\node_modules\.pnpm\minio@8.0.1\node_modules\minio\dist\main\internal\xml-parser.ts:36
  const e = new errors.S3Error() as unknown as Record<string, unknown>
            ^
S3Error: Object name contains unsupported characters.
    at parseError (S:\.nocodb\source\nocodb\node_modules\.pnpm\minio@8.0.1\node_modules\minio\dist\main\internal\xml-parser.ts:36:13)
    at Object.parseResponseError (S:\.nocodb\source\nocodb\node_modules\.pnpm\minio@8.0.1\node_modules\minio\dist\main\internal\xml-parser.ts:85:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.makeRequestStreamAsync (S:\.nocodb\source\nocodb\node_modules\.pnpm\minio@8.0.1\node_modules\minio\dist\main\internal\client.ts:735:19)
    at async Client.initiateNewMultipartUpload (S:\.nocodb\source\nocodb\node_modules\.pnpm\minio@8.0.1\node_modules\minio\dist\main\internal\client.ts:1352:17)
    at async Client.uploadStream (S:\.nocodb\source\nocodb\node_modules\.pnpm\minio@8.0.1\node_modules\minio\dist\main\internal\client.ts:1708:18) {
  code: 'XMinioInvalidObjectName',
  key: 'nc\\thumbnails\\noco\\pymw3rk8q5yz8j1\\mot6v2b40hapq1y\\c9w5ayiiucuvyw1\\photo_2024-03-05_15-25-47 (2)_k91TE.jpg\\tiny.jpg',
  bucketname: 'bucket',
  resource: '/bucket/nc\\thumbnails\\noco\\pymw3rk8q5yz8j1\\mot6v2b40hapq1y\\c9w5ayiiucuvyw1\\photo_2024-03-05_15-25-47 (2)_k91TE.jpg\\tiny.jpg',
  requestid: '17EA749567EBE254',
  hostid: '16a716ab4ba280df873845393d2428d5b31c5d78cbc20ec41a606d6ad0b8ec37',
  amzRequestid: '17EA749567EBE254',
  amzId2: '16a716ab4ba280df873845393d2428d5b31c5d78cbc20ec41a606d6ad0b8ec37',
  amzBucketRegion: undefined
}
[nodemon] app crashed - waiting for file changes before starting...

### Desired Behavior

no error

### Project Details

nocodb git clone in VS Code for 09.08.2024

**Comment by DarkPhoenix2704** [comment]
Hi @anskibe 

Would you be able to provide the cell contents of an attachment field.

**Comment by anskibe** [comment]
[Nest] 11540  - 11.08.2024, 09:30:19   ERROR [ThumbnailGeneratorProcessor] Failed to generate thumbnails for https://minio-1.local.host:9000/nc/uploads/noco/pymw3rk8q5yz8j1/mot6v2b40hapq1y/c9w5ayiiucuvyw1/photo_2024-03-05_15-25-47 (2)_87Atr.jpg
S3Error: The specified key does not exist.
    at parseError (S:\.nocodb\source\nocodb\node_modules\.pnpm\minio@8.0.1\node_modules\minio\dist\main\internal\xml-parser.ts:36:13)
    at Object.parseResponseError (S:\.nocodb\source\nocodb\node_modules\.pnpm\minio@8.0.1\node_modules\minio\dist\main\internal\xml-parser.ts:85:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.makeRequestStreamAsync (S:\.nocodb\source\nocodb\node_modules\.pnpm\minio@8.0.1\node_modules\minio\dist\main\internal\client.ts:735:19)
    at async Client.getPartialObject (S:\.nocodb\source\nocodb\node_modules\.pnpm\minio@8.0.1\node_modules\minio\dist\main\internal\client.ts:1072:12)
    at async Minio.fileRead (S:\.nocodb\source\nocodb\packages\nocodb\src\plugins\mino\Minio.ts:48:18)
    at async ThumbnailGeneratorProcessor.getFileData (S:\.nocodb\source\nocodb\packages\nocodb\src\modules\jobs\jobs\thumbnail-generator\thumbnail-generator.processor.ts:144:18)
    at async ThumbnailGeneratorProcessor.generateThumbnail (S:\.nocodb\source\nocodb\packages\nocodb\src\modules\jobs\jobs\thumbnail-generator\thumbnail-generator.processor.ts:61:38)
    at async S:\.nocodb\source\nocodb\packages\nocodb\src\modules\jobs\jobs\thumbnail-generator\thumbnail-generator.processor.ts:25:27
    at async Promise.all (index 0)


![photo_2024-03-05_15-25-47 (2)](https://github.com/user-attachments/assets/7c8f06bc-d847-4c65-8b24-61ad382d2cbc)

**Comment by anskibe** [comment]
> Hi @anskibe
> 
> Would you be able to provide the cell contents of an attachment field.

i attached file in previous message (white image)

**Comment by anskibe** [comment]
here is the file photo_2024-03-05_15-25-47 (2)_k91TE.jpg\tiny.jpg


![photo_2024-03-05_15-25-47 (2)](https://github.com/user-attachments/assets/dabeafec-6a26-4858-8ac2-40d6db63b56e)

**Comment by anskibe** [comment]
![image](https://github.com/user-attachments/assets/75cf9c5a-2286-4ac5-b4db-c43a5d1a79c1)

**Comment by anskibe** [comment]
![image](https://github.com/user-attachments/assets/af04f5fb-ee1e-424a-a1ef-030b25ae0a6a)

**Comment by anskibe** [comment]
then i just ctrl + c and pnpm start:backend
and everything continue working, files are displayed in noco
![image](https://github.com/user-attachments/assets/2ed175bb-f307-4898-8437-9124ba11dd16)
![image](https://github.com/user-attachments/assets/a0701819-161e-4487-aafa-b543709334cc)

**Comment by anskibe** [comment]
also i see that files in Minio aren't deleted after deletion in nocodb attachment cell

**Comment by anskibe** [comment]
i'm testing this problem now

and i can assume that this error related to every .jpg that i'm trying to upload with nocodb into minio via attachment field
only .jpg images for now

there is no problem with other file formats

**Comment by anskibe** [comment]
well
it's also crashes after uploading file named like  Радченко М.Г., Хрусталева Е.Ю. - 1С Предприятие 8.3 Практическое пособие разработчика. Примеры и типовые приемы - 2023.pdf

**Comment by anskibe** [comment]
then i renamed it to Radchenko M G Khrustaleva E Yu 1C Enterprise 83 Practical guide for the developer Examples and typical techniques 2023.pdf

and it uploads sucessfully (previously it even doesn't uploaded

**Comment by anskibe** [comment]
photo5274082469710255425.jpg
also causes crash

S:\.nocodb\source\nocodb\node_modules\.pnpm\minio@8.0.1\node_modules\minio\dist\main\internal\xml-parser.ts:36
  const e = new errors.S3Error() as unknown as Record<string, unknown>
            ^
S3Error: Object name contains unsupported characters.
    at parseError (S:\.nocodb\source\nocodb\node_modules\.pnpm\minio@8.0.1\node_modules\minio\dist\main\internal\xml-parser.ts:36:13)
    at Object.parseResponseError (S:\.nocodb\source\nocodb\node_modules\.pnpm\minio@8.0.1\node_modules\minio\dist\main\internal\xml-parser.ts:85:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.makeRequestStreamAsync (S:\.nocodb\source\nocodb\node_modules\.pnpm\minio@8.0.1\node_modules\minio\dist\main\internal\client.ts:735:19)
    at async Client.initiateNewMultipartUpload (S:\.nocodb\source\nocodb\node_modules\.pnpm\minio@8.0.1\node_modules\minio\dist\main\internal\client.ts:1352:17)
    at async Client.uploadStream (S:\.nocodb\source\nocodb\node_modules\.pnpm\minio@8.0.1\node_modules\minio\dist\main\internal\client.ts:1708:18) {
  code: 'XMinioInvalidObjectName',
  key: 'nc\\thumbnails\\noco\\pymw3rk8q5yz8j1\\mot6v2b40hapq1y\\c9w5ayiiucuvyw1\\photo5274082469710255425_Lgepp.jpg\\tiny.jpg',
  bucketname: 'bucket',
  resource: '/bucket/nc\\thumbnails\\noco\\pymw3rk8q5yz8j1\\mot6v2b40hapq1y\\c9w5ayiiucuvyw1\\photo5274082469710255425_Lgepp.jpg\\tiny.jpg',
  requestid: '17EAA05DBCB01028',
  hostid: '16a716ab4ba280df873845393d2428d5b31c5d78cbc20ec41a606d6ad0b8ec37',
  amzRequestid: '17EAA05DBCB01028',
  amzId2: '16a716ab4ba280df873845393d2428d5b31c5d78cbc20ec41a606d6ad0b8ec37',
  amzBucketRegion: undefined
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by anskibe** [comment]
[{"url":"https://minio-1.local.host:9000/nc/uploads/noco/pymw3rk8q5yz8j1/mot6v2b40hapq1y/c9w5ayiiucuvyw1/photo5274082469710255425_Lgepp.jpg","title":"photo5274082469710255425.jpg","mimetype":"image/jpeg","size":216809,"width":1280,"height":720}]

**Comment by anskibe** [comment]
bucket/nc/uploads/noco/pymw3rk8q5yz8j1/mot6v2b40hapq1y/c9w5ayiiucuvyw1/photo5274082469710255425_Lgepp.jpg

actual minio path
