### ISSUE TITLE
🐛 Bug: Upload via URL bug

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#9217]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

```
[Nest] 8  - 08/11/2024, 1:31:16 AM   ERROR [AttachmentsService] TypeError: (intermediate value)(intermediate value)(intermediate value).replace is not a function
[Nest] 8  - 08/11/2024, 1:31:16 AM   ERROR [GlobalExceptionFilter] (intermediate value)(intermediate value)(intermediate value).replace is not a function
TypeError: (intermediate value)(intermediate value)(intermediate value).replace is not a function
    at PresignedUrl.getSignedUrl (/usr/src/app/docker/main.js:2:1462822)
    at PresignedUrl.signAttachment (/usr/src/app/docker/main.js:2:1464460)
    at /usr/src/app/docker/main.js:2:1847447
    at async run (/usr/src/app/node_modules/p-queue/dist/index.js:163:29)
```

### Desired Behavior

no error

### Project Details

Docker - version not specified

**Comment by dstala** [comment]
https://discord.com/channels/661905455894888490/661905455894888493/1272768358269583405
