### ISSUE TITLE
🐛 Bug: Docker with MS SQL init db error

### ISSUE THREAD

**Issue by kptkachenko** [nocodb/nocodb#9220]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

First start container.

docker run -d -p 8080:8080 \
    -e NC_DB="mssql://host:port?u=user&p=password&d=database" \
    -e NC_AUTH_JWT_SECRET="569a1821-0a93-45e8-87ab-eb857f20a010" \
    nocodb/nocodb:latest

ERROR [ExceptionHandler] ALTER TABLE [nc_audit_v2] ALTER COLUMN [base_id] nvarchar(20) -
AggregateError: ALTER TABLE [nc_audit_v2] ALTER COLUMN [base_id] nvarchar(20) -
    at RequestTokenHandler.onErrorMessage (/usr/src/app/node_modules/tedious/lib/token/handler.js:297:30)
    at Readable.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:18:33)
    at Readable.emit (node:events:519:28)
    at Readable.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3)
    at Readable.push (node:internal/streams/readable:391:5)
    at nextAsync (node:internal/streams/from:194:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Desired Behavior

need to fix

### Project Details

NocoDB with docker

**Comment by kptkachenko** [comment]
Latest worked with MS-SQL image is nocodb/nocodb:0.207.3
