### ISSUE TITLE
🐛 Bug: TypeError: e.split is not a function when trying to run ,eq, query

### ISSUE THREAD

**Issue by yorickvP** [nocodb/nocodb#9309]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Run a data list query via the api with `?w=(name,eq,hello)`

Log:
```
TypeError: e.split is not a function
    at W (/usr/src/app/docker/main.js:2:642838)
    at BaseModelSqlv2.count (/usr/src/app/docker/main.js:2:516956)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async DatasService.getDataList (/usr/src/app/docker/main.js:2:2001612)
    at async DatasService.dataList (/usr/src/app/docker/main.js:2:1999300)
    at async DataTableService.dataList (/usr/src/app/docker/main.js:2:1987746)
    at async DataTableController.dataList (/usr/src/app/docker/main.js:2:372877)
[Nest] 9  - 08/21/2024, 2:23:14 PM   ERROR [DatasService] TypeError: e.split is not a function
```

### Desired Behavior

Query works as documetned

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.255.0**

**Comment by yorickvP** [comment]
The W function seems to correspond to `extractFilterFromXwhere`

**Comment by dstala** [comment]
Tried this -- worked fine for me. Can you help me with complete API URL that you tried it out?

```curl
curl -X 'GET' \
  'https://app.nocodb.com/api/v2/tables/m2v69wm2g73ylco/records?where=%28Name%2Ceq%2CRaju%29&limit=25&shuffle=0&offset=0' \
  -H 'accept: application/json' \
  -H 'xc-token: xc-token'
```
