### ISSUE TITLE
🐛 Bug: attempting to upgrade docker container nocodb/nocodb:latest fails on migration file "nc_054_id_length"

### ISSUE THREAD

**Issue by sesa-emation** [nocodb/nocodb#9315]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

When attempting to upgrade nocodb to the latest container version I get the error

```
migration file "nc_054_id_length" failed
migration failed with error: ALTER TABLE [nc_audit_v2] ALTER COLUMN [base_id] nvarchar(20) - 
[Nest] 8  - 08/22/2024, 7:02:25 AM     LOG [NestFactory] Starting Nest application...
[Nest] 8  - 08/22/2024, 7:02:25 AM     LOG [InstanceLoader] PassportModule dependencies initialized +1ms
[Nest] 8  - 08/22/2024, 7:02:25 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
[Nest] 8  - 08/22/2024, 7:02:25 AM     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
[Nest] 8  - 08/22/2024, 7:02:25 AM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 8  - 08/22/2024, 7:02:25 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 8  - 08/22/2024, 7:02:25 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 8  - 08/22/2024, 7:02:25 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 8  - 08/22/2024, 7:02:25 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +1ms
[Nest] 8  - 08/22/2024, 7:02:25 AM     LOG [nc_046_comment_mentions] Migration Started
[Nest] 8  - 08/22/2024, 7:02:25 AM     LOG [nc_046_comment_mentions] Data from Audit Table fetched, batch: 0 - 1000
[Nest] 8  - 08/22/2024, 7:02:25 AM     LOG [nc_046_comment_mentions] Data from Audit Table formatted
[Nest] 8  - 08/22/2024, 7:02:25 AM     LOG [nc_046_comment_mentions] Data migrated from Audit Table to Comments Table
[Nest] 8  - 08/22/2024, 7:02:25 AM   ERROR [ExceptionHandler] ALTER TABLE [nc_audit_v2] ALTER COLUMN [base_id] nvarchar(20) - 
AggregateError: ALTER TABLE [nc_audit_v2] ALTER COLUMN [base_id] nvarchar(20) - 
    at RequestTokenHandler.onErrorMessage (/usr/src/app/node_modules/tedious/lib/token/handler.js:297:30)
    at Readable.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:18:33)
    at Readable.emit (node:events:519:28)
    at Readable.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3)
    at Readable.push (node:internal/streams/readable:391:5)
    at nextAsync (node:internal/streams/from:194:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Trying to execute the SQL query to alter the table manually, SQL Server responds with the error
``Index "nc_audit_v2_project_id_index" is dependent on column "base_id".``

It appears that for altering the column size the index needs to be removed first, after altering the size it needs to be re-added.

### Desired Behavior

NocoDB upgrade completes successfully

### Project Details

```
NocoDB used as docker: true
NocoDB version: 0.255.0
Database used in NC_DB_URL: mssql
Project was created by clicking: N/A
Database on which spreadsheet is created : N/A
OS on which NocoDB is running : Linux 6.8.8-1-default x86_64 GNU/Linux
Node.js version if running as node : N/A
Database version : Microsoft SQL Server 2014
```

**Comment by dstala** [comment]
@sesa-emation do you still see any issue with upgrades?

**Comment by sesa-emation** [comment]
We are no longer using NocoDB, however I have logged into our test server, pulled the latest image (sha256:96c37dc0b3118afe541df1656dfb69846074258af35ec3d56e4827bf88514567) and recreated the old container. The same error message still appears.

**Comment by dstala** [comment]
this issue seems to be an isolated one & would need manual intervention. please DM me on discord to follow it through (Username dstala)
