### ISSUE TITLE
🐛 Bug: Formula error handling

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#9357]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Try to save formula without feeding anything. 

```
[20:52:55.355] ERROR (79161): TypeError: Cannot read properties of undefined (reading 'length')
    at Jsep.gobbleExpressions (/Users/rajuudava/NocoDB/nocohub/node_modules/.pnpm/jsep@1.3.8/node_modules/jsep/src/jsep.js:323:33)
    at Jsep.parse (/Users/rajuudava/NocoDB/nocohub/node_modules/.pnpm/jsep@1.3.8/node_modules/jsep/src/jsep.js:303:22)
    at jsep (/Users/rajuudava/NocoDB/nocohub/node_modules/.pnpm/jsep@1.3.8/node_modules/jsep/src/jsep.js:965:39)
    at substituteColumnAliasWithIdInFormula (/Users/rajuudava/NocoDB/nocohub/packages/nocodb-sdk/src/lib/formulaHelpers.ts:98:29)
    at ColumnsService.columnAdd (/Users/rajuudava/NocoDB/nocohub/packages/nocodb/src/services/columns.service.ts:1763:69)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ColumnsController.columnAdd (/Users/rajuudava/NocoDB/nocohub/packages/nocodb/src/controllers/columns.controller.ts:39:12)
    req: {
      "id": "c11ef7e0-8b30-4c38-9e9d-d139342a3ddd",
      "method": "POST",
      "url": "/api/v1/db/meta/tables/mtz9im0n6n73y7o/columns",
      "clientId": "018b03a5-c462-7cfa-b808-272f2678fd34"
    }
    context: "GlobalExceptionFilter"
    workspaceId: "winwk5gv"
    projectId: "pjgpee350n3tpy1"
    ip: "::1"
    id: "us2ssonj5658isc9"
    path: "/api/v1/db/meta/tables/mtz9im0n6n73y7o/columns"
    clientId: "018b03a5-c462-7cfa-b808-272f2678fd34"
```

### Desired Behavior

- Disable Save field until formula is fed OR
- Handle the scenario as required if we try to save without any formula being input

### Project Details

255.0

**Comment by DarkPhoenix2704** [comment]
@dstala This is already handled in latest develop. The formula can't be saved if it is invalid
