### ISSUE TITLE
🐛 Bug: Invalid Scope at Migration

### ISSUE THREAD

**Issue by premudeshi** [nocodb/nocodb#9442]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Docker compose with NocoDB 0.109.7 running. I attempted to pull the image and start the docker compose stack again, when after all the DB migration, the command line prompts this error. 
```
[Nest] 8  - 09/06/2024, 3:14:21 PM   ERROR [ExceptionHandler] Invalid scope
Error: Invalid scope
    at NcError.metaError (/usr/src/app/docker/main.js:2:1103890)
    at MetaService.metaGet2 (/usr/src/app/docker/main.js:2:1232617)
    at Column.get (/usr/src/app/docker/main.js:2:1386787)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async t.default [as handler] (/usr/src/app/docker/main.js:2:2252005)
    at async NcUpgrader.upgrade (/usr/src/app/docker/main.js:2:2240557)
    at async InstanceWrapper.useFactory [as metatype] (/usr/src/app/docker/main.js:2:1831149)
    at async Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:369:37)
    at async callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:65:34)
    at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:144:24)
```

### Desired Behavior

Update runs smoothly.

### Project Details

```
NocoDB used as docker: true
NocoDB version: 0.109.7
Databased used: mySQL
OS: Ubuntu
```

**Comment by dstala** [comment]
since you are upgrading from a relatively older version, this upgrade issue might need manual intervention to debug it further. please dm me on discord to discuss further (username: dstala)
