### ISSUE TITLE
🐛 Bug: Unable to resolve pg container name in coolify

### ISSUE THREAD

**Issue by shadysamir** [nocodb/nocodb#9449]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

- On coolify, start a new project.
- Set up a PG service.
- Set up a nocodb service
- Add env variable NC_DB with information about the PG service including container name as hostname pg://j4g44okskok04cks4kwogkkg:5432?u=postgres&p=<password>&d=postgres
After deployment the application fails to start with the error log:
```
[Nest] 8  - 09/07/2024, 10:33:05 PM   ERROR ;5;3m[ExceptionHandler] Error: getaddrinfo EAI_AGAIN j4g44okskok04cks4kwogkkg
Error: Error: getaddrinfo EAI_AGAIN j4g44okskok04cks4kwogkkg
    at NcConfig.create (/usr/src/app/docker/main.js:2:2228217)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InstanceWrapper.useFactory [as metatype] (/usr/src/app/docker/main.js:2:1830025)
    at async Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:369:37)
    at async callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:65:34)
    at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:144:24)
    at async Injector.loadInstance (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:70:13)
    at async Injector.loadProvider (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:97:9)
    at async /usr/src/app/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 3)
```

### Desired Behavior

Knex is able to resolve container name and connets to db. I tried NC_DB_JSON and I'm getting the same error.

### Project Details

NocoDB on coolify

**Comment by shadysamir** [comment]
To verify the issue is not related to coolify, I created my own nodejs mini app inside the same project and tested the connection json with pg and woth knex. They both resolved the container name properly and connected successfully to the db

**Comment by dstala** [comment]
resolved here; please reopen if you are facing issue still
https://community.nocodb.com/t/cannot-access-main-postgres-database-with-coolify/1353/5

**Comment by shadysamir** [comment]
@dstala this is my own thread over there. And it's not resolved. I tested knex library in my own application and it worked while it still can't resolve the db container name in nocodb.

**Comment by shadysamir** [comment]
@dstala I think I do not have the permission to reopen the issue.

**Comment by shadysamir** [comment]
I tried the solution provided by the bot in the comments and added `NODE_OPTIONS="--dns-result-order=ipv4first"`  env variable. Still nocodb is unable to resolve the db container name

**Comment by shadysamir** [comment]
Solved by setting "use provided network" in coolify nocodb application settings.
