### ISSUE TITLE
🐛 Bug: error when creating barcode field with formula field as source

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#9492]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

create barcode field with formula field as source

```
TypeError: Cannot read properties of null (reading 'error')
    at extractColumn (/Users/rajuudava/NocoDB/nocohub/packages/nocodb/src/ee/services/data-opt/pg-helpers.ts:864:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 3)
    at async extractColumns (/Users/rajuudava/NocoDB/nocohub/packages/nocodb/src/ee/services/data-opt/pg-helpers.ts:128:3)
    at async singleQueryList (/Users/rajuudava/NocoDB/nocohub/packages/nocodb/src/ee/services/data-opt/pg-helpers.ts:1494:3)
    at async DataOptService.list (/Users/rajuudava/NocoDB/nocohub/packages/nocodb/src/ee/services/data-opt/data-opt.service.ts:52:14)
    at async DatasService.dataList (/Users/rajuudava/NocoDB/nocohub/packages/nocodb/src/ee/services/datas.service.ts:112:22)
    at async DataAliasController.dataList (/Users/rajuudava/NocoDB/nocohub/packages/nocodb/src/controllers/data-alias.controller.ts:45:26)
[14:45:16.889] ERROR (12282): TypeError: Cannot read properties of null (reading 'error')
    at extractColumn (/Users/rajuudava/NocoDB/nocohub/packages/nocodb/src/ee/services/data-opt/pg-helpers.ts:864:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 3)
    at async extractColumns (/Users/rajuudava/NocoDB/nocohub/packages/nocodb/src/ee/services/data-opt/pg-helpers.ts:128:3)
    at async singleQueryList (/Users/rajuudava/NocoDB/nocohub/packages/nocodb/src/ee/services/data-opt/pg-helpers.ts:1494:3)
    at async DataOptService.list (/Users/rajuudava/NocoDB/nocohub/packages/nocodb/src/ee/services/data-opt/data-opt.service.ts:52:14)
    at async DatasService.dataList (/Users/rajuudava/NocoDB/nocohub/packages/nocodb/src/ee/services/datas.service.ts:112:22)
    at async DataAliasController.dataList (/Users/rajuudava/NocoDB/nocohub/packages/nocodb/src/controllers/data-alias.controller.ts:45:26)
    req: {
      "id": "d42e4c47-7c55-485b-b5ac-72ff4b96ac5c",
      "method": "GET",
      "url": "/api/v1/db/data/noco/pu3osw9g95nsz6d/mfbygg4yltk18lz/views/vwnig3ghgrf5f5hl?offset=0&limit=100",
      "clientId": "018b03a5-c462-7cfa-b808-272f2678fd34"
    }
    context: "GlobalExceptionFilter"
    workspaceId: "w0g28lhe"
    projectId: "pu3osw9g95nsz6d"
    ip: "::1"
    id: "us7krphu8imfcr1v"
    path: "/api/v1/db/data/noco/pu3osw9g95nsz6d/mfbygg4yltk18lz/views/vwnig3ghgrf5f5hl"
    clientId: "018b03a5-c462-7cfa-b808-272f2678fd34"


```

### Desired Behavior

no error

### Project Details

255.2

**Comment by o1lab** [comment]
Its fine in latest version/
