### ISSUE TITLE
🐛 Bug: Install worked but cannot find my server.

### ISSUE THREAD

**Issue by TheRealJamesRussell** [nocodb/nocodb#9507]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

1. Get a subdomain
2. Point it to your server
3. run the upstall script
4. give your domain
5. say yest to ssl
6. go to your domain

### Desired Behavior

When I do the above I would like nocodb to hosted on the subdomain i've given.

### Project Details

Can't access the ... button, Currently hosting didn't work.

Let me know. What info you need from me, I am unsure whether to share my NocoDB logs?

**Comment by TheRealJamesRussell** [comment]
Going through the list:
docker ps 

i get this list of running services:
![image](https://github.com/user-attachments/assets/5d37144b-bbd9-44c2-a2df-1a1871e64093)

tried: docker logs nocodb
no such container exists

But I didn't explicitly install via docker or compose. just used your upstall script

Also checked my ports. all allowed in ufw.

Should upstall have installed a docker container called nocodb?

**Comment by TheRealJamesRussell** [comment]
Doing -a helped. Activated, Issue is it keeps restarting, it's like up for 1 second. then restarts. up 1 second, restart.

I got the logs:
[Nest] 8  - 09/18/2024, 9:56:49 AM     LOG [NestFactory] Starting Nest application...
[Nest] 8  - 09/18/2024, 9:56:49 AM     LOG [InstanceLoader] PassportModule dependencies initialized +1ms
[Nest] 8  - 09/18/2024, 9:56:49 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
[Nest] 8  - 09/18/2024, 9:56:49 AM     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
[Nest] 8  - 09/18/2024, 9:56:49 AM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 8  - 09/18/2024, 9:56:49 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 8  - 09/18/2024, 9:56:49 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
[Nest] 8  - 09/18/2024, 9:56:49 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 8  - 09/18/2024, 9:56:49 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
[Nest] 8  - 09/18/2024, 9:56:49 AM   ERROR [ExceptionHandler] error: password authentication failed for user "postgres"
Error: error: password authentication failed for user "postgres"
    at NcConfig.create (/usr/src/app/docker/main.js:2:2228217)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InstanceWrapper.useFactory [as metatype] (/usr/src/app/docker/main.js:2:1830025)
    at async Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:369:37)
    at async callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:65:34)
    at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:144:24)
    at async Injector.loadInstance (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:70:13)
    at async Injector.loadProvider (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:97:9)
    at async /usr/src/app/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 3)
╔══════════════════════════════════════════════════════════════════════════════╗║                                                                              ║║   EXCEPTION OCCURED!! in PGClient @ createDatabaseIfNotExists                ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   MESSAGE:                                                                   ║║   password authentication failed for user "postgres"                         ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   CODE:                                                                      ║║   28P01                                                                      ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   STACK:                                                                     ║║   error: password authentication failed for user "postgres"                  ║║   at Parser.parseErrorMessage                                                ║║   (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)              ║║   at Parser.handlePacket                                                     ║║   (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)              ║║   at Parser.parse                                                            ║║   (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)               ║║   at Socket.<anonymous>                                                      ║║   (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)                ║║   at Socket.emit (node:events:519:28)                                        ║║   at Socket.emit (node:domain:488:12)                                        ║║   at addChunk (node:internal/streams/readable:559:12)                        ║║   at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)     ║║   at Readable.push (node:internal/streams/readable:390:5)                    ║║   at TCP.onStreamRead (node:internal/stream_base_commons:191:23)             ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║                                                                              ║║                                                                              ║╚══════════════════════════════════════════════════════════════════════════════╝
error: password authentication failed for user "postgres"
    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
  length: 104,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '323',
  routine: 'auth_failed'
}
[Nest] 8  - 09/18/2024, 9:57:54 AM     LOG [NestFactory] Starting Nest application...
[Nest] 8  - 09/18/2024, 9:57:54 AM     LOG [InstanceLoader] PassportModule dependencies initialized +0ms
[Nest] 8  - 09/18/2024, 9:57:54 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +1ms
[Nest] 8  - 09/18/2024, 9:57:54 AM     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
[Nest] 8  - 09/18/2024, 9:57:54 AM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 8  - 09/18/2024, 9:57:54 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 8  - 09/18/2024, 9:57:54 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 8  - 09/18/2024, 9:57:54 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 8  - 09/18/2024, 9:57:54 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
[Nest] 8  - 09/18/2024, 9:57:54 AM   ERROR [ExceptionHandler] error: password authentication failed for user "postgres"
Error: error: password authentication failed for user "postgres"
    at NcConfig.create (/usr/src/app/docker/main.js:2:2228217)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InstanceWrapper.useFactory [as metatype] (/usr/src/app/docker/main.js:2:1830025)
    at async Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:369:37)
    at async callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:65:34)
    at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:144:24)
    at async Injector.loadInstance (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:70:13)
    at async Injector.loadProvider (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:97:9)
    at async /usr/src/app/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 3)
james@server:~/NoobsDB$

**Comment by pranavxc** [comment]
> Doing -a helped. Activated, Issue is it keeps restarting, it's like up for 1 second. then restarts. up 1 second, restart.
> 
> I got the logs:
> 
> ```
> [Nest] 8  - 09/18/2024, 9:56:49 AM     LOG [NestFactory] Starting Nest application...
> [Nest] 8  - 09/18/2024, 9:56:49 AM     LOG [InstanceLoader] PassportModule dependencies initialized +1ms
> [Nest] 8  - 09/18/2024, 9:56:49 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
> [Nest] 8  - 09/18/2024, 9:56:49 AM     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
> [Nest] 8  - 09/18/2024, 9:56:49 AM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
> [Nest] 8  - 09/18/2024, 9:56:49 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
> [Nest] 8  - 09/18/2024, 9:56:49 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
> [Nest] 8  - 09/18/2024, 9:56:49 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
> [Nest] 8  - 09/18/2024, 9:56:49 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
> [Nest] 8  - 09/18/2024, 9:56:49 AM   ERROR [ExceptionHandler] error: password authentication failed for user "postgres"
> Error: error: password authentication failed for user "postgres"
>     at NcConfig.create (/usr/src/app/docker/main.js:2:2228217)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async InstanceWrapper.useFactory [as metatype] (/usr/src/app/docker/main.js:2:1830025)
>     at async Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:369:37)
>     at async callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:65:34)
>     at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:144:24)
>     at async Injector.loadInstance (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:70:13)
>     at async Injector.loadProvider (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:97:9)
>     at async /usr/src/app/node_modules/@nestjs/core/injector/instance-loader.js:56:13
>     at async Promise.all (index 3)
> ╔══════════════════════════════════════════════════════════════════════════════╗║                                                                              ║║   EXCEPTION OCCURED!! in PGClient @ createDatabaseIfNotExists                ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   MESSAGE:                                                                   ║║   password authentication failed for user "postgres"                         ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   CODE:                                                                      ║║   28P01                                                                      ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   STACK:                                                                     ║║   error: password authentication failed for user "postgres"                  ║║   at Parser.parseErrorMessage                                                ║║   (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)              ║║   at Parser.handlePacket                                                     ║║   (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)              ║║   at Parser.parse                                                            ║║   (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)               ║║   at Socket.<anonymous>                                                      ║║   (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)                ║║   at Socket.emit (node:events:519:28)                                        ║║   at Socket.emit (node:domain:488:12)                                        ║║   at addChunk (node:internal/streams/readable:559:12)                        ║║   at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)     ║║   at Readable.push (node:internal/streams/readable:390:5)                    ║║   at TCP.onStreamRead (node:internal/stream_base_commons:191:23)             ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║                                                                              ║║                                                                              ║╚══════════════════════════════════════════════════════════════════════════════╝
> error: password authentication failed for user "postgres"
>     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
>     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
>     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
>     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
>     at Socket.emit (node:events:519:28)
>     at Socket.emit (node:domain:488:12)
>     at addChunk (node:internal/streams/readable:559:12)
>     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
>     at Readable.push (node:internal/streams/readable:390:5)
>     at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
>   length: 104,
>   severity: 'FATAL',
>   code: '28P01',
>   detail: undefined,
>   hint: undefined,
>   position: undefined,
>   internalPosition: undefined,
>   internalQuery: undefined,
>   where: undefined,
>   schema: undefined,
>   table: undefined,
>   column: undefined,
>   dataType: undefined,
>   constraint: undefined,
>   file: 'auth.c',
>   line: '323',
>   routine: 'auth_failed'
> }
> [Nest] 8  - 09/18/2024, 9:57:54 AM     LOG [NestFactory] Starting Nest application...
> [Nest] 8  - 09/18/2024, 9:57:54 AM     LOG [InstanceLoader] PassportModule dependencies initialized +0ms
> [Nest] 8  - 09/18/2024, 9:57:54 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +1ms
> [Nest] 8  - 09/18/2024, 9:57:54 AM     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
> [Nest] 8  - 09/18/2024, 9:57:54 AM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
> [Nest] 8  - 09/18/2024, 9:57:54 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
> [Nest] 8  - 09/18/2024, 9:57:54 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
> [Nest] 8  - 09/18/2024, 9:57:54 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
> [Nest] 8  - 09/18/2024, 9:57:54 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
> [Nest] 8  - 09/18/2024, 9:57:54 AM   ERROR [ExceptionHandler] error: password authentication failed for user "postgres"
> Error: error: password authentication failed for user "postgres"
>     at NcConfig.create (/usr/src/app/docker/main.js:2:2228217)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async InstanceWrapper.useFactory [as metatype] (/usr/src/app/docker/main.js:2:1830025)
>     at async Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:369:37)
>     at async callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:65:34)
>     at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:144:24)
>     at async Injector.loadInstance (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:70:13)
>     at async Injector.loadProvider (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:97:9)
>     at async /usr/src/app/node_modules/@nestjs/core/injector/instance-loader.js:56:13
>     at async Promise.all (index 3)
> ```

From the error it looks like database password defined in the env is not correct. It could be a url encoding related issue when password includes special characters, I will try to figure out and get back to you soon.

**Comment by pranavxc** [comment]
I've populated a passqord with all possible special characters, and everything seems fine. However, there are two potential causes for this issue:

1. An existing `postgres` folder from a previous run may be present, possibly with a different password.
2. You might have changed the PostgreSQL password directly in the `.env` file after running Docker Compose.

#### Solution
1. Stop the Docker Compose services by navigating to the `nocodb` folder and running:
   ```bash
   sudo docker compose stop
   ```
2. Remove the `postgres` folder from the directory (assuming it contains no important data).
3. Restart Docker Compose with:
   ```bash
   sudo docker compose up -d
   ``` 

---
If still not resolving the issue please ping me the docker-compose.yml file and docker.env file in discord - https://discord.gg/5RgZmkW ( username `pranavxc` )

**Comment by TheRealJamesRussell** [comment]
> An existing postgres folder from a previous run may be present, possibly with a different password.

This is very possible, I think in past I hosted something else using postgre. Will come back if it solved.

**Comment by dstala** [comment]
please reopen this ticket if issue still persists
