### ISSUE TITLE
🐛 Bug: I put Kanban as iframe but i can't edit it and meet error when i click the chr

### ISSUE THREAD

**Issue by GhostYouling** [nocodb/nocodb#9515]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

I put my kanban in a iframe, but when i click the card, i meet this problem. I can not move the card too

### Desired Behavior

I hope it can be fixed

### Project Details

message: Please call `useProvideViewGroupBy` on the appropriate parent component

Error: Please call `useProvideViewGroupBy` on the appropriate parent component
    at je (http://localhost:8080/dashboard/_nuxt/DHpFDOWn.js:1:9369)
    at setup (http://localhost:8080/dashboard/_nuxt/Ds0wKRPC.js:1:2188)
    at Gs (http://localhost:8080/dashboard/_nuxt/BLa8BlGD.js:14:1375)
    at vD (http://localhost:8080/dashboard/_nuxt/BLa8BlGD.js:14:56019)
    at vx (http://localhost:8080/dashboard/_nuxt/BLa8BlGD.js:14:55802)
    at ee (http://localhost:8080/dashboard/_nuxt/BLa8BlGD.js:14:41734)
    at X (http://localhost:8080/dashboard/_nuxt/BLa8BlGD.js:14:41608)
    at T (http://localhost:8080/dashboard/_nuxt/BLa8BlGD.js:14:38166)
    at Cd.qe [as fn] (http://localhost:8080/dashboard/_nuxt/BLa8BlGD.js:14:42904)
    at Cd.run (http://localhost:8080/dashboard/_nuxt/BLa8BlGD.js:10:1517)

**Comment by GhostYouling** [comment]
sorry for my computer setting, i can't upoad the image.  The thing i do is use kanban as iframe in code streamlit.components.v1.iframe("http://localhost:8080/dashboard/#/nc/kanban/629ac954-9dc0-4b00-917d-c3a30257c4cf", width=1200, height=600)

**Comment by GhostYouling** [comment]
@dosu I get an error in console like this:
Blocked aria-hidden on a <div> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden. <div tabindex=​"0" aria-hidden=​"true" style=​"width:​ 0px;​ height:​ 0px;​ overflow:​ hidden;​ outline:​ none;​">​</div>​Understand this error

**Comment by o1lab** [comment]
Feel free to reopen if issues persists.
