### ISSUE TITLE
[Bug] Failed testing minio endpoint

### ISSUE THREAD

**Issue by handoyo-lyrid** [nocodb/nocodb#954]
NocoDB used as docker : true 
NocoDB version : v0.84.6
Database used in NC_DB URL  :  pg
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created :  pg 
OS on which NocoDB is running : node:14-slim docker image
Node.js version if running as node : v14
Database version : PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

**Steps To Reproduce**
1. Go to App Store
2. Click on add Minio Endpoint, and fill the appropriate endpoint. And click test.
3. See error
![image](https://user-images.githubusercontent.com/62451515/149648701-18f25b33-54b3-420c-8d46-399f61acc381.png)

2022-01-16T05:29:19Z App: nocodb:template:@LYR - S3Error: Object name contains a leading slash.
    at Object.parseError (/usr/src/nocodb.template/node_modules/minio/dist/main/xml-parsers.js:79:11)
    at /usr/src/nocodb.template/node_modules/minio/dist/main/transformers.js:165:22
    at DestroyableTransform._flush (/usr/src/nocodb.template/node_modules/minio/dist/main/transformers.js:89:10)
    at DestroyableTransform.prefinish (/usr/src/nocodb.template/node_modules/readable-stream/lib/_stream_transform.js:129:10)
    at DestroyableTransform.emit (events.js:400:28)
    at DestroyableTransform.emit (domain.js:475:12)
    at prefinish (/usr/src/nocodb.template/node_modules/readable-stream/lib/_stream_writable.js:611:14)
    at finishMaybe (/usr/src/nocodb.template/node_modules/readable-stream/lib/_stream_writable.js:620:5)
    at endWritable (/usr/src/nocodb.template/node_modules/readable-stream/lib/_stream_writable.js:643:3)
    at DestroyableTransform.Writable.end (/usr/src/nocodb.template/node_modules/readable-stream/lib/_stream_writable.js:571:22) {
  code: 'XMinioInvalidObjectName',
  key: '/nc-test-file.txt',
  bucketname: 'nocodb',
  resource: '/nocodb//nc-test-file.txt',
  requestid: '16CAA91DB23861D1',
  hostid: '924eb1db-a00f-4d68-b840-a7b573bf19b9',
  amzRequestid: null,
  amzId2: null,
  amzBucketRegion: null
}

There's a leading slash added on the key.

**Expected behavior**
No error on test of course 👍

**Comment by pranavxc** [comment]
Fixed in `0.84.7`
