### ISSUE TITLE
🐛 Bug:  TypeError: Cannot read properties of null (reading 'date_format') while update external PG table

### ISSUE THREAD

**Issue by swim2sun** [nocodb/nocodb#9731]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

1. add external Postgresql datasource
2. connect external datasource
3. update table field, fot this case I modify one column's datatype from 'single line text' to 'single select' 

### Desired Behavior

update datatype successfully

### Project Details

instance start with docker compose:
```
version: '2.1'
services:
  nocodb:
    image: nocodb/nocodb:latest
    ports:
      - "8082:8080"
    restart: always
    volumes:
```

### Attachments

error logs:
```
nocodb-1  | ╔══════════════════════════════════════════════════════════════════════════════╗║
                                                   ║║   EXCEPTION OCCURED!! in PGClient @ tableUpdate
           ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   MESSAGE:
           ║║   Cannot read properties of null (reading 'date_format')                     ║║
                                                   ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   CODE:
                                                   ║║   undefined
           ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -
           ║║   STACK:                                                                     ║║   TypeError: Cannot read properties of null (reading 'date_format')          ║║   at PGClient.alterTableColumn (/usr/src/app/docker/main.js:2:1000402)       ║║   at PGClient.alterTableChangeColumn                                         ║║   (/usr/src/app/docker/main.js:2:998868)                                     ║║   at PGClient.tableUpdate (/usr/src/app/docker/main.js:2:994363)             ║║   at SqlMgrv2.sqlOpPlus (/usr/src/app/docker/main.js:2:1089627)              ║║   at process.processTicksAndRejections                                       ║║   (node:internal/process/task_queues:95:5)
           ║║   at async ColumnsService.columnUpdate                                       ║║   (/usr/src/app/docker/main.js:2:2006326)                                    ║║   at async ColumnsService.columnBulk
           ║║   (/usr/src/app/docker/main.js:2:2036140)                                    ║║   at async ColumnsController.columnBulk                                      ║║   (/usr/src/app/docker/main.js:2:377471)
           ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -
           ║║                                                                              ║║
                                                   ║╚══════════════════════════════════════════════════════════════════════════════╝
nocodb-1  | TypeError: Cannot read properties of null (reading 'date_format')
nocodb-1  |     at PGClient.alterTableColumn (/usr/src/app/docker/main.js:2:1000402)
nocodb-1  |     at PGClient.alterTableChangeColumn (/usr/src/app/docker/main.js:2:998868)
nocodb-1  |     at PGClient.tableUpdate (/usr/src/app/docker/main.js:2:994363)
nocodb-1  |     at SqlMgrv2.sqlOpPlus (/usr/src/app/docker/main.js:2:1089627)
nocodb-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
nocodb-1  |     at async ColumnsService.columnUpdate (/usr/src/app/docker/main.js:2:2006326)
nocodb-1  |     at async ColumnsService.columnBulk (/usr/src/app/docker/main.js:2:2036140)
nocodb-1  |     at async ColumnsController.columnBulk (/usr/src/app/docker/main.js:2:377471)
```

**Comment by dstala** [comment]
Unable to reproduce this on latest release (0.260.2). Please reopen this ticket if issue persists, preferably with sample data that leads to this issue.
