### ISSUE TITLE
🐛 Bug: Cannot change the type of the first field

### ISSUE THREAD

**Issue by chevdor** [nocodb/nocodb#9758]
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Similar to the old #1949 .
New table, no data.
When I attempt to change the `Title` to `Number` and `save`, it fails and the logs show:
```
╔══════════════════════════════════════════════════════════════════════════════╗║                                                                              ║║   EXCEPTION OCCURED!! in PGClient @ tableUpdate                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   MESSAGE:                                                                   ║║   Cannot read properties of null (reading 'date_format')                     ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   CODE:                                                                      ║║   undefined                                                                  ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║   STACK:                                                                     ║║   TypeError: Cannot read properties of null (reading 'date_format')          ║║   at PGClient.alterTableColumn (/usr/src/app/docker/main.js:2:1000402)       ║║   at PGClient.alterTableChangeColumn                                         ║║   (/usr/src/app/docker/main.js:2:998868)                                     ║║   at PGClient.tableUpdate (/usr/src/app/docker/main.js:2:994363)             ║║   at SqlMgrv2.sqlOpPlus (/usr/src/app/docker/main.js:2:1089627)              ║║   at process.processTicksAndRejections                                       ║║   (node:internal/process/task_queues:95:5)                                   ║║   at async ColumnsService.columnUpdate                                       ║║   (/usr/src/app/docker/main.js:2:2011679)                                    ║║   at async ColumnsService.columnBulk                                         ║║   (/usr/src/app/docker/main.js:2:2036140)                                    ║║   at async ColumnsController.columnBulk                                      ║║   (/usr/src/app/docker/main.js:2:377471)                                     ║║                                                                              ║║   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    ║║   - - - - - - - - - - - - - - - - - - - - - -                                ║║                                                                              ║║                                                                              ║╚══════════════════════════════════════════════════════════════════════════════╝
TypeError: Cannot read properties of null (reading 'date_format')
    at PGClient.alterTableColumn (/usr/src/app/docker/main.js:2:1000402)
    at PGClient.alterTableChangeColumn (/usr/src/app/docker/main.js:2:998868)
    at PGClient.tableUpdate (/usr/src/app/docker/main.js:2:994363)
    at SqlMgrv2.sqlOpPlus (/usr/src/app/docker/main.js:2:1089627)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ColumnsService.columnUpdate (/usr/src/app/docker/main.js:2:2011679)
    at async ColumnsService.columnBulk (/usr/src/app/docker/main.js:2:2036140)
    at async ColumnsController.columnBulk (/usr/src/app/docker/main.js:2:377471)
```

### Desired Behavior

The type can be changed.

### Project Details

Nocodb in k8s. Using latest image.

**Comment by dstala** [comment]
If you are trying this on your self hosted instance, please share NocoDB base information.

**Comment by chevdor** [comment]
@dstala what additional information do you see relevant ?

**Comment by dstala** [comment]
Use this menu to copy base information
https://docs.nocodb.com/FAQs#how-to-check-my-project-info-

**Comment by chevdor** [comment]
Here it is:
```
Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.257.2**
```
