### ISSUE TITLE
pnpm start:backend  : Property 'getType' does not exist on type 'Mime'.

### ISSUE THREAD

**Issue by aigem** [nocodb/nocodb#9945]
nocodb git:(develop) pnpm start:backend  

> nocodb-root@ start:backend /cloudide/workspace/Nodejs/nocodb
> pnpm --filter=nocodb run start

> nocodb@0.258.3 start /cloudide/workspace/Nodejs/nocodb/packages/nocodb
> pnpm run watch:run

> nocodb@0.258.3 watch:run /cloudide/workspace/Nodejs/nocodb/packages/nocodb
> cross-env NC_DISABLE_TELE=true NODE_ENV=development EE=true nodemon -e ts,js -w ./src -x "ts-node src/run/docker --log-error --project tsconfig.json"

[nodemon] 3.1.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts,js
[nodemon] starting `ts-node src/run/docker --log-error --project tsconfig.json`
/cloudide/workspace/Nodejs/nocodb/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.30_typescript@5.4.5/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/helpers/attachmentHelpers.ts:23:29 - error TS2339: Property 'getType' does not exist on type 'Mime'.

23       const mimeType = mime.getType(extWithoutQuery);
                               ~~~~~~~

    at createTSError (/cloudide/workspace/Nodejs/nocodb/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.30_typescript@5.4.5/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/cloudide/workspace/Nodejs/nocodb/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.30_typescript@5.4.5/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/cloudide/workspace/Nodejs/nocodb/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.30_typescript@5.4.5/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/cloudide/workspace/Nodejs/nocodb/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.30_typescript@5.4.5/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/cloudide/workspace/Nodejs/nocodb/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.30_typescript@5.4.5/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Object.require.extensions.<computed> [as .ts] (/cloudide/workspace/Nodejs/nocodb/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.30_typescript@5.4.5/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19) {
  diagnosticCodes: [ 2339 ]
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by mertmit** [comment]
Hi @aigem, thanks for the report
Please stick to node version 18.19.1 until we upgrade it for repo (we have some dependency issues for upgrade)

**Comment by cansik** [comment]
Even with `18.19.1` I have the same issue. Tried to setup the development env like described in https://docs.nocodb.com/engineering/development-setup. But the backend can not be started.

```js
Node.js v18.19.1
ERROR in ./src/helpers/attachmentHelpers.ts:23:29
TS2339: Property 'getType' does not exist on type 'Mime'.
    21 |
    22 |     if (extWithoutQuery) {
  > 23 |       const mimeType = mime.getType(extWithoutQuery);
       |                             ^^^^^^^
    24 |       return previewableMimeTypes.some((type) => mimeType?.includes(type));
    25 |     }
    26 |   }
```

Moment seems also to be missing.

```js
ERROR in ./src/modules/jobs/jobs/at-import/at-import.processor.ts:1:20
TS2307: Cannot find module 'moment' or its corresponding type declarations.
  > 1 | import moment from 'moment';
      |                    ^^^^^^^^
    2 | import { SqlUiFactory, UITypes } from 'nocodb-sdk';
    3 | import Airtable from 'airtable';
    4 | import hash from 'object-hash';

ERROR in ./src/modules/jobs/jobs/data-export/data-export.processor.ts:5:20
TS2307: Cannot find module 'moment' or its corresponding type declarations.
    3 | import iconv from 'iconv-lite';
    4 | import { Injectable, Logger } from '@nestjs/common';
  > 5 | import moment from 'moment';
      |                    ^^^^^^^^
    6 | import type { Job } from 'bull';
    7 | import { type DataExportJobData } from '~/interface/Jobs';
    8 | import { elapsedTime, initTime } from '~/modules/jobs/helpers';
```
