### ISSUE TITLE
uuid data type not working in searches in postgres

### ISSUE THREAD

**Issue by marco-santulli** [nocodb/nocodb#996]
I just reported also an error with bigint types (issue #589 ). I am just saying this because there might be a "pattern" on different column types.

Doing a search on a table, using a column of type "uuid" on a postgres DB with nocodb release 0.84.7, I get the following error (note I also get a similar error in the log just before this one on select without the count):

error: select count("risultato_match"."risultato_id") as "count" from "risultato_match" where "risultato_match"."id_estrazione_movimento
" ilike $1 limit $2 - operator does not exist: uuid ~~* unknown
    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 202,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No operator matches the given name and argument types. You might need to add explicit type casts.',

**Comment by wingkwong** [comment]
Fixed in ``0.84.12``.
